import { describe, expect, it } from "vitest";

import { define } from "../src/builders/index.js";
import { defineMod } from "../src/index.js";
import { validate, type ValidationDiagnostic } from "../src/validate/index.js";

/**
 * The checks that only exist below the first level.
 *
 * A definition body is a handful of keys; the script inside it is hundreds, and
 * every one of them is somewhere a name can be misspelled. The game drops an
 * unknown key without a word wherever it appears, so a checker that stops at the
 * body is checking almost nothing.
 */
const findings = (mod: Parameters<typeof validate>[0]): readonly ValidationDiagnostic[] => validate(mod);

const at = (mod: Parameters<typeof validate>[0], code: string): readonly ValidationDiagnostic[] =>
  findings(mod).filter((diagnostic) => diagnostic.code === code);

describe("validation below the first level", () => {
  it("finds a misspelled trigger inside a trigger block", () => {
    const mod = defineMod({ name: "Deep", version: "1", supportedVersion: "v4.4.*" }).add(
      define("building", "deep_lab", {
        category: "research",
        allow: { has_country_flagg: "x" },
      }),
    );

    const unknown = at(mod, "unknown-field");
    expect(unknown).toHaveLength(1);
    expect(unknown[0]?.path).toBe("allow");
    expect(unknown[0]?.message).toContain("has_country_flagg");
  });

  it("follows a scope change into the block it opens", () => {
    const mod = defineMod({ name: "Scope", version: "1", supportedVersion: "v4.4.*" }).add(
      define("building", "scope_lab", {
        category: "research",
        on_built: { owner: { add_resourcee: { energy: 10 } } },
      }),
    );

    const unknown = at(mod, "unknown-field");
    expect(unknown).toHaveLength(1);
    expect(unknown[0]?.path).toBe("on_built.owner");
  });

  it("checks the names inside a modifier block", () => {
    const mod = defineMod({ name: "Mods", version: "1", supportedVersion: "v4.4.*" }).add(
      define("building", "mod_lab", {
        category: "research",
        planet_modifier: { job_researcher_add: 2, job_researcher_addd: 2 },
      }),
    );

    const unknown = at(mod, "unknown-modifier");
    expect(unknown).toHaveLength(1);
    expect(unknown[0]?.message).toContain("job_researcher_addd");
  });

  it("accepts a modifier generated by the mod's own definition", () => {
    const mod = defineMod({ name: "Own", version: "1", supportedVersion: "v4.4.*" })
      .add(define("job", "sts_curator", { category: "specialist" }))
      .add(
        define("building", "own_lab", {
          category: "research",
          planet_modifier: { job_sts_curator_add: 2 },
        }),
      );

    expect(at(mod, "unknown-modifier")).toHaveLength(0);
  });

  it("accepts a static modifier's id where a modifier belongs", () => {
    // The id merges that modifier's contents in; vanilla does it 66 times.
    const mod = defineMod({ name: "Static", version: "1", supportedVersion: "v4.4.*" }).add(
      define("building", "static_lab", {
        category: "research",
        planet_modifier: { resolution_sanctions_tech: 1 },
      }),
    );

    expect(at(mod, "unknown-modifier")).toHaveLength(0);
  });

  it("rejects a parameter the scripted effect it calls does not take", () => {
    const mod = defineMod({ name: "Params", version: "1", supportedVersion: "v4.4.*" }).add(
      define("building", "param_lab", {
        category: "research",
        on_built: { pop_group_transfer_ethic: { ETHOS: "ethic_militarist", NO_SUCH_PARAM: "x" } },
      }),
    );

    const unknown = at(mod, "unknown-field");
    expect(unknown).toHaveLength(1);
    expect(unknown[0]?.message).toContain("NO_SUCH_PARAM");
  });

  it("reads a key without regard to case, as the game does", () => {
    const mod = defineMod({ name: "Case", version: "1", supportedVersion: "v4.4.*" }).add(
      define("building", "case_lab", {
        category: "research",
        // Vanilla writes `TRIGGER` and `LIMIT` in places the rules spell lower.
        on_built: { IF: { LIMIT: { exists: "owner" }, owner: { add_resource: { energy: 10 } } } },
      }),
    );

    expect(at(mod, "unknown-field")).toHaveLength(0);
  });

  it("catches a trigger read on the wrong kind of object", () => {
    // A building's `potential` runs on a planet. `is_colony` reads a planet, so
    // it belongs there and not under `owner`, which is a country.
    const mod = defineMod({ name: "Scoped", version: "1", supportedVersion: "v4.4.*" }).add(
      define("building", "scoped_lab", {
        category: "research",
        potential: { is_colony: true, owner: { is_colony: true } },
      }),
    );

    const wrong = at(mod, "wrong-scope");
    expect(wrong).toHaveLength(1);
    expect(wrong[0]?.path).toBe("potential.owner");
    expect(wrong[0]?.message).toContain("country");
  });

  it("names a value the rules do not accept", () => {
    // `category` is drawn from a fixed set, and `tier` is a technology_tier id.
    const mod = defineMod({ name: "Values", version: "1", supportedVersion: "v4.4.*" }).add({
      type: "building",
      directory: "common/buildings",
      id: "value_lab",
      body: { category: "reserach", base_buildtime: "soon" },
    });

    const unknown = at(mod, "unknown-value");
    expect(unknown).toHaveLength(2);
    expect(unknown.map((diagnostic) => diagnostic.message).join(" ")).toContain("reserach");
  });

  it("reads an event on the object its kind names", () => {
    // A planet event reads a planet and a country event a country, and the two
    // are the same type with the same fields.
    const mod = defineMod({ name: "Kinds", version: "1", supportedVersion: "v4.4.*" })
      .add(define("event", "sts_kind.1", { trigger: { is_colony: true } }, { as: "planet_event" }))
      .add(define("event", "sts_kind.2", { trigger: { is_colony: true } }, { as: "country_event" }));

    const wrong = at(mod, "wrong-scope");
    expect(wrong).toHaveLength(1);
    expect(wrong[0]?.definition).toBe("sts_kind.2");
  });

  it("names an event id with no namespace", () => {
    const mod = defineMod({ name: "NoNs", version: "1", supportedVersion: "v4.4.*" }).add(
      define("event", "sts_demo_one", { is_triggered_only: true }, { as: "country_event" }),
    );

    expect(at(mod, "unnamespaced-event")).toHaveLength(1);
  });

  it("says when a definition takes a base-game id over", () => {
    const mod = defineMod({ name: "Override", version: "1", supportedVersion: "v4.4.*" }).add(
      define("building", "building_capital", { category: "government" }),
    );

    expect(at(mod, "replaces-vanilla-definition")).toHaveLength(1);
  });

  it("names a field the definition needs and does not have", () => {
    // Every one of vanilla's own bypasses carries `name`, so the requirement is
    // the game's rather than the corpus's guess. The generated type refuses this
    // body outright; the record is built by hand to exercise the check that
    // catches a body no compiler saw.
    const mod = defineMod({ name: "Bare", version: "1", supportedVersion: "v4.4.*" }).add({
      type: "bypass",
      directory: "common/bypass",
      id: "bare_bypass",
      body: { icon_frame: 1 },
    });

    const missing = at(mod, "missing-field");
    expect(missing.length).toBeGreaterThan(0);
    expect(missing.map((diagnostic) => diagnostic.message).join(" ")).toContain("name");
  });
});
