// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import { block, defineType, field, keyedBlocks, occurs, primitive, replaceScope, triggerEntries } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const achievement: DefinitionType = defineType({
  id: DefinitionTypeId.Achievement,
  source: keyedBlocks("common", true, {
    files: ["achievements.txt"],
    rootKeyFilter: { mode: "include", values: ["achievement"] },
  }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("id", primitive("integer"), occurs.one),
    field("possible", block([triggerEntries()]), occurs.one, { scope: replaceScope({ root: ScopeId.Country }) }),
    field("happened", block([triggerEntries()]), occurs.one, { scope: replaceScope({ root: ScopeId.Country }) }),
  ],
});
