// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import {
  block,
  defineType,
  field,
  keyedBlocks,
  modifierRuleEntries,
  occurs,
  primitive,
  triggerEntries,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const advisorVoice: DefinitionType = defineType({
  id: DefinitionTypeId.AdvisorVoice,
  source: keyedBlocks("sound/advisor_voice_types"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("scalar"), occurs.one),
    field("icon", primitive("file"), occurs.one),
    field("playable", block([triggerEntries()]), occurs.optional),
    field("weight", block([modifierRuleEntries()]), occurs.one),
    field("name", primitive("scalar"), occurs.one),
    field("icon", primitive("file"), occurs.one),
    field("playable", block([triggerEntries()]), occurs.optional),
    field("weight", block([modifierRuleEntries()]), occurs.one),
  ],
});
