// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  field,
  keyedBlocks,
  occurs,
  replaceScope,
  ruleSetEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const agreementResource: DefinitionType = defineType({
  id: DefinitionTypeId.AgreementResource,
  source: keyedBlocks("common/agreement_resources"),
  variants: [],
  localisation: [definitionLocalisation("Name", "", true)],
  modifiers: [],
  entries: [
    field(
      "resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.one,
      { scope: replaceScope({ root: ScopeId.Agreement }) },
    ),
    field(
      "resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.one,
      { scope: replaceScope({ root: ScopeId.Agreement }) },
    ),
  ],
});
