// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  field,
  fieldPresent,
  item,
  keyedBlocks,
  modifierEntries,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  triggerEntries,
  typeRef,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const agreementTermValue: DefinitionType = defineType({
  id: DefinitionTypeId.AgreementTermValue,
  source: keyedBlocks("common/agreement_term_values"),
  variants: [
    { id: "discrete", when: fieldPresent("term") },
    { id: "discrete_number", when: fieldPresent("term") },
    { id: "specialist_type", when: fieldPresent("term") },
    { id: "resource", when: fieldPresent("term") },
  ],
  localisation: [definitionLocalisation("Name", "", false)],
  modifiers: [],
  entries: [
    field("term", typeRef("agreement_term"), occurs.one, {
      documentation: "The term in agreement_terms that this value applies to",
    }),
    whenVariant("discrete", [field("term", typeRef("agreement_term", "discrete"), occurs.one)]),
    whenVariant("discrete_number", [field("term", typeRef("agreement_term", "discrete_number"), occurs.one)]),
    whenVariant("specialist_type", [field("term", typeRef("agreement_term", "specialist_type"), occurs.one)]),
    whenVariant("resource", [
      field("term", typeRef("agreement_term", "resource"), occurs.one),
      field("resources", block([item(typeRef("resource"), occurs.any)]), occurs.optional),
      field("subsidy_multiplier", primitive("number"), occurs.optional),
      field("subsidy_monthly_multiplier", primitive("number"), occurs.optional),
      field("resource_min", block([modifierRuleEntries()]), occurs.optional),
      field("resource_max", block([modifierRuleEntries()]), occurs.optional),
    ]),
    field(
      "subject_resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.Country }) },
    ),
    field(
      "overlord_resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.Country }) },
    ),
    field("owner_modifier", block([modifierEntries()]), occurs.optional, {
      documentation: "A modifier that applies to the Agreement owner country. Can stack multiple times.",
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("unique_owner_modifier", block([modifierEntries()]), occurs.optional, {
      documentation: "A modifier that applies to the Agreement owner country. Only applies once.",
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("target_modifier", block([modifierEntries()]), occurs.optional, {
      documentation: "A modifier that applies to the Agreement target country. Can stack multiple times.",
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("unique_target_modifier", block([modifierEntries()]), occurs.optional, {
      documentation: "A modifier that applies to the Agreement target country. Only applies once.",
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("loyalty_change", primitive("integer"), occurs.optional, {
      documentation: "How much the subject's loyalty will change when a new agreement with this term starts",
    }),
    field(
      "ai_acceptance",
      block([
        field("overlord", primitive("integer"), occurs.optional, {
          documentation: "Willingness of AI overlord to accept this term",
        }),
        field("subject", primitive("integer"), occurs.optional, {
          documentation: "Willingness of AI subject to accept this term",
        }),
      ]),
      occurs.optional,
    ),
    field(
      "triggered_loyalty_change",
      block([
        field("trigger", block([triggerEntries()]), occurs.one, { scope: replaceScope({ root: ScopeId.Agreement }) }),
        field("loyalty_change", primitive("integer"), occurs.one),
        field(
          "ai_acceptance",
          block([
            field("overlord", primitive("integer"), occurs.optional, {
              documentation: "Willingness of AI overlord to accept this term",
            }),
            field("subject", primitive("integer"), occurs.optional, {
              documentation: "Willingness of AI subject to accept this term",
            }),
          ]),
          occurs.optional,
        ),
      ]),
      occurs.any,
      {
        documentation:
          'How much the subject\'s loyalty will additionally change when a new agreement with this term starts, if "trigger" is true',
      },
    ),
    field("activate_effect", block([effectEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Agreement }),
    }),
    field("deactivate_effect", block([effectEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Agreement }),
    }),
    field("possible", block([triggerEntries()]), occurs.optional, { scope: replaceScope({ root: ScopeId.Agreement }) }),
    field("potential", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Agreement }),
    }),
    field("extra_term_text_subject", primitive("localisation"), occurs.optional, {
      documentation:
        'What should be shown in the "extra terms" panel for the subject if this term value is active (default is to not show it) This loc key can use $SUBJECT$ and $OVERLORD$ to show the name of the relevant empire, and $MODIFIER$ to show the modifiers applying to the subject',
    }),
    field("extra_term_text_overlord", primitive("localisation"), occurs.optional, {
      documentation:
        'What should be shown in the "extra terms" panel for the overlord if this term value is active (default is to not show it) Loc key can use $SUBJECT$ and $OVERLORD$ to show the name of the relevant empire, $MODIFIER$ for the overlord\'s modifiers, and $RESOURCES$ for the net resources it gains',
    }),
    field("term", typeRef("agreement_term"), occurs.one, {
      documentation: "The term in agreement_terms that this value applies to",
    }),
    whenVariant("discrete", [field("term", typeRef("agreement_term", "discrete"), occurs.one)]),
    whenVariant("discrete_number", [field("term", typeRef("agreement_term", "discrete_number"), occurs.one)]),
    whenVariant("specialist_type", [field("term", typeRef("agreement_term", "specialist_type"), occurs.one)]),
    whenVariant("resource", [
      field("term", typeRef("agreement_term", "resource"), occurs.one),
      field("resources", block([item(typeRef("resource"), occurs.any)]), occurs.optional),
      field("subsidy_multiplier", primitive("number"), occurs.optional),
      field("subsidy_monthly_multiplier", primitive("number"), occurs.optional),
      field("resource_min", block([modifierRuleEntries()]), occurs.optional),
      field("resource_max", block([modifierRuleEntries()]), occurs.optional),
    ]),
    field(
      "subject_resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.Country }) },
    ),
    field(
      "overlord_resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.Country }) },
    ),
    field("owner_modifier", block([modifierEntries()]), occurs.optional, {
      documentation: "A modifier that applies to the Agreement owner country. Can stack multiple times.",
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("unique_owner_modifier", block([modifierEntries()]), occurs.optional, {
      documentation: "A modifier that applies to the Agreement owner country. Only applies once.",
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("target_modifier", block([modifierEntries()]), occurs.optional, {
      documentation: "A modifier that applies to the Agreement target country. Can stack multiple times.",
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("unique_target_modifier", block([modifierEntries()]), occurs.optional, {
      documentation: "A modifier that applies to the Agreement target country. Only applies once.",
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("loyalty_change", primitive("integer"), occurs.optional, {
      documentation: "How much the subject's loyalty will change when a new agreement with this term starts",
    }),
    field(
      "ai_acceptance",
      block([
        field("overlord", primitive("integer"), occurs.optional, {
          documentation: "Willingness of AI overlord to accept this term",
        }),
        field("subject", primitive("integer"), occurs.optional, {
          documentation: "Willingness of AI subject to accept this term",
        }),
      ]),
      occurs.optional,
    ),
    field(
      "triggered_loyalty_change",
      block([
        field("trigger", block([triggerEntries()]), occurs.one, { scope: replaceScope({ root: ScopeId.Agreement }) }),
        field("loyalty_change", primitive("integer"), occurs.one),
        field(
          "ai_acceptance",
          block([
            field("overlord", primitive("integer"), occurs.optional, {
              documentation: "Willingness of AI overlord to accept this term",
            }),
            field("subject", primitive("integer"), occurs.optional, {
              documentation: "Willingness of AI subject to accept this term",
            }),
          ]),
          occurs.optional,
        ),
      ]),
      occurs.any,
      {
        documentation:
          'How much the subject\'s loyalty will additionally change when a new agreement with this term starts, if "trigger" is true',
      },
    ),
    field("activate_effect", block([effectEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Agreement }),
    }),
    field("deactivate_effect", block([effectEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Agreement }),
    }),
    field("possible", block([triggerEntries()]), occurs.optional, { scope: replaceScope({ root: ScopeId.Agreement }) }),
    field("potential", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Agreement }),
    }),
    field("extra_term_text_subject", primitive("localisation"), occurs.optional, {
      documentation:
        'What should be shown in the "extra terms" panel for the subject if this term value is active (default is to not show it) This loc key can use $SUBJECT$ and $OVERLORD$ to show the name of the relevant empire, and $MODIFIER$ to show the modifiers applying to the subject',
    }),
    field("extra_term_text_overlord", primitive("localisation"), occurs.optional, {
      documentation:
        'What should be shown in the "extra terms" panel for the overlord if this term value is active (default is to not show it) Loc key can use $SUBJECT$ and $OVERLORD$ to show the name of the relevant empire, $MODIFIER$ for the overlord\'s modifiers, and $RESOURCES$ for the net resources it gains',
    }),
  ],
});
