// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  enumRef,
  field,
  item,
  keyedBlocks,
  modifierRuleEntries,
  occurs,
  primitive,
  triggerEntries,
  typeKey,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const aiPersonality: DefinitionType = defineType({
  id: DefinitionTypeId.AiPersonality,
  source: keyedBlocks("common/personalities"),
  variants: [],
  localisation: [
    definitionLocalisation("Name", "personality_$", true),
    definitionLocalisation("Description", "personality_$_desc", true),
  ],
  modifiers: [],
  entries: [
    field("aggressiveness", primitive("number"), occurs.optional, {
      documentation:
        "Affects chance of declaring wars, chance of sending insults, and how much % of fleet power is committed to offense (at 0, 50% is committed, at 1 it is more like 75%, at 2 it is 100%; higher values still count extra towards war dec and insult chance)",
    }),
    field("trade_willingness", primitive("number"), occurs.optional, {
      documentation: "At 1.0 willingness they will accept a deal that is equally good for both sides",
    }),
    field("bravery", primitive("number"), occurs.optional, {
      documentation:
        "Affects the chance that they will pick rivals & war targets of similar strength instead of picking on the weak",
    }),
    field("combat_bravery", primitive("number"), occurs.optional),
    field("military_spending", primitive("number"), occurs.optional, {
      documentation: "Affects mineral & energy budget that goes to navies and armies",
    }),
    field("colony_spending", primitive("number"), occurs.optional, {
      documentation: "Affects mineral & energy budget that goes to new colonies",
    }),
    field("federation_acceptance", primitive("integer"), occurs.optional, {
      documentation: "Added directly to chance of accepting to form/join a federation",
    }),
    field("nap_acceptance", primitive("integer"), occurs.optional, {
      documentation: "Added directly to chance of accepting to form a non-aggression pact",
    }),
    field("commercial_pact_acceptance", primitive("integer"), occurs.optional, {
      documentation: "Added directly to chance of accepting to form a commercial pact",
    }),
    field("research_agreement_acceptance", primitive("integer"), occurs.optional, {
      documentation: "Added directly to chance of accepting to form a research agreement",
    }),
    field("defensive_pact_acceptance", primitive("integer"), occurs.optional, {
      documentation: "Added directly to chance of accepting to form a defensive pact",
    }),
    field("migration_pact_acceptance", primitive("integer"), occurs.optional, {
      documentation: "Added directly to chance of accepting to form a migration pact",
    }),
    field("loyalty_acceptance", primitive("number"), occurs.optional, {
      documentation:
        "As overlord, multiplied by subject loyalty change and added to acceptance of a deal; Low values mean we don't care if subjects are loyal or not, high means we like loyal subjects",
    }),
    field("advanced_start_chance", primitive("integer"), occurs.optional, {
      documentation:
        "likelihood of this empire being an advanced start (higher = better chance of being one of empires selected for advanced start)",
    }),
    field("weapon_preferences", enumRef(EnumId.ComponentTags), occurs.optional),
    field("armor_ratio", primitive("number"), occurs.optional, {
      documentation: "Amount of armor they should aim for on ships",
    }),
    field("shields_ratio", primitive("number"), occurs.optional, {
      documentation: "Amount of shields they should aim for on ships",
    }),
    field("hull_ratio", primitive("number"), occurs.optional, {
      documentation: "Amount of hull boosters they should aim for on ships (if available)",
    }),
    field(
      "ship_roles",
      block([field(typeKey("ship_size"), enumRef(EnumId.ShipSizeShipRoles), occurs.any)]),
      occurs.optional,
      { documentation: 'List of "<ship_size> = <role>" statements; AI will use the corresponding role for that size' },
    ),
    field("threat_modifier", primitive("number"), occurs.optional, {
      documentation: "Affects how much threat is generated for this empire when others are conquered",
    }),
    field("threat_others_modifier", primitive("number"), occurs.optional, {
      documentation: "Affects how much threat is generated for other empires when this empire is conquered",
    }),
    field("friction_modifier", primitive("number"), occurs.optional, { documentation: "Affects border friction" }),
    field("claims_modifier", primitive("number"), occurs.optional, {
      documentation: "Affects opinion penalty from claims",
    }),
    field(
      "behaviour",
      block([
        field("conqueror", primitive("boolean"), occurs.optional, {
          documentation: "Will they conquer planets from other empires?",
        }),
        field("subjugator", primitive("boolean"), occurs.optional, {
          documentation: "Will they vassalize other empires?",
        }),
        field("liberator", primitive("boolean"), occurs.optional, {
          documentation: "Will they liberate conquered empires?",
        }),
        field("opportunist", primitive("boolean"), occurs.optional, {
          documentation: "Are they more likely to attack someone already embroiled in war?",
        }),
        field("slaver", primitive("boolean"), occurs.optional, { documentation: "Will they enslave pops?" }),
        field("caste_system", primitive("boolean"), occurs.optional),
        field("uplifter", primitive("boolean"), occurs.optional, {
          documentation: "Will they uplift and enlighten other species?",
        }),
        field("purger", primitive("boolean"), occurs.optional, { documentation: "Will they purge alien pops?" }),
        field("displacer", primitive("boolean"), occurs.optional),
        field("infiltrator", primitive("boolean"), occurs.optional, {
          documentation: "Will they infiltrate primitives?",
        }),
        field("dominator", primitive("boolean"), occurs.optional, { documentation: "Will they invade primitives?" }),
        field("robot_exploiter", primitive("boolean"), occurs.optional, {
          documentation: "Will they use robots for menial labor?",
        }),
        field("robot_liberator", primitive("boolean"), occurs.optional, {
          documentation: "Will they give rights to robots?",
        }),
        field("propagator", primitive("boolean"), occurs.optional, {
          documentation: "Will they only get aggressive once boxed in?",
        }),
        field("multispecies", primitive("boolean"), occurs.optional, {
          documentation: "Will they give rights to aliens?",
        }),
        field("crisis_fighter", primitive("boolean"), occurs.optional, {
          documentation: "Will they consider fighting the crisis? (If 'no' they will only care about themselves.)",
        }),
        field("wants_tribute", primitive("boolean"), occurs.optional),
        field("sneak_attacker", primitive("boolean"), occurs.optional, {
          documentation: "Will they use cloaked fleets to attack their enemies?",
        }),
        field("decadent", primitive("boolean"), occurs.optional),
        field("isolationist", primitive("boolean"), occurs.optional, { documentation: "Always keep borders closed?" }),
        field("attack_neutrals", primitive("boolean"), occurs.optional),
        field("holy_planets", primitive("boolean"), occurs.optional, { documentation: "special for spiritualist FE" }),
        field("demands_clear_borders", primitive("boolean"), occurs.optional),
        field("crisis_leader", primitive("boolean"), occurs.optional, {
          documentation:
            "Will they fight the crisis and invite others to do so (Fallen Empires special behaviour. Emperor/Custodian will behave the same way regardless of this flag.)",
        }),
        field("custodian", primitive("boolean"), occurs.optional, {
          documentation: "special for awakened machine fallen empires, prevents colonization & locks attitude",
        }),
        field("enigmatic", primitive("boolean"), occurs.optional, {
          documentation: "special for machine fallen empires",
        }),
        field("limited", primitive("boolean"), occurs.optional, { documentation: "prevents certain AI behaviours" }),
        field("berserker", primitive("boolean"), occurs.optional, {
          documentation: "special for awakened machine fallen empires, prevents colonization & locks attitude",
        }),
      ]),
      occurs.optional,
    ),
    field("allow", block([triggerEntries()]), occurs.optional),
    field("weight_modifier", block([modifierRuleEntries()]), occurs.optional, {
      documentation: "NOTE: Weight is additive for personalities!",
    }),
    field("ai_module_overrides", block([item(primitive("scalar"), occurs.oneOrMore)]), occurs.optional),
  ],
});
