// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { anyKey, defineType, field, keyedBlocks, occurs, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const alertIcon: DefinitionType = defineType({
  id: DefinitionTypeId.AlertIcon,
  source: keyedBlocks("common", true, { files: ["alerts.txt"], rootKeyFilter: { mode: "include", values: ["icon"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [field(anyKey(), typeRef("sprite"), occurs.any)],
});
