// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, field, keyedBlocks, occurs, ruleSetEntries, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const alert: DefinitionType = defineType({
  id: DefinitionTypeId.Alert,
  source: keyedBlocks("common", true, {
    files: ["alerts.txt"],
    rootKeyFilter: { mode: "include", values: ["alert"] },
    container: { kind: "named-container", key: "alerts" },
  }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [ruleSetEntries("alert_category"), field("sound", typeRef("sound_effect"), occurs.one)],
});
