// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import {
  defineType,
  definitionLocalisation,
  field,
  fieldEquals,
  occurs,
  primitive,
  taggedBlocks,
  typeRef,
  unlessVariant,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const ambientObject: DefinitionType = defineType({
  id: DefinitionTypeId.AmbientObject,
  source: taggedBlocks("common/ambient_objects", "name", []),
  variants: [
    { id: "show_name", when: fieldEquals("show_name", true) },
    { id: "selectable", when: fieldEquals("selectable", true) },
  ],
  localisation: [definitionLocalisation("name", "", true, "show_name")],
  modifiers: [],
  entries: [
    whenVariant("show_name", [
      field("name", primitive("localisation"), occurs.one, { documentation: "A localisation key." }),
    ]),
    unlessVariant("show_name", [field("name", primitive("scalar"), occurs.one)]),
    whenVariant("selectable", [
      field("description", primitive("localisation"), occurs.one),
      field("tooltip", primitive("localisation"), occurs.one),
    ]),
    unlessVariant("selectable", [
      field("description", primitive("localisation"), occurs.optional),
      field("tooltip", primitive("localisation"), occurs.optional),
    ]),
    field("entity", typeRef("model_entity"), occurs.one),
    field("selectable", primitive("boolean"), occurs.optional),
    field("show_name", primitive("boolean"), occurs.optional, {
      documentation: "Determines whether you can read the name of the object ingame.",
    }),
    whenVariant("show_name", [
      field("name", primitive("localisation"), occurs.one, { documentation: "A localisation key." }),
    ]),
    unlessVariant("show_name", [field("name", primitive("scalar"), occurs.one)]),
    whenVariant("selectable", [
      field("description", primitive("localisation"), occurs.one),
      field("tooltip", primitive("localisation"), occurs.one),
    ]),
    unlessVariant("selectable", [
      field("description", primitive("localisation"), occurs.optional),
      field("tooltip", primitive("localisation"), occurs.optional),
    ]),
    field("entity", typeRef("model_entity"), occurs.one),
    field("selectable", primitive("boolean"), occurs.optional),
    field("show_name", primitive("boolean"), occurs.optional, {
      documentation: "Determines whether you can read the name of the object ingame.",
    }),
  ],
});
