// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  between,
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  enumRef,
  field,
  keyedBlocks,
  modifierRuleEntries,
  numericKey,
  occurs,
  primitive,
  replaceScope,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const anomalyCategory: DefinitionType = defineType({
  id: DefinitionTypeId.AnomalyCategory,
  source: keyedBlocks("common/anomalies"),
  variants: [],
  localisation: [definitionLocalisation("Name", "$", true)],
  modifiers: [],
  entries: [
    field("should_ai_use", primitive("boolean"), occurs.optional, {
      documentation: "Yes makes the anomaly exclusively used by the AI, no by the player. Default: no",
    }),
    field("should_ai_and_humans_use", primitive("boolean"), occurs.optional, {
      documentation: "If set to yes, this allows both the player and the AI to use the anomaly",
    }),
    field("desc", primitive("localisation"), occurs.optional, {
      documentation: "Optional. Will use <anomaly_category>_description if not specified.",
    }),
    field(
      "desc",
      block([
        field("trigger", block([triggerEntries()]), occurs.one, { documentation: "Scope: planet, from = ship" }),
        field("text", primitive("localisation"), occurs.one),
      ]),
      occurs.any,
      { scope: replaceScope({ root: ScopeId.Planet, from: ScopeId.Ship }) },
    ),
    field("picture", typeRef("sprite"), occurs.optional, { documentation: "Picture displayed in category window" }),
    field("level", primitive("integer", { min: 1, max: 10 }), occurs.one, { documentation: "Anomaly level, 1 to 10" }),
    field("null_spawn_chance", primitive("number", { min: 0, max: 1 }), occurs.optional, {
      documentation:
        "Default 0. 0.0 - 1.0 (0 to 100%) chance category will NOT spawn even if it is picked by the anomaly die roll. Used to make categories for unusual objects (e.g. black holes) actually rare.",
    }),
    field("max_once", primitive("boolean"), occurs.optional, {
      documentation: "default NO, if true will spawn category only once per empire",
    }),
    field("max_once_global", primitive("boolean"), occurs.optional, {
      documentation: "default NO, if true will spawn category only once per game",
    }),
    field(
      "spawn_chance",
      block([
        modifierRuleEntries(),
        // vanilla 4.4.6: 301 of 327 write a `modifier` with no `factor` — it is
        // `add`, `mult` or a bare trigger list instead.
        field("modifier", block([field("factor", enumRef(EnumId.ExeSetVariable), occurs.optional)]), occurs.any),
      ]),
      occurs.optional,
      {
        documentation:
          "Chance for this anomaly category to spawn, relative to other valid categories. Default: base = 0. Scope: planet, from = ship",
        scope: replaceScope({ root: ScopeId.Planet, from: ScopeId.Ship }),
      },
    ),
    field("on_spawn", block([effectEntries()]), occurs.optional, {
      documentation:
        "Executes immediately when anomaly category is spawned. Scopes are this/root: planet, from: ship. NOTE: on_spawn effects will not run if category is spawned through console",
      scope: replaceScope({ root: ScopeId.Planet, from: ScopeId.Ship }),
    }),
    field("on_success", typeRef("event", "ship"), occurs.one, {
      documentation: "Picks anomaly event to fire; similar to random_list",
    }),
    field(
      "on_success",
      block([
        field(numericKey(), typeRef("event", "ship"), between(0, 100)),
        field(
          "int",
          block([
            field("max_once", primitive("boolean"), occurs.optional, {
              documentation: "Individual outcomes default to max_once = yes",
            }),
            field("max_once_global", primitive("boolean"), occurs.optional, {
              documentation: "Individual outcomes default to max_once_global = no",
            }),
            modifierRuleEntries(),
            field("anomaly_event", typeRef("event", "ship"), occurs.optional),
            field("ship_event", typeRef("event", "ship"), occurs.optional),
          ]),
          between(0, 100),
        ),
      ]),
      occurs.one,
    ),
  ],
});
