// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import {
  block,
  defineType,
  effectEntries,
  field,
  keyedBlocks,
  literal,
  modifierRuleEntries,
  occurs,
  primitive,
  scriptValue,
  triggerEntries,
  typeKey,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const artifactActions: DefinitionType = defineType({
  id: DefinitionTypeId.ArtifactActions,
  source: keyedBlocks("common/artifact_actions"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("sound", typeRef("sound_effect"), occurs.optional),
    field(
      "resources",
      block([
        field("category", literal("artifact_actions"), occurs.one),
        field(
          "cost",
          block([
            field(typeKey("resource"), primitive("integer"), occurs.one),
            field("multiplier", scriptValue("number"), occurs.optional),
          ]),
          occurs.one,
        ),
      ]),
      occurs.optional,
    ),
    field("ai_weight", block([modifierRuleEntries()]), occurs.optional),
    field("potential", block([triggerEntries()]), occurs.optional),
    field("allow", block([triggerEntries()]), occurs.optional),
    field("effect", block([effectEntries()]), occurs.optional),
    field("sound", typeRef("sound_effect"), occurs.optional),
    field(
      "resources",
      block([
        field("category", literal("artifact_actions"), occurs.one),
        field(
          "cost",
          block([
            field(typeKey("resource"), primitive("integer"), occurs.one),
            field("multiplier", scriptValue("number"), occurs.optional),
          ]),
          occurs.one,
        ),
      ]),
      occurs.optional,
    ),
    field("ai_weight", block([modifierRuleEntries()]), occurs.optional),
    field("potential", block([triggerEntries()]), occurs.optional),
    field("allow", block([triggerEntries()]), occurs.optional),
    field("effect", block([effectEntries()]), occurs.optional),
  ],
});
