// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  field,
  keyedBlocks,
  modifierRuleEntries,
  occurs,
  ruleSetEntries,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const artifactAction: DefinitionType = defineType({
  id: DefinitionTypeId.ArtifactAction,
  source: keyedBlocks("common/artifact_action"),
  entryScope: ScopeId.Country,
  variants: [],
  localisation: [definitionLocalisation("Name", "", true), definitionLocalisation("Desc", "_desc", true)],
  modifiers: [],
  entries: [
    field(
      "resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.optional,
    ),
    field("ai_weight", block([modifierRuleEntries()]), occurs.optional),
    field("potential", block([triggerEntries()]), occurs.one),
    field("effect", block([effectEntries()]), occurs.optional),
    field("allow", block([triggerEntries()]), occurs.optional),
    field("sound", typeRef("sound_effect"), occurs.optional),
  ],
});
