// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, definitionLocalisation, field, keyedBlocks, occurs, primitive } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const attitude: DefinitionType = defineType({
  id: DefinitionTypeId.Attitude,
  source: keyedBlocks("common/attitudes"),
  variants: [],
  localisation: [definitionLocalisation("name", "attitude_$", true)],
  modifiers: [],
  entries: [
    field("type", primitive("scalar"), occurs.one),
    field(
      "behaviour",
      block([
        field("attack", primitive("boolean"), occurs.optional),
        field("weaken", primitive("boolean"), occurs.optional),
        field("alliance", primitive("boolean"), occurs.optional),
        field("vassalize", primitive("boolean"), occurs.optional),
        field("trade", primitive("boolean"), occurs.optional),
        field("coexist", primitive("boolean"), occurs.optional),
      ]),
      occurs.one,
    ),
  ],
});
