// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { between, block, defineType, field, item, occurs, primitive, taggedBlocks } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const bitmapfont: DefinitionType = defineType({
  id: DefinitionTypeId.Bitmapfont,
  source: taggedBlocks("interface", "name", [], true, {
    rootKeyFilter: { mode: "include", values: ["bitmapfont"] },
    container: { kind: "any-container" },
  }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("scalar"), occurs.one),
    field("path", primitive("scalar"), occurs.optional),
    field("fontfiles", block([item(primitive("scalar"), occurs.oneOrMore)]), occurs.optional),
    field("color", primitive("scalar"), occurs.one),
    field("cursor_offset", block([item(primitive("integer"), between(2, 2))]), occurs.optional),
    field("selection_offset", block([item(primitive("integer"), between(2, 2))]), occurs.optional),
  ],
});
