// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  field,
  keyedBlocks,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  triggerEntries,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const bombardmentStance: DefinitionType = defineType({
  id: DefinitionTypeId.BombardmentStance,
  source: keyedBlocks("common/bombardment_stances"),
  variants: [],
  localisation: [
    definitionLocalisation("Name", "bombardment_$", true),
    definitionLocalisation("Desc", "bombardment_$_desc", true),
  ],
  modifiers: [],
  entries: [
    field("trigger", block([triggerEntries()]), occurs.one, { scope: replaceScope({ root: ScopeId.Fleet }) }),
    field("default", primitive("boolean"), occurs.one, {
      documentation: "Is this the default stance that new fleets will use?",
    }),
    field("stop_when_armies_dead", primitive("boolean"), occurs.optional, {
      documentation: "Will this stance continue to bombard planets where all defensive armies are dead? default = no",
    }),
    field("stop_when_ground_combat", primitive("boolean"), occurs.optional),
    field("abduct_pops", primitive("boolean"), occurs.optional, {
      documentation:
        "Will this stance attempt to abduct pops to your own planets instead of killing them? default = no",
    }),
    field("accept_surrender", primitive("boolean"), occurs.optional, {
      documentation: "Will fleets in this stance consider accepting surrender? default = no",
    }),
    field("planet_damage", primitive("number"), occurs.optional, {
      documentation: "General scale of damage to planet, default = 1.0",
    }),
    field("army_damage", primitive("number"), occurs.optional, {
      documentation: "General scale of damage to armies, default = 1.0",
    }),
    field("kill_pop_chance", block([modifierRuleEntries()]), occurs.optional, {
      documentation: "Chance that a pop is killed when planetary damage reaches 100%, default = 0",
    }),
    field("min_pops_to_kill_pop", primitive("integer", { min: 0, max: null }), occurs.optional, {
      documentation:
        "Will not kill/abduct pops if pops <= this number already, default = 0. Doesn't work for nations that doesn't have diplomatic wars!",
    }),
    field(
      "kill_pop_amount",
      block([field("min", primitive("integer"), occurs.one), field("max", primitive("integer"), occurs.one)]),
      occurs.optional,
    ),
    field("ai_weight", block([modifierRuleEntries()]), occurs.one, {
      scope: replaceScope({ root: ScopeId.Fleet, from: ScopeId.Planet }),
    }),
    field(
      "planet_damage",
      block([field("base", primitive("integer"), occurs.one), modifierRuleEntries()]),
      occurs.optional,
    ),
  ],
});
