// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  anyScope,
  block,
  defineType,
  effectEntries,
  field,
  keyedBlocks,
  occurs,
  replaceScope,
  triggerEntries,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const buttonEffect: DefinitionType = defineType({
  id: DefinitionTypeId.ButtonEffect,
  source: keyedBlocks("common/button_effects"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("potential", block([triggerEntries()]), occurs.one, {
      scope: replaceScope({ root: anyScope(), from: ScopeId.Country }),
    }),
    field("allow", block([triggerEntries()]), occurs.one, {
      scope: replaceScope({ root: anyScope(), from: ScopeId.Country }),
    }),
    field("effect", block([effectEntries()]), occurs.optional, {
      scope: replaceScope({ root: anyScope(), from: ScopeId.Country }),
    }),
  ],
});
