// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  effectEntries,
  enumRef,
  field,
  fieldEquals,
  item,
  keyedBlocks,
  occurs,
  primitive,
  replaceScope,
  triggerEntries,
  typeRef,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const bypass: DefinitionType = defineType({
  id: DefinitionTypeId.Bypass,
  source: keyedBlocks("common/bypass"),
  variants: [{ id: "scripted", when: fieldEquals("connection_type", "scripted_connection") }],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("localisation"), occurs.one, {
      documentation: "the localization key used in triggers and effects for the type",
    }),
    field("is_pathfind", primitive("boolean"), occurs.one, {
      documentation:
        "whether this type can be automatically used by the pathfinding (otherwise you'll have to right click the object containing it)",
    }),
    field("requires_exploration", primitive("boolean"), occurs.optional, {
      documentation: "whether this bypass type needs to be 'seen' before it can be used",
    }),
    field("respect_closed_borders", primitive("boolean"), occurs.optional, {
      documentation:
        "whether use of this bypass type is blocked if the destination country has closed borders to you (default: no)",
    }),
    field("block_access_if_hostile", primitive("boolean"), occurs.optional, {
      documentation:
        "whether use of this bypass type is blocked if the destination country is hostile to you (default: no)",
    }),
    field("uses_action", primitive("boolean"), occurs.one, {
      documentation: "whether this type needs an action or can be used automagically",
    }),
    field("always_active", primitive("boolean"), occurs.one, {
      documentation:
        "whether bypasses of these types are automatically active on creation, or if they need to be researched/upgraded to be activated",
    }),
    field("windup_time", primitive("integer"), occurs.one, {
      documentation: 'time spent "prepping" in the system before going through the bypass',
    }),
    field("winddown_time", primitive("integer"), occurs.one, {
      documentation: 'time spent "recovering" in the system after going through the bypass',
    }),
    field("ftl_multiplier", primitive("number"), occurs.optional, { documentation: "0 means instant" }),
    field("extends_sensors", primitive("boolean"), occurs.optional, {
      documentation: 'whether you can "see through" the bypass and extends your sensor range to the other side',
    }),
    field("icon_frame", primitive("integer"), occurs.one),
    field("remember_instances", primitive("boolean"), occurs.one, {
      documentation:
        "whether countries remember meeting a specific instance of that type, or if they just remember seeing the type in general",
    }),
    field("galactic_map_tooltip_header", primitive("localisation"), occurs.one),
    field("galactic_map_tooltip_desc", primitive("localisation"), occurs.one),
    field("system_view_tooltip_header", primitive("localisation"), occurs.optional),
    field("connection_type", enumRef(EnumId.BypassConnectionType), occurs.one),
    field("ftl_ship_effect", primitive("scalar"), occurs.one, {
      documentation: "what effect to spawn on the ship when they jump through the bypass",
    }),
    field("ftl_bypass_effect", typeRef("model_entity"), occurs.one, {
      documentation: "what effect to spawn on the bypass when a ship jumps through",
    }),
    field("can_bypass_be_locked", primitive("boolean"), occurs.optional),
    field("bypass_effect", primitive("scalar"), occurs.optional),
    field("animation_time", primitive("integer"), occurs.one, {
      documentation: "number of days to wait for the jump animation to be played",
    }),
    field(
      "prerequisites",
      block([item(typeRef("technology"), occurs.oneOrMore, { severity: "information" })]),
      occurs.optional,
    ),
    field("on_pre_explore", block([effectEntries()]), occurs.optional, {
      documentation: 'an effect that is called just before the jump of a right click "explore" action of a fleet',
    }),
    field("country_can_use", block([triggerEntries()]), occurs.optional, {
      documentation:
        "trigger to evaluate if a country can use bypasses of this type. this: country, from: (optional) system owner; default: { always = yes }",
      scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Country }),
    }),
    field("potential", block([triggerEntries()]), occurs.optional),
    field("on_action", primitive("scalar"), occurs.optional, {
      documentation:
        "The name of the on-action event that will be fired upon entering FTL (if set) THIS = Fleet FROM = System jumping to FROMFROM = System jumped from",
    }),
    whenVariant("scripted", [
      field(
        "scripted_connection",
        block([
          field("node", block([triggerEntries()]), occurs.one, {
            documentation: 'defines endpoints that can only reach the "nexus"',
            scope: replaceScope({ root: ScopeId.System }),
          }),
          field("nexus", block([triggerEntries()]), occurs.one, {
            documentation: 'defines endpoint(s) that can reach all "nodes" (but not other nexuses)',
            scope: replaceScope({ root: ScopeId.System }),
          }),
        ]),
        occurs.one,
      ),
    ]),
  ],
});
