// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  effectEntries,
  field,
  keyedBlocks,
  literal,
  occurs,
  primitive,
  replaceScope,
  triggerEntries,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const cloudType: DefinitionType = defineType({
  id: DefinitionTypeId.CloudType,
  source: keyedBlocks("common/dust_clouds"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field(
      "textures",
      block([
        field("opacity_texture", primitive("file"), occurs.one),
        field("diffuse_texture", primitive("file"), occurs.one),
        field("lightning_texture_atlas", primitive("file"), occurs.one),
        field("lightning_horisontal_tiles", primitive("integer"), occurs.one),
        field("lightning_vertical_tiles", primitive("integer"), occurs.one),
      ]),
      occurs.one,
    ),
    field(
      "parameters",
      block([
        field("min_size", primitive("number"), occurs.one),
        field("max_size", primitive("number"), occurs.one),
        field("size_change_speed", primitive("number"), occurs.one),
        field("rotation_speed", primitive("number"), occurs.one),
        field("counter_rotation_speed", primitive("number"), occurs.one),
        field("min_opacity", primitive("number"), occurs.one),
        field("max_opacity", primitive("number"), occurs.one),
        field("opacity_change_speed", primitive("number"), occurs.one),
        field("lightning_intencity_min", primitive("number"), occurs.one),
        field("lightning_intencity_max", primitive("number"), occurs.one),
        field("lightning_duration_min", primitive("number"), occurs.one),
        field("lightning_duration_max", primitive("number"), occurs.one),
        field("lightning_switch_interval_min", primitive("number"), occurs.one),
        field("lightning_switch_interval_max", primitive("number"), occurs.one),
        field("size_change_reversion", primitive("boolean"), occurs.one),
        field("opacity_change_reversion", primitive("boolean"), occurs.one),
      ]),
      occurs.one,
    ),
    field(
      "ambient_object",
      block([
        field("type", literal("synth_queen_tempest"), occurs.one),
        field("scale", primitive("number"), occurs.one),
        field("centric", primitive("boolean"), occurs.one),
      ]),
      occurs.optional,
    ),
    field("on_system_added", block([effectEntries()]), occurs.optional, {
      scope: replaceScope({ from: ScopeId.Country }),
    }),
    field("on_system_removed", block([effectEntries()]), occurs.optional, {
      scope: replaceScope({ from: ScopeId.Country }),
    }),
    field("condition", block([triggerEntries()]), occurs.optional),
  ],
});
