// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import { defineType, keyedBlocks } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const colonyAutomationException: DefinitionType = defineType({
  id: DefinitionTypeId.ColonyAutomationException,
  source: keyedBlocks("common/colony_automation_exceptions"),
  entryScope: ScopeId.Planet,
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [],
});
