// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, field, keyedBlocks, literal, occurs, primitive } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const colorDefine: DefinitionType = defineType({
  id: DefinitionTypeId.ColorDefine,
  source: keyedBlocks("flags", true, { container: { kind: "named-container", key: "colors" } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("flag", primitive("colour", undefined, undefined, "rgb"), occurs.one),
    field("flag", primitive("colour", undefined, undefined, "hsv"), occurs.one),
    field("map", primitive("colour", undefined, undefined, "rgb"), occurs.one),
    field("map", primitive("colour", undefined, undefined, "hsv"), occurs.one),
    field("ship", primitive("colour", undefined, undefined, "rgb"), occurs.one),
    field("ship", primitive("colour", undefined, undefined, "hsv"), occurs.one),
    field("use_as_border_color", literal(false), occurs.optional),
  ],
});
