// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import {
  defineType,
  definitionLocalisation,
  field,
  fieldEquals,
  occurs,
  primitive,
  taggedBlocks,
  typeRef,
  unlessVariant,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const componentSet: DefinitionType = defineType({
  id: DefinitionTypeId.ComponentSet,
  source: taggedBlocks("common/component_sets", "key", []),
  variants: [{ id: "required_component", when: fieldEquals("required_component_set", true) }],
  localisation: [
    definitionLocalisation("Name", "", true),
    definitionLocalisation("Description", "_DESC", false),
    definitionLocalisation("Ship Description", "ship_$_DESC", false),
    definitionLocalisation("Station Description", "station_$_DESC", false),
  ],
  modifiers: [],
  entries: [
    field("required_component_set", primitive("boolean"), occurs.optional),
    field("is_core_component_set", primitive("boolean"), occurs.optional),
    field("affects_target_type", primitive("boolean"), occurs.optional),
    field("is_space_fauna_component_set", primitive("boolean"), occurs.optional),
    field("is_default_space_fauna_component_set", primitive("boolean"), occurs.optional),
    whenVariant("required_component", [
      field("key", primitive("scalar"), occurs.one),
      field("icon", primitive("scalar"), occurs.optional),
      field("icon_frame", primitive("scalar"), occurs.optional),
    ]),
    unlessVariant("required_component", [
      field("key", primitive("localisation"), occurs.one),
      field("icon", typeRef("sprite"), occurs.one),
      field("icon_frame", primitive("integer"), occurs.one),
    ]),
  ],
});
