// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import {
  block,
  defineType,
  effectEntries,
  field,
  keyedBlocks,
  literal,
  occurs,
  primitive,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const cosmicStormMission: DefinitionType = defineType({
  id: DefinitionTypeId.CosmicStormMission,
  source: keyedBlocks("common/missions"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("desc", primitive("localisation"), occurs.one),
    field("event_chain", typeRef("event_chain"), occurs.one),
    field("icon", primitive("file"), occurs.one),
    field("picture", typeRef("sprite"), occurs.one),
    field("location", literal(true), occurs.optional),
    field("abort_trigger", block([triggerEntries()]), occurs.one),
    field(
      "counter",
      block([field("localisation", block([field("max", primitive("integer"), occurs.optional)]), occurs.any)]),
      occurs.any,
    ),
    field("on_daily", block([effectEntries()]), occurs.optional),
    field("on_monthly", block([effectEntries()]), occurs.optional),
    field("on_stop", block([effectEntries()]), occurs.optional),
    field("on_success", block([effectEntries()]), occurs.optional),
    field("desc", primitive("localisation"), occurs.one),
    field("event_chain", typeRef("event_chain"), occurs.one),
    field("icon", primitive("file"), occurs.one),
    field("picture", typeRef("sprite"), occurs.one),
    field("location", literal(true), occurs.optional),
    field("abort_trigger", block([triggerEntries()]), occurs.one),
    field(
      "counter",
      block([field("localisation", block([field("max", primitive("integer"), occurs.optional)]), occurs.any)]),
      occurs.any,
    ),
    field("on_daily", block([effectEntries()]), occurs.optional),
    field("on_monthly", block([effectEntries()]), occurs.optional),
    field("on_stop", block([effectEntries()]), occurs.optional),
    field("on_success", block([effectEntries()]), occurs.optional),
  ],
});
