// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  field,
  keyedBlocks,
  modifierEntries,
  modifierRuleEntries,
  occurs,
  primitive,
  scriptValue,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const councilAgenda: DefinitionType = defineType({
  id: DefinitionTypeId.CouncilAgenda,
  source: keyedBlocks("common/council_agendas"),
  variants: [],
  localisation: [
    definitionLocalisation("Name", "council_agenda_$_name", true),
    definitionLocalisation("Description", "council_agenda_$_desc", true),
    definitionLocalisation("Alternate Description (Hive)", "council_agenda_$_desc_hive", false),
    definitionLocalisation("Alternate Description (Machine)", "council_agenda_$_desc_machine", false),
    definitionLocalisation("Effect", "council_agenda_$_effect", false),
  ],
  modifiers: [],
  entries: [
    field("agenda_cost", scriptValue("number"), occurs.one),
    field("agenda_cooldown", scriptValue("number"), occurs.optional, {
      documentation:
        "Optional, Overrides COUNCIL_AGENDA_COOLDOWN define, how many days until the agenda can be selected again",
    }),
    field("potential", block([triggerEntries()]), occurs.one),
    field("allow", block([triggerEntries()]), occurs.one),
    field("initial_effect_custom_loc", primitive("localisation"), occurs.optional, {
      documentation: "Custom localization for the initial effect, if you're using weird on_actions to have one",
    }),
    field("modifier", block([modifierEntries()]), occurs.optional, {
      documentation:
        "Modifiers applied while the agenda is active (being prepared); usually similar but smaller modifiers compared to the finish_modifier",
    }),
    field("init_effect", block([effectEntries()]), occurs.optional),
    field("effect", block([effectEntries()]), occurs.optional, {
      documentation: "Effects executed once the agenda is finished (launched); displayed in the agenda tooltip",
    }),
    field("agenda_finish_modifier_duration", scriptValue("number"), occurs.optional, {
      documentation:
        "Optional, Overrides COUNCIL_AGENDA_FINISH_MODIFIER_DURATION define how many days the agenda's finish_modifier lasts for",
    }),
    field("finish_modifier", typeRef("static_modifier"), occurs.optional, {
      documentation: "Static modifier applied to the country upon finishing (launching) the agenda",
    }),
    field("ai_weight", block([modifierRuleEntries()]), occurs.optional),
  ],
});
