// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  field,
  keyedBlocks,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  typeKey,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const countryCustomization: DefinitionType = defineType({
  id: DefinitionTypeId.CountryCustomization,
  source: keyedBlocks("common/country_customization"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field(
      "colony_shelter",
      block([
        field("default", typeRef("building"), occurs.one),
        field(typeKey("planet_class"), typeRef("building"), occurs.any),
      ]),
      occurs.one,
    ),
    field(
      "graphical_culture_for_random_empire",
      block([
        field(
          typeKey("graphical_culture"),
          block([
            field(
              "modifier",
              block([
                field("add", primitive("integer"), occurs.one),
                field("species_portrait", typeRef("portrait"), occurs.optional),
                field("OR", block([field("species_portrait", typeRef("portrait"), occurs.any)]), occurs.optional),
              ]),
              occurs.any,
            ),
            field(
              "modifier",
              block([
                field("add", primitive("integer"), occurs.one),
                field("graphical_culture", typeRef("graphical_culture"), occurs.one),
              ]),
              occurs.any,
            ),
          ]),
          occurs.any,
        ),
      ]),
      occurs.optional,
    ),
    field("weight", block([modifierRuleEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
  ],
});
