// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  enumRef,
  field,
  keyedBlocks,
  literal,
  modifierRuleEntries,
  occurs,
  triggerEntries,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const crisisObjective: DefinitionType = defineType({
  id: DefinitionTypeId.CrisisObjective,
  source: keyedBlocks("common/crisis_objectives"),
  variants: [],
  localisation: [definitionLocalisation("Name", "_name", true), definitionLocalisation("Description", "_desc", true)],
  modifiers: [],
  entries: [
    field("potential", block([triggerEntries()]), occurs.optional),
    field(
      "reward",
      block([modifierRuleEntries(), field("divide", enumRef(EnumId.ExeSetVariable), occurs.optional)]),
      occurs.one,
    ),
    field("recurring", literal(true), occurs.optional),
    field("potential", block([triggerEntries()]), occurs.optional),
    field(
      "reward",
      block([modifierRuleEntries(), field("divide", enumRef(EnumId.ExeSetVariable), occurs.optional)]),
      occurs.one,
    ),
    field("recurring", literal(true), occurs.optional),
  ],
});
