// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, field, item, keyedBlocks, occurs, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const crisisPath: DefinitionType = defineType({
  id: DefinitionTypeId.CrisisPath,
  source: keyedBlocks("common/crisis_paths"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("crisis_currency", typeRef("resource"), occurs.one),
    field("levels", block([item(typeRef("crisis_level"), occurs.any)]), occurs.one),
    field("objectives", block([item(typeRef("crisis_objective"), occurs.any)]), occurs.one),
  ],
});
