// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import {
  block,
  defineType,
  effectEntries,
  field,
  item,
  keyedBlocks,
  occurs,
  primitive,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const crisisLevel: DefinitionType = defineType({
  id: DefinitionTypeId.CrisisLevel,
  source: keyedBlocks("common/crisis_levels"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("allow", block([triggerEntries()]), occurs.optional),
    field("required_crisis_currency", primitive("integer"), occurs.one),
    field("perks", block([item(typeRef("menace_perk"), occurs.any)]), occurs.one),
    field("on_unlock", block([effectEntries()]), occurs.one),
    field("allow", block([triggerEntries()]), occurs.optional),
    field("required_crisis_currency", primitive("integer"), occurs.one),
    field("perks", block([item(typeRef("menace_perk"), occurs.any)]), occurs.one),
    field("on_unlock", block([effectEntries()]), occurs.one),
  ],
});
