// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  field,
  item,
  keyedBlocks,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const decision: DefinitionType = defineType({
  id: DefinitionTypeId.Decision,
  source: keyedBlocks("common/decisions"),
  variants: [],
  localisation: [definitionLocalisation("name", "$", true), definitionLocalisation("desc", "$_desc", true)],
  modifiers: [],
  entries: [
    field("owned_planets_only", primitive("boolean"), occurs.optional),
    field("enactment_time", primitive("integer"), occurs.optional),
    field("sound", typeRef("sound"), occurs.optional),
    field("sound", typeRef("sound_effect"), occurs.optional),
    field("icon", primitive("icon", undefined, "gfx/interface/icons/decisions"), occurs.optional),
    field("icon", typeRef("decision"), occurs.optional),
    field(
      "custom_tooltip",
      block([field("success_text", primitive("localisation"), occurs.optional), triggerEntries()]),
      occurs.optional,
    ),
    field(
      "resources",
      block([field("category", typeRef("economic_category"), occurs.optional), ruleSetEntries("economic_template")]),
      occurs.optional,
    ),
    field("show_tech_unlock_if", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("potential", block([triggerEntries()]), occurs.optional),
    field("allow", block([triggerEntries()]), occurs.optional),
    field("abort_trigger", block([triggerEntries()]), occurs.optional),
    field("abort_effect", block([effectEntries()]), occurs.optional),
    field("on_queued", block([effectEntries()]), occurs.optional),
    field("on_unqueued", block([effectEntries()]), occurs.optional),
    field("effect", block([effectEntries()]), occurs.one),
    field("ai_weight", block([modifierRuleEntries()]), occurs.optional),
    field("prerequisites", block([item(typeRef("technology"), occurs.oneOrMore)]), occurs.optional),
  ],
});
