// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  enumKey,
  field,
  fileDefinitions,
  literal,
  modifierRuleEntries,
  occurs,
  replaceScope,
  rootKeyIs,
  triggerEntries,
  typeKey,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const diploPhrase: DefinitionType = defineType({
  id: DefinitionTypeId.DiploPhrase,
  source: fileDefinitions("common/diplo_phrases"),
  variants: [
    { id: "greetings", when: rootKeyIs("greetings") },
    { id: "action_ask", when: rootKeyIs("action_ask_to_become") },
    { id: "action_demand", when: rootKeyIs("action_demand_") },
    { id: "trade_offer", when: rootKeyIs("action_offer_trade_deal") },
    { id: "declare_war", when: rootKeyIs("action_declare_war") },
  ],
  localisation: [],
  modifiers: [],
  entries: [
    field(
      "greetings",
      block([
        field(
          "localisation",
          block([
            field("trigger", block([triggerEntries()]), occurs.one, {
              scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Country }),
            }),
            field("weight", block([modifierRuleEntries()]), occurs.any),
          ]),
          occurs.any,
        ),
      ]),
      occurs.optional,
    ),
    field(
      "action_ask",
      block([
        field(
          enumKey(EnumId.DiploPhraseTypes),
          block([
            field(
              "localisation",
              block([
                field("trigger", block([triggerEntries()]), occurs.one, {
                  scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Country }),
                }),
                field("weight", block([modifierRuleEntries()]), occurs.any),
                field("only_for_trade", literal(true), occurs.optional, {
                  documentation: "Only with action_offer_trade_deal",
                }),
                field("only_for_gift", literal(true), occurs.optional, {
                  documentation: "Only with action_offer_trade_deal",
                }),
              ]),
              occurs.any,
            ),
          ]),
          occurs.one,
        ),
      ]),
      occurs.any,
    ),
    field(
      "action_demand",
      block([
        field(
          enumKey(EnumId.DiploPhraseTypes),
          block([
            field(
              "localisation",
              block([
                field("trigger", block([triggerEntries()]), occurs.one, {
                  scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Country }),
                }),
                field("weight", block([modifierRuleEntries()]), occurs.any),
                field("only_for_trade", literal(true), occurs.optional, {
                  documentation: "Only with action_offer_trade_deal",
                }),
                field("only_for_gift", literal(true), occurs.optional, {
                  documentation: "Only with action_offer_trade_deal",
                }),
              ]),
              occurs.any,
            ),
          ]),
          occurs.one,
        ),
      ]),
      occurs.any,
    ),
    field(
      typeKey("diplomatic_action"),
      block([
        field(
          enumKey(EnumId.DiploPhraseTypes),
          block([
            field(
              "localisation",
              block([
                field("trigger", block([triggerEntries()]), occurs.optional, {
                  scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Country }),
                }),
                field("weight", block([modifierRuleEntries()]), occurs.any),
                field("only_for_trade", literal(true), occurs.optional, {
                  documentation: "Only with action_offer_trade_deal",
                }),
                field("only_for_gift", literal(true), occurs.optional, {
                  documentation: "Only with action_offer_trade_deal",
                }),
              ]),
              occurs.any,
            ),
          ]),
          occurs.any,
        ),
      ]),
      occurs.any,
    ),
    field(
      enumKey(EnumId.ExclusiveDiplomacyAsk),
      block([
        field(
          enumKey(EnumId.DiploPhraseTypes),
          block([
            field(
              "localisation",
              block([
                field("trigger", block([triggerEntries()]), occurs.one, {
                  scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Country }),
                }),
                field("weight", block([modifierRuleEntries()]), occurs.any),
                field("only_for_trade", literal(true), occurs.optional, {
                  documentation: "Only with action_offer_trade_deal",
                }),
                field("only_for_gift", literal(true), occurs.optional, {
                  documentation: "Only with action_offer_trade_deal",
                }),
              ]),
              occurs.any,
            ),
          ]),
          occurs.any,
        ),
      ]),
      occurs.any,
    ),
    field(
      enumKey(EnumId.ExclusiveDiplomacyDemand),
      block([
        field(
          enumKey(EnumId.DiploPhraseTypes),
          block([
            field(
              "localisation",
              block([
                field("trigger", block([triggerEntries()]), occurs.one, {
                  scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Country }),
                }),
                field("weight", block([modifierRuleEntries()]), occurs.any),
                field("only_for_trade", literal(true), occurs.optional, {
                  documentation: "Only with action_offer_trade_deal",
                }),
                field("only_for_gift", literal(true), occurs.optional, {
                  documentation: "Only with action_offer_trade_deal",
                }),
              ]),
              occurs.any,
            ),
          ]),
          occurs.any,
        ),
      ]),
      occurs.any,
    ),
  ],
});
