// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  enumRef,
  field,
  fieldEquals,
  generatedModifier,
  item,
  keyedBlocks,
  modifierEntries,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const district: DefinitionType = defineType({
  id: DefinitionTypeId.District,
  source: keyedBlocks("common/districts"),
  entryScope: ScopeId.Planet,
  variants: [
    { id: "capped", when: fieldEquals("is_capped_by_modifier", true) },
    { id: "uncapped", when: fieldEquals("is_capped_by_modifier", false) },
  ],
  localisation: [
    definitionLocalisation("Name", "", true),
    definitionLocalisation("Desc", "_desc", true),
    definitionLocalisation("Plural", "_plural", true),
  ],
  modifiers: [generatedModifier("planet_", "_build_speed_mult", "Planets")],
  entries: [
    field("is_uncapped", block([triggerEntries()]), occurs.optional),
    field("base_cap_amount", primitive("integer"), occurs.optional),
    field("default_starting_district", primitive("boolean"), occurs.optional),
    field("inherits_capped_modifiers_from", typeRef("district"), occurs.optional),
    field("expansion_planner", primitive("boolean"), occurs.optional),
    field("base_buildtime", primitive("integer"), occurs.optional, { documentation: "Default = 0" }),
    field("desc", primitive("localisation"), occurs.any),
    field(
      "desc",
      block([
        field("trigger", block([triggerEntries()]), occurs.one),
        field("text", primitive("localisation"), occurs.one),
      ]),
      occurs.any,
    ),
    field(
      "triggered_name",
      block([
        field("trigger", block([triggerEntries()]), occurs.optional),
        field("text", primitive("localisation"), occurs.optional),
      ]),
      occurs.any,
    ),
    field(
      "triggered_flavor_desc",
      block([
        field("trigger", block([triggerEntries()]), occurs.optional),
        field("text", primitive("localisation"), occurs.optional),
      ]),
      occurs.any,
    ),
    field("min_for_deposits_on_planet", primitive("integer"), occurs.optional),
    field("max_for_deposits_on_planet", primitive("integer"), occurs.optional),
    field("icon", primitive("icon", undefined, "gfx/interface/icons/districts"), occurs.optional),
    field("overlay_icon", typeRef("sprite"), occurs.optional),
    field("gridbox", enumRef(EnumId.Gridbox), occurs.optional),
    field("is_capped_by_modifier", primitive("boolean"), occurs.optional),
    field("expansion_planner", primitive("boolean"), occurs.optional, {
      documentation: "whether this district should be shown in the expansion planner;",
    }),
    field("exempt_from_ai_planet_specialization", primitive("boolean"), occurs.optional, {
      documentation: "whether this district is exempt from being swapped into groups by the AI; default: no",
    }),
    field("can_demolish", primitive("boolean"), occurs.optional),
    field("destroy_trigger", block([triggerEntries()]), occurs.optional),
    field("show_tech_unlock_if", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("show_on_uncolonized", block([triggerEntries()]), occurs.optional),
    field("potential", block([triggerEntries()]), occurs.one),
    field("allow", block([triggerEntries()]), occurs.optional),
    field("on_queued", block([effectEntries()]), occurs.optional),
    field("on_unqueued", block([effectEntries()]), occurs.optional),
    field("on_built", block([effectEntries()]), occurs.optional),
    field("on_destroy", block([effectEntries()]), occurs.optional),
    field("prerequisites", block([item(typeRef("technology"), occurs.any)]), occurs.optional),
    field("conversion_ratio", primitive("number"), occurs.optional),
    field("convert_to", block([item(typeRef("district"), occurs.any)]), occurs.optional),
    field("expansion_planner_type", typeRef("district"), occurs.optional),
    field(
      "resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.optional,
    ),
    field("zone_slots", block([item(typeRef("zone_slots"), occurs.any)]), occurs.optional),
    field("planet_modifier", block([modifierEntries()]), occurs.any, { scope: replaceScope({ root: ScopeId.Planet }) }),
    ruleSetEntries("triggered_planet_modifier_planet"),
    ruleSetEntries("triggered_desc"),
    field("ai_weight", block([modifierRuleEntries()]), occurs.optional),
    ruleSetEntries("ai_resource_production"),
    field("ai_estimate_without_unemployment", primitive("boolean"), occurs.optional),
    field("additional_ai_weight", primitive("integer"), occurs.optional),
    field("ai_weight_coefficient", primitive("number"), occurs.optional),
  ],
});
