// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  field,
  keyedBlocks,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  triggerEntries,
  typeKey,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const economicPlan: DefinitionType = defineType({
  id: DefinitionTypeId.EconomicPlan,
  source: keyedBlocks("common/economic_plans"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("income", block([field(typeKey("resource"), primitive("integer"), occurs.oneOrMore)]), occurs.optional),
    field("focus", block([field(typeKey("resource"), primitive("integer"), occurs.oneOrMore)]), occurs.optional),
    field(
      "subplan",
      block([
        field("potential", block([triggerEntries()]), occurs.optional, {
          scope: replaceScope({ root: ScopeId.Country }),
        }),
        field("income", block([field(typeKey("resource"), primitive("integer"), occurs.oneOrMore)]), occurs.optional),
        field("focus", block([field(typeKey("resource"), primitive("integer"), occurs.oneOrMore)]), occurs.optional),
        field("pops", primitive("integer"), occurs.optional),
        field("empire_size", primitive("number"), occurs.optional),
        field("naval_cap", primitive("integer"), occurs.optional),
        field("set_name", primitive("scalar"), occurs.optional),
        field("scaling", primitive("boolean"), occurs.optional),
        field("optional", primitive("boolean"), occurs.optional),
      ]),
      occurs.oneOrMore,
    ),
    field("pops", primitive("integer"), occurs.optional),
    field("empire_size", primitive("number"), occurs.optional),
    field("naval_cap", primitive("integer"), occurs.optional),
    field("ai_weight", block([modifierRuleEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
  ],
});
