// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import {
  between,
  block,
  defineType,
  enumRef,
  field,
  fieldEquals,
  fieldPresent,
  item,
  keyedBlocks,
  literal,
  occurs,
  primitive,
  triggerEntries,
  typeRef,
  unlessVariant,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const economicCategory: DefinitionType = defineType({
  id: DefinitionTypeId.EconomicCategory,
  source: keyedBlocks("common/economic_categories"),
  variants: [
    { id: "has_parent", when: fieldPresent("parent") },
    { id: "hidden", when: fieldEquals("hidden", true) },
  ],
  localisation: [],
  modifiers: [],
  entries: [
    field("parent", typeRef("economic_category"), occurs.optional),
    field("use_for_ai_budget", primitive("boolean"), occurs.optional),
    unlessVariant("hidden", [field("icon", primitive("scalar"), occurs.one)]),
    whenVariant("hidden", [field("hidden", literal(true), occurs.one)]),
    field("modifier_category", enumRef(EnumId.ScriptedModifierCategories), occurs.any),
    field("hidden", primitive("boolean"), occurs.optional),
    field("category", enumRef(EnumId.ScriptedModifierCategories), occurs.optional, {
      documentation:
        "sets the modifier category, which is sometimes used to determine whether it is applied to a certain object (so make sure this is set to what you want)",
    }),
    field(
      "triggered_produces_modifier",
      block([
        whenVariant("has_parent", [field("use_parent_icon", literal(true), occurs.optional)]),
        field("key", primitive("scalar"), occurs.one),
        field("use_parent_icon", literal(true), occurs.optional),
        field("trigger", block([triggerEntries()]), occurs.optional),
        field("modifier_types", block([item(enumRef(EnumId.EconomicModifierTypes), between(0, 2))]), occurs.one),
      ]),
      occurs.any,
    ),
    field(
      "triggered_cost_modifier",
      block([
        field("key", primitive("scalar"), occurs.one),
        field("use_parent_icon", literal(true), occurs.optional),
        field("trigger", block([triggerEntries()]), occurs.optional),
        field("use_parent_icon", literal(true), occurs.optional),
        field("modifier_types", block([item(enumRef(EnumId.EconomicModifierTypes), between(0, 2))]), occurs.one),
      ]),
      occurs.any,
    ),
    field(
      "triggered_upkeep_modifier",
      block([
        field("key", primitive("scalar"), occurs.one),
        field("use_parent_icon", literal(true), occurs.optional),
        field("trigger", block([triggerEntries()]), occurs.optional),
        field("modifier_types", block([item(enumRef(EnumId.EconomicModifierTypes), between(0, 2))]), occurs.one),
      ]),
      occurs.any,
    ),
    field("ai_use_parent_for_resources_upkeep", block([item(typeRef("resource"), occurs.oneOrMore)]), occurs.optional),
    field(
      "generate_mult_modifiers",
      block([item(enumRef(EnumId.EconomicModifierCategories), between(0, 3))]),
      between(0, 2),
    ),
    field(
      "generate_add_modifiers",
      block([item(enumRef(EnumId.EconomicModifierCategories), between(0, 3))]),
      between(0, 2),
    ),
    field("add_unscaled_value_to_tooltip", primitive("boolean"), occurs.optional),
    field("scaled_value_key", primitive("localisation"), occurs.optional),
  ],
});
