// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  between,
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  field,
  fieldEquals,
  item,
  keyedBlocks,
  literal,
  modifierEntries,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  triggerEntries,
  typeRef,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const edict: DefinitionType = defineType({
  id: DefinitionTypeId.Edict,
  source: keyedBlocks("common/edicts"),
  variants: [{ id: "edict_ambition", when: fieldEquals("is_ambition", true) }],
  localisation: [
    definitionLocalisation("Name", "edict_$", true),
    definitionLocalisation("Description", "edict_$_desc", true),
  ],
  modifiers: [],
  entries: [
    field("length", primitive("integer"), occurs.one),
    field("icon", typeRef("sprite"), occurs.one),
    field("is_wartime_edict", literal(true), occurs.optional),
    field("edict_lock_in_months", primitive("integer"), occurs.optional),
    field("edict_cap_usage", primitive("integer"), occurs.optional),
    whenVariant("edict_ambition", [field("is_ambition", literal(true), occurs.one)]),
    field(
      "resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.optional,
    ),
    field("unity_cost_mult", primitive("number"), occurs.optional),
    field(
      "modifier",
      block([
        field("custom_tooltip", primitive("localisation"), occurs.optional),
        field("show_only_custom_tooltip", primitive("boolean"), occurs.optional),
        modifierEntries(),
      ]),
      occurs.any,
      { scope: replaceScope({ root: ScopeId.Country }) },
    ),
    field("relay_network_modifier", block([modifierEntries()]), occurs.optional),
    field("potential", block([triggerEntries()]), occurs.any),
    field("allow", block([triggerEntries()]), occurs.optional),
    field("prerequisites", block([item(typeRef("technology"), between(0, 100))]), occurs.optional),
    field("show_tech_unlock_if", block([triggerEntries()]), occurs.optional),
    field("ai_weight", block([modifierRuleEntries()]), occurs.optional),
    field("effect", block([effectEntries()]), occurs.optional),
    field("on_disabled", block([effectEntries()]), occurs.optional),
    ruleSetEntries("triggered_country_modifier_country"),
  ],
});
