// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, field, item, occurs, primitive, primitiveKey, taggedBlocks, valueSet } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const empireNamePartsList: DefinitionType = defineType({
  id: DefinitionTypeId.EmpireNamePartsList,
  source: taggedBlocks("common/random_names", "key", [], true, {
    rootKeyFilter: { mode: "include", values: ["empire_name_parts_list"] },
  }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("key", valueSet("empire_name_parts"), occurs.one, {
      documentation: "Unique ID by which list can be referred to from name format via <key>.",
    }),
    field(
      "parts",
      block([
        field(primitiveKey("localisation"), primitive("integer"), occurs.any),
        item(primitive("localisation"), occurs.any),
      ]),
      occurs.one,
      { documentation: "List of possible parts. Random weights to the right are optional" },
    ),
  ],
});
