// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  enumRef,
  field,
  fieldEquals,
  item,
  keyedBlocks,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  triggerEntries,
  typeRef,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const espionageOperation: DefinitionType = defineType({
  id: DefinitionTypeId.EspionageOperation,
  source: keyedBlocks("common/espionage_operation_types"),
  variants: [
    { id: "no_target", when: fieldEquals("target", "none") },
    { id: "megastructure", when: fieldEquals("target", "megastructure") },
    { id: "country", when: fieldEquals("target", "country") },
    { id: "fleet", when: fieldEquals("target", "fleet") },
    { id: "army", when: fieldEquals("target", "army") },
    { id: "pop_faction", when: fieldEquals("target", "pop_faction") },
    { id: "federation", when: fieldEquals("target", "federation") },
    { id: "starbase", when: fieldEquals("target", "starbase") },
    { id: "spynetwork", when: fieldEquals("target", "spynetwork") },
  ],
  localisation: [definitionLocalisation("Name", "", true)],
  modifiers: [],
  entries: [
    field("target", enumRef(EnumId.EspionageOperationTargets), occurs.optional),
    field("categories", block([item(typeRef("espionage_category"), occurs.oneOrMore)]), occurs.one),
    field("picture", typeRef("sprite"), occurs.one),
    field("desc", primitive("localisation"), occurs.oneOrMore),
    field(
      "desc",
      block([
        field("trigger", block([triggerEntries()]), occurs.one),
        field("text", primitive("localisation"), occurs.one),
      ]),
      occurs.oneOrMore,
    ),
    field("stages", primitive("integer"), occurs.one),
    field("spy_power_cost", primitive("integer"), occurs.one),
    field(
      "resources",
      block([
        field("category", typeRef("economic_category"), occurs.one),
        ruleSetEntries("economic_template_no_produce"),
      ]),
      occurs.one,
    ),
    field("potential", block([triggerEntries()]), occurs.one),
    field("allow", block([triggerEntries()]), occurs.one),
    field("abort", block([triggerEntries()]), occurs.optional),
    whenVariant("megastructure", [
      field("target_allow", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Megastructure }),
      }),
      field("target_potential", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Megastructure }),
      }),
    ]),
    whenVariant("country", [
      field("target_allow", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Country }),
      }),
      field("target_potential", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Country }),
      }),
    ]),
    whenVariant("fleet", [
      field("target_allow", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Fleet }),
      }),
      field("target_potential", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Fleet }),
      }),
    ]),
    whenVariant("army", [
      field("target_allow", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Megastructure }),
      }),
      field("target_potential", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Megastructure }),
      }),
    ]),
    whenVariant("pop_faction", [
      field("target_allow", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.PopFaction }),
      }),
      field("target_potential", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.PopFaction }),
      }),
    ]),
    whenVariant("federation", [
      field("target_allow", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Federation }),
      }),
      field("target_potential", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Federation }),
      }),
    ]),
    whenVariant("starbase", [
      field("target_allow", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Starbase }),
      }),
      field("target_potential", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Starbase }),
      }),
    ]),
    whenVariant("spynetwork", [
      field("target_allow", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.SpyNetwork }),
      }),
      field("target_potential", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.SpyNetwork }),
      }),
    ]),
    field(
      "stage",
      block([
        field("difficulty", primitive("integer"), occurs.one),
        field("icon", typeRef("sprite"), occurs.one),
        field("event", typeRef("event", "espionage_operation"), occurs.one),
      ]),
      occurs.oneOrMore,
    ),
    field("on_roll_failed", block([effectEntries()]), occurs.one),
    field("on_create", block([effectEntries()]), occurs.one),
  ],
});
