// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  field,
  keyedBlocks,
  occurs,
  primitive,
  replaceScope,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const eventChain: DefinitionType = defineType({
  id: DefinitionTypeId.EventChain,
  source: keyedBlocks("common/event_chains"),
  variants: [],
  localisation: [definitionLocalisation("Title", "_title", true), definitionLocalisation("Description", "_desc", true)],
  modifiers: [],
  entries: [
    field("icon", primitive("file"), occurs.optional),
    field("picture", typeRef("sprite"), occurs.optional),
    field(
      "counter",
      block([field("localisation", block([field("max", primitive("integer"), occurs.optional)]), occurs.any)]),
      occurs.any,
    ),
    field("abort_trigger", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("icon", primitive("file"), occurs.optional),
    field("picture", typeRef("sprite"), occurs.optional),
    field(
      "counter",
      block([field("localisation", block([field("max", primitive("integer"), occurs.optional)]), occurs.any)]),
      occurs.any,
    ),
    field("abort_trigger", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
  ],
});
