// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  allOf,
  anyKey,
  anyScope,
  anyValue,
  between,
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  enumRef,
  field,
  fieldEquals,
  fieldPresent,
  literal,
  modifierRuleEntries,
  namedValue,
  occurs,
  primitive,
  rootKeyIs,
  ruleSetEntries,
  scopeGroup,
  scopeKey,
  scopeRef,
  scriptValue,
  taggedBlocks,
  triggerEntries,
  typeRef,
  unlessVariant,
  valueSet,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const event: DefinitionType = defineType({
  id: DefinitionTypeId.Event,
  source: taggedBlocks("events", "id", []),
  variants: [
    {
      id: "country",
      when: rootKeyIs("country_event"),
      entryScope: ScopeId.Country,
      displayName: "Country Event",
      abbreviation: "CE",
    },
    { id: "observer", when: rootKeyIs("observer_event"), entryScope: ScopeId.Country, displayName: "Observer Event" },
    { id: "pop", when: rootKeyIs("pop_event"), entryScope: ScopeId.Pop, displayName: "Pop Event", abbreviation: "PoE" },
    {
      id: "pop_group",
      when: rootKeyIs("pop_group_event"),
      entryScope: ScopeId.PopGroup,
      displayName: "Pop Group Event",
      abbreviation: "PGE",
    },
    {
      id: "pop_faction",
      when: rootKeyIs("pop_faction_event"),
      entryScope: ScopeId.PopFaction,
      displayName: "Pop Faction Event",
      abbreviation: "PFE",
    },
    {
      id: "planet",
      when: rootKeyIs("planet_event"),
      entryScope: ScopeId.Planet,
      displayName: "Planet Event",
      abbreviation: "PE",
    },
    {
      id: "first_contact",
      when: rootKeyIs("first_contact_event"),
      entryScope: ScopeId.FirstContact,
      displayName: "First Contact Event",
      abbreviation: "FCE",
    },
    {
      id: "astral",
      when: rootKeyIs("astral_rift_event"),
      entryScope: ScopeId.AstralRift,
      displayName: "Astral Event",
      abbreviation: "ARE",
    },
    {
      id: "bypass",
      when: rootKeyIs("bypass_event"),
      entryScope: ScopeId.Bypass,
      displayName: "Bypass Event",
      abbreviation: "BPE",
    },
    {
      id: "ship",
      when: rootKeyIs("ship_event"),
      entryScope: ScopeId.Ship,
      displayName: "Ship Event",
      abbreviation: "SE",
    },
    {
      id: "fleet",
      when: rootKeyIs("fleet_event"),
      entryScope: ScopeId.Fleet,
      displayName: "Fleet Event",
      abbreviation: "FE",
    },
    {
      id: "system",
      when: rootKeyIs("system_event"),
      entryScope: ScopeId.System,
      displayName: "System Event",
      abbreviation: "SyE",
    },
    {
      id: "starbase",
      when: rootKeyIs("starbase_event"),
      entryScope: ScopeId.Starbase,
      displayName: "Starbase Event",
      abbreviation: "StE",
    },
    {
      id: "espionage_operation",
      when: rootKeyIs("espionage_operation_event"),
      entryScope: ScopeId.EspionageOperation,
      displayName: "Espionage Event",
      abbreviation: "EOE",
    },
    {
      id: "leader",
      when: rootKeyIs("leader_event"),
      entryScope: ScopeId.Leader,
      displayName: "Leader Event",
      abbreviation: "LE",
    },
    {
      id: "situation",
      when: rootKeyIs("situation_event"),
      entryScope: ScopeId.Situation,
      displayName: "Situation Event",
      abbreviation: "SiE",
    },
    {
      id: "agreement",
      when: rootKeyIs("agreement_event"),
      entryScope: ScopeId.Agreement,
      displayName: "Agreement Event",
      abbreviation: "AE",
    },
    { id: "scopeless", when: rootKeyIs("event") },
    { id: "hidden", when: fieldEquals("hide_window", true) },
    { id: "diplomatic", when: fieldEquals("diplomatic", true) },
    {
      id: "default",
      when: allOf(
        fieldEquals("hide_window", false),
        fieldEquals("diplomatic", false),
        fieldPresent("event_window_type"),
        fieldPresent("event_picture_background"),
      ),
    },
    { id: "leader_recruit", when: fieldEquals("event_window_type", "leader_recruit") },
    { id: "leader_story", when: fieldEquals("event_window_type", "leader_story") },
    { id: "triggered", when: fieldEquals("is_triggered_only", true) },
    { id: "inherited", when: fieldPresent("base") },
  ],
  localisation: [definitionLocalisation("title", "$title", false)],
  modifiers: [],
  entries: [
    field("id", primitive("scalar"), occurs.one),
    field("is_test_event", literal(true), occurs.optional),
    field("diplomatic_title", primitive("localisation"), occurs.optional),
    field("event_message_type", primitive("localisation"), occurs.optional),
    whenVariant("inherited", [
      field("base", typeRef("event"), occurs.one),
      field("desc_clear", literal(true), occurs.optional),
      field("option_clear", literal(true), occurs.optional),
      field("trigger_clear", literal(true), occurs.optional),
      field("picture_clear", literal(true), occurs.optional),
      field("show_sound_clear", literal(true), occurs.optional),
    ]),
    unlessVariant("hidden", [
      field("title", primitive("localisation"), occurs.one),
      field("desc", primitive("localisation"), occurs.one),
      field(
        "desc",
        block([
          field(
            "trigger",
            block([
              triggerEntries(),
              field(
                "switch",
                block([
                  field("trigger", primitive("scalar"), occurs.one),
                  field(
                    anyKey(),
                    block([
                      field(
                        "if",
                        block([
                          field("limit", block([triggerEntries()]), occurs.one),
                          field("text", primitive("localisation"), occurs.one),
                        ]),
                        occurs.optional,
                      ),
                      field("text", primitive("localisation"), occurs.optional),
                    ]),
                    between(2, null),
                  ),
                ]),
                occurs.optional,
              ),
              field(
                scopeKey(anyScope()),
                block([
                  triggerEntries(),
                  field(
                    "switch",
                    block([
                      field("trigger", primitive("scalar"), occurs.one),
                      field(
                        anyKey(),
                        block([
                          field(
                            "if",
                            block([
                              field("limit", block([triggerEntries()]), occurs.one),
                              field("text", primitive("localisation"), occurs.one),
                            ]),
                            occurs.optional,
                          ),
                          field("text", primitive("localisation"), occurs.optional),
                        ]),
                        between(2, null),
                      ),
                    ]),
                    occurs.optional,
                  ),
                ]),
                occurs.any,
              ),
            ]),
            occurs.optional,
          ),
          field(
            "exclusive_trigger",
            block([
              triggerEntries(),
              field(
                "switch",
                block([
                  field("trigger", primitive("scalar"), occurs.one),
                  field(
                    anyKey(),
                    block([
                      field(
                        "if",
                        block([
                          field("limit", block([triggerEntries()]), occurs.one),
                          field("text", primitive("localisation"), occurs.one),
                        ]),
                        occurs.optional,
                      ),
                      field("text", primitive("localisation"), occurs.optional),
                    ]),
                    between(2, null),
                  ),
                ]),
                occurs.optional,
              ),
              field(
                scopeKey(anyScope()),
                block([
                  triggerEntries(),
                  field(
                    "switch",
                    block([
                      field("trigger", primitive("scalar"), occurs.one),
                      field(
                        anyKey(),
                        block([
                          field(
                            "if",
                            block([
                              field("limit", block([triggerEntries()]), occurs.one),
                              field("text", primitive("localisation"), occurs.one),
                            ]),
                            occurs.optional,
                          ),
                          field("text", primitive("localisation"), occurs.optional),
                        ]),
                        between(2, null),
                      ),
                    ]),
                    occurs.optional,
                  ),
                ]),
                occurs.any,
              ),
            ]),
            occurs.optional,
          ),
          field("text", primitive("localisation"), occurs.any),
          field("show_sound", typeRef("sound_effect"), occurs.optional),
        ]),
        occurs.one,
      ),
      field("picture", typeRef("sprite"), occurs.any),
      field(
        "picture",
        block([
          field("picture", typeRef("sprite"), occurs.any),
          field(
            "picture",
            block([
              field("trigger", block([triggerEntries()]), occurs.one),
              field("picture", typeRef("sprite"), occurs.one),
            ]),
            occurs.any,
          ),
          field("trigger", block([triggerEntries()]), occurs.optional),
        ]),
        occurs.any,
      ),
      field("show_sound", typeRef("sound_effect"), occurs.any),
      field(
        "show_sound",
        block([
          field("sound", typeRef("sound_effect"), occurs.one),
          field("sound_is_advisor", primitive("boolean"), occurs.optional),
          field("trigger", block([triggerEntries()]), occurs.optional),
        ]),
        occurs.any,
      ),
      field("force_open", primitive("boolean"), occurs.optional, {
        documentation: "Force a diplomatic event to be viewed",
      }),
      field("location", scopeRef(ScopeId.Planet), occurs.optional),
      field("location", scopeRef(ScopeId.System), occurs.optional),
      field("location", scopeRef(ScopeId.Ship), occurs.optional),
      field("location", scopeRef(ScopeId.Fleet), occurs.optional),
      field("location", scopeRef(ScopeId.Country), occurs.optional),
      field("location", scopeRef(ScopeId.Pop), occurs.optional),
      field("location", scopeRef(ScopeId.Starbase), occurs.optional),
      field("location", scopeRef(ScopeId.Bypass), occurs.optional),
      field("location", scopeRef(ScopeId.AstralRift), occurs.optional),
      field("location", valueSet("event_target"), occurs.optional),
      field("event_chain", typeRef("event_chain"), occurs.optional),
      field("situation", scopeRef(ScopeId.Situation), occurs.optional),
      field("diplomatic", primitive("boolean"), occurs.optional),
      field("event_window_type", enumRef(EnumId.EventWindowType), occurs.optional),
      field("event_picture_background", typeRef("sprite"), between(0, 0)),
      ruleSetEntries("picture_event_data"),
      field("auto_opens", primitive("boolean"), occurs.optional, {
        documentation: "Forces the event to pop-up even if player has suppressed pop ups",
      }),
      field("notification_event_icon", typeRef("sprite"), occurs.optional),
      field("is_test_event", primitive("boolean"), occurs.optional),
      field("desc_clear", literal(true), occurs.optional),
      field("option_clear", literal(true), occurs.optional),
      field("trigger_clear", literal(true), occurs.optional),
      field(
        "option",
        block([
          field("name", primitive("localisation"), occurs.oneOrMore),
          field(
            "name",
            block([
              field(
                "trigger",
                block([
                  triggerEntries(),
                  field(
                    "switch",
                    block([
                      field("trigger", primitive("scalar"), occurs.one),
                      field(
                        anyKey(),
                        block([
                          field(
                            "if",
                            block([
                              field("limit", block([triggerEntries()]), occurs.one),
                              field("text", primitive("localisation"), occurs.one),
                            ]),
                            occurs.optional,
                          ),
                          field("text", primitive("localisation"), occurs.optional),
                        ]),
                        between(2, null),
                      ),
                    ]),
                    occurs.optional,
                  ),
                  field(
                    scopeKey(anyScope()),
                    block([
                      triggerEntries(),
                      field(
                        "switch",
                        block([
                          field("trigger", primitive("scalar"), occurs.one),
                          field(
                            anyKey(),
                            block([
                              field(
                                "if",
                                block([
                                  field("limit", block([triggerEntries()]), occurs.one),
                                  field("text", primitive("localisation"), occurs.one),
                                ]),
                                occurs.optional,
                              ),
                              field("text", primitive("localisation"), occurs.optional),
                            ]),
                            between(2, null),
                          ),
                        ]),
                        occurs.optional,
                      ),
                    ]),
                    occurs.any,
                  ),
                ]),
                occurs.one,
              ),
              field("text", primitive("localisation"), occurs.optional),
            ]),
            occurs.oneOrMore,
          ),
          field(
            "name",
            block([
              field("exclusive_trigger", block([triggerEntries()]), occurs.one),
              field("text", primitive("localisation"), occurs.one),
            ]),
            occurs.oneOrMore,
          ),
          field(
            "icon",
            block([
              field("icon", typeRef("sprite"), occurs.one),
              field("icon_background", typeRef("sprite"), occurs.optional),
              field("text", primitive("localisation"), occurs.optional),
            ]),
            occurs.optional,
          ),
          field("sound", primitive("scalar"), occurs.optional),
          field("trigger", block([triggerEntries()]), occurs.optional),
          field("allow", block([triggerEntries()]), occurs.any),
          field("exclusive_trigger", block([triggerEntries()]), occurs.optional),
          field("ai_chance", block([modifierRuleEntries()]), occurs.optional),
          whenVariant("diplomatic", [
            field("response_text", primitive("localisation"), occurs.optional),
            field("is_dialog_only", primitive("boolean"), occurs.optional),
          ]),
          whenVariant("leader_recruit", [
            field("tag", enumRef(EnumId.LeaderRecruitTagType), occurs.optional),
            field("response_text", primitive("localisation"), occurs.optional),
            field("is_dialog_only", primitive("boolean"), occurs.optional),
          ]),
          whenVariant("leader_story", [
            field("response_text", primitive("localisation"), occurs.optional),
            field("is_dialog_only", primitive("boolean"), occurs.optional),
          ]),
          field("default_hide_option", primitive("boolean"), occurs.optional, {
            documentation: 'Binds this option to the "dismiss" action',
          }),
          field("custom_gui", primitive("scalar"), occurs.optional),
          effectEntries(),
          field("response_text", primitive("localisation"), occurs.optional),
          field("is_dialog_only", literal(true), occurs.optional),
          field("hide_option_if_not_allowed", primitive("boolean"), occurs.optional),
          field(
            "ai_trade_facility",
            block([
              effectEntries(),
              field("offer_hire_mercenary_fleet", primitive("boolean"), occurs.optional),
              field("offer_prolong_fleet_contract", primitive("boolean"), occurs.optional),
              field(
                "info_gathering",
                block([
                  field(
                    "get_trade_data",
                    block([field("target", scopeGroup("target_country"), occurs.one)]),
                    occurs.one,
                  ),
                ]),
                occurs.optional,
              ),
              field(
                "option_selection",
                block([
                  field(
                    "if",
                    block([
                      field(
                        "limit",
                        block([
                          field(
                            "is_offer_terms_actual",
                            block([field("target", scopeGroup("target_country"), occurs.one)]),
                            occurs.optional,
                          ),
                          triggerEntries(),
                        ]),
                        occurs.one,
                      ),
                      effectEntries(),
                    ]),
                    occurs.optional,
                  ),
                ]),
                occurs.optional,
              ),
              field(
                "allow",
                block([
                  field(
                    "can_afford_special_offer",
                    block([field("target", scopeGroup("target_country"), occurs.one)]),
                    occurs.optional,
                  ),
                  triggerEntries(),
                ]),
                occurs.optional,
              ),
            ]),
            occurs.optional,
          ),
        ]),
        occurs.any,
      ),
    ]),
    whenVariant("hidden", [
      field("title", anyValue(), occurs.optional, { severity: "information" }),
      field("desc", anyValue(), occurs.optional, { severity: "information" }),
      field("picture", primitive("scalar"), between(0, 0), { severity: "information" }),
      field("location", primitive("scalar"), between(0, 0), { severity: "information" }),
      field("show_sound", primitive("scalar"), between(0, 0), { severity: "information" }),
      field("auto_opens", primitive("boolean"), between(0, 0)),
    ]),
    field("message_desc", primitive("localisation"), occurs.optional),
    field("hide_window", primitive("boolean"), occurs.optional),
    field("is_triggered_only", primitive("boolean"), occurs.optional),
    whenVariant("triggered", [
      field(
        "weight_multiplier",
        block([field("factor", primitive("number"), occurs.one), modifierRuleEntries()]),
        occurs.optional,
      ),
    ]),
    field("abort_trigger", block([triggerEntries()]), occurs.optional, {
      documentation:
        "Event will cancel (disappear without executing any of the effects in the options) if these triggers return true.",
    }),
    field("abort_effect", block([effectEntries()]), occurs.optional, {
      documentation: "Effects executed when abort_trigger returns true.",
    }),
    field("fire_only_once", primitive("boolean"), occurs.optional),
    field("trackable", primitive("boolean"), occurs.optional),
    field("is_advisor_event", primitive("boolean"), occurs.optional),
    field("auto_select", primitive("boolean"), occurs.optional),
    unlessVariant("triggered", [
      field(
        "mean_time_to_happen",
        block([
          field("years", primitive("integer"), occurs.optional),
          field("months", primitive("integer"), occurs.optional),
          field("days", primitive("integer"), occurs.optional),
          modifierRuleEntries(),
        ]),
        occurs.optional,
      ),
    ]),
    whenVariant("country", [
      field("event_chain", typeRef("event_chain"), occurs.optional),
      field("pre_triggers", block([ruleSetEntries("country_pre_trigger")]), occurs.optional, {
        documentation: "Like trigger, but only uses certain simple triggers",
      }),
      field("specimen", typeRef("specimen"), occurs.optional),
      field(
        "weight_multiplier",
        block([
          field("factor", primitive("integer"), occurs.optional),
          field(
            "modifier",
            block([
              field("add", scriptValue("number"), occurs.optional),
              field("factor", primitive("number"), occurs.optional),
              triggerEntries(),
            ]),
            occurs.any,
          ),
        ]),
        occurs.optional,
      ),
    ]),
    whenVariant("diplomatic", [
      field("diplomatic_title", primitive("localisation"), occurs.optional, {
        documentation:
          "The title that shows at the top of the diplomatic screen (above the portrait/room, not above the event text)",
      }),
      ruleSetEntries("picture_event_data"),
      field("custom_gui", primitive("scalar"), occurs.optional),
      field("custom_gui_option", primitive("scalar"), occurs.optional),
    ]),
    whenVariant("leader_recruit", [
      field("notification_event_icon", typeRef("sprite"), occurs.optional),
      ruleSetEntries("picture_event_data"),
    ]),
    whenVariant("leader_story", [
      field("event_picture_background", typeRef("sprite"), occurs.optional),
      ruleSetEntries("picture_event_data"),
    ]),
    whenVariant("planet", [
      field("pre_triggers", block([ruleSetEntries("planet_pre_trigger")]), occurs.optional, {
        documentation: "Like trigger, but only uses certain simple triggers",
      }),
      ruleSetEntries("picture_event_data"),
      field("specimen", typeRef("specimen"), occurs.optional),
      field("event_chain", typeRef("event_chain"), occurs.optional),
    ]),
    whenVariant("fleet", [
      field("event_chain", typeRef("event_chain"), occurs.optional),
      field("archaeology", primitive("boolean"), occurs.optional),
      field("specimen", typeRef("specimen"), occurs.optional),
    ]),
    whenVariant("ship", [field("specimen", typeRef("specimen"), occurs.optional)]),
    whenVariant("first_contact", [field("first_contact", primitive("boolean"), occurs.optional)]),
    whenVariant("astral", [
      field("difficulty", namedValue("variable"), occurs.optional),
      field("astral_rift", literal(true), occurs.optional),
      field("specimen", typeRef("specimen"), occurs.optional),
    ]),
    whenVariant("situation", [
      field("situation", scopeRef(ScopeId.Situation), occurs.optional),
      field("pre_triggers", block([ruleSetEntries("situation_pre_trigger")]), occurs.optional, {
        documentation: "Like trigger, but only uses certain simple triggers",
      }),
      field("specimen", typeRef("specimen"), occurs.optional),
    ]),
    whenVariant("espionage_operation", [field("espionage_operation", primitive("boolean"), occurs.optional)]),
    whenVariant("pop", [
      field("pre_triggers", block([ruleSetEntries("pop_pre_trigger")]), occurs.optional, {
        documentation: "Like trigger, but only uses certain simple triggers",
      }),
    ]),
    whenVariant("pop_group", [
      field("pre_triggers", block([ruleSetEntries("pop_pre_trigger")]), occurs.optional, {
        documentation: "Like trigger, but only uses certain simple triggers",
      }),
    ]),
    whenVariant("leader", [
      field("pre_triggers", block([ruleSetEntries("leader_pre_trigger")]), occurs.optional, {
        documentation: "Like trigger, but only uses certain simple triggers",
      }),
    ]),
    whenVariant("starbase", [
      field("pre_triggers", block([ruleSetEntries("starbase_pre_trigger")]), occurs.optional, {
        documentation: "Like trigger, but only uses certain simple triggers",
      }),
    ]),
    whenVariant("system", [
      field("pre_triggers", block([ruleSetEntries("system_pre_trigger")]), occurs.optional, {
        documentation: "Like trigger, but only uses certain simple triggers",
      }),
    ]),
    field("trigger", block([triggerEntries()]), occurs.optional),
    field(
      "immediate",
      block([
        field("allow", block([triggerEntries()]), occurs.optional),
        effectEntries(),
        field("name", primitive("localisation"), occurs.optional),
        field(
          "ai_trade_facility",
          block([
            effectEntries(),
            field("offer_hire_mercenary_fleet", primitive("boolean"), occurs.optional),
            field("offer_prolong_fleet_contract", primitive("boolean"), occurs.optional),
            field(
              "info_gathering",
              block([
                field("get_trade_data", block([field("target", scopeGroup("target_country"), occurs.one)]), occurs.one),
              ]),
              occurs.optional,
            ),
            field(
              "option_selection",
              block([
                field(
                  "if",
                  block([
                    field(
                      "limit",
                      block([
                        field(
                          "is_offer_terms_actual",
                          block([field("target", scopeGroup("target_country"), occurs.one)]),
                          occurs.optional,
                        ),
                        triggerEntries(),
                      ]),
                      occurs.one,
                    ),
                    effectEntries(),
                  ]),
                  occurs.optional,
                ),
              ]),
              occurs.optional,
            ),
            field(
              "allow",
              block([
                field(
                  "can_afford_special_offer",
                  block([field("target", scopeGroup("target_country"), occurs.one)]),
                  occurs.optional,
                ),
                triggerEntries(),
              ]),
              occurs.optional,
            ),
          ]),
          occurs.optional,
        ),
        field("run_in_ai_mode", primitive("boolean"), occurs.optional),
        field("ai_chance", block([field("factor", literal(1), occurs.one)]), occurs.optional),
      ]),
      occurs.any,
    ),
    field("after", block([effectEntries()]), occurs.any),
  ],
});
