import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";
import {
  allOf,
  block,
  defineType,
  effectBlock,
  effectEntries,
  enumRef,
  fieldAbsent,
  fieldEquals,
  fieldPresent,
  forbidden,
  modifierRuleBlock,
  modifierRuleEntries,
  not,
  oneOf,
  oneOrMore,
  optional,
  primitive,
  repeatable,
  required,
  rootKeyIs,
  scopeRef,
  taggedBlocks,
  triggerBlock,
  typeRef,
  unlessVariant,
  valueSet,
  whenVariant,
} from "../ir.js";
import type { DefinitionType } from "../ir.js";

const eventTags: readonly string[] = [
  "agreement_event",
  "astral_rift_event",
  "bypass_event",
  "carrier_event",
  "colony_event",
  "country_event",
  "espionage_operation_event",
  "event",
  "first_contact_event",
  "fleet_event",
  "leader_event",
  "observer_event",
  "planet_event",
  "pop_event",
  "pop_faction_event",
  "pop_group_event",
  "ship_event",
  "situation_event",
  "starbase_event",
  "system_event",
];

const conditionalLocalisation: ReturnType<typeof oneOf> = oneOf(
  primitive("localisation"),
  block([
    optional("trigger", triggerBlock()),
    optional("exclusive_trigger", triggerBlock()),
    repeatable("text", primitive("localisation")),
    optional("show_sound", typeRef("sound_effect")),
  ]),
);

const eventOption: ReturnType<typeof block> = block([
  oneOrMore("name", conditionalLocalisation),
  optional(
    "icon",
    block([
      required("icon", typeRef("sprite")),
      optional("icon_background", typeRef("sprite")),
      optional("text", primitive("localisation")),
    ]),
  ),
  optional("sound", primitive("scalar")),
  optional("trigger", triggerBlock()),
  repeatable("allow", triggerBlock()),
  optional("exclusive_trigger", triggerBlock()),
  optional("ai_chance", modifierRuleBlock()),
  optional("default_hide_option", primitive("boolean")),
  optional("custom_gui", primitive("scalar")),
  optional("response_text", primitive("localisation")),
  optional("is_dialog_only", primitive("boolean")),
  optional("hide_option_if_not_allowed", primitive("boolean")),
  whenVariant("diplomatic", [
    optional("response_text", primitive("localisation")),
    optional("is_dialog_only", primitive("boolean")),
  ]),
  whenVariant("leader_recruit", [
    optional("tag", primitive("scalar")),
    optional("response_text", primitive("localisation")),
    optional("is_dialog_only", primitive("boolean")),
  ]),
  whenVariant("leader_story", [
    optional("response_text", primitive("localisation")),
    optional("is_dialog_only", primitive("boolean")),
  ]),
  effectEntries(),
]);

export const event: DefinitionType = defineType({
  id: DefinitionTypeId.Event,
  source: taggedBlocks("events", "id", eventTags),
  variants: [
    {
      id: "agreement",
      when: rootKeyIs("agreement_event"),
      entryScope: ScopeId.Agreement,
      displayName: "Agreement Event",
      abbreviation: "AE",
    },
    {
      id: "astral",
      when: rootKeyIs("astral_rift_event"),
      entryScope: ScopeId.AstralRift,
      displayName: "Astral Rift Event",
      abbreviation: "ARE",
    },
    {
      id: "bypass",
      when: rootKeyIs("bypass_event"),
      entryScope: ScopeId.Bypass,
      displayName: "Bypass Event",
      abbreviation: "BPE",
    },
    {
      id: "carrier",
      when: rootKeyIs("carrier_event"),
      displayName: "Carrier Event",
    },
    {
      id: "colony",
      when: rootKeyIs("colony_event"),
      entryScope: ScopeId.Planet,
      displayName: "Colony Event",
    },
    {
      id: "country",
      when: rootKeyIs("country_event", "observer_event"),
      entryScope: ScopeId.Country,
      displayName: "Country Event",
      abbreviation: "CE",
    },
    {
      id: "espionage_operation",
      when: rootKeyIs("espionage_operation_event"),
      entryScope: ScopeId.EspionageOperation,
      displayName: "Espionage Operation Event",
      abbreviation: "EOE",
    },
    {
      id: "first_contact",
      when: rootKeyIs("first_contact_event"),
      entryScope: ScopeId.FirstContact,
      displayName: "First Contact Event",
      abbreviation: "FCE",
    },
    {
      id: "fleet",
      when: rootKeyIs("fleet_event"),
      entryScope: ScopeId.Fleet,
      displayName: "Fleet Event",
      abbreviation: "FE",
    },
    {
      id: "leader",
      when: rootKeyIs("leader_event"),
      entryScope: ScopeId.Leader,
      displayName: "Leader Event",
      abbreviation: "LE",
    },
    {
      id: "planet",
      when: rootKeyIs("planet_event"),
      entryScope: ScopeId.Planet,
      displayName: "Planet Event",
      abbreviation: "PE",
    },
    {
      id: "pop",
      when: rootKeyIs("pop_event"),
      entryScope: ScopeId.Pop,
      displayName: "Pop Event",
      abbreviation: "PoE",
    },
    {
      id: "pop_faction",
      when: rootKeyIs("pop_faction_event"),
      entryScope: ScopeId.PopFaction,
      displayName: "Pop Faction Event",
      abbreviation: "PFE",
    },
    {
      id: "pop_group",
      when: rootKeyIs("pop_group_event"),
      entryScope: ScopeId.PopGroup,
      displayName: "Pop Group Event",
      abbreviation: "PGE",
    },
    {
      id: "scopeless",
      when: rootKeyIs("event"),
      displayName: "Scopeless Event",
    },
    {
      id: "ship",
      when: rootKeyIs("ship_event"),
      entryScope: ScopeId.Ship,
      displayName: "Ship Event",
      abbreviation: "SE",
    },
    {
      id: "situation",
      when: rootKeyIs("situation_event"),
      entryScope: ScopeId.Situation,
      displayName: "Situation Event",
      abbreviation: "SiE",
    },
    {
      id: "starbase",
      when: rootKeyIs("starbase_event"),
      entryScope: ScopeId.Starbase,
      displayName: "Starbase Event",
      abbreviation: "StE",
    },
    {
      id: "system",
      when: rootKeyIs("system_event"),
      entryScope: ScopeId.System,
      displayName: "System Event",
      abbreviation: "SyE",
    },
    { id: "hidden", when: fieldEquals("hide_window", true) },
    { id: "diplomatic", when: fieldEquals("diplomatic", true) },
    {
      id: "default",
      when: allOf(
        fieldAbsent("event_window_type"),
        fieldAbsent("event_picture_background"),
        not(fieldEquals("diplomatic", true)),
        not(fieldEquals("hide_window", true)),
      ),
    },
    { id: "leader_recruit", when: fieldEquals("event_window_type", "leader_recruit") },
    { id: "leader_story", when: fieldEquals("event_window_type", "leader_story") },
    { id: "triggered", when: fieldEquals("is_triggered_only", true) },
    { id: "inherited", when: fieldPresent("base") },
  ],
  localisation: [
    {
      role: "title",
      source: { kind: "field", field: "title" },
      required: true,
      primary: true,
      variant: "default",
    },
  ],
  modifiers: [],
  entries: [
    required("id", primitive("scalar")),
    optional("is_test_event", primitive("boolean")),
    optional("diplomatic_title", primitive("localisation")),
    optional("event_message_type", primitive("localisation")),
    whenVariant("inherited", [
      required("base", typeRef("event")),
      optional("desc_clear", primitive("boolean")),
      optional("option_clear", primitive("boolean")),
      optional("trigger_clear", primitive("boolean")),
      optional("picture_clear", primitive("boolean")),
      optional("show_sound_clear", primitive("boolean")),
    ]),
    unlessVariant("hidden", [
      required("title", primitive("localisation")),
      required("desc", conditionalLocalisation),
      repeatable(
        "picture",
        oneOf(
          typeRef("sprite"),
          block([repeatable("picture", typeRef("sprite")), optional("trigger", triggerBlock())]),
        ),
      ),
      repeatable(
        "show_sound",
        oneOf(
          typeRef("sound_effect"),
          block([
            required("sound", typeRef("sound_effect")),
            optional("sound_is_advisor", primitive("boolean")),
            optional("trigger", triggerBlock()),
          ]),
        ),
      ),
      optional("force_open", primitive("boolean"), {
        documentation: "Force a diplomatic event to be viewed.",
      }),
      optional(
        "location",
        oneOf(
          scopeRef(ScopeId.Planet),
          scopeRef(ScopeId.System),
          scopeRef(ScopeId.Ship),
          scopeRef(ScopeId.Fleet),
          scopeRef(ScopeId.Country),
          scopeRef(ScopeId.Pop),
          scopeRef(ScopeId.Starbase),
          scopeRef(ScopeId.Bypass),
          scopeRef(ScopeId.AstralRift),
          valueSet("event_target"),
        ),
      ),
      optional("event_chain", typeRef("event_chain")),
      optional("situation", scopeRef(ScopeId.Situation)),
      optional("diplomatic", primitive("boolean")),
      optional("event_window_type", enumRef(EnumId.EventWindowType)),
      repeatable("option", eventOption),
      optional("auto_opens", primitive("boolean")),
      optional("notification_event_icon", typeRef("sprite")),
    ]),
    whenVariant("hidden", [
      optional("title", primitive("scalar"), { severity: "information" }),
      optional("desc", primitive("scalar"), { severity: "information" }),
      forbidden("picture", primitive("scalar"), { severity: "information" }),
      forbidden("location", primitive("scalar"), { severity: "information" }),
      forbidden("show_sound", primitive("scalar"), { severity: "information" }),
      forbidden("auto_opens", primitive("boolean")),
    ]),
    whenVariant("default", [
      forbidden("event_window_type", enumRef(EnumId.EventWindowType)),
      forbidden("event_picture_background", typeRef("sprite")),
    ]),
    whenVariant("leader_story", [optional("event_picture_background", typeRef("sprite"))]),
    optional("message_desc", primitive("localisation")),
    optional("hide_window", primitive("boolean")),
    optional("is_triggered_only", primitive("boolean")),
    whenVariant("triggered", [
      optional("weight_multiplier", block([required("factor", primitive("number")), modifierRuleEntries()])),
    ]),
    unlessVariant("triggered", [
      optional(
        "mean_time_to_happen",
        block([
          optional("years", primitive("integer")),
          optional("months", primitive("integer")),
          optional("days", primitive("integer")),
          modifierRuleEntries(),
        ]),
      ),
    ]),
    optional("abort_trigger", triggerBlock(), {
      documentation: "Cancel the event when these triggers are true.",
    }),
    optional("abort_effect", effectBlock(), {
      documentation: "Effects run when abort_trigger cancels the event.",
    }),
    optional("fire_only_once", primitive("boolean")),
    optional("trackable", primitive("boolean")),
    optional("is_advisor_event", primitive("boolean")),
    optional("auto_select", primitive("boolean")),
    whenVariant("country", [
      optional("pre_triggers", triggerBlock()),
      optional("specimen", typeRef("specimen")),
      optional("event_chain", typeRef("event_chain")),
    ]),
    whenVariant("planet", [
      optional("pre_triggers", triggerBlock()),
      optional("specimen", typeRef("specimen")),
      optional("event_chain", typeRef("event_chain")),
    ]),
    whenVariant("fleet", [
      optional("event_chain", typeRef("event_chain")),
      optional("archaeology", primitive("boolean")),
      optional("specimen", typeRef("specimen")),
    ]),
    whenVariant("ship", [optional("specimen", typeRef("specimen"))]),
    whenVariant("first_contact", [optional("first_contact", primitive("boolean"))]),
    whenVariant("astral", [
      optional("difficulty", primitive("script-value")),
      optional("astral_rift", primitive("boolean")),
      optional("specimen", typeRef("specimen")),
    ]),
    whenVariant("situation", [
      optional("situation", scopeRef(ScopeId.Situation)),
      optional("pre_triggers", triggerBlock()),
      optional("specimen", typeRef("specimen")),
    ]),
    whenVariant("espionage_operation", [optional("espionage_operation", primitive("boolean"))]),
    whenVariant("pop", [optional("pre_triggers", triggerBlock())]),
    whenVariant("pop_group", [optional("pre_triggers", triggerBlock())]),
    whenVariant("leader", [optional("pre_triggers", triggerBlock())]),
    whenVariant("starbase", [optional("pre_triggers", triggerBlock())]),
    whenVariant("system", [optional("pre_triggers", triggerBlock())]),
    optional("trigger", triggerBlock()),
    repeatable(
      "immediate",
      block([
        optional("allow", triggerBlock()),
        optional("name", primitive("localisation")),
        optional("run_in_ai_mode", primitive("boolean")),
        optional("ai_chance", block([required("factor", primitive("number"))])),
        effectEntries(),
      ]),
    ),
    repeatable("after", effectBlock()),
  ],
  documentation:
    "An event definition selected by its root tag and id field. Carrier and colony tags are retained from vanilla even though the upstream CWT omits them.",
});
