// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  field,
  keyedBlocks,
  modifierEntries,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  triggerEntries,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const federationLaw: DefinitionType = defineType({
  id: DefinitionTypeId.FederationLaw,
  source: keyedBlocks("common/federation_laws"),
  variants: [],
  localisation: [definitionLocalisation("Name", "$", true), definitionLocalisation("Description", "$_desc", true)],
  modifiers: [],
  entries: [
    field("unlocks_centralization", primitive("integer"), occurs.optional),
    field("cohesion_growth", primitive("number"), occurs.optional),
    field("required_centralization", block([field("base", primitive("integer"), occurs.one)]), occurs.optional),
    field("display_level", primitive("integer"), occurs.optional),
    field("allow", block([triggerEntries()]), occurs.one, { scope: replaceScope({ root: ScopeId.Federation }) }),
    field("potential", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Federation }),
    }),
    field(
      "modifier",
      block([field("description", primitive("localisation"), occurs.optional), modifierEntries()]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.Federation }) },
    ),
    field("on_enact", block([effectEntries()]), occurs.optional, { scope: replaceScope({ root: ScopeId.Federation }) }),
    field("ai_weight", block([ruleSetEntries("modifier_rule_with_loc")]), occurs.one, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
  ],
});
