// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  field,
  item,
  keyedBlocks,
  literal,
  occurs,
  replaceScope,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const federationLawCategory: DefinitionType = defineType({
  id: DefinitionTypeId.FederationLawCategory,
  source: keyedBlocks("common/federation_law_categories"),
  variants: [],
  localisation: [definitionLocalisation("Name", "", true), definitionLocalisation("Description", "_desc", true)],
  modifiers: [],
  entries: [
    field("show_succession_date", literal(true), occurs.optional),
    field("centralization", literal(true), occurs.optional),
    field("laws", block([item(typeRef("federation_law"), occurs.oneOrMore)]), occurs.one),
    field("potential", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Federation }),
    }),
  ],
});
