// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import {
  block,
  defineType,
  effectEntries,
  enumRef,
  field,
  keyedBlocks,
  occurs,
  primitive,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const focusCardKey: DefinitionType = defineType({
  id: DefinitionTypeId.FocusCardKey,
  source: keyedBlocks("common/country_focus/focus_cards"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("category", enumRef(EnumId.CardCategoriesFocus), occurs.optional),
    field("tier", primitive("integer"), occurs.optional),
    field("background", typeRef("sprite"), occurs.optional),
    field("base", typeRef("focus_card_key"), occurs.optional),
    field("name", primitive("localisation"), occurs.one),
    field("desc", primitive("localisation"), occurs.one),
    field("hint", primitive("localisation"), occurs.one),
    field("lore", primitive("localisation"), occurs.one),
    field("possible", block([triggerEntries()]), occurs.optional),
    field("condition_for_achievement", block([triggerEntries()]), occurs.one),
    field("on_success", block([effectEntries()]), occurs.optional),
  ],
});
