// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import { block, defineType, enumRef, field, occurs, primitive, taggedBlocks } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const font: DefinitionType = defineType({
  id: DefinitionTypeId.Font,
  source: taggedBlocks("fonts", "name", [], true, { rootKeyFilter: { mode: "include", values: ["font"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("scalar"), occurs.one),
    field(
      "fontstyle",
      block([
        field("style", enumRef(EnumId.FontStyle), occurs.one),
        field("file", primitive("file"), occurs.one, { documentation: "supports *.ttf and *.otf files!" }),
      ]),
      occurs.one,
    ),
    field("name", primitive("scalar"), occurs.one),
    field(
      "fontstyle",
      block([
        field("style", enumRef(EnumId.FontStyle), occurs.one),
        field("file", primitive("file"), occurs.one, { documentation: "supports *.ttf and *.otf files!" }),
      ]),
      occurs.one,
    ),
  ],
});
