// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import { block, defineType, enumRef, field, item, occurs, primitive, taggedBlocks, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const globalShipDesign: DefinitionType = defineType({
  id: DefinitionTypeId.GlobalShipDesign,
  source: taggedBlocks("common/global_ship_designs", "name", []),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("localisation"), occurs.optional),
    field("roles", enumRef(EnumId.ShipSizeShipRoles), occurs.optional),
    field("upgrades_to", primitive("localisation"), occurs.optional),
    field("upgrades_to", block([item(primitive("localisation"), occurs.any)]), occurs.optional),
    field("creature_designer_template", primitive("boolean"), occurs.optional),
    field("newborn_ship_design", primitive("localisation"), occurs.optional),
    field("country_type", typeRef("country_type"), occurs.optional),
    field("fleet_specialization_tag", enumRef(EnumId.ComponentTags), occurs.optional),
    field("use_design_name", primitive("boolean"), occurs.optional),
    field("is_event_design", primitive("boolean"), occurs.optional),
    field("allow_buildable_trigger", typeRef("scripted_trigger"), occurs.optional),
    field("is_special_buildable", primitive("boolean"), occurs.optional),
    field("graphical_culture", typeRef("graphical_culture"), occurs.optional),
    field("ship_size", typeRef("ship_size"), occurs.optional),
    field("custom_trade_weight", primitive("integer"), occurs.optional),
    field("hide_size", primitive("boolean"), occurs.optional),
    field("regenerates_when_disabled", primitive("boolean"), occurs.optional),
    field(
      "section",
      block([
        field("template", typeRef("section_template"), occurs.optional),
        field("slot", enumRef(EnumId.SectionSlots), occurs.optional),
        field(
          "component",
          block([
            field("slot", enumRef(EnumId.ComponentSlots), occurs.optional),
            field("slot", enumRef(EnumId.UtilityComponentSlots), occurs.optional),
            field("template", typeRef("component_template"), occurs.optional),
          ]),
          occurs.any,
        ),
      ]),
      occurs.any,
    ),
    field("required_component", typeRef("component_template", "utility_component_template"), occurs.any),
    field(
      "growth_stages",
      block([
        item(
          block([
            field("ship_size", typeRef("ship_size"), occurs.one),
            field("custom_military_power", primitive("number"), occurs.optional),
            field(
              "section",
              block([
                field("template", typeRef("section_template"), occurs.one),
                field("slot", enumRef(EnumId.SectionSlots), occurs.one),
                field(
                  "component",
                  block([
                    field("slot", enumRef(EnumId.ComponentSlots), occurs.optional),
                    field("slot", enumRef(EnumId.UtilityComponentSlots), occurs.optional),
                    field("template", typeRef("component_template"), occurs.optional),
                  ]),
                  occurs.any,
                ),
              ]),
              occurs.one,
            ),
            field("required_component", typeRef("component_template", "utility_component_template"), occurs.any),
          ]),
          occurs.any,
        ),
      ]),
      occurs.optional,
    ),
  ],
});
