// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, field, keyedBlocks, occurs, primitive, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const grandArchiveShipCategoryType: DefinitionType = defineType({
  id: DefinitionTypeId.GrandArchiveShipCategoryType,
  source: keyedBlocks("common/ship_categories"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("rarity_icons", typeRef("sprite"), occurs.optional),
    field("uses_name_list", primitive("boolean"), occurs.optional),
    field("namelist", typeRef("name_list"), occurs.optional),
    field("desc", primitive("localisation"), occurs.optional),
    field("prefers_nebula", primitive("boolean"), occurs.optional),
    field("preferred_planet_class", typeRef("planet_class"), occurs.optional),
    field("sexual_breeding", primitive("boolean"), occurs.optional),
    field("growth_tooltip", primitive("localisation"), occurs.optional),
    field("rarity_icons", typeRef("sprite"), occurs.optional),
    field("uses_name_list", primitive("boolean"), occurs.optional),
    field("namelist", typeRef("name_list"), occurs.optional),
    field("desc", primitive("localisation"), occurs.optional),
    field("prefers_nebula", primitive("boolean"), occurs.optional),
    field("preferred_planet_class", typeRef("planet_class"), occurs.optional),
    field("sexual_breeding", primitive("boolean"), occurs.optional),
    field("growth_tooltip", primitive("localisation"), occurs.optional),
  ],
});
