// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import {
  between,
  block,
  defineType,
  field,
  item,
  keyedBlocks,
  literal,
  occurs,
  primitive,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const graphicalCulture: DefinitionType = defineType({
  id: DefinitionTypeId.GraphicalCulture,
  source: keyedBlocks("common/graphical_culture"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("has_city_graphics", literal(false), occurs.optional),
    field("fallback", typeRef("graphical_culture"), occurs.optional),
    field("ship_color", primitive("boolean"), occurs.optional),
    field(
      "ship_lighting",
      block([
        field("cam_light_1_dir", block([item(primitive("number"), between(3, 3))]), occurs.one),
        field("cam_light_2_dir", block([item(primitive("number"), between(3, 3))]), occurs.one),
        field("cam_light_3_dir", block([item(primitive("number"), between(3, 3))]), occurs.one),
        field("intensity_near", primitive("number"), occurs.optional, { documentation: "Amount of light when near" }),
        field("intensity_far", primitive("number"), occurs.optional, { documentation: "Amount when far away" }),
        field("near_value", primitive("integer"), occurs.optional, { documentation: "Near threshold" }),
        field("far_value", primitive("integer"), occurs.optional, { documentation: "Far threshold" }),
        field("rim_start_near", primitive("number"), occurs.optional),
        field("rim_stop_near", primitive("number"), occurs.optional),
        field("rim_start_far", primitive("number"), occurs.optional),
        field("rim_stop_far", primitive("number"), occurs.optional),
        field("ambient_near", primitive("number"), occurs.optional),
        field("ambient_far", primitive("number"), occurs.optional),
      ]),
      occurs.optional,
    ),
    field("ship_kinds", block([item(typeRef("grand_archive_ship_category_type"), occurs.any)]), occurs.optional),
    field(
      "ship_selection_weight",
      block([
        field("base", primitive("integer"), occurs.one),
        field("modifier", block([field("set", primitive("integer"), occurs.one), triggerEntries()]), occurs.any),
      ]),
      occurs.optional,
    ),
    field("randomized", block([triggerEntries()]), occurs.optional),
    field("selectable", block([triggerEntries()]), occurs.optional),
    field("has_city_graphics", literal(false), occurs.optional),
    field("fallback", typeRef("graphical_culture"), occurs.optional),
    field("ship_color", primitive("boolean"), occurs.optional),
    field(
      "ship_lighting",
      block([
        field("cam_light_1_dir", block([item(primitive("number"), between(3, 3))]), occurs.one),
        field("cam_light_2_dir", block([item(primitive("number"), between(3, 3))]), occurs.one),
        field("cam_light_3_dir", block([item(primitive("number"), between(3, 3))]), occurs.one),
        field("intensity_near", primitive("number"), occurs.optional, { documentation: "Amount of light when near" }),
        field("intensity_far", primitive("number"), occurs.optional, { documentation: "Amount when far away" }),
        field("near_value", primitive("integer"), occurs.optional, { documentation: "Near threshold" }),
        field("far_value", primitive("integer"), occurs.optional, { documentation: "Far threshold" }),
        field("rim_start_near", primitive("number"), occurs.optional),
        field("rim_stop_near", primitive("number"), occurs.optional),
        field("rim_start_far", primitive("number"), occurs.optional),
        field("rim_stop_far", primitive("number"), occurs.optional),
        field("ambient_near", primitive("number"), occurs.optional),
        field("ambient_far", primitive("number"), occurs.optional),
      ]),
      occurs.optional,
    ),
    field("ship_kinds", block([item(typeRef("grand_archive_ship_category_type"), occurs.any)]), occurs.optional),
    field(
      "ship_selection_weight",
      block([
        field("base", primitive("integer"), occurs.one),
        field("modifier", block([field("set", primitive("integer"), occurs.one), triggerEntries()]), occurs.any),
      ]),
      occurs.optional,
    ),
    field("randomized", block([triggerEntries()]), occurs.optional),
    field("selectable", block([triggerEntries()]), occurs.optional),
  ],
});
