// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, keyedBlocks, ruleSetEntries } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const guiType: DefinitionType = defineType({
  id: DefinitionTypeId.GuiType,
  source: keyedBlocks("interface", true, { rootKeyFilter: { mode: "include", values: ["guiTypes"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [ruleSetEntries("gui"), ruleSetEntries("gui_button")],
});
