// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, field, item, keyedBlocks, occurs, primitive } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const intelCategory: DefinitionType = defineType({
  id: DefinitionTypeId.IntelCategory,
  source: keyedBlocks("common/intel_categories"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("intel_level", block([item(primitive("scalar"), occurs.any)]), occurs.any),
    field("intel_level", block([item(primitive("scalar"), occurs.any)]), occurs.any),
  ],
});
