// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, field, item, keyedBlocks, occurs, primitive, typeKey } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const intelLevel: DefinitionType = defineType({
  id: DefinitionTypeId.IntelLevel,
  source: keyedBlocks("common/intel_levels"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("frame", primitive("integer"), occurs.one),
    field("intel", block([item(primitive("integer", { min: 0, max: 100 }), occurs.any)]), occurs.one),
    field(typeKey("intel_category"), primitive("integer"), occurs.oneOrMore),
  ],
});
