// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { bareValues, defineType } from "../ir.js";

import type { DefinitionType } from "../ir.js";

// cwt declares this `type_per_file`, which makes the identifier `00_tags` — the
// file name — and every tag vanilla writes unknown. The game's own
// `common/job_tags/00_tags.txt` is a list of bare words, and `pop_jobs` writes
// `tags = { crime enforcer }` against them.
export const jobTags: DefinitionType = defineType({
  id: DefinitionTypeId.JobTags,
  source: bareValues("common/job_tags"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [],
});
