// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  enumRef,
  field,
  fieldEquals,
  fieldPresent,
  generatedModifier,
  item,
  keyedBlocks,
  literal,
  modifierEntries,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  scriptValue,
  triggerEntries,
  typeKey,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const job: DefinitionType = defineType({
  id: DefinitionTypeId.Job,
  source: keyedBlocks("common/pop_jobs"),
  entryScope: ScopeId.PopGroup,
  variants: [
    { id: "uncapped_by_modifier", when: fieldEquals("is_capped_by_modifier", true) },
    { id: "possible", when: fieldPresent("possible") },
  ],
  localisation: [
    definitionLocalisation("Name", "job_$", true),
    definitionLocalisation("Plural", "job_$_plural", false),
    definitionLocalisation("Desc", "job_$_desc", false),
    definitionLocalisation("Modifier", "mod_job_$_add", true, "uncapped_by_modifier"),
    definitionLocalisation("Per Pop Modifier", "mod_job_$_per_pop", false, "uncapped_by_modifier"),
    definitionLocalisation("Per Pop Modifier (short)", "mod_job_$_per_pop_short", false, "uncapped_by_modifier"),
    definitionLocalisation("Plural", "job_$_plural", true, "possible"),
    definitionLocalisation("Desc", "job_$_desc", true, "possible"),
  ],
  modifiers: [
    generatedModifier("job_", "_add", "Planets"),
    generatedModifier("job_", "_per_pop", "Planets"),
    generatedModifier("job_", "_per_crime", "Planets"),
  ],
  entries: [
    field(
      "desc",
      block([
        field("trigger", block([triggerEntries()]), occurs.one, { scope: replaceScope({ root: ScopeId.Planet }) }),
        field("text", primitive("localisation"), occurs.one),
      ]),
      occurs.any,
    ),
    field("auto_generate_description", primitive("boolean"), occurs.any),
    field("category", typeRef("social_strata"), occurs.optional),
    field("can_be_automated", primitive("boolean"), occurs.optional),
    field("first_come_first_served", primitive("boolean"), occurs.optional),
    field("condition_string", primitive("localisation"), occurs.optional),
    field("building_icon", typeRef("building"), occurs.optional),
    field("building_icon", primitive("icon", undefined, "gfx/interface/icons/buildings"), occurs.optional),
    field(
      "building_icon",
      primitive("icon", undefined, "gfx/interface/icons/buildings/old_production"),
      occurs.optional,
    ),
    field("clothes_texture_index", primitive("integer"), occurs.optional),
    field("icon", primitive("file", undefined, "gfx/interface/icons/jobs/job_,.dds"), occurs.optional),
    field("exempt_from_ai_amenity_prioritization", primitive("boolean"), occurs.optional),
    field("is_capped_by_modifier", primitive("boolean"), occurs.optional),
    field("count_as_available_for_ai", primitive("boolean"), occurs.optional),
    field("allow_only_same_rank_pops", primitive("boolean"), occurs.optional),
    field("can_set_priority", primitive("boolean"), occurs.optional),
    field("is_pre_sapient", primitive("boolean"), occurs.optional),
    field("ignores_sapience", primitive("boolean"), occurs.optional),
    field("ignores_favorite", primitive("boolean"), occurs.optional),
    field("purge", typeRef("purge_type"), occurs.optional),
    field("contributes_to_diplo_weight", primitive("boolean"), occurs.optional, {
      documentation: "Sets whether the job contributes to diplo weight. Default = yes",
    }),
    field("possible_pre_triggers", block([ruleSetEntries("pop_pre_trigger")]), occurs.optional, {
      documentation: "Only uses certain simple triggers.",
    }),
    field("possible_precalc", literal("can_fill_ruler_job"), occurs.optional),
    field("possible_precalc", literal("can_fill_specialist_job"), occurs.optional),
    field("possible_precalc", literal("can_fill_worker_job"), occurs.optional),
    field("possible_precalc", literal("can_fill_drone_job"), occurs.optional),
    field("possible_precalc", literal("can_fill_precursor_job"), occurs.optional),
    field("possible_precalc", enumRef(EnumId.JobTriggers), occurs.optional),
    field("possible", block([triggerEntries()]), occurs.optional),
    field(
      "resources",
      block([
        field("category", typeRef("economic_category"), occurs.optional),
        field(
          "produces",
          block([
            field("trigger", block([triggerEntries()]), occurs.optional, {
              scope: replaceScope({ root: ScopeId.Planet }),
            }),
            field(typeKey("resource"), primitive("number"), occurs.any),
            field("multiplier", scriptValue("number"), occurs.any),
            field("mult", scriptValue("number"), occurs.any),
          ]),
          occurs.any,
        ),
        field(
          "upkeep",
          block([
            field("trigger", block([triggerEntries()]), occurs.optional, {
              scope: replaceScope({ root: ScopeId.Planet }),
            }),
            field(typeKey("resource"), primitive("number"), occurs.any),
            field("multiplier", scriptValue("number"), occurs.any),
            field("mult", scriptValue("number"), occurs.any),
          ]),
          occurs.any,
        ),
      ]),
      occurs.any,
    ),
    field(
      "overlord_resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.optional,
    ),
    field("pop_modifier", block([modifierEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.PopGroup }),
    }),
    field("country_modifier", block([modifierEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("system_modifier", block([modifierEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.System }),
    }),
    field("planet_modifier", block([modifierEntries()]), occurs.any, {
      documentation: "Multiple planet_modifiers blocks result in only the last one applying",
      scope: replaceScope({ root: ScopeId.Planet }),
    }),
    ruleSetEntries("triggered_planet_modifier_pop"),
    ruleSetEntries("triggered_planet_modifier_planet"),
    ruleSetEntries("triggered_country_modifier_planet"),
    ruleSetEntries("triggered_country_modifier_pop"),
    ruleSetEntries("triggered_planet_modifier_pop_group"),
    ruleSetEntries("triggered_planet_pop_group_modifier_species"),
    ruleSetEntries("triggered_pop_modifier"),
    field("weight", block([modifierRuleEntries()]), occurs.optional),
    field("auto_trait_prio", block([item(primitive("localisation"), occurs.any)]), occurs.optional),
    field(
      "swappable_data",
      block([
        field(
          "default",
          block([
            field("building_icon", primitive("icon", undefined, "gfx/interface/icons/buildings"), occurs.optional),
            field("building_icon", typeRef("building"), occurs.optional),
            field("icon", primitive("file", undefined, "gfx/interface/icons/jobs/job_,.dds"), occurs.optional),
            field("desc", primitive("localisation"), occurs.optional),
            field("condition_string", primitive("localisation"), occurs.optional),
          ]),
          occurs.one,
        ),
        field(
          "swap_type",
          block([
            field("trigger", block([triggerEntries()]), occurs.one),
            field("name", typeRef("job"), occurs.optional),
            field("name", primitive("localisation"), occurs.optional),
            field("desc", primitive("localisation"), occurs.optional),
            field("icon", primitive("file", undefined, "gfx/interface/icons/jobs/job_,.dds"), occurs.optional),
            field("building_icon", primitive("icon", undefined, "gfx/interface/icons/buildings"), occurs.optional),
            field("building_icon", typeRef("building"), occurs.optional),
            field("condition_string", primitive("localisation"), occurs.optional),
            field("weight", primitive("integer"), occurs.one),
          ]),
          occurs.any,
          { scope: replaceScope({ root: ScopeId.Planet }) },
        ),
      ]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.PopGroup }) },
    ),
    field(
      "promotion",
      block([field("time", primitive("integer"), occurs.one), field("effect", block([effectEntries()]), occurs.one)]),
      occurs.optional,
    ),
    field(
      "demotion",
      block([field("time", primitive("integer"), occurs.one), field("effect", block([effectEntries()]), occurs.one)]),
      occurs.any,
    ),
    field("tags", block([item(typeRef("job_tags"), occurs.any)]), occurs.optional),
    field(
      "triggered_tags",
      block([
        field("trigger", block([triggerEntries()]), occurs.one),
        field("tags", block([item(typeRef("job_tags"), occurs.any)]), occurs.one),
      ]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.Planet }) },
    ),
  ],
});
