// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  between,
  block,
  defineType,
  definitionLocalisation,
  enumRef,
  field,
  item,
  keyedBlocks,
  literal,
  occurs,
  primitive,
  replaceScope,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const mapMode: DefinitionType = defineType({
  id: DefinitionTypeId.MapMode,
  source: keyedBlocks("common/map_modes"),
  variants: [],
  localisation: [definitionLocalisation("name", "$", true), definitionLocalisation("desc", "$_desc", true)],
  modifiers: [],
  entries: [
    field("icon", typeRef("sprite"), occurs.one),
    field("enable_terra_incognita", primitive("boolean"), occurs.one),
    field("can_change_point_of_view", primitive("boolean"), occurs.optional),
    field("display_storms", primitive("boolean"), occurs.optional),
    field("tutorial", literal("STORM_FORECAST_MAP_MODE"), occurs.optional),
    field("shortcut", primitive("scalar"), occurs.optional),
    field("display_claims", primitive("boolean"), occurs.optional),
    field("display_espionage_operations", primitive("boolean"), occurs.optional),
    field("visible", block([triggerEntries()]), occurs.optional),
    field(
      "color",
      block([
        field("type", literal("country_and_borders"), occurs.optional),
        field("type", literal("country"), occurs.optional),
        field("type", literal("borders"), occurs.optional),
        field("zoom", primitive("integer"), occurs.optional),
        field("value", literal("country"), occurs.one),
        field("value", literal("union"), occurs.one),
        field("value", block([item(primitive("number"), between(3, 4))]), occurs.one),
        field("custom_tooltip", primitive("localisation"), occurs.optional),
        field("hardcoded_tooltip", enumRef(EnumId.HardcodedMapModeTooltip), occurs.optional),
        field("condition", block([triggerEntries()]), occurs.one, {
          scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Country }),
        }),
        field("filter", enumRef(EnumId.HardcodedMapModeFilters), occurs.optional),
      ]),
      occurs.oneOrMore,
    ),
  ],
});
