// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  field,
  keyedBlocks,
  modifierEntries,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const megaOverclock: DefinitionType = defineType({
  id: DefinitionTypeId.MegaOverclock,
  source: keyedBlocks("common/megastructure_overclock_types"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("icon", typeRef("sprite"), occurs.one),
    field("potential", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.System, from: ScopeId.Country }),
    }),
    field("resources", block([ruleSetEntries("economic_template")]), occurs.optional),
    field(
      "modifier",
      block([field("custom_tooltip", primitive("localisation"), occurs.any), modifierEntries()]),
      occurs.one,
      { scope: replaceScope({ root: ScopeId.Country }) },
    ),
    field("icon", typeRef("sprite"), occurs.one),
    field("potential", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.System, from: ScopeId.Country }),
    }),
    field("resources", block([ruleSetEntries("economic_template")]), occurs.optional),
    field(
      "modifier",
      block([field("custom_tooltip", primitive("localisation"), occurs.any), modifierEntries()]),
      occurs.one,
      { scope: replaceScope({ root: ScopeId.Country }) },
    ),
  ],
});
