// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  enumRef,
  field,
  fieldPresent,
  item,
  keyedBlocks,
  literal,
  modifierEntries,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  scriptValue,
  triggerEntries,
  typeRef,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const megastructure: DefinitionType = defineType({
  id: DefinitionTypeId.Megastructure,
  source: keyedBlocks("common/megastructures"),
  variants: [
    { id: "base_level", when: fieldPresent("placement_rules") },
    { id: "has_prereqs", when: fieldPresent("prerequisites") },
  ],
  localisation: [
    definitionLocalisation("Name", "$", true),
    definitionLocalisation("Description", "$_DESC", true),
    definitionLocalisation("Details", "$_MEGASTRUCTURE_DETAILS", true, "base_level"),
    definitionLocalisation("Delayed info", "$_CONSTRUCTION_INFO_DELAYED", false, "base_level"),
  ],
  modifiers: [],
  entries: [
    field("entity", primitive("scalar"), occurs.one),
    field("rotate_to_center", primitive("boolean"), occurs.optional),
    field("scale_offset", primitive("boolean"), occurs.optional),
    field("use_planet_resource", primitive("boolean"), occurs.optional),
    field("construction_entity", primitive("scalar"), occurs.optional),
    field("construction_scale", primitive("number"), occurs.optional),
    field("portrait", typeRef("sprite"), occurs.optional),
    field("place_entity_on_planet_plane", primitive("boolean"), occurs.optional),
    field("build_type", enumRef(EnumId.MegBuildType), occurs.optional),
    field("must_select_ship_design", primitive("boolean"), occurs.optional),
    field(
      "entity_offset",
      block([field("x", primitive("number"), occurs.one), field("y", primitive("number"), occurs.one)]),
      occurs.optional,
    ),
    field("is_grand_archive", primitive("boolean"), occurs.optional),
    field("construction_blocks_others", primitive("boolean"), occurs.optional),
    field("build_outside_gravity_well", primitive("boolean"), occurs.optional),
    field("show_galactic_map_icon", primitive("boolean"), occurs.optional),
    field("show_in_outliner", primitive("boolean"), occurs.optional, {
      documentation: "Default yes, if yes megastructure will be shown in outliner",
    }),
    field("outliner_trigger", block([triggerEntries()]), occurs.optional, {
      documentation:
        "an extra trigger to allow scripted reasons to hide the megastructure. if defined both show_in_outliner and this trigger need to be true for the megastructure to show in the outliner",
      scope: replaceScope({ root: ScopeId.Megastructure }),
    }),
    field("bypass_type", typeRef("bypass"), occurs.optional),
    field("upgrade_desc", primitive("localisation"), occurs.optional, {
      documentation: "also possible to use here upgrade_desc = hide, and localisations are not required in that case",
    }),
    field("upgrade_desc", literal("hide"), occurs.optional, {
      documentation: "also possible to use here upgrade_desc = hide, and localisations are not required in that case",
    }),
    field("upgrade_from", block([item(typeRef("megastructure"), occurs.any)]), occurs.optional),
    field("custom_tooltip_requirements", primitive("localisation"), occurs.optional),
    field("build_system_tooltip", primitive("localisation"), occurs.optional),
    field("prerequisites", block([item(typeRef("technology"), occurs.oneOrMore)]), occurs.optional),
    whenVariant("has_prereqs", [
      field("show_prereqs", primitive("boolean"), occurs.optional),
      field("prereq_name", primitive("localisation"), occurs.optional),
    ]),
    ruleSetEntries("triggered_country_modifier_country"),
    field("potential", block([triggerEntries()]), occurs.optional, { scope: replaceScope({ root: ScopeId.Country }) }),
    field("possible", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.System, from: ScopeId.Country }),
    }),
    field("starbase", typeRef("starbase_level"), occurs.optional),
    field("build_time", primitive("integer"), occurs.optional),
    field("plane_offset", primitive("number"), occurs.optional),
    field(
      "resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.optional,
    ),
    field("overlord_can_upgrade", primitive("boolean"), occurs.optional),
    field("scales_with_planet", primitive("boolean"), occurs.optional),
    field("is_ruined_orbital_ring", primitive("boolean"), occurs.optional),
    field(
      "country_modifier",
      block([field("custom_tooltip", primitive("localisation"), occurs.any), modifierEntries()]),
      occurs.optional,
      { documentation: "accepts country modifiers", scope: replaceScope({ root: ScopeId.Country }) },
    ),
    field("ship_modifier", block([modifierEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Ship }),
    }),
    field("station_modifier", block([modifierEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Megastructure }),
    }),
    field(
      "placement_rules",
      block([
        triggerEntries(),
        field("planet_possible", block([triggerEntries()]), occurs.optional, {
          scope: replaceScope({ root: ScopeId.Planet }),
        }),
      ]),
      occurs.optional,
    ),
    field("on_build_queued", block([effectEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.System, from: ScopeId.Country, fromFrom: ScopeId.Fleet }),
    }),
    field("on_build_unqueued", block([effectEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.System, from: ScopeId.Country, fromFrom: ScopeId.Fleet }),
    }),
    field("on_build_start", block([effectEntries()]), occurs.optional, {
      scope: replaceScope({
        root: ScopeId.System,
        from: ScopeId.Country,
        fromFrom: ScopeId.Megastructure,
        fromFromFrom: ScopeId.Fleet,
      }),
    }),
    field("on_build_cancel", block([effectEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.System, from: ScopeId.Country }),
    }),
    field("on_build_complete", block([effectEntries()]), occurs.optional, {
      scope: replaceScope({
        root: ScopeId.System,
        from: ScopeId.Country,
        fromFrom: ScopeId.Megastructure,
        fromFromFrom: ScopeId.Fleet,
      }),
    }),
    field("ai_weight", block([modifierRuleEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.System, from: ScopeId.Country, fromFrom: ScopeId.Megastructure }),
    }),
    field("sensor_range", primitive("integer"), occurs.optional),
    field("hyperlane_range", primitive("integer"), occurs.optional),
    field("construction_blocks_and_blocked_by", enumRef(EnumId.MegastructureBlockType), occurs.optional, {
      documentation:
        "the type of constructions that block (and are in turn blocked by) this construction, default: multi_stage_type",
    }),
    field("victory_score", primitive("integer"), occurs.optional),
    field("build_megastructure_no_cost_localization_key", primitive("localisation"), occurs.optional),
    field("hide_name", primitive("boolean"), occurs.optional),
    field(
      "dismantle_cost",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.optional,
    ),
    field("dismantle_time", primitive("integer"), occurs.optional),
    field("dismantle_potential", block([triggerEntries()]), occurs.optional),
    field("can_be_dismantled_by_non_owner", primitive("boolean"), occurs.optional),
    field("dismantle_possible", block([triggerEntries()]), occurs.optional),
    field("should_ai_dismantle", block([triggerEntries()]), occurs.optional),
    field("on_dismantle_complete", block([effectEntries()]), occurs.optional),
    field("is_shroud_seal", primitive("boolean"), occurs.optional),
    field("overclock_types", block([item(typeRef("mega_overclock"), occurs.any)]), occurs.optional),
    field("cycle_length_in_days", scriptValue("number"), occurs.optional),
    field("cycle_title", primitive("localisation"), occurs.optional),
    field("cycle_desc", primitive("localisation"), occurs.optional),
    field("cycle_icon", typeRef("sprite"), occurs.optional),
    field("on_cycle_complete", block([effectEntries()]), occurs.optional),
  ],
});
