// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  field,
  keyedBlocks,
  modifierEntries,
  occurs,
  replaceScope,
  ruleSetEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const menacePerk: DefinitionType = defineType({
  id: DefinitionTypeId.MenacePerk,
  source: keyedBlocks("common/menace_perks"),
  variants: [],
  localisation: [definitionLocalisation("Name", "", true), definitionLocalisation("Description", "_desc", true)],
  modifiers: [],
  entries: [
    field("portrait", typeRef("sprite"), occurs.one),
    field(
      "resources",
      block([
        field("category", typeRef("economic_category"), occurs.one),
        ruleSetEntries("economic_template_only_produces"),
      ]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.Country }) },
    ),
    field("modifier", block([modifierEntries()]), occurs.optional, { scope: replaceScope({ root: ScopeId.Country }) }),
    field("on_unlock", block([effectEntries()]), occurs.optional, { scope: replaceScope({ root: ScopeId.Country }) }),
  ],
});
