// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import { block, defineType, enumRef, field, occurs, primitive, taggedBlocks, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const modelMesh: DefinitionType = defineType({
  id: DefinitionTypeId.ModelMesh,
  source: taggedBlocks("gfx/models", "name", [], true, {
    rootKeyFilter: { mode: "include", values: ["pdxmesh"] },
    container: { kind: "named-container", key: "objectTypes" },
  }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("scalar"), occurs.one),
    field("file", primitive("file"), occurs.one),
    field("scale", primitive("number"), occurs.optional),
    field(
      "meshsettings",
      block([
        field("name", primitive("scalar"), occurs.optional),
        field("index", primitive("integer"), occurs.optional),
        field("shader", primitive("scalar"), occurs.optional),
        field("texture_diffuse", primitive("scalar"), occurs.optional),
        field("texture_normal", primitive("scalar"), occurs.optional),
        field("texture_specular", primitive("scalar"), occurs.optional),
        field("texture_wpo", primitive("scalar"), occurs.optional),
      ]),
      occurs.any,
    ),
    field(
      "animation",
      block([
        field("id", enumRef(EnumId.ModelAnimationTypes), occurs.one),
        field("id", primitive("scalar"), occurs.one),
        field("type", typeRef("model_animation"), occurs.one),
      ]),
      occurs.any,
    ),
    field("cull_distance", primitive("scalar"), occurs.optional),
    field("name", primitive("scalar"), occurs.one),
    field("file", primitive("file"), occurs.one),
    field("scale", primitive("number"), occurs.optional),
    field(
      "meshsettings",
      block([
        field("name", primitive("scalar"), occurs.optional),
        field("index", primitive("integer"), occurs.optional),
        field("shader", primitive("scalar"), occurs.optional),
        field("texture_diffuse", primitive("scalar"), occurs.optional),
        field("texture_normal", primitive("scalar"), occurs.optional),
        field("texture_specular", primitive("scalar"), occurs.optional),
        field("texture_wpo", primitive("scalar"), occurs.optional),
      ]),
      occurs.any,
    ),
    field(
      "animation",
      block([
        field("id", enumRef(EnumId.ModelAnimationTypes), occurs.one),
        field("id", primitive("scalar"), occurs.one),
        field("type", typeRef("model_animation"), occurs.one),
      ]),
      occurs.any,
    ),
    field("cull_distance", primitive("scalar"), occurs.optional),
  ],
});
