// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import { block, defineType, enumRef, field, keyedBlocks, occurs, primitive, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const mutationsType: DefinitionType = defineType({
  id: DefinitionTypeId.MutationsType,
  source: keyedBlocks("common/mutations"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("type", enumRef(EnumId.TypeOfMutation), occurs.optional),
    field("icon", typeRef("sprite"), occurs.one),
    field("ship_limit", primitive("integer"), occurs.optional),
    field(
      "ship_components",
      block([
        field("small", typeRef("component_template"), occurs.optional),
        field("medium", typeRef("component_template"), occurs.optional),
        field("large", typeRef("component_template"), occurs.optional),
        field("extra_large", typeRef("component_template"), occurs.optional),
      ]),
      occurs.optional,
    ),
    field("is_unique", primitive("boolean"), occurs.optional),
    field("upgrades_to", typeRef("mutations_type"), occurs.optional),
    field("component_slot_size_to_disable", enumRef(EnumId.WeaponSlotSize), occurs.optional),
    field("custom_tooltip", primitive("localisation"), occurs.optional),
  ],
});
