// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { between, block, defineType, field, item, keyedBlocks, occurs, primitive, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const nadditionalcontent: DefinitionType = defineType({
  id: DefinitionTypeId.Nadditionalcontent,
  source: keyedBlocks("common/defines", true, { rootKeyFilter: { mode: "include", values: ["NAdditionalContent"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("ADDITIONAL_CONTENT_TAB_FIRST_SPRITE_ACTIVE", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_TAB_FIRST_SPRITE_INACTIVE", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_TAB_REST_SPRITE_ACTIVE", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_TAB_REST_SPRITE_INACTIVE", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_MODE_FIRST_SPRITE_ACTIVE", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_MODE_FIRST_SPRITE_INACTIVE", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_MODE_REST_SPRITE_ACTIVE", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_MODE_REST_SPRITE_INACTIVE", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_ITEM_LABEL_NEW", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_ITEM_LABEL_RECOMMENDED", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_ITEM_LABEL_DISCOUNT", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_ITEM_LABEL_OWNED", typeRef("sprite"), occurs.optional),
    field(
      "ADDITIONAL_CONTENT_ITEM_LABEL_OWNED_TEXT_COLOR",
      block([item(primitive("number"), between(4, 4))]),
      occurs.optional,
    ),
    field(
      "ADDITIONAL_CONTENT_ITEM_LABEL_DEFAULT_TEXT_COLOR",
      block([item(primitive("number"), between(4, 4))]),
      occurs.optional,
    ),
    field("ADDITIONAL_CONTENT_ITEM_FRAME", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_ITEM_FRAME_NEW", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_ITEM_FRAME_RECOMMENDED", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_ITEM_FRAME_DISCOUNT", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_ITEM_FRAME_OWNED", typeRef("sprite"), occurs.optional),
    field("ADDITIONAL_CONTENT_PORTRAIT_PREVIEW_SCALE_SMALL", primitive("number"), occurs.optional),
    field("ADDITIONAL_CONTENT_LOADING_SHOW_SPINNER_DELAY", primitive("number"), occurs.optional),
    field("ADDITIONAL_CONTENT_LOADING_MINIMUM_SPINNER_TIME", primitive("number"), occurs.optional),
    field("TIMELINE_NAVIGATION_AMOUNT_OF_ZOOM_LEVELS", primitive("number"), occurs.optional),
    field("TIMELINE_MAX_PAGE_SQUARES", primitive("number"), occurs.optional),
  ],
});
