// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, field, keyedBlocks, occurs, primitive } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const namedColor: DefinitionType = defineType({
  id: DefinitionTypeId.NamedColor,
  source: keyedBlocks("common/named_colors"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("color", primitive("colour", undefined, undefined, "rgb"), occurs.one),
    field("color", primitive("colour", undefined, undefined, "rgb"), occurs.one),
  ],
});
