// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, field, keyedBlocks, occurs, primitive } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const narmy: DefinitionType = defineType({
  id: DefinitionTypeId.Narmy,
  source: keyedBlocks("common/defines", true, { rootKeyFilter: { mode: "include", values: ["NArmy"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("MONTHLY_REINFORCE", primitive("number"), occurs.optional),
    field("BASE_HEALTH", primitive("number"), occurs.optional),
    field("BASE_DAMAGE_MIN", primitive("number"), occurs.optional),
    field("BASE_DAMAGE_MAX", primitive("number"), occurs.optional),
    field("BASE_MORALE", primitive("number"), occurs.optional),
    field("MORALE_DAMAGE_MULT", primitive("number"), occurs.optional),
    field("MONTHLY_MORALE_REGENERATION", primitive("number"), occurs.optional),
    field("DISENGAGED_EFFECT", primitive("number"), occurs.optional),
    field("BROKEN_MORALE_EFFECT", primitive("number"), occurs.optional),
    field("LOW_MORALE_THRESHOLD", primitive("number"), occurs.optional),
    field("LOW_MORALE_EFFECT", primitive("number"), occurs.optional),
    field("ARMY_EXP_GAIN_DAMAGE_DEALT", primitive("number"), occurs.optional),
    field("ARMY_EXP_GAIN_DAMAGE_TAKEN", primitive("number"), occurs.optional),
    field("ARMY_EXP_EXPERIENCED", primitive("number"), occurs.optional),
    field("ARMY_EXP_VETERAN", primitive("number"), occurs.optional),
    field("ARMY_EXP_ELITE", primitive("number"), occurs.optional),
    field("NUM_DAYS_BEFORE_RETREAT", primitive("number"), occurs.optional),
    field("RETREAT_UNIT_LOST_MIN_CHANCE", primitive("number"), occurs.optional),
    field("RETREAT_UNIT_LOST_MAX_CHANCE", primitive("number"), occurs.optional),
    field("GROUND_COMBAT_RANDOM_TARGETING_WEIGHT", primitive("number"), occurs.optional),
    field("GROUND_COMBAT_LOW_HEALTH_THRESHOLD", primitive("number"), occurs.optional),
    field("GROUND_COMBAT_LOW_HEALTH_TARGETING_WEIGHT", primitive("number"), occurs.optional),
    field("ARMY_MILITARY_POWER_SCALE", primitive("number"), occurs.optional),
    field("ARMY_MILITARY_POWER_EXPONENT", primitive("number"), occurs.optional),
    field("ARMY_MILITARY_POWER_DAMAGE_MULT", primitive("number"), occurs.optional),
    field("ARMY_MILITARY_POWER_MORALE_DAMAGE_MULT", primitive("number"), occurs.optional),
    field("ARMY_MILITARY_POWER_HEALTH_MULT", primitive("number"), occurs.optional),
    field("ARMY_MILITARY_POWER_MORALE_MULT", primitive("number"), occurs.optional),
    field("ARMY_MILITARY_POWER_NO_MORALE_FACTOR", primitive("number"), occurs.optional),
    field("ARMY_DISENGAGE_BASE_CHANCE", primitive("number"), occurs.optional),
    field("ARMY_DISENGAGE_MAX_CHANCE", primitive("number"), occurs.optional),
    field("ARMY_DISENGAGE_HEALTH_THRESHOLD", primitive("number"), occurs.optional),
    field("ARMY_DISENGAGE_MORALE_DIV", primitive("number"), occurs.optional),
    field("ARMY_DISENGAGE_MORALE_MIN_DIV", primitive("number"), occurs.optional),
    field("ARMY_DISENGAGE_TARGET_PRIO", primitive("number"), occurs.optional),
  ],
});
