// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, keyedBlocks } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const nengine: DefinitionType = defineType({
  id: DefinitionTypeId.Nengine,
  source: keyedBlocks("common/defines", true, { rootKeyFilter: { mode: "include", values: ["NEngine"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [],
});
