// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  field,
  keyedBlocks,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const observationStationMission: DefinitionType = defineType({
  id: DefinitionTypeId.ObservationStationMission,
  source: keyedBlocks("common/observation_station_missions"),
  variants: [],
  localisation: [
    definitionLocalisation("name", "mission_$", true),
    definitionLocalisation("desc", "mission_$_desc", true),
  ],
  modifiers: [],
  entries: [
    field("icon", typeRef("sprite"), occurs.one),
    field("small_icon", primitive("integer"), occurs.one),
    field(
      "resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.optional,
    ),
    field("potential", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Planet }),
    }),
    field("valid", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Planet }),
    }),
    field("monthly_progress", primitive("number", { min: 0, max: 1 }), occurs.optional),
    field("completion_event", typeRef("event", "country"), occurs.optional),
    field("completion_sound", typeRef("sound_effect"), occurs.optional),
    field("ai_weight", block([modifierRuleEntries()]), occurs.one),
    field("icon", typeRef("sprite"), occurs.one),
    field("small_icon", primitive("integer"), occurs.one),
    field(
      "resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.optional,
    ),
    field("potential", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Planet }),
    }),
    field("valid", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Planet }),
    }),
    field("monthly_progress", primitive("number", { min: 0, max: 1 }), occurs.optional),
    field("completion_event", typeRef("event", "country"), occurs.optional),
    field("completion_sound", typeRef("sound_effect"), occurs.optional),
    field("ai_weight", block([modifierRuleEntries()]), occurs.one),
  ],
});
