// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, field, item, keyedBlocks, literal, numericKey, occurs, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const onAction: DefinitionType = defineType({
  id: DefinitionTypeId.OnAction,
  source: keyedBlocks("common/on_actions"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("events", block([item(typeRef("event"), occurs.any)]), occurs.optional),
    field(
      "random_events",
      block([field(numericKey(), literal(0), occurs.any), field(numericKey(), typeRef("event"), occurs.any)]),
      occurs.optional,
    ),
  ],
});
