// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  enumRef,
  field,
  fieldEquals,
  fieldPresent,
  keyedBlocks,
  literal,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  triggerEntries,
  unlessVariant,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const opinionModifier: DefinitionType = defineType({
  id: DefinitionTypeId.OpinionModifier,
  source: keyedBlocks("common/opinion_modifiers"),
  variants: [
    { id: "triggered_opinion_modifier", when: fieldPresent("trigger") },
    { id: "block_triggered", when: fieldEquals("block_triggered", true) },
  ],
  localisation: [definitionLocalisation("Name", "$", true)],
  modifiers: [],
  entries: [
    field(
      "opinion",
      block([
        modifierRuleEntries({ documentation: "root = country with the opinion, from = country it has the opinion of" }),
        field("modifier", block([field("factor", enumRef(EnumId.ExeSetVariable), occurs.one)]), occurs.any),
      ]),
      occurs.one,
      { scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Country }) },
    ),
    field("opinion", primitive("number"), occurs.one),
    unlessVariant("triggered_opinion_modifier", [
      field("decay", primitive("number"), occurs.optional),
      field(
        "decay",
        block([
          modifierRuleEntries({
            documentation: "root = country with the opinion, from = country it has the opinion of",
          }),
        ]),
        occurs.optional,
        { scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Country }) },
      ),
      field("growth", primitive("number"), occurs.optional),
      field(
        "growth",
        block([
          modifierRuleEntries({
            documentation: "root = country with the opinion, from = country it has the opinion of",
          }),
        ]),
        occurs.optional,
        { scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Country }) },
      ),
      field("accumulative", primitive("boolean"), occurs.optional, { documentation: "No by default" }),
      field("min", primitive("integer", { min: -9999, max: -1 }), occurs.optional, {
        documentation: "For use with accumulative if the base is negative",
      }),
      field("max", primitive("integer", { min: 1, max: 999 }), occurs.optional, {
        documentation: "For use with accumulative if the base is positive",
      }),
      field("unique", primitive("boolean"), occurs.optional),
      field("monthly", literal(true), occurs.optional),
      field("months", primitive("integer"), occurs.optional),
    ]),
    whenVariant("block_triggered", [
      field("block_triggered", literal(true), occurs.one, {
        documentation: "stops modifier from automatically triggering when trigger evaluates to true",
      }),
      field("min", primitive("integer", { min: -9999, max: -1 }), occurs.optional, {
        documentation: "For use with accumulative if the base is negative",
      }),
      field("max", primitive("integer", { min: 1, max: 999 }), occurs.optional, {
        documentation: "For use with accumulative if the base is positive",
      }),
    ]),
    whenVariant("triggered_opinion_modifier", [
      field("trigger", block([triggerEntries()]), occurs.one, {
        documentation: "root = country with the opinion, from = country it has the opinion of",
        scope: replaceScope({ root: ScopeId.Country, from: ScopeId.Country }),
      }),
    ]),
  ],
});
