// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, field, item, keyedBlocks, occurs, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const ownershipLimit: DefinitionType = defineType({
  id: DefinitionTypeId.OwnershipLimit,
  source: keyedBlocks("common/country_limits/ownership_limits"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("ship_of_size_limits", block([item(typeRef("ship_of_size_limit"), occurs.oneOrMore)]), occurs.optional),
  ],
});
