// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, taggedBlocks } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const paragonUiNameType: DefinitionType = defineType({
  id: DefinitionTypeId.ParagonUiNameType,
  source: taggedBlocks("interface", "name", [], true, {
    files: ["paragon_ui_types.gui"],
    rootKeyFilter: { mode: "include", values: ["containerWindowType"] },
    container: { kind: "named-container", key: "guiTypes" },
  }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [],
});
