// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  between,
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  enumRef,
  field,
  item,
  keyedBlocks,
  modifierRuleEntries,
  occurs,
  primitive,
  ruleSetEntries,
  scriptValue,
  triggerEntries,
  typeKey,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const patrons: DefinitionType = defineType({
  id: DefinitionTypeId.Patrons,
  source: keyedBlocks("common/patrons", false),
  entryScope: ScopeId.Country,
  variants: [],
  localisation: [definitionLocalisation("Name", "$", true), definitionLocalisation("Description", "$_desc", true)],
  modifiers: [],
  entries: [
    field("category", enumRef(EnumId.PatronsCategory), occurs.optional),
    field("color", block([item(primitive("number"), between(4, 4))]), occurs.one),
    field("potential", block([triggerEntries()]), occurs.optional),
    field("text_color_code", primitive("scalar"), occurs.optional),
    field("first_contact_event", typeRef("event"), occurs.optional),
    field("covenant_event", typeRef("event"), occurs.optional),
    field("covenant_confirmation_time", scriptValue("number"), occurs.optional),
    field("add_modifier", primitive("boolean"), occurs.optional),
    field("pre_communications_name_format", primitive("scalar"), occurs.optional),
    field(
      "position",
      block([field("x", primitive("number"), occurs.one), field("y", primitive("number"), occurs.one)]),
      occurs.optional,
    ),
    field("callings", block([item(typeRef("patrons_callings"), occurs.any)]), occurs.optional),
    field("deeds", block([item(typeRef("patrons_deeds"), occurs.any)]), occurs.optional),
    field(
      "covenant",
      block([
        field("name", primitive("localisation"), occurs.optional),
        field("icon", primitive("scalar"), occurs.optional),
        field("desc", primitive("localisation"), occurs.optional),
        ruleSetEntries("triggered_modifier_country"),
        field("custom_tooltip", primitive("localisation"), occurs.optional),
        field("show_only_custom_tooltip", primitive("boolean"), occurs.optional),
      ]),
      occurs.optional,
    ),
    field(
      "passive_accord",
      block([
        field("name", primitive("localisation"), occurs.optional),
        field("hide_desc", primitive("boolean"), occurs.optional),
        field("icon", primitive("scalar"), occurs.optional),
        ruleSetEntries("triggered_modifier_country"),
        field(
          "desc",
          block([
            field("text", primitive("localisation"), occurs.optional),
            field("trigger", block([triggerEntries()]), occurs.optional),
          ]),
          occurs.any,
        ),
        field(
          "on_unlock",
          block([
            field("potential", block([triggerEntries()]), occurs.optional),
            field("custom_tooltip", primitive("localisation"), occurs.optional),
            effectEntries(),
          ]),
          occurs.any,
        ),
        field(
          "on_revert",
          block([field("custom_tooltip", primitive("localisation"), occurs.optional), effectEntries()]),
          occurs.optional,
        ),
      ]),
      occurs.any,
    ),
    field(
      "active_accord",
      block([
        field("name", primitive("localisation"), occurs.optional),
        field("icon", primitive("scalar"), occurs.optional),
        field("sound", typeRef("sound_effect"), occurs.optional),
        field("cooldown", primitive("integer"), occurs.optional),
        field("cost_override_key", primitive("localisation"), occurs.optional),
        field("first_cooldown", primitive("integer"), occurs.optional),
        field(
          "activation_cost",
          block([field("cost", block([field(typeKey("resource"), primitive("integer"), occurs.any)]), occurs.one)]),
          occurs.optional,
        ),
        field("potential", block([triggerEntries()]), occurs.optional),
        field(
          "possible",
          block([
            field("custom_tooltip", primitive("localisation"), occurs.optional),
            field(
              "custom_tooltip",
              block([
                field("text", primitive("localisation"), occurs.optional),
                field("fail_text", primitive("localisation"), occurs.optional),
                triggerEntries(),
              ]),
              occurs.optional,
            ),
            triggerEntries(),
          ]),
          occurs.optional,
        ),
        field(
          "effect",
          block([field("custom_tooltip", primitive("localisation"), occurs.optional), effectEntries()]),
          occurs.optional,
        ),
        field("on_revert", block([effectEntries()]), occurs.optional),
        field(
          "ai_will_do",
          block([triggerEntries(), field("factor", primitive("number"), occurs.optional), modifierRuleEntries()]),
          occurs.optional,
        ),
      ]),
      occurs.any,
    ),
  ],
});
