// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, field, keyedBlocks, occurs, primitive, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const pingmap: DefinitionType = defineType({
  id: DefinitionTypeId.Pingmap,
  source: keyedBlocks("gfx/pingmap"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("system_entity", typeRef("model_entity"), occurs.one),
    field("galaxy_entity", typeRef("model_entity"), occurs.one),
    field("system_normal_zoom", primitive("integer"), occurs.one),
    field("galaxy_normal_zoom", primitive("integer"), occurs.one),
    field("duration", primitive("integer"), occurs.one),
    field("system_entity", typeRef("model_entity"), occurs.one),
    field("galaxy_entity", typeRef("model_entity"), occurs.one),
    field("system_normal_zoom", primitive("integer"), occurs.one),
    field("galaxy_normal_zoom", primitive("integer"), occurs.one),
    field("duration", primitive("integer"), occurs.one),
  ],
});
