// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { between, block, defineType, field, item, keyedBlocks, occurs, primitive, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const planetKillerAnimation: DefinitionType = defineType({
  id: DefinitionTypeId.PlanetKillerAnimation,
  source: keyedBlocks("gfx/projectiles/planet_destruction"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("texture", primitive("file"), occurs.one),
    field("color", block([item(primitive("number"), between(4, 4))]), occurs.one),
    field("planet_dissolve_color_mult", block([item(primitive("number"), between(3, 3))]), occurs.optional),
    field("windup_entity", typeRef("model_entity"), occurs.optional),
    field("ship_fire_entity", typeRef("model_entity"), occurs.optional),
    field("planet_hit_entity", typeRef("model_entity"), occurs.optional),
    field("star_hit_entity", typeRef("model_entity"), occurs.optional),
    field("megastructure_hit_entity", typeRef("model_entity"), occurs.optional),
    field("hit_entity_positioning", primitive("scalar"), occurs.optional),
    field("planet_overlay_entity", typeRef("model_entity"), occurs.optional),
    field(
      "windup",
      block([
        field("duration", primitive("number"), occurs.one),
        field("width", block([item(primitive("number"), between(2, 8))]), occurs.optional),
        field("texture_scroll_speed", block([item(primitive("number"), between(2, 6))]), occurs.optional),
        field("texture_tiling", primitive("number"), occurs.optional),
        field("alpha", block([item(primitive("number"), between(2, 10))]), occurs.optional),
      ]),
      occurs.one,
    ),
    field(
      "start",
      block([
        field("duration", primitive("number"), occurs.one),
        field("width", block([item(primitive("number"), between(2, 10))]), occurs.one),
        field("texture_scroll_speed", block([item(primitive("number"), between(2, 6))]), occurs.one),
        field("texture_tiling", primitive("number"), occurs.one),
        field("alpha", block([item(primitive("number"), between(2, 10))]), occurs.one),
      ]),
      occurs.one,
      {
        documentation:
          'If the ship\'s entity has a state called "kill_planet" and that state has an event with id "beam_start" then the game will delay this state until that event has fired. This allows the entities to set their own timing and allows more freedom in the animations. width, texture_scroll_speed, texture_tiling, and alpha all support animation curves and constant assignment for example, width = 1.0 will give the beam a constant width of 1.0 width = { 0.0 1.0 \t1.0 2.0 } will make the beam start with a width of 1.0 and interpolate to a width of 2.0 after one second has passed width = { timestamp value timestamp value timestamp value } timestamp values are scaled so that 1.0 matches duration',
      },
    ),
    field(
      "in_progress",
      block([
        field("duration", primitive("number"), occurs.one),
        field("width", block([item(primitive("number"), between(2, 10))]), occurs.one),
        field("texture_scroll_speed", block([item(primitive("number"), between(2, 6))]), occurs.one),
        field("texture_tiling", block([item(primitive("number"), between(2, 2))]), occurs.one),
        field("alpha", block([item(primitive("number"), between(2, 10))]), occurs.one),
      ]),
      occurs.one,
    ),
    field(
      "end",
      block([
        field("duration", primitive("number"), occurs.one),
        field("width", block([item(primitive("number"), between(2, 10))]), occurs.one),
        field("texture_scroll_speed", primitive("number"), occurs.one),
        field("texture_tiling", primitive("number"), occurs.one),
        field("alpha", block([item(primitive("number"), between(2, 10))]), occurs.one),
      ]),
      occurs.one,
    ),
    field(
      "fade",
      block([
        field("fade_in", block([item(primitive("number"), between(2, 2))]), occurs.one, {
          documentation: "<Fade-in/out start/end percentage> <Width in world units>",
        }),
        field("fade_out", block([item(primitive("number"), between(2, 2))]), occurs.one),
      ]),
      occurs.one,
    ),
  ],
});
