// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import {
  anyKey,
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  enumRef,
  field,
  keyedBlocks,
  modifierRuleEntries,
  occurs,
  primitive,
  ruleSetEntries,
  scopeRef,
  triggerEntries,
  typeKey,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const popFaction: DefinitionType = defineType({
  id: DefinitionTypeId.PopFaction,
  source: keyedBlocks("common/pop_faction_types"),
  variants: [],
  localisation: [
    definitionLocalisation("Name", "pft_$", true),
    definitionLocalisation("Description", "pft_$_desc", true),
  ],
  modifiers: [],
  entries: [
    field("unique", primitive("boolean"), occurs.one, {
      documentation: "Allows to have multiple of this faction type within a single country",
    }),
    field("support_multiplier", primitive("number"), occurs.optional, {
      documentation: "How much extra weight will receive a candidate from this faction",
    }),
    field("guiding_ethic", typeRef("ethos"), occurs.optional, { documentation: "Primary ethic for this faction" }),
    field("visual_ethic", primitive("localisation"), occurs.optional),
    field("use_guiding_ethic_as_pop_filter", primitive("boolean"), occurs.optional),
    field("persistent_faction", primitive("boolean"), occurs.optional),
    field("can_rename", primitive("boolean"), occurs.optional),
    field("election_header", typeRef("sprite"), occurs.optional, { documentation: "UI color for candidate header" }),
    field("is_potential", block([triggerEntries()]), occurs.optional, {
      documentation: "This = Country. Existence requirements for this faction",
    }),
    field(
      "parameters",
      block([
        field(
          anyKey(),
          block([
            field("type", enumRef(EnumId.ScopeTypeTokens), occurs.one),
            field("valid_objects", block([triggerEntries()]), occurs.optional),
          ]),
          occurs.optional,
        ),
      ]),
      occurs.optional,
    ),
    field(
      "valid",
      block([
        triggerEntries(),
        field(
          "parameter:sector",
          block([field("debug_scope_type", scopeRef(), occurs.optional), triggerEntries()]),
          occurs.optional,
          { documentation: "HAS TO BE REWORKED !!! ###" },
        ),
      ]),
      occurs.optional,
      { documentation: "This = Pop faction. Existence requirements for defined parameter" },
    ),
    field("can_join_pre_triggers", block([ruleSetEntries("pop_pre_trigger")]), occurs.optional, {
      documentation:
        "This = Pop. Determines which pops are able to join this faction. Only uses certain simple triggers.",
    }),
    field("can_join_faction", block([triggerEntries()]), occurs.one, {
      documentation: "This = Pop. Determines which pops are able to join this faction",
    }),
    field("attraction", block([modifierRuleEntries()]), occurs.optional, {
      documentation: "This = Pop. Pop's willingness weight to join this faction",
    }),
    field("leader", block([modifierRuleEntries()]), occurs.optional, {
      documentation: "This = Leader. Pop's willingness weight to join this faction",
    }),
    field("on_create", block([effectEntries()]), occurs.optional, {
      documentation: "This = Pop faction. Some effects, immediately after faction has been established.",
    }),
    field("on_destroy", block([effectEntries()]), occurs.optional, {
      documentation: "This = Pop faction. Some effects, immediately after faction has been removed.",
    }),
    field(
      "demand",
      block([
        field("title", primitive("localisation"), occurs.optional, {
          documentation: "Issue title, shown in faction manager screen",
        }),
        field("unfulfilled_title", primitive("localisation"), occurs.optional, {
          documentation: "Unfulfilled issue title, shown in faction manager screen",
        }),
        field("desc", primitive("localisation"), occurs.optional, {
          documentation: "Issue full description, shown in faction manager screen",
        }),
        field("fulfilled_effect", primitive("number"), occurs.optional, {
          documentation: "Positive happiness effect on faction, if demand is satisfied",
        }),
        field("unfulfilled_effect", primitive("number"), occurs.optional, {
          documentation: "Negative happiness effect on faction, if demand is not satisfied",
        }),
        field("council_demand", primitive("boolean"), occurs.optional, { documentation: "Council Demand" }),
        field("potential", block([triggerEntries()]), occurs.optional, { documentation: "This = Pop faction." }),
        field("trigger", block([triggerEntries()]), occurs.one, { documentation: "This = Pop faction." }),
      ]),
      occurs.any,
      { documentation: "This = Pop faction. Faction dynamic requests & issues." },
    ),
    field(
      "actions",
      block([
        field(
          anyKey(),
          block([
            field("title", primitive("localisation"), occurs.optional),
            field("description", primitive("localisation"), occurs.optional),
            field("cost", block([field(typeKey("resource"), primitive("integer"), occurs.one)]), occurs.optional),
            field("potential", block([triggerEntries()]), occurs.optional, { documentation: "This = Pop faction." }),
            field("valid", block([triggerEntries()]), occurs.optional, { documentation: "This = Pop faction." }),
            field("effect", block([effectEntries()]), occurs.optional, { documentation: "This = Pop faction." }),
            field("ai_weight", block([modifierRuleEntries()]), occurs.optional, {
              documentation: "This = Pop faction.",
            }),
          ]),
          occurs.any,
        ),
      ]),
      occurs.optional,
      { documentation: "This = Pop faction. Actions for this pop faction type (buttons)" },
    ),
    field(
      "resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.one,
    ),
    field(
      "extortion_resource",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.optional,
    ),
  ],
});
