// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import { block, defineType, field, item, keyedBlocks, occurs, replaceScope, triggerEntries, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const portraitGroup: DefinitionType = defineType({
  id: DefinitionTypeId.PortraitGroup,
  source: keyedBlocks("gfx/portraits/portraits", true, {
    container: { kind: "named-container", key: "portrait_groups" },
  }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("default", typeRef("portrait"), occurs.optional),
    field(
      "game_setup",
      block([
        field(
          "add",
          block([
            field("trigger", block([triggerEntries()]), occurs.optional, {
              scope: replaceScope({ root: ScopeId.Country }),
            }),
            field("portraits", block([item(typeRef("portrait"), occurs.any)]), occurs.one),
          ]),
          occurs.any,
        ),
        field(
          "set",
          block([
            field("trigger", block([triggerEntries()]), occurs.optional, {
              scope: replaceScope({ root: ScopeId.Country }),
            }),
            field("portraits", block([item(typeRef("portrait"), occurs.any)]), occurs.one),
          ]),
          occurs.any,
        ),
      ]),
      occurs.optional,
    ),
    field(
      "leader",
      block([
        field(
          "add",
          block([
            field("trigger", block([triggerEntries()]), occurs.optional, {
              scope: replaceScope({ root: ScopeId.Leader }),
            }),
            field("portraits", block([item(typeRef("portrait"), occurs.any)]), occurs.one),
          ]),
          occurs.any,
        ),
        field(
          "set",
          block([
            field("trigger", block([triggerEntries()]), occurs.optional, {
              scope: replaceScope({ root: ScopeId.Leader }),
            }),
            field("portraits", block([item(typeRef("portrait"), occurs.any)]), occurs.one),
          ]),
          occurs.any,
        ),
      ]),
      occurs.optional,
    ),
    field(
      "ruler",
      block([
        field(
          "add",
          block([
            field("trigger", block([triggerEntries()]), occurs.optional, {
              scope: replaceScope({ root: ScopeId.Leader }),
            }),
            field("portraits", block([item(typeRef("portrait"), occurs.any)]), occurs.one),
          ]),
          occurs.any,
        ),
        field(
          "set",
          block([
            field("trigger", block([triggerEntries()]), occurs.optional, {
              scope: replaceScope({ root: ScopeId.Leader }),
            }),
            field("portraits", block([item(typeRef("portrait"), occurs.any)]), occurs.one),
          ]),
          occurs.any,
        ),
      ]),
      occurs.optional,
    ),
    field(
      "pop",
      block([
        field(
          "add",
          block([
            field("trigger", block([triggerEntries()]), occurs.optional, {
              scope: replaceScope({ root: ScopeId.Pop }),
            }),
            field("portraits", block([item(typeRef("portrait"), occurs.any)]), occurs.one),
          ]),
          occurs.any,
        ),
        field(
          "set",
          block([
            field("trigger", block([triggerEntries()]), occurs.optional, {
              scope: replaceScope({ root: ScopeId.Pop }),
            }),
            field("portraits", block([item(typeRef("portrait"), occurs.any)]), occurs.one),
          ]),
          occurs.any,
        ),
      ]),
      occurs.optional,
    ),
    field(
      "species",
      block([
        field(
          "add",
          block([
            field("trigger", block([triggerEntries()]), occurs.optional, {
              scope: replaceScope({ root: ScopeId.Species }),
            }),
            field("portraits", block([item(typeRef("portrait"), occurs.any)]), occurs.one),
          ]),
          occurs.any,
        ),
        field(
          "set",
          block([
            field("trigger", block([triggerEntries()]), occurs.optional, {
              scope: replaceScope({ root: ScopeId.Species }),
            }),
            field("portraits", block([item(typeRef("portrait"), occurs.any)]), occurs.one),
          ]),
          occurs.any,
        ),
      ]),
      occurs.optional,
    ),
  ],
});
