// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, field, item, keyedBlocks, occurs, primitive, triggerEntries, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const portrait: DefinitionType = defineType({
  id: DefinitionTypeId.Portrait,
  source: keyedBlocks("gfx/portraits/portraits", true, { container: { kind: "named-container", key: "portraits" } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("entity", typeRef("model_entity"), occurs.one),
    field("clothes_selector", typeRef("asset_selector", "clothes"), occurs.one),
    field("attachment_selector", typeRef("asset_selector", "hair"), occurs.one),
    field("custom_attachment_label", primitive("localisation"), occurs.optional),
    field(
      "custom_close_up_position_offset",
      block([field("x", primitive("integer"), occurs.one), field("y", primitive("integer"), occurs.one)]),
      occurs.optional,
    ),
    field(
      "custom_mid_close_up_position_offset",
      block([field("x", primitive("integer"), occurs.one), field("y", primitive("integer"), occurs.one)]),
      occurs.optional,
    ),
    field("custom_mid_close_up_scale", primitive("number"), occurs.optional),
    field("custom_close_up_scale", primitive("number"), occurs.optional),
    field("greeting_sound", typeRef("sound_effect"), occurs.optional),
    field(
      "character_textures",
      block([
        item(primitive("file"), occurs.any),
        field(
          "tied_texture",
          block([
            field("texture", primitive("file"), occurs.one),
            field("evolution_variants", block([item(primitive("integer"), occurs.one)]), occurs.one),
          ]),
          occurs.any,
        ),
      ]),
      occurs.optional,
    ),
    field(
      "portrait_evolution",
      block([
        field(
          "variants",
          block([
            item(
              block([
                field(
                  "value",
                  block([
                    item(
                      block([
                        field("decal", primitive("file"), occurs.one),
                        field("mask", primitive("file"), occurs.one),
                      ]),
                      occurs.any,
                    ),
                  ]),
                  occurs.one,
                ),
                field("trigger", block([triggerEntries()]), occurs.optional),
              ]),
              occurs.any,
            ),
          ]),
          occurs.one,
        ),
      ]),
      occurs.optional,
    ),
  ],
});
