// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, field, occurs, primitive, taggedBlocks, triggerEntries } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const preCommunicationsNameFormat: DefinitionType = defineType({
  id: DefinitionTypeId.PreCommunicationsNameFormat,
  source: taggedBlocks("common/random_names", "format", [], true, {
    rootKeyFilter: { mode: "include", values: ["pre_communications_name_format"] },
  }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field(
      "random_weight",
      block([
        field("factor", primitive("number"), occurs.one),
        field("modifier", block([field("add", primitive("number"), occurs.one), triggerEntries()]), occurs.any),
      ]),
      occurs.one,
    ),
    field("format", primitive("name-format", undefined, undefined, "pre_communications_name_parts"), occurs.one),
  ],
});
