// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, field, item, occurs, primitive, primitiveKey, taggedBlocks, valueSet } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const preCommunicationsNamePartsList: DefinitionType = defineType({
  id: DefinitionTypeId.PreCommunicationsNamePartsList,
  source: taggedBlocks("common/random_names", "key", [], true, {
    rootKeyFilter: { mode: "include", values: ["pre_communications_name_parts_list"] },
  }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("key", valueSet("pre_communications_name_parts"), occurs.one),
    field("cyclic", primitive("boolean"), occurs.optional),
    field(
      "parts",
      block([
        field(primitiveKey("localisation"), primitive("integer"), occurs.any),
        item(primitive("localisation"), occurs.any),
      ]),
      occurs.one,
    ),
  ],
});
