// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, definitionLocalisation, field, keyedBlocks, occurs, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const preFtlAge: DefinitionType = defineType({
  id: DefinitionTypeId.PreFtlAge,
  source: keyedBlocks("common/technology_ages/preftl"),
  variants: [],
  localisation: [definitionLocalisation("Name", "", true), definitionLocalisation("Description", "_desc", true)],
  modifiers: [],
  entries: [field("next_age", typeRef("pre_ftl_age"), occurs.optional)],
});
