// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, field, keyedBlocks, occurs, primitive, triggerEntries, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const precursors: DefinitionType = defineType({
  id: DefinitionTypeId.Precursors,
  source: keyedBlocks("common/precursor_civilizations"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("size", primitive("integer"), occurs.one),
    field("picture", typeRef("sprite"), occurs.optional),
    field("possible", block([triggerEntries()]), occurs.optional),
    field("size", primitive("integer"), occurs.one),
    field("picture", typeRef("sprite"), occurs.optional),
    field("possible", block([triggerEntries()]), occurs.optional),
  ],
});
