// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, field, item, keyedBlocks, occurs, primitive } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const prescriptedCountryFlags: DefinitionType = defineType({
  id: DefinitionTypeId.PrescriptedCountryFlags,
  source: keyedBlocks("common/prescripted_flags"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [field("flags", block([item(primitive("scalar"), occurs.any)]), occurs.one)],
});
