// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  effectEntries,
  field,
  keyedBlocks,
  modifierEntries,
  occurs,
  primitive,
  replaceScope,
  scriptValue,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const psionicAuras: DefinitionType = defineType({
  id: DefinitionTypeId.PsionicAuras,
  source: keyedBlocks("common/patrons/psionic_auras", false),
  entryScope: ScopeId.Country,
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("patron", typeRef("patrons"), occurs.optional),
    field("background", typeRef("sprite"), occurs.optional),
    field(
      "owner_fleet_modifier",
      block([
        field("potential", block([triggerEntries()]), occurs.optional),
        field(
          "modifier",
          block([field("custom_tooltip", primitive("localisation"), occurs.optional), modifierEntries()]),
          occurs.one,
        ),
      ]),
      occurs.any,
      { scope: replaceScope({ root: ScopeId.Ship }) },
    ),
    field(
      "owner_planet_modifier",
      block([
        field("potential", block([triggerEntries()]), occurs.optional),
        field(
          "modifier",
          block([field("custom_tooltip", primitive("localisation"), occurs.optional), modifierEntries()]),
          occurs.one,
        ),
      ]),
      occurs.any,
      { scope: replaceScope({ root: ScopeId.Planet }) },
    ),
    field(
      "neutral_fleet_modifier",
      block([
        field("potential", block([triggerEntries()]), occurs.optional),
        field(
          "modifier",
          block([field("custom_tooltip", primitive("localisation"), occurs.optional), modifierEntries()]),
          occurs.one,
        ),
      ]),
      occurs.any,
      { scope: replaceScope({ root: ScopeId.Ship }) },
    ),
    field(
      "neutral_planet_modifier",
      block([
        field("potential", block([triggerEntries()]), occurs.optional),
        field(
          "modifier",
          block([field("custom_tooltip", primitive("localisation"), occurs.optional), modifierEntries()]),
          occurs.one,
        ),
      ]),
      occurs.any,
      { scope: replaceScope({ root: ScopeId.Planet }) },
    ),
    field(
      "rival_fleet_modifier",
      block([
        field("potential", block([triggerEntries()]), occurs.optional),
        field(
          "modifier",
          block([field("custom_tooltip", primitive("localisation"), occurs.optional), modifierEntries()]),
          occurs.one,
          { scope: replaceScope({ root: ScopeId.Ship }) },
        ),
      ]),
      occurs.any,
      { scope: replaceScope({ root: ScopeId.Fleet }) },
    ),
    field(
      "rival_planet_modifier",
      block([
        field("potential", block([triggerEntries()]), occurs.optional),
        field(
          "modifier",
          block([field("custom_tooltip", primitive("localisation"), occurs.optional), modifierEntries()]),
          occurs.one,
        ),
      ]),
      occurs.any,
      { scope: replaceScope({ root: ScopeId.Planet }) },
    ),
    field(
      "daily_decrease",
      block([
        field("base", primitive("integer"), occurs.one),
        field(
          "modifier",
          block([
            field("add", scriptValue("number"), occurs.optional),
            triggerEntries(),
            field("desc", primitive("localisation"), occurs.optional),
          ]),
          occurs.any,
        ),
      ]),
      occurs.any,
      { scope: replaceScope({ root: ScopeId.System }) },
    ),
    field(
      "intensity_level",
      block([
        field("end", scriptValue("number"), occurs.one),
        field(
          "owner_fleet_modifier",
          block([
            field("potential", block([triggerEntries()]), occurs.optional),
            field(
              "modifier",
              block([field("custom_tooltip", primitive("localisation"), occurs.optional), modifierEntries()]),
              occurs.one,
            ),
          ]),
          occurs.any,
          { scope: replaceScope({ root: ScopeId.Ship }) },
        ),
        field(
          "owner_planet_modifier",
          block([
            field("potential", block([triggerEntries()]), occurs.optional),
            field(
              "modifier",
              block([field("custom_tooltip", primitive("localisation"), occurs.optional), modifierEntries()]),
              occurs.one,
            ),
          ]),
          occurs.any,
          { scope: replaceScope({ root: ScopeId.Planet }) },
        ),
        field(
          "neutral_fleet_modifier",
          block([
            field("potential", block([triggerEntries()]), occurs.optional),
            field(
              "modifier",
              block([field("custom_tooltip", primitive("localisation"), occurs.optional), modifierEntries()]),
              occurs.one,
            ),
          ]),
          occurs.any,
          { scope: replaceScope({ root: ScopeId.Ship }) },
        ),
        field(
          "neutral_planet_modifier",
          block([
            field("potential", block([triggerEntries()]), occurs.optional),
            field(
              "modifier",
              block([field("custom_tooltip", primitive("localisation"), occurs.optional), modifierEntries()]),
              occurs.one,
            ),
          ]),
          occurs.any,
          { scope: replaceScope({ root: ScopeId.Planet }) },
        ),
        field(
          "rival_fleet_modifier",
          block([
            field("potential", block([triggerEntries()]), occurs.optional),
            field(
              "modifier",
              block([field("custom_tooltip", primitive("localisation"), occurs.optional), modifierEntries()]),
              occurs.one,
              { scope: replaceScope({ root: ScopeId.Ship }) },
            ),
          ]),
          occurs.any,
          { scope: replaceScope({ root: ScopeId.Fleet }) },
        ),
        field(
          "rival_planet_modifier",
          block([
            field("potential", block([triggerEntries()]), occurs.optional),
            field(
              "modifier",
              block([field("custom_tooltip", primitive("localisation"), occurs.optional), modifierEntries()]),
              occurs.one,
            ),
          ]),
          occurs.any,
          { scope: replaceScope({ root: ScopeId.Planet }) },
        ),
        field("ai_weight_coefficient", primitive("number"), occurs.optional),
      ]),
      occurs.any,
    ),
    field("aura_galaxy_texture", primitive("file"), occurs.one),
    field("aura_hyperlane_texture", primitive("file"), occurs.one),
    field(
      "on_start",
      block([field("custom_tooltip", primitive("localisation"), occurs.optional), effectEntries()]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.System }) },
    ),
    field(
      "on_monthly",
      block([field("custom_tooltip", primitive("localisation"), occurs.optional), effectEntries()]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.System }) },
    ),
    field(
      "on_progress_complete",
      block([field("custom_tooltip", primitive("localisation"), occurs.optional), effectEntries()]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.System }) },
    ),
    field(
      "on_vanish",
      block([field("custom_tooltip", primitive("localisation"), occurs.optional), effectEntries()]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.System }) },
    ),
    field("increase_trigger", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.System }),
    }),
    field(
      "monthly_increase",
      block([
        field("base", primitive("integer"), occurs.one),
        field(
          "modifier",
          block([
            field("custom_tooltip", primitive("localisation"), occurs.optional),
            modifierEntries(),
            triggerEntries(),
            field("subtract", scriptValue("number"), occurs.optional),
            field("add", scriptValue("number"), occurs.optional),
            field("desc", primitive("localisation"), occurs.optional),
          ]),
          occurs.any,
        ),
      ]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.System }) },
    ),
    field(
      "monthly_decrease",
      block([
        field("base", primitive("integer"), occurs.one),
        field(
          "modifier",
          block([
            field("custom_tooltip", primitive("localisation"), occurs.optional),
            modifierEntries(),
            triggerEntries(),
            field("subtract", scriptValue("number"), occurs.optional),
            field("add", scriptValue("number"), occurs.optional),
            field("desc", primitive("localisation"), occurs.optional),
          ]),
          occurs.any,
        ),
      ]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.System }) },
    ),
    field(
      "on_gain_level",
      block([field("custom_tooltip", primitive("localisation"), occurs.optional), effectEntries()]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.System }) },
    ),
    field(
      "on_lose_level",
      block([field("custom_tooltip", primitive("localisation"), occurs.optional), effectEntries()]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.System }) },
    ),
    field(
      "on_type_change",
      block([field("custom_tooltip", primitive("localisation"), occurs.optional), effectEntries()]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.System }) },
    ),
    field(
      "triggered_system_modifier",
      block([
        field("potential", block([triggerEntries()]), occurs.optional),
        modifierEntries(),
        field("mult", scriptValue("number"), occurs.optional),
        field("custom_tooltip", primitive("localisation"), occurs.optional),
      ]),
      occurs.any,
      { scope: replaceScope({ root: ScopeId.System, from: ScopeId.System }) },
    ),
  ],
});
