// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { between, defineType, item, keyedBlocks, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const randomizableCombo: DefinitionType = defineType({
  id: DefinitionTypeId.RandomizableCombo,
  source: keyedBlocks("flags", true, { rootKeyFilter: { mode: "include", values: ["randomizable_combo"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [item(typeRef("color_define"), between(3, 3)), item(typeRef("color_define"), between(3, 3))],
});
