// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  field,
  item,
  keyedBlocks,
  literal,
  occurs,
  primitive,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const resolutionCategory: DefinitionType = defineType({
  id: DefinitionTypeId.ResolutionCategory,
  source: keyedBlocks("common/resolution_categories"),
  variants: [],
  localisation: [definitionLocalisation("Name", "", true)],
  modifiers: [],
  entries: [
    field("group", primitive("localisation"), occurs.one),
    field("icon", typeRef("sprite"), occurs.one),
    field("multiple_active_resolutions", literal(true), occurs.optional),
    field("resolution_types", block([item(typeRef("resolution"), occurs.oneOrMore)]), occurs.one),
  ],
});
