// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  enumKey,
  field,
  keyedBlocks,
  literal,
  modifierEntries,
  modifierRuleEntries,
  occurs,
  primitive,
  ruleSetEntries,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const resolution: DefinitionType = defineType({
  id: DefinitionTypeId.Resolution,
  source: keyedBlocks("common/resolutions"),
  variants: [],
  localisation: [definitionLocalisation("Name", "$", true), definitionLocalisation("Description", "$_desc", true)],
  modifiers: [],
  entries: [
    field("icon", primitive("scalar"), occurs.one),
    field(
      "resources",
      block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
      occurs.one,
    ),
    field("target", primitive("boolean"), occurs.one, {
      documentation: "Does the resolution require a target country?",
    }),
    field("level", primitive("integer"), occurs.optional),
    field("sanction", literal(true), occurs.optional),
    field("fire_and_forget", literal(true), occurs.optional),
    field("harmful", primitive("boolean"), occurs.optional),
    field(
      "modifier",
      block([
        field("description", primitive("localisation"), occurs.optional),
        modifierEntries(),
        field("custom_tooltip", primitive("localisation"), occurs.optional),
        field("show_only_custom_tooltip", primitive("boolean"), occurs.optional),
      ]),
      occurs.any,
      {
        documentation: "Modifier to be applied to all community members if passed. Apparently. Not sure about that...",
      },
    ),
    ruleSetEntries("triggered_modifier_country", {
      documentation: "Modifier to be applied to all community members if passed and the potential trigger is true",
    }),
    field("effect", block([effectEntries()]), occurs.optional, {
      documentation: "Effect to be applied if passed, scope is country",
    }),
    field("fail_effects", block([effectEntries()]), occurs.optional, {
      documentation: "Effect to be applied if failed, scope is country",
    }),
    field("potential", block([triggerEntries()]), occurs.optional),
    field("active", block([triggerEntries()]), occurs.optional, {
      documentation: "Resolution only in effect while this trigger is met",
    }),
    field("allow", block([triggerEntries()]), occurs.optional),
    field("breach", block([triggerEntries()]), occurs.optional),
    field("valid_target", block([triggerEntries()]), occurs.optional),
    field(
      "ai_weight",
      block([field(enumKey(EnumId.WeightOrBase), primitive("number"), occurs.one), modifierRuleEntries()]),
      occurs.one,
    ),
  ],
});
