// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, item, keyedBlocks, literal, occurs, triggerEntries } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const scriptedTrigger: DefinitionType = defineType({
  id: DefinitionTypeId.ScriptedTrigger,
  source: keyedBlocks("common/scripted_triggers", true, {
    rootKeyFilter: {
      mode: "exclude",
      values: [
        "pop_amount",
        "sapient_pop_amount",
        "psionic_pop_amount",
        "is_leader_in_storm",
        "can_artifact_analysis_give_$SPECIMEN$",
      ],
    },
  }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [item(literal("optimize_memory"), occurs.any), triggerEntries()],
});
