// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import {
  defineType,
  enumRef,
  field,
  keyedBlocks,
  literal,
  modifierRuleEntries,
  occurs,
  primitive,
  scriptValue,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const scriptValueDefinition: DefinitionType = defineType({
  id: DefinitionTypeId.ScriptValue,
  source: keyedBlocks("common/script_values"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    modifierRuleEntries(),
    field("mult", primitive("number"), occurs.any),
    field("mult", scriptValue("number"), occurs.any),
    field("mult", literal("trigger:xxxxxxxxx"), occurs.any),
    field("mult", enumRef(EnumId.OrderBy), occurs.any),
    field("mult", enumRef(EnumId.ExeSetVariable), occurs.any),
    field("divide", primitive("integer"), occurs.any),
    field("divide", scriptValue("number"), occurs.any),
    field("divide", literal("trigger:xxxxxxxxx"), occurs.any),
    field("divide", enumRef(EnumId.OrderBy), occurs.any),
    field("divide", enumRef(EnumId.ExeSetVariable), occurs.any),
    field("add", primitive("number"), occurs.any),
    field("add", scriptValue("number"), occurs.any),
    field("add", literal("trigger:xxxxxxxxx"), occurs.any),
    field("add", enumRef(EnumId.OrderBy), occurs.any),
    field("add", enumRef(EnumId.ExeSetVariable), occurs.any),
    field("subtract", primitive("number"), occurs.any),
    field("subtract", scriptValue("number"), occurs.any),
    field("subtract", literal("trigger:xxxxxxxxx"), occurs.any),
    field("subtract", enumRef(EnumId.OrderBy), occurs.any),
    field("subtract", enumRef(EnumId.ExeSetVariable), occurs.any),
  ],
});
