// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import {
  block,
  defineType,
  field,
  modifierRuleEntries,
  occurs,
  primitive,
  scriptValue,
  taggedBlocks,
  triggerEntries,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const scriptedLoc: DefinitionType = defineType({
  id: DefinitionTypeId.ScriptedLoc,
  source: taggedBlocks("common/scripted_loc", "name", []),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("scalar"), occurs.one),
    field("random", primitive("boolean"), occurs.optional),
    field(
      "text",
      block([
        field("weight", block([modifierRuleEntries()]), occurs.optional),
        field("weight", primitive("number"), occurs.optional),
        field("trigger", block([triggerEntries()]), occurs.optional),
        field("localization_key", primitive("localisation"), occurs.one),
      ]),
      occurs.any,
    ),
    field("default", primitive("localisation"), occurs.optional),
    field("value", scriptValue("number"), occurs.optional, { documentation: "value = value:<some_script_value>" }),
    field("name", primitive("scalar"), occurs.one),
    field("random", primitive("boolean"), occurs.optional),
    field(
      "text",
      block([
        field("weight", block([modifierRuleEntries()]), occurs.optional),
        field("weight", primitive("number"), occurs.optional),
        field("trigger", block([triggerEntries()]), occurs.optional),
        field("localization_key", primitive("localisation"), occurs.one),
      ]),
      occurs.any,
    ),
    field("default", primitive("localisation"), occurs.optional),
    field("value", scriptValue("number"), occurs.optional, { documentation: "value = value:<some_script_value>" }),
  ],
});
