// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import {
  block,
  defineType,
  field,
  fieldEquals,
  keyedBlocks,
  literal,
  modifierRuleEntries,
  occurs,
  primitive,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const sectorFocus: DefinitionType = defineType({
  id: DefinitionTypeId.SectorFocus,
  source: keyedBlocks("common/sector_focuses"),
  variants: [{ id: "hidden", when: fieldEquals("hidden", true) }],
  localisation: [],
  modifiers: [],
  entries: [
    field("hidden", literal(true), occurs.optional),
    field("clear_blockers", primitive("boolean"), occurs.optional),
    field("ai_weight", block([modifierRuleEntries()]), occurs.optional),
    field(
      "district",
      block([
        field("key", typeRef("district"), occurs.one),
        field("weight", block([modifierRuleEntries()]), occurs.one),
      ]),
      occurs.any,
    ),
    field(
      "building",
      block([
        field("key", typeRef("building"), occurs.one),
        field("priority", literal(true), occurs.optional, {
          documentation:
            "only works on buildings and upgrades; puts them at the front of the list (otherwise it will pick a district first, then a building, then an upgrade)",
        }),
        field("exempt_from_jobs_check", literal(true), occurs.optional, {
          documentation: "gets built whether or not a pop would work the jobs",
        }),
        field("weight", block([modifierRuleEntries()]), occurs.one),
      ]),
      occurs.any,
    ),
    field("hidden", literal(true), occurs.optional),
    field("clear_blockers", primitive("boolean"), occurs.optional),
    field("ai_weight", block([modifierRuleEntries()]), occurs.optional),
    field(
      "district",
      block([
        field("key", typeRef("district"), occurs.one),
        field("weight", block([modifierRuleEntries()]), occurs.one),
      ]),
      occurs.any,
    ),
    field(
      "building",
      block([
        field("key", typeRef("building"), occurs.one),
        field("priority", literal(true), occurs.optional, {
          documentation:
            "only works on buildings and upgrades; puts them at the front of the list (otherwise it will pick a district first, then a building, then an upgrade)",
        }),
        field("exempt_from_jobs_check", literal(true), occurs.optional, {
          documentation: "gets built whether or not a pop would work the jobs",
        }),
        field("weight", block([modifierRuleEntries()]), occurs.one),
      ]),
      occurs.any,
    ),
  ],
});
