// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  anyKey,
  anyScope,
  between,
  block,
  defineType,
  definitionLocalisation,
  enumRef,
  field,
  fieldEquals,
  item,
  keyedBlocks,
  literal,
  modifierEntries,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  scriptValue,
  triggerEntries,
  typeKey,
  typeRef,
  unlessVariant,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const shipSize: DefinitionType = defineType({
  id: DefinitionTypeId.ShipSize,
  source: keyedBlocks("common/ship_sizes"),
  variants: [
    { id: "station", when: fieldEquals("is_space_station", true) },
    { id: "ship", when: fieldEquals("is_space_station", false) },
    { id: "starbase", when: fieldEquals("class", "shipclass_starbase") },
    { id: "designable", when: fieldEquals("is_designable", true) },
  ],
  localisation: [definitionLocalisation("Name", "$", true), definitionLocalisation("Plural", "$_plural", true)],
  modifiers: [],
  entries: [
    field("graphical_culture", block([item(typeRef("graphical_culture"), occurs.oneOrMore)]), between(0, 2)),
    field("graphical_culture", primitive("boolean"), between(0, 2)),
    field("is_space_object", primitive("boolean"), occurs.optional),
    field("is_reckoning_ship", primitive("boolean"), occurs.optional),
    field("scales_with_planet", primitive("boolean"), occurs.optional),
    field("can_be_inspected", primitive("boolean"), occurs.optional),
    field("pre_communications_name", primitive("localisation"), occurs.optional),
    field("entity", typeRef("model_entity"), occurs.optional),
    field("entity", primitive("scalar"), occurs.optional),
    field("formation_priority", primitive("integer"), occurs.optional),
    field("max_speed", primitive("number"), occurs.optional),
    field("acceleration", primitive("number"), occurs.optional),
    field("rotation_speed", primitive("number"), occurs.optional),
    field("collision_radius", primitive("number"), occurs.optional),
    field("max_hitpoints", primitive("integer"), occurs.optional),
    field("is_listed", primitive("boolean"), occurs.optional),
    field("components_add_to_cost", primitive("boolean"), occurs.optional),
    field("is_entropy_conduit", primitive("boolean"), occurs.optional),
    field("is_designable", primitive("boolean"), occurs.optional),
    field("never_mia", primitive("boolean"), occurs.optional),
    field("build_time", primitive("integer"), occurs.optional, {
      documentation: "may be deprecated, tell Dayshine and Caligula if yes",
    }),
    field("is_civilian", primitive("boolean"), occurs.optional),
    field("cloaking_forbidden", literal(true), occurs.optional, { documentation: "hides the cloaking button" }),
    field("build_block_radius", primitive("integer"), occurs.optional),
    field("can_disable", primitive("boolean"), occurs.optional),
    field("never_lost", primitive("boolean"), occurs.optional),
    field("ship_family_name", enumRef(EnumId.EnumShipFamilyName), occurs.optional),
    field("growth_stage_descriptor", primitive("localisation"), occurs.optional),
    field("available_to_everyone", primitive("boolean"), occurs.optional),
    field("on_click_sound", typeRef("sound_effect"), occurs.optional),
    field("is_hero_ship", primitive("boolean"), occurs.optional),
    field("custom_state_loc_prefix", primitive("scalar"), occurs.optional),
    field("hero_ship_fleet_background", typeRef("sprite"), occurs.optional),
    whenVariant("starbase", [
      field("modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Starbase }),
      }),
      field("icon_frame", primitive("integer"), occurs.optional),
    ]),
    unlessVariant("starbase", [
      field("modifier", block([modifierEntries()]), occurs.optional, { scope: replaceScope({ root: ScopeId.Ship }) }),
    ]),
    field("ship_modifier", block([modifierEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Ship }),
    }),
    field("size_multiplier", primitive("number"), occurs.optional),
    field("map_counter_icon", primitive("scalar"), occurs.optional),
    field("hull_scale", primitive("number"), occurs.optional),
    field("fleet_slot_size", primitive("integer"), occurs.optional),
    field(
      "section_slots",
      block([
        field(
          anyKey(),
          block([
            field("locator", enumRef(EnumId.Locators), occurs.oneOrMore),
            field("locator", primitive("scalar"), occurs.oneOrMore),
          ]),
          occurs.oneOrMore,
        ),
      ]),
      occurs.optional,
    ),
    field("icon", primitive("scalar"), occurs.optional, {
      documentation:
        "Determines sprites. ship_size_military_1 is default. The following sprite keys are generated from it: GFX_text_<key>, GFX_<key>, GFX_<key>_top, GFX_<key>_top_damaged",
    }),
    field("use_shipnames_from", typeRef("ship_size"), occurs.optional),
    field("evaluation_resource", typeRef("resource"), occurs.optional),
    field("role_background", typeRef("sprite"), occurs.optional),
    field("is_bio_ship", primitive("boolean"), occurs.optional),
    field("bioship_growth_progress_required", scriptValue("number"), occurs.optional),
    field("upgrades_to", typeRef("ship_size"), occurs.optional),
    field("combat_size_multiplier", primitive("integer"), occurs.optional),
    field("num_target_locators", primitive("integer"), occurs.optional),
    field("is_space_station", primitive("boolean"), occurs.optional),
    field("icon_frame", primitive("integer"), occurs.optional),
    field("base_buildtime", primitive("integer"), occurs.optional),
    field("can_have_federation_design", primitive("boolean"), occurs.optional),
    field("enable_default_design", primitive("boolean"), occurs.optional),
    field("enable_3dview_in_ship_browser", primitive("boolean"), occurs.optional),
    field("selectable", block([field("host_has_dlc", enumRef(EnumId.Dlcs), occurs.optional)]), occurs.optional),
    field("default_behavior", typeRef("ship_behavior"), occurs.optional),
    field("ship_roles", block([item(enumRef(EnumId.ShipSizeShipRoles), occurs.any)]), occurs.optional, {
      documentation: "Show up as selectable roles in the ship designer",
    }),
    field(
      "triggered_ship_roles",
      block([
        item(
          block([
            field("name", enumRef(EnumId.ShipSizeShipRoles), occurs.one),
            field("trigger", block([triggerEntries()]), occurs.one, { scope: replaceScope({ root: ScopeId.Country }) }),
          ]),
          occurs.oneOrMore,
        ),
      ]),
      occurs.optional,
      {
        documentation:
          "List of triggered ship roles, show up in the ship designer when the trigger is true, executes on country scope",
      },
    ),
    field("prerequisites", block([item(typeRef("technology"), occurs.any)]), occurs.optional),
    field("class", enumRef(EnumId.ShipsizeClasses), occurs.one),
    field("construction_type", literal("starbase"), occurs.optional),
    field("construction_type", literal("starbase_shipyard"), occurs.optional),
    field("construction_type", literal("spaceport"), occurs.optional),
    field("construction_type", literal("starbase_defenses"), occurs.optional),
    field("selectable", block([triggerEntries()]), occurs.optional),
    field("possible_starbase", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Starbase }),
    }),
    field("potential_starbase", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Starbase }),
    }),
    field("required_component_set", typeRef("component_set", "required_component"), occurs.any),
    field("valid_target_aggressive_stance", primitive("boolean"), occurs.optional),
    field("auto_upgrade", primitive("boolean"), occurs.optional),
    field("ship_class_icon_frame", primitive("integer"), occurs.optional),
    field("uses_name_prefix", primitive("boolean"), occurs.optional),
    field("takes_name_from_ship_design", primitive("boolean"), occurs.optional),
    field("flip_control_on_disable", primitive("boolean"), occurs.optional),
    field("combat_disengage_chance", primitive("number"), occurs.optional),
    field("enable_3dview_in_ship_browser", literal(true), occurs.optional, {
      documentation: "if yes, ship design will have a 3d view in the ship browser",
    }),
    field("potential_country", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("possible_country", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("potential_planet", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Planet }),
    }),
    field("possible_planet", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Planet }),
    }),
    field("potential_construction", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: anyScope() }),
    }),
    field("possible_construction", block([triggerEntries()]), occurs.optional, {
      scope: replaceScope({ root: anyScope() }),
    }),
    field(
      "resources",
      block([field("category", typeRef("economic_category"), occurs.optional), ruleSetEntries("economic_template")]),
      occurs.optional,
    ),
    field(
      "min_upgrade_cost",
      block([field(typeKey("resource"), primitive("number"), occurs.oneOrMore)]),
      occurs.optional,
    ),
    field(
      "ai_ship_data",
      block([
        field("min", scriptValue("integer"), occurs.optional),
        field("max", scriptValue("integer"), occurs.optional),
        field("system_mult", scriptValue("number"), occurs.optional),
        field("planet_mult", scriptValue("number"), occurs.optional),
        field("fraction", block([modifierRuleEntries()]), occurs.optional, {
          scope: replaceScope({ root: ScopeId.Country }),
        }),
        field("fraction", primitive("number"), occurs.optional, { scope: replaceScope({ root: ScopeId.Country }) }),
      ]),
      occurs.optional,
    ),
    field("construction_type", block([item(enumRef(EnumId.ConstructionType), occurs.any)]), occurs.optional),
    field("is_space_fauna_ship", primitive("boolean"), occurs.optional),
    field("icon_cloned", primitive("scalar"), occurs.optional),
    field(
      "space_fauna_values",
      block([
        field(
          "age_threshold",
          block([
            field("min", primitive("integer"), occurs.optional),
            field("max", primitive("integer"), occurs.optional),
          ]),
          occurs.one,
        ),
        field(
          "culling_value",
          block([
            field("category", literal("vivarium"), occurs.one),
            field("produces", block([field(typeKey("resource"), scriptValue("number"), occurs.one)]), occurs.one),
          ]),
          occurs.one,
        ),
        field("icon_frame", primitive("integer"), occurs.one),
        field("monthly_initial_breeding_chance", primitive("integer"), occurs.optional),
        field("monthly_increased_breeding_chance", primitive("integer"), occurs.optional),
        field("breeding_cooldown_months", primitive("integer"), occurs.optional),
        field("reanimated_ship_design", primitive("localisation"), occurs.optional),
        field("merge_with_individuals_amount_to_upgrade", primitive("integer"), occurs.optional),
        field("can_breed_alone", primitive("boolean"), occurs.optional),
      ]),
      occurs.optional,
    ),
    field("ship_category", typeRef("grand_archive_ship_category_type"), occurs.optional),
    field("mutation_components_size", enumRef(EnumId.MutationComponentsSize), occurs.optional),
    field("is_reanimated", primitive("boolean"), occurs.optional),
    field(
      "map_icon_override",
      block([
        field("normal", typeRef("sprite"), occurs.one),
        field("mixed", typeRef("sprite"), occurs.one),
        field("cloaked", typeRef("sprite"), occurs.one),
      ]),
      occurs.optional,
    ),
  ],
});
