// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import { defineType, enumRef, field, occurs, primitive, taggedBlocks } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const shipBehavior: DefinitionType = defineType({
  id: DefinitionTypeId.ShipBehavior,
  source: taggedBlocks("common/ship_behaviors", "name", []),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("scalar"), occurs.one),
    field("desc", primitive("localisation"), occurs.optional),
    field("range_components", enumRef(EnumId.RangeComponentsEnum), occurs.optional),
    field("preferred_attack_range", primitive("integer"), occurs.optional),
    field("preferred_attack_range", enumRef(EnumId.CombatRange), occurs.optional),
    field("formation_distance", primitive("integer"), occurs.optional),
    field("formation_distance", enumRef(EnumId.CombatRange), occurs.optional),
    field("return_to_formation_distance", primitive("integer"), occurs.optional),
    field("return_to_formation_distance", enumRef(EnumId.CombatRange), occurs.optional),
    field("collision_awareness", primitive("number"), occurs.optional),
    field("collision_strafe", primitive("number"), occurs.optional),
    field("collision_radius", primitive("number"), occurs.optional),
    field("attack_move_pattern", enumRef(EnumId.MovePattern), occurs.optional),
    field("passive_move_pattern", enumRef(EnumId.MovePattern), occurs.optional),
    field("source_target_anchor_factor", primitive("number"), occurs.optional),
    field("combat_source_anchor", enumRef(EnumId.CombatAnchor), occurs.optional),
    field("combat_target_anchor", enumRef(EnumId.CombatAnchor), occurs.optional),
    field("ignore_combat_movement", primitive("boolean"), occurs.optional),
  ],
});
