// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  anyKey,
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  enterScope,
  enumRef,
  field,
  fieldEquals,
  item,
  keyedBlocks,
  literal,
  modifierEntries,
  modifierRuleEntries,
  numericKey,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  scriptValue,
  triggerEntries,
  typeRef,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const situationType: DefinitionType = defineType({
  id: DefinitionTypeId.SituationType,
  source: keyedBlocks("common/situations"),
  variants: [
    { id: "monodirectional", when: fieldEquals("progress_direction", "monodirectional") },
    { id: "bidirectional", when: fieldEquals("progress_direction", "bidirectional") },
  ],
  localisation: [
    definitionLocalisation("Name", "$", true),
    definitionLocalisation("Type Name", "$_type", true),
    definitionLocalisation("Description", "$_desc", false),
    definitionLocalisation("Monthly Change Tooltip", "$_monthly_change_tooltip", true),
  ],
  modifiers: [],
  entries: [
    field("picture", typeRef("sprite"), occurs.any),
    field("desc", primitive("localisation"), occurs.any),
    field("initial_progress", primitive("integer"), occurs.optional),
    field(
      "picture",
      block([
        field("picture", typeRef("sprite"), occurs.one),
        field("trigger", block([triggerEntries()]), occurs.one, { scope: replaceScope({ root: ScopeId.Situation }) }),
      ]),
      occurs.any,
    ),
    field("category", enumRef(EnumId.SituationCategory), occurs.optional, {
      documentation: "Affects the tone of various UI elements",
    }),
    field(
      "desc",
      block([
        field("trigger", block([triggerEntries()]), occurs.one),
        field("text", primitive("localisation"), occurs.optional),
      ]),
      occurs.any,
      { scope: replaceScope({ root: ScopeId.Situation }) },
    ),
    field("on_start", block([effectEntries()]), occurs.optional, {
      documentation: "Effects when the Situation is created",
    }),
    field("on_fail", block([effectEntries()]), occurs.optional, {
      documentation:
        "Effects when Situation's total progress is below 0 You should always call destroy_situation = this from here or from an event fired by here",
    }),
    field("on_abort", block([effectEntries()]), occurs.optional, {
      documentation: "Effects when Situation is cancelled via abort_trigger trigger",
    }),
    field("abort_trigger", block([triggerEntries()]), occurs.optional, {
      documentation: "Trigger for when a Situation should abort, firing on_abort",
    }),
    field("modifier", block([modifierEntries()]), occurs.optional, {
      documentation: "Modifier applying to the country experiencing the situation",
      scope: enterScope(ScopeId.Country),
    }),
    ruleSetEntries("triggered_modifier_situation", {
      documentation: "Triggered modifier applying to the country experiencing the situation, if the triggers are true",
    }),
    field("target_modifier", block([modifierEntries()]), occurs.optional, {
      documentation: "Modifier applying to the target planet of a Situation. Does not work on other scope types!",
      scope: enterScope(ScopeId.Planet),
    }),
    ruleSetEntries("triggered_target_modifier_situation", {
      documentation:
        "Modifier applying to the target planet of a Situation, if the triggers are true. Does not work on other scope types!",
    }),
    field(
      "on_monthly",
      block([
        field("events", block([item(typeRef("event"), occurs.any)]), occurs.optional),
        field(
          "random_events",
          block([field(numericKey(), literal(0), occurs.any), field(numericKey(), typeRef("event"), occurs.any)]),
          occurs.optional,
        ),
      ]),
      occurs.optional,
      {
        documentation:
          'Note: technically, this is an on_action called test_situation. So don\'t call your situation "on_monthly_pulse"!',
      },
    ),
    field(
      "monthly_progress",
      block([field("add", primitive("integer"), occurs.optional), ruleSetEntries("modifier_rule_with_loc")]),
      occurs.one,
      { documentation: "Every month, progress ticks up or down based on factors defined here" },
    ),
    field("on_progress_complete", block([effectEntries()]), occurs.optional, {
      documentation:
        "Effects when Situation's progress has reached its completion You should always call destroy_situation = this from here or from an event fired by here",
    }),
    field(
      "approach",
      block([
        field("name", primitive("localisation"), occurs.one, {
          documentation:
            'This is localised. If you add a loc key "approach_a_desc", it will also show, but this is optional.',
        }),
        field("icon", typeRef("sprite"), occurs.one),
        field("icon_background", typeRef("sprite"), occurs.one),
        field("default", literal(true), occurs.optional, {
          documentation:
            "Sets the Approach to be the Situation's default. This means that it will be picked when the Situation starts, and if the current Approach is invalidated (fails potential or allow check). This won't happen while the Situation is locked, so events which demand a choice of Approach can lock the situation (set_situation_locked) in immediate (or the Situation's on_start) and unlock them in after.",
        }),
        field("allow", block([triggerEntries()]), occurs.optional, {
          documentation: "If this fails, the Approach is greyed out",
        }),
        field("potential", block([triggerEntries()]), occurs.optional, {
          documentation: "If this fails, the Approach is not shown",
        }),
        field("modifier", block([modifierEntries()]), occurs.optional, { scope: enterScope(ScopeId.Country) }),
        ruleSetEntries("triggered_modifier_situation"),
        field("target_modifier", block([modifierEntries()]), occurs.optional, { scope: enterScope(ScopeId.Planet) }),
        ruleSetEntries("triggered_target_modifier_situation"),
        field(
          "resources",
          block([
            field("category", typeRef("economic_category"), occurs.optional),
            ruleSetEntries("economic_template"),
          ]),
          occurs.optional,
        ),
        field("on_select", block([effectEntries()]), occurs.optional, {
          documentation: "Effect when you pick the Approach.",
        }),
        field("ai_weight", primitive("integer"), occurs.optional),
        field("ai_weight", block([modifierRuleEntries()]), occurs.optional),
        field("active_tooltip", primitive("localisation"), occurs.optional),
      ]),
      occurs.any,
    ),
    field("title", primitive("localisation"), occurs.any),
    field(
      "title",
      block([
        field("trigger", block([triggerEntries()]), occurs.one),
        field("text", primitive("localisation"), occurs.one),
      ]),
      occurs.any,
    ),
    field("start_value", primitive("number"), occurs.optional, {
      documentation: "Situation will start at this number. Default is 0",
    }),
    field("progress_direction", enumRef(EnumId.ProgressDirection), occurs.optional, {
      documentation: "(defaults to monodirectional)",
    }),
    whenVariant("bidirectional", [
      field("complete_category", enumRef(EnumId.SituationCategory), occurs.optional, {
        documentation: "Only for progress_direction = bidirectional - only affects progress towards completion (right)",
      }),
      field("fail_category", enumRef(EnumId.SituationCategory), occurs.optional, {
        documentation: "Only for progress_direction = bidirectional - only affects progress towards fail (left)",
      }),
    ]),
    field("complete_icon", typeRef("sprite"), occurs.any, {
      documentation: "Defines icon that will appear on the right side of the bar",
    }),
    field("complete_icon_frame", typeRef("sprite"), occurs.any),
    field("fail_icon", typeRef("sprite"), occurs.optional, {
      documentation: "Defines icon that will appear on the left side of the bar",
    }),
    field("fail_icon_frame", typeRef("sprite"), occurs.optional),
    field(
      "stages",
      block([
        field(
          anyKey(),
          block([
            field("end", primitive("integer"), occurs.optional, {
              documentation:
                "Where the stage ends and a new one starts. Determines the end value of the Situation, if it is the final stage.",
            }),
            field(
              "end",
              block([
                field("base", primitive("integer"), occurs.optional),
                field("mult", scriptValue("number"), occurs.optional),
              ]),
              occurs.optional,
            ),
            field("icon", typeRef("sprite"), occurs.one),
            field("icon_background", typeRef("sprite"), occurs.one),
            field("custom_tooltip", primitive("localisation"), occurs.optional),
            field("on_first_enter", block([effectEntries()]), occurs.optional, {
              documentation: "Effect for the first time this stage fires (hidden in the UI)",
            }),
            field("on_enter", block([effectEntries()]), occurs.optional),
            field("potential", block([triggerEntries()]), occurs.optional),
            field("modifier", block([modifierEntries()]), occurs.optional, { scope: enterScope(ScopeId.Country) }),
            ruleSetEntries("triggered_modifier_situation"),
            field("target_modifier", block([modifierEntries()]), occurs.optional, {
              scope: enterScope(ScopeId.Planet),
            }),
            ruleSetEntries("triggered_target_modifier_situation"),
          ]),
          occurs.oneOrMore,
          {
            documentation:
              "Expects the key to be localised. You can also define <key>_desc and it will show on the tooltip, but this is optional.",
          },
        ),
      ]),
      occurs.any,
    ),
    field(
      "triggered_blocked_desc",
      block([
        field("trigger", block([triggerEntries()]), occurs.one),
        field("text", primitive("localisation"), occurs.one),
      ]),
      occurs.any,
    ),
  ],
});
