// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, field, occurs, primitive, taggedBlocks, typeKey } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const solarSystemInitializerRandomList: DefinitionType = defineType({
  id: DefinitionTypeId.SolarSystemInitializerRandomList,
  source: taggedBlocks("common/solar_system_initializers", "name", [], true, {
    rootKeyFilter: { mode: "include", values: ["random_list"] },
  }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("scalar"), occurs.one),
    field(typeKey("solar_system_initializer"), primitive("integer"), occurs.oneOrMore),
  ],
});
