// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  anyScope,
  block,
  defineType,
  effectEntries,
  enumRef,
  field,
  fieldPresent,
  item,
  keyedBlocks,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  triggerEntries,
  typeRef,
  unlessVariant,
  valueSet,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const solarSystemInitializer: DefinitionType = defineType({
  id: DefinitionTypeId.SolarSystemInitializer,
  source: keyedBlocks("common/solar_system_initializers", true, {
    rootKeyFilter: { mode: "exclude", values: ["random_list"] },
  }),
  variants: [{ id: "fallen_empire_initializer_sub", when: fieldPresent("usage") }],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("localisation"), occurs.optional),
    field("class", typeRef("star_class"), occurs.one),
    field("class", enumRef(EnumId.StarClassRandomList), occurs.one),
    field("namelist", primitive("scalar"), occurs.optional),
    field("flags", block([item(valueSet("star_flag"), occurs.any)]), occurs.optional),
    field(
      "asteroid_belt",
      block([
        field("type", typeRef("asteroid_belt_type"), occurs.one),
        field("radius", primitive("integer"), occurs.one),
        field(
          "radius",
          block([field("min", primitive("integer"), occurs.one), field("max", primitive("integer"), occurs.one)]),
          occurs.one,
        ),
      ]),
      occurs.any,
    ),
    field("usage", enumRef(EnumId.UsageType), occurs.any),
    field("usage_odds", primitive("number"), occurs.optional),
    field("usage_odds", block([modifierRuleEntries()]), occurs.optional),
    field("max_instances", primitive("integer"), occurs.optional, {
      documentation: "accepts negative numbers, negative numbers = unrestricted",
    }),
    field("spawn_chance", primitive("integer"), occurs.optional),
    field("scaled_spawn_chance", primitive("integer"), occurs.optional),
    field("scaled_spawn_settings", primitive("scalar"), occurs.optional),
    field("prevent_anomalies", primitive("boolean"), occurs.optional),
    field("primitive_system", primitive("boolean"), occurs.optional),
    field("inner_radius_offset", primitive("integer"), occurs.optional),
    field("outer_radius_offset", primitive("integer"), occurs.optional),
    unlessVariant("fallen_empire_initializer_sub", [
      ruleSetEntries("planet_initializer", { scope: replaceScope({ root: anyScope() }) }),
    ]),
    whenVariant("fallen_empire_initializer_sub", [
      ruleSetEntries("planet_initializer", { scope: replaceScope({ root: ScopeId.Country }) }),
    ]),
    field("change_orbit", primitive("integer"), occurs.any),
    field(
      "change_orbit",
      block([field("min", primitive("integer"), occurs.one), field("max", primitive("integer"), occurs.one)]),
      occurs.any,
    ),
    field(
      "orbital_line",
      block([
        field("orbit_distance_from_parent", primitive("number"), occurs.one, {
          documentation:
            "distance from the center, *not* relative to the previous planet or orbital line's orbit distance",
        }),
      ]),
      occurs.any,
      { documentation: "creates a standalone orbital line, unrelated to any other object" },
    ),
    unlessVariant("fallen_empire_initializer_sub", [
      field("init_effect", block([effectEntries()]), occurs.any, {
        documentation:
          "the scope here is galactic_object scope, with prev being set to the previous system that was initialized by this tree ( if any ). Root will point to the first system in the tree or the root of the calling event.",
        scope: replaceScope({ root: anyScope() }),
      }),
    ]),
    whenVariant("fallen_empire_initializer_sub", [
      field("init_effect", block([effectEntries()]), occurs.any, {
        documentation:
          "the scope here is galactic_object scope, with prev being set to the previous system that was initialized by this tree ( if any ). Root will point to the first system in the tree or the root of the calling event.",
        scope: replaceScope({ root: ScopeId.Country }),
      }),
    ]),
    field("mandatory_neighbors", primitive("boolean"), occurs.optional),
    field(
      "neighbor_system",
      block([
        field("initializer", typeRef("solar_system_initializer"), occurs.one),
        field("distance", primitive("integer"), occurs.optional),
        field(
          "distance",
          block([field("min", primitive("integer"), occurs.one), field("max", primitive("integer"), occurs.one)]),
          occurs.optional,
        ),
        field("hyperlane_distance", primitive("integer"), occurs.optional),
        field(
          "hyperlane_distance",
          block([field("min", primitive("integer"), occurs.one), field("max", primitive("integer"), occurs.one)]),
          occurs.optional,
        ),
        field("hyperlane_jumps", primitive("integer"), occurs.optional),
        field(
          "hyperlane_jumps",
          block([field("min", primitive("integer"), occurs.one), field("max", primitive("integer"), occurs.one)]),
          occurs.optional,
        ),
        field("spawn_chance", primitive("integer"), occurs.optional),
        field("trigger", block([triggerEntries()]), occurs.optional),
        field("min_orientation_angle", primitive("integer"), occurs.optional),
        field("max_orientation_angle", primitive("integer"), occurs.optional),
      ]),
      occurs.any,
    ),
    field("SIZE", enumRef(EnumId.VoidwormsSpawnSystemSize), occurs.optional),
    field("name", primitive("localisation"), occurs.optional),
    field("class", typeRef("star_class"), occurs.one),
    field("class", enumRef(EnumId.StarClassRandomList), occurs.one),
    field("namelist", primitive("scalar"), occurs.optional),
    field("flags", block([item(valueSet("star_flag"), occurs.any)]), occurs.optional),
    field(
      "asteroid_belt",
      block([
        field("type", typeRef("asteroid_belt_type"), occurs.one),
        field("radius", primitive("integer"), occurs.one),
        field(
          "radius",
          block([field("min", primitive("integer"), occurs.one), field("max", primitive("integer"), occurs.one)]),
          occurs.one,
        ),
      ]),
      occurs.any,
    ),
    field("usage", enumRef(EnumId.UsageType), occurs.any),
    field("usage_odds", primitive("number"), occurs.optional),
    field("usage_odds", block([modifierRuleEntries()]), occurs.optional),
    field("max_instances", primitive("integer"), occurs.optional, {
      documentation: "accepts negative numbers, negative numbers = unrestricted",
    }),
    field("spawn_chance", primitive("integer"), occurs.optional),
    field("scaled_spawn_chance", primitive("integer"), occurs.optional),
    field("scaled_spawn_settings", primitive("scalar"), occurs.optional),
    field("prevent_anomalies", primitive("boolean"), occurs.optional),
    field("primitive_system", primitive("boolean"), occurs.optional),
    field("inner_radius_offset", primitive("integer"), occurs.optional),
    field("outer_radius_offset", primitive("integer"), occurs.optional),
    unlessVariant("fallen_empire_initializer_sub", [
      ruleSetEntries("planet_initializer", { scope: replaceScope({ root: anyScope() }) }),
    ]),
    whenVariant("fallen_empire_initializer_sub", [
      ruleSetEntries("planet_initializer", { scope: replaceScope({ root: ScopeId.Country }) }),
    ]),
    field("change_orbit", primitive("integer"), occurs.any),
    field(
      "change_orbit",
      block([field("min", primitive("integer"), occurs.one), field("max", primitive("integer"), occurs.one)]),
      occurs.any,
    ),
    field(
      "orbital_line",
      block([
        field("orbit_distance_from_parent", primitive("number"), occurs.one, {
          documentation:
            "distance from the center, *not* relative to the previous planet or orbital line's orbit distance",
        }),
      ]),
      occurs.any,
      { documentation: "creates a standalone orbital line, unrelated to any other object" },
    ),
    unlessVariant("fallen_empire_initializer_sub", [
      field("init_effect", block([effectEntries()]), occurs.any, {
        documentation:
          "the scope here is galactic_object scope, with prev being set to the previous system that was initialized by this tree ( if any ). Root will point to the first system in the tree or the root of the calling event.",
        scope: replaceScope({ root: anyScope() }),
      }),
    ]),
    whenVariant("fallen_empire_initializer_sub", [
      field("init_effect", block([effectEntries()]), occurs.any, {
        documentation:
          "the scope here is galactic_object scope, with prev being set to the previous system that was initialized by this tree ( if any ). Root will point to the first system in the tree or the root of the calling event.",
        scope: replaceScope({ root: ScopeId.Country }),
      }),
    ]),
    field("mandatory_neighbors", primitive("boolean"), occurs.optional),
    field(
      "neighbor_system",
      block([
        field("initializer", typeRef("solar_system_initializer"), occurs.one),
        field("distance", primitive("integer"), occurs.optional),
        field(
          "distance",
          block([field("min", primitive("integer"), occurs.one), field("max", primitive("integer"), occurs.one)]),
          occurs.optional,
        ),
        field("hyperlane_distance", primitive("integer"), occurs.optional),
        field(
          "hyperlane_distance",
          block([field("min", primitive("integer"), occurs.one), field("max", primitive("integer"), occurs.one)]),
          occurs.optional,
        ),
        field("hyperlane_jumps", primitive("integer"), occurs.optional),
        field(
          "hyperlane_jumps",
          block([field("min", primitive("integer"), occurs.one), field("max", primitive("integer"), occurs.one)]),
          occurs.optional,
        ),
        field("spawn_chance", primitive("integer"), occurs.optional),
        field("trigger", block([triggerEntries()]), occurs.optional),
        field("min_orientation_angle", primitive("integer"), occurs.optional),
        field("max_orientation_angle", primitive("integer"), occurs.optional),
      ]),
      occurs.any,
    ),
    field("SIZE", enumRef(EnumId.VoidwormsSpawnSystemSize), occurs.optional),
  ],
});
