// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, field, occurs, primitive, taggedBlocks } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const song: DefinitionType = defineType({
  id: DefinitionTypeId.Song,
  source: taggedBlocks("music", "name", [], true, { rootKeyFilter: { mode: "include", values: ["song"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [field("name", primitive("scalar"), occurs.one), field("name", primitive("scalar"), occurs.one)],
});
