// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, field, item, occurs, primitive, taggedBlocks, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const soundCategory: DefinitionType = defineType({
  id: DefinitionTypeId.SoundCategory,
  source: taggedBlocks("sound", "name", [], true, { rootKeyFilter: { mode: "include", values: ["category"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("scalar"), occurs.one),
    field("soundeffects", block([item(typeRef("sound_effect"), occurs.any)]), occurs.one),
    field(
      "compressor",
      block([
        field("enabled", primitive("boolean"), occurs.one),
        field("pregain", primitive("number"), occurs.one),
        field("postgain", primitive("number"), occurs.one),
        field("ratio", primitive("number"), occurs.one),
        field("threshold", primitive("number"), occurs.one),
        field("attacktime", primitive("number"), occurs.one),
        field("releasetime", primitive("number"), occurs.one),
      ]),
      occurs.optional,
    ),
    field("name", primitive("scalar"), occurs.one),
    field("soundeffects", block([item(typeRef("sound_effect"), occurs.any)]), occurs.one),
    field(
      "compressor",
      block([
        field("enabled", primitive("boolean"), occurs.one),
        field("pregain", primitive("number"), occurs.one),
        field("postgain", primitive("number"), occurs.one),
        field("ratio", primitive("number"), occurs.one),
        field("threshold", primitive("number"), occurs.one),
        field("attacktime", primitive("number"), occurs.one),
        field("releasetime", primitive("number"), occurs.one),
      ]),
      occurs.optional,
    ),
  ],
});
