// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, field, occurs, primitive, taggedBlocks, typeKey, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const soundGroup: DefinitionType = defineType({
  id: DefinitionTypeId.SoundGroup,
  source: taggedBlocks("sound", "name", [], true, { rootKeyFilter: { mode: "include", values: ["soundgroup"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("scalar"), occurs.one),
    field(
      "soundoverride",
      block([field("name", typeRef("sound"), occurs.one), field("file", primitive("scalar"), occurs.one)]),
      occurs.any,
    ),
    field(
      "soundeffectoverrides",
      block([field(typeKey("sound_effect"), typeRef("sound_effect"), occurs.any)]),
      occurs.optional,
    ),
    field("soundfileoverrides", block([field(typeKey("sound"), primitive("scalar"), occurs.any)]), occurs.optional),
    field("sort_order", primitive("integer"), occurs.optional),
    field("name", primitive("scalar"), occurs.one),
    field(
      "soundoverride",
      block([field("name", typeRef("sound"), occurs.one), field("file", primitive("scalar"), occurs.one)]),
      occurs.any,
    ),
    field(
      "soundeffectoverrides",
      block([field(typeKey("sound_effect"), typeRef("sound_effect"), occurs.any)]),
      occurs.optional,
    ),
    field("soundfileoverrides", block([field(typeKey("sound"), primitive("scalar"), occurs.any)]), occurs.optional),
    field("sort_order", primitive("integer"), occurs.optional),
  ],
});
