// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, field, keyedBlocks, occurs, primitive } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const soundMasterCompressor: DefinitionType = defineType({
  id: DefinitionTypeId.SoundMasterCompressor,
  source: keyedBlocks("sound", true, { rootKeyFilter: { mode: "include", values: ["master_compressor"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("pregain", primitive("number"), occurs.one),
    field("postgain", primitive("number"), occurs.one),
    field("ratio", primitive("number"), occurs.one),
    field("threshold", primitive("number"), occurs.one),
    field("attacktime", primitive("number"), occurs.one),
    field("releasetime", primitive("number"), occurs.one),
  ],
});
