// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import { between, block, defineType, enumRef, field, item, occurs, primitive, taggedBlocks, typeRef } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const soundEffect: DefinitionType = defineType({
  id: DefinitionTypeId.SoundEffect,
  source: taggedBlocks("sound", "name", [], true, { rootKeyFilter: { mode: "include", values: ["soundeffect"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("scalar"), occurs.one),
    field("loop", primitive("boolean"), occurs.optional),
    field(
      "sounds",
      block([
        field(
          "weighted_sound",
          block([field("sound", typeRef("sound"), occurs.one), field("weight", primitive("integer"), occurs.one)]),
          occurs.any,
        ),
        field("sound", typeRef("sound"), occurs.any),
      ]),
      occurs.one,
    ),
    field("max_audible", primitive("integer"), occurs.optional),
    field("max_audible_behaviour", enumRef(EnumId.AudibleBehaviour), occurs.optional),
    field("playbackrate_random_offset", block([item(primitive("number"), between(2, 2))]), occurs.optional),
    field("volume", primitive("number"), occurs.optional),
    field("looping_volume_random_offset", primitive("boolean"), occurs.optional),
    field("looping_delay_random_offset", primitive("boolean"), occurs.optional),
    field("looping_playbackrate_random_offset", primitive("boolean"), occurs.optional),
    field("volume_random_offset", block([item(primitive("number"), between(2, 2))]), occurs.optional),
    field("is3d", primitive("boolean"), occurs.optional),
    field("fade_out", primitive("number"), occurs.optional),
    field("fade_in", primitive("number"), occurs.optional),
    field("playbackrate_random_offset", block([item(primitive("number"), between(2, 2))]), occurs.optional),
    field("delay_random_offset", block([item(primitive("number"), between(2, 2))]), occurs.optional),
    field("playbackrate", primitive("integer"), occurs.optional),
    field("falloff", typeRef("sound_falloff"), occurs.optional),
    field("random_sound_when_looping", primitive("boolean"), occurs.optional),
    field("prevent_random_repetition", primitive("boolean"), occurs.optional),
  ],
});
