// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, field, occurs, primitive, taggedBlocks } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const sound: DefinitionType = defineType({
  id: DefinitionTypeId.Sound,
  source: taggedBlocks("sound", "name", [], true, { rootKeyFilter: { mode: "include", values: ["sound"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("scalar"), occurs.one),
    field("file", primitive("scalar"), occurs.one),
    field("volume", primitive("number"), occurs.optional),
    field("always_load", primitive("boolean"), occurs.optional),
    field("priority", primitive("integer"), occurs.optional),
  ],
});
