// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import { defineType, enumRef, field, occurs, primitive, taggedBlocks } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const soundFalloff: DefinitionType = defineType({
  id: DefinitionTypeId.SoundFalloff,
  source: taggedBlocks("sound", "name", [], true, { rootKeyFilter: { mode: "include", values: ["falloff"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("scalar"), occurs.one),
    field("type", enumRef(EnumId.FalloffType), occurs.optional),
    field("height_scale", primitive("number"), occurs.optional),
    field("min_distance", primitive("number"), occurs.one),
    field("max_distance", primitive("number"), occurs.one),
    field("name", primitive("scalar"), occurs.one),
    field("type", enumRef(EnumId.FalloffType), occurs.optional),
    field("height_scale", primitive("number"), occurs.optional),
    field("min_distance", primitive("number"), occurs.one),
    field("max_distance", primitive("number"), occurs.one),
  ],
});
