// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import {
  block,
  defineType,
  enumRef,
  field,
  keyedBlocks,
  occurs,
  primitive,
  ruleSetEntries,
  scriptValue,
  typeKey,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const specimen: DefinitionType = defineType({
  id: DefinitionTypeId.Specimen,
  source: keyedBlocks("common/specimens"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("icon", typeRef("sprite"), occurs.one),
    field("type", enumRef(EnumId.SpecimenType), occurs.one),
    field("is_tradable", primitive("boolean"), occurs.optional),
    field("is_sellable", primitive("boolean"), occurs.optional),
    field("RARITY", enumRef(EnumId.Rarity), occurs.optional),
    ruleSetEntries("triggered_country_modifier_country"),
    field(
      "resources",
      block([
        field("category", typeRef("economic_category"), occurs.one),
        ruleSetEntries("economic_template_only_produces"),
        field(
          "upkeep",
          block([
            field("mult", scriptValue("number"), occurs.any),
            field(typeKey("resource"), primitive("integer"), occurs.any),
          ]),
          occurs.optional,
        ),
      ]),
      occurs.any,
    ),
    field("icon", typeRef("sprite"), occurs.one),
    field("type", enumRef(EnumId.SpecimenType), occurs.one),
    field("is_tradable", primitive("boolean"), occurs.optional),
    field("is_sellable", primitive("boolean"), occurs.optional),
    field("RARITY", enumRef(EnumId.Rarity), occurs.optional),
    ruleSetEntries("triggered_country_modifier_country"),
    field(
      "resources",
      block([
        field("category", typeRef("economic_category"), occurs.one),
        ruleSetEntries("economic_template_only_produces"),
        field(
          "upkeep",
          block([
            field("mult", scriptValue("number"), occurs.any),
            field(typeKey("resource"), primitive("integer"), occurs.any),
          ]),
          occurs.optional,
        ),
      ]),
      occurs.any,
    ),
  ],
});
