// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { anyKey, block, defineType, field, keyedBlocks, occurs, primitive } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const speciesNamedList: DefinitionType = defineType({
  id: DefinitionTypeId.SpeciesNamedList,
  source: keyedBlocks("common/species_names", true, { container: { kind: "named-container", key: "named_lists" } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field(
      anyKey(),
      block([
        field("name", primitive("localisation"), occurs.one),
        field("plural", primitive("localisation"), occurs.one),
      ]),
      occurs.oneOrMore,
    ),
  ],
});
