// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import {
  between,
  block,
  defineType,
  enumRef,
  field,
  item,
  literal,
  occurs,
  primitive,
  rootKeyIs,
  taggedBlocks,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const sprite: DefinitionType = defineType({
  id: DefinitionTypeId.Sprite,
  source: taggedBlocks("interface", "name", [], true, {
    rootKeyFilter: { mode: "exclude", values: ["progressbartype", "PieChartType"] },
    container: { kind: "named-container", key: "spriteTypes" },
  }),
  variants: [
    { id: "normal", when: rootKeyIs("spriteType") },
    { id: "cornered_tile", when: rootKeyIs("corneredTileSpriteType") },
    { id: "flag_sprite", when: rootKeyIs("flagSpriteType") },
    { id: "framed_animated_sprite", when: rootKeyIs("frameAnimatedSpriteType") },
    { id: "text_sprite", when: rootKeyIs("textSpriteType") },
  ],
  localisation: [],
  modifiers: [],
  entries: [
    field("name", primitive("scalar"), occurs.one),
    field("textureFile", primitive("file"), occurs.optional),
    field("masking_texture", primitive("file"), occurs.optional),
    field("effectFile", primitive("file"), occurs.optional),
    field("alwaysTransparent", primitive("boolean"), occurs.optional),
    field("parent", typeRef("sprite"), occurs.optional),
    field(
      "upper_left",
      block([field("x", primitive("integer"), occurs.one), field("y", primitive("integer"), occurs.one)]),
      occurs.optional,
    ),
    field(
      "lower_right",
      block([field("x", primitive("integer"), occurs.one), field("y", primitive("integer"), occurs.one)]),
      occurs.optional,
    ),
    field("transParencecheck", primitive("boolean"), occurs.optional),
    field(
      "borderSize",
      block([field("x", primitive("number"), occurs.one), field("y", primitive("number"), occurs.one)]),
      occurs.optional,
    ),
    field(
      "hitbox_margin",
      block([field("x", primitive("integer"), occurs.one), field("y", primitive("integer"), occurs.one)]),
      occurs.optional,
    ),
    field("noOfFrames", primitive("integer"), occurs.optional),
    field("type", enumRef(EnumId.SpriteType), occurs.optional),
    field("character", primitive("boolean"), occurs.optional),
    field("tilingCenter", primitive("boolean"), occurs.optional),
    field("clicksound", typeRef("sound_effect"), occurs.optional),
    field("loadType", primitive("scalar"), occurs.optional),
    field("legacy_lazy_load", primitive("boolean"), occurs.any),
    field("alternate_configurations", block([item(literal("holographic"), occurs.one)]), occurs.any),
    field("close_up", primitive("boolean"), occurs.optional),
    field("mid_close_up", literal(true), occurs.optional),
    field(
      "animation",
      block([
        field("animationmaskfile", primitive("file"), occurs.optional),
        field("animationtexturefile", primitive("file"), occurs.optional),
        field("animationrotation", primitive("number", { min: -360, max: 360 }), occurs.optional),
        field("animationlooping", primitive("boolean"), occurs.optional),
        field("animationtime", primitive("number"), occurs.optional),
        field("animationdelay", primitive("number"), occurs.optional),
        field("animationblendmode", enumRef(EnumId.AnimationMode), occurs.optional),
        field("animationtype", enumRef(EnumId.AnimationType), occurs.optional),
        field(
          "animationrotationoffset",
          block([field("x", primitive("number"), occurs.one), field("y", primitive("number"), occurs.one)]),
          occurs.optional,
        ),
        field(
          "animationtexturescale",
          block([field("x", primitive("number"), occurs.one), field("y", primitive("number"), occurs.one)]),
          occurs.optional,
        ),
        field("animationframes", block([item(primitive("integer"), between(1, 3))]), occurs.optional),
      ]),
      occurs.any,
    ),
    field(
      "bg_position",
      block([field("x", primitive("number"), occurs.one), field("y", primitive("number"), occurs.one)]),
      occurs.optional,
    ),
    field(
      "bg_size",
      block([field("width", primitive("integer"), occurs.one), field("height", primitive("integer"), occurs.one)]),
      occurs.optional,
    ),
    field(
      "symbol_position",
      block([field("x", primitive("number"), occurs.one), field("y", primitive("number"), occurs.one)]),
      occurs.optional,
    ),
    field(
      "symbol_size",
      block([field("width", primitive("number"), occurs.one), field("height", primitive("number"), occurs.one)]),
      occurs.optional,
    ),
    field("texture_size", enumRef(EnumId.TextureSize), occurs.optional),
    field(
      "mask_offset",
      block([field("x", primitive("number"), occurs.one), field("y", primitive("number"), occurs.one)]),
      occurs.optional,
    ),
    field(
      "mask_size",
      block([field("width", primitive("integer"), occurs.one), field("height", primitive("integer"), occurs.one)]),
      occurs.optional,
    ),
    field("play_on_show", primitive("boolean"), occurs.optional),
    field("animation_rate_fps", primitive("integer"), occurs.optional),
    field("looping", primitive("boolean"), occurs.optional),
    field("sprite_sheet_sprite_type", typeRef("sprite"), occurs.optional),
    field("default_frame", primitive("integer"), occurs.optional),
    field(
      "size",
      block([field("x", primitive("integer"), occurs.one), field("y", primitive("integer"), occurs.one)]),
      occurs.optional,
    ),
  ],
});
