// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import { block, defineType, field, keyedBlocks, occurs, primitive, replaceScope, triggerEntries } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const startScreenMessage: DefinitionType = defineType({
  id: DefinitionTypeId.StartScreenMessage,
  source: keyedBlocks("common/start_screen_messages", true, { rootKeyFilter: { mode: "include", values: ["part"] } }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("location", primitive("integer"), occurs.one),
    field("localization", primitive("localisation"), occurs.one),
    field("trigger", block([triggerEntries()]), occurs.one, { scope: replaceScope({ root: ScopeId.Country }) }),
  ],
});
