// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  field,
  fieldEquals,
  keyedBlocks,
  modifierEntries,
  occurs,
  primitive,
  replaceScope,
  typeKey,
  typeRef,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const subjectSpecialistPerk: DefinitionType = defineType({
  id: DefinitionTypeId.SubjectSpecialistPerk,
  source: keyedBlocks("common/specialist_subject_perks"),
  variants: [
    { id: "main", when: fieldEquals("main_perk", true) },
    { id: "non_main", when: fieldEquals("main_perk", false) },
  ],
  localisation: [definitionLocalisation("Name", "", true), definitionLocalisation("Description", "_desc", false)],
  modifiers: [],
  entries: [
    field("main_perk", primitive("boolean"), occurs.optional),
    whenVariant("non_main", [field("icon", typeRef("sprite"), occurs.one)]),
    field(
      "subject_modifier",
      block([modifierEntries(), field("description", primitive("localisation"), occurs.optional)]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.Country }) },
    ),
    field(
      "overlord_modifier",
      block([modifierEntries(), field("description", primitive("localisation"), occurs.optional)]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.Country }) },
    ),
    field("activate_effect", block([effectEntries()]), occurs.optional, {
      documentation: "Invoked when the perk is activated",
      scope: replaceScope({ root: ScopeId.Agreement }),
    }),
    field("deactivate_effect", block([effectEntries()]), occurs.optional, {
      documentation: "Invoked when the perk is deactivated",
      scope: replaceScope({ root: ScopeId.Agreement }),
    }),
    field(
      "overlord_relay_network_modifier",
      block([field(typeKey("static_modifier"), primitive("number"), occurs.any)]),
      occurs.optional,
      {
        documentation:
          "Static modifiers that are applied to the overlord's planets if the capitals of both empires are connected via the hyperlane network",
      },
    ),
    field("desc", block([field("description", primitive("localisation"), occurs.one)]), occurs.optional, {
      documentation: "Additional description text for this subject specialist perk",
    }),
  ],
});
