// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  field,
  keyedBlocks,
  occurs,
  primitive,
  triggerEntries,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const subspeciesIntegrationType: DefinitionType = defineType({
  id: DefinitionTypeId.SubspeciesIntegrationType,
  source: keyedBlocks("common/species_rights/subspecies_integration_types"),
  variants: [],
  localisation: [
    definitionLocalisation("Name", "", true),
    definitionLocalisation("Tooltip", "_tooltip", true),
    definitionLocalisation("Delayed tooltip", "_tooltip_delayed", true),
  ],
  modifiers: [],
  entries: [
    field("integration", primitive("boolean"), occurs.one),
    field("allow", block([triggerEntries()]), occurs.optional),
    field("ai_will_do", block([field("factor", primitive("integer"), occurs.one)]), occurs.one),
  ],
});
