// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, definitionLocalisation, fieldPresent, taggedBlocks } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const swappedCivic: DefinitionType = defineType({
  id: DefinitionTypeId.SwappedCivic,
  source: taggedBlocks("common/governments/civics", "name", [], true, {
    rootKeyFilter: { mode: "include", values: ["swap_type"] },
    container: { kind: "any-container" },
  }),
  variants: [{ id: "localised", when: fieldPresent("name") }],
  localisation: [
    definitionLocalisation("Name", "$", true, "localised"),
    definitionLocalisation("Description", "$_desc", true, "localised"),
  ],
  modifiers: [],
  entries: [],
});
