// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  field,
  keyedBlocks,
  modifierRuleEntries,
  occurs,
  replaceScope,
  triggerEntries,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const systemType: DefinitionType = defineType({
  id: DefinitionTypeId.SystemType,
  source: keyedBlocks("common/system_types"),
  variants: [],
  localisation: [definitionLocalisation("name", "", true)],
  modifiers: [],
  entries: [
    field("potential", block([triggerEntries()]), occurs.one, { scope: replaceScope({ root: ScopeId.System }) }),
    field("weight_modifier", block([modifierRuleEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.System }),
    }),
    field("potential", block([triggerEntries()]), occurs.one, { scope: replaceScope({ root: ScopeId.System }) }),
    field("weight_modifier", block([modifierRuleEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.System }),
    }),
  ],
});
