// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId } from "../catalog.js";

import { defineType, enumRef, field, keyedBlocks, occurs } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const targettype: DefinitionType = defineType({
  id: DefinitionTypeId.Targettype,
  source: keyedBlocks("common/target_types"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("target_type", enumRef(EnumId.TargetTypeEnum), occurs.one),
    field("target_type", enumRef(EnumId.TargetTypeEnum), occurs.one),
  ],
});
