// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import { block, defineType, field, keyedBlocks, modifierRuleEntries, occurs, primitive, replaceScope } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const technologyTier: DefinitionType = defineType({
  id: DefinitionTypeId.TechnologyTier,
  source: keyedBlocks("common/technology/tier"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("previously_unlocked", primitive("integer"), occurs.optional),
    field("weight_modifier", block([modifierRuleEntries()]), occurs.any, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("previously_unlocked", primitive("integer"), occurs.optional),
    field("weight_modifier", block([modifierRuleEntries()]), occurs.any, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
  ],
});
