// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  between,
  block,
  defineType,
  definitionLocalisation,
  enumKey,
  enumRef,
  field,
  fieldEquals,
  fieldPresent,
  item,
  keyedBlocks,
  modifierEntries,
  modifierRuleEntries,
  namedValueKey,
  occurs,
  primitive,
  replaceScope,
  scriptValue,
  triggerEntries,
  typeKey,
  typeRef,
  unlessVariant,
  valueSet,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const technology: DefinitionType = defineType({
  id: DefinitionTypeId.Technology,
  source: keyedBlocks("common/technology", false),
  variants: [
    { id: "repeatable", when: fieldPresent("levels") },
    { id: "start_tech", when: fieldEquals("start_tech", true) },
  ],
  localisation: [definitionLocalisation("Name", "$", true), definitionLocalisation("Description", "$_desc", true)],
  modifiers: [],
  entries: [
    field("area", enumRef(EnumId.ResearchAreas), occurs.one),
    field("tier", typeRef("technology_tier"), occurs.one),
    field("category", block([item(typeRef("technology_category"), occurs.one)]), occurs.one),
    field("icon", primitive("icon", undefined, "gfx/interface/icons/technologies"), occurs.optional),
    field("weight", primitive("number"), occurs.optional),
    field("cost", block([modifierRuleEntries()]), occurs.optional),
    field("cost", scriptValue("number"), occurs.optional),
    unlessVariant("start_tech", [
      field("is_rare", primitive("boolean"), occurs.optional),
      field("is_dangerous", primitive("boolean"), occurs.optional),
      field("weight", primitive("number"), occurs.optional),
      field("levels", primitive("integer", { min: -1, max: 100 }), occurs.optional),
    ]),
    field(
      "prerequisites",
      block([
        item(typeRef("technology"), between(0, 100)),
        field("OR", block([item(typeRef("technology"), between(0, 100))]), occurs.optional),
      ]),
      occurs.optional,
    ),
    field("potential", block([triggerEntries()]), occurs.optional, { scope: replaceScope({ root: ScopeId.Country }) }),
    field("gateway", primitive("scalar"), occurs.optional),
    whenVariant("repeatable", [field("cost_per_level", primitive("integer"), occurs.one)]),
    field("weight_groups", block([item(valueSet("tech_weight_group"), occurs.any)]), occurs.optional, {
      documentation:
        "a weight group increases the chances of a technology appearing - if another tech of a similar group is picked.",
    }),
    field(
      "mod_weight_if_group_picked",
      block([field(namedValueKey("tech_weight_group"), primitive("number"), occurs.any)]),
      occurs.any,
    ),
    field("start_tech", primitive("boolean"), occurs.optional),
    field("is_reverse_engineerable", primitive("boolean"), occurs.optional),
    field("is_rare", primitive("boolean"), occurs.optional),
    field("ai_update_type", enumRef(EnumId.TechAiType), occurs.optional),
    field("is_insight", primitive("boolean"), occurs.optional, { documentation: "default = no" }),
    field("feature_flags", block([item(enumRef(EnumId.FeatureFlags), between(0, 100))]), occurs.optional),
    field(
      "modifier",
      block([
        field("description", primitive("localisation"), occurs.optional),
        field("description_parameters", block([field("POINTS", primitive("integer"), occurs.one)]), occurs.optional),
        modifierEntries(),
        field("show_only_custom_tooltip", primitive("boolean"), occurs.optional),
        field("custom_tooltip", primitive("localisation"), occurs.optional),
      ]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.Country }) },
    ),
    field(
      "technology_swap",
      block([
        field("name", typeRef("technology"), occurs.optional),
        field("name", primitive("localisation"), occurs.optional),
        field("inherit_icon", primitive("boolean"), occurs.optional),
        field("inherit_effects", primitive("boolean"), occurs.optional),
        field("trigger", block([triggerEntries()]), occurs.optional),
        field(
          "prereqfor_desc",
          block([
            field(
              "custom",
              block([
                field("title", primitive("localisation"), occurs.one),
                field("desc", primitive("localisation"), occurs.optional),
              ]),
              occurs.one,
            ),
          ]),
          occurs.any,
        ),
        field("weight", block([field("factor", primitive("integer"), occurs.one)]), occurs.optional),
        field(
          "modifier",
          block([
            field("description", primitive("localisation"), occurs.optional),
            modifierEntries(),
            field("show_only_custom_tooltip", primitive("boolean"), occurs.optional),
            field("custom_tooltip", primitive("localisation"), occurs.optional),
          ]),
          occurs.optional,
        ),
        field("area", enumRef(EnumId.ResearchAreas), occurs.optional),
        field("category", block([item(typeRef("technology_category"), occurs.one)]), occurs.optional),
      ]),
      occurs.any,
      { scope: replaceScope({ root: ScopeId.Country }) },
    ),
    field(
      "prereqfor_desc",
      block([
        field("hide_prereq_for_desc", enumRef(EnumId.PrereqForCategories), between(0, 4)),
        field(
          enumKey(EnumId.PrereqForCategories),
          block([
            field("title", primitive("localisation"), occurs.one),
            field("desc", primitive("localisation"), occurs.optional),
          ]),
          between(0, 4),
        ),
      ]),
      occurs.any,
    ),
    field("weight_modifier", block([modifierRuleEntries()]), occurs.any, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("ai_weight", block([modifierRuleEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field(
      "starting_potential",
      block([field(typeKey("scripted_trigger"), primitive("boolean"), occurs.any), triggerEntries()]),
      occurs.optional,
      { scope: replaceScope({ root: ScopeId.Country }) },
    ),
  ],
});
