// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  definitionLocalisation,
  field,
  keyedBlocks,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const technologyCategory: DefinitionType = defineType({
  id: DefinitionTypeId.TechnologyCategory,
  source: keyedBlocks("common/technology/category"),
  variants: [],
  localisation: [definitionLocalisation("Name", "$", true), definitionLocalisation("Description", "$_desc", true)],
  modifiers: [],
  entries: [
    field("icon", primitive("file"), occurs.one),
    field("weight_modifier", block([modifierRuleEntries()]), occurs.any, {
      scope: replaceScope({ root: ScopeId.Country }),
    }),
  ],
});
