// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { anyKey, between, block, defineType, field, item, keyedBlocks, primitive } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const textcolors: DefinitionType = defineType({
  id: DefinitionTypeId.Textcolors,
  source: keyedBlocks("interface", true, {
    rootKeyFilter: { mode: "include", values: ["textcolors"] },
    container: { kind: "named-container", key: "bitmapfonts" },
  }),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field(anyKey(), block([item(primitive("integer", { min: 0, max: 255 }), between(3, 3))]), between(14, null)),
    field(anyKey(), block([item(primitive("integer", { min: 0, max: 255 }), between(3, 3))]), between(14, null)),
  ],
});
