// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { block, defineType, effectEntries, field, keyedBlocks, occurs, primitive, triggerEntries } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const tradableActions: DefinitionType = defineType({
  id: DefinitionTypeId.TradableActions,
  source: keyedBlocks("common/tradable_actions"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("fire_and_forget", primitive("boolean"), occurs.optional),
    field("potential", block([triggerEntries()]), occurs.optional),
    field("active", block([triggerEntries()]), occurs.optional),
    field("on_traded_effect", block([effectEntries()]), occurs.optional),
    field("on_deal_ended_sender_effect", block([effectEntries()]), occurs.optional),
    field("on_deal_ended_recipient_effect", block([effectEntries()]), occurs.optional),
    field(
      "ai_weight",
      block([
        field("weight", primitive("number"), occurs.one),
        field(
          "modifier",
          block([
            field("factor", primitive("number"), occurs.optional),
            field("weight", primitive("number"), occurs.optional),
            triggerEntries(),
          ]),
          occurs.any,
        ),
      ]),
      occurs.optional,
    ),
  ],
});
