// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  field,
  keyedBlocks,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  triggerEntries,
  typeKey,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const tradeConversion: DefinitionType = defineType({
  id: DefinitionTypeId.TradeConversion,
  source: keyedBlocks("common/trade_conversions"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("potential", block([triggerEntries()]), occurs.one, { scope: replaceScope({ from: ScopeId.Country }) }),
    field("weight", block([modifierRuleEntries()]), occurs.one),
    field("conversion_rate", block([field(typeKey("resource"), primitive("number"), occurs.oneOrMore)]), occurs.one),
    field("economic_category", typeRef("economic_category"), occurs.one),
    field("potential", block([triggerEntries()]), occurs.one, { scope: replaceScope({ from: ScopeId.Country }) }),
    field("weight", block([modifierRuleEntries()]), occurs.one),
    field("conversion_rate", block([field(typeKey("resource"), primitive("number"), occurs.oneOrMore)]), occurs.one),
    field("economic_category", typeRef("economic_category"), occurs.one),
  ],
});
