// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, ScopeId } from "../catalog.js";

import {
  anyKey,
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  field,
  keyedBlocks,
  modifierEntries,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  scriptValue,
  triggerEntries,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const tradition: DefinitionType = defineType({
  id: DefinitionTypeId.Tradition,
  source: keyedBlocks("common/traditions"),
  variants: [],
  localisation: [
    definitionLocalisation("Name", "$", true),
    definitionLocalisation("Flavor", "$_delayed", false),
    definitionLocalisation("Effects", "$_desc", false),
  ],
  modifiers: [],
  entries: [
    field(
      "modifier",
      block([
        field("description", primitive("localisation"), occurs.optional),
        field(
          "description_parameters",
          block([
            field(anyKey(), primitive("number"), occurs.any, {
              documentation: "Any value can go here to be used in localisation",
            }),
          ]),
          occurs.optional,
        ),
        modifierEntries(),
        field("custom_tooltip", primitive("localisation"), occurs.any),
        field("show_only_custom_tooltip", primitive("boolean"), occurs.optional),
      ]),
      occurs.optional,
      { documentation: "accepts only country modifiers", scope: replaceScope({ root: ScopeId.Country }) },
    ),
    ruleSetEntries("triggered_modifier_country"),
    field("ai_weight", block([modifierRuleEntries()]), occurs.optional, {
      documentation:
        "the ai_weight in traditions applies both to the main traditions and the tradition swaps, there are no seperate fields.",
      scope: replaceScope({ root: ScopeId.Country }),
    }),
    field("possible", block([triggerEntries()]), occurs.optional, { scope: replaceScope({ root: ScopeId.Country }) }),
    field("on_enabled", block([effectEntries()]), occurs.optional, { scope: replaceScope({ root: ScopeId.Country }) }),
    field("unlocks_agenda", typeRef("council_agenda"), occurs.optional),
    field("custom_tooltip", primitive("localisation"), occurs.any),
    field("custom_tooltip_with_modifiers", primitive("localisation"), occurs.any),
    field(
      "tradition_swap",
      block([
        field("name", primitive("scalar"), occurs.optional),
        field("inherit_icon", primitive("boolean"), occurs.optional),
        field("inherit_name", primitive("boolean"), occurs.optional),
        field("inherit_effects", primitive("boolean"), occurs.optional),
        field("custom_tooltip", primitive("localisation"), occurs.any),
        field("custom_tooltip_with_modifiers", primitive("localisation"), occurs.any),
        field("unlocks_agenda", typeRef("council_agenda"), occurs.optional),
        field(
          "modifier",
          block([
            field("description", primitive("localisation"), occurs.optional),
            field(
              "description_parameters",
              block([
                field(anyKey(), primitive("number"), occurs.any, {
                  documentation: "Any value can go here to be used in localisation",
                }),
              ]),
              occurs.optional,
            ),
            modifierEntries(),
            field("custom_tooltip", primitive("localisation"), occurs.any),
            field("show_only_custom_tooltip", primitive("boolean"), occurs.any),
          ]),
          occurs.optional,
          { documentation: "accepts only country modifiers", scope: replaceScope({ root: ScopeId.Country }) },
        ),
        field("on_enabled", block([effectEntries()]), occurs.optional, {
          scope: replaceScope({ root: ScopeId.Country }),
        }),
        field("weight", block([modifierRuleEntries()]), occurs.optional, {
          documentation:
            "this determines the chances of a tradition swap appearing for a given empire IF multiple swaps are potential.",
          scope: replaceScope({ root: ScopeId.Country }),
        }),
        field("trigger", block([triggerEntries()]), occurs.optional, {
          scope: replaceScope({ root: ScopeId.Country }),
        }),
        field(
          "triggered_modifier",
          block([
            field("potential", block([triggerEntries()]), occurs.optional),
            modifierEntries(),
            field("mult", scriptValue("number"), occurs.optional),
          ]),
          occurs.any,
          { scope: replaceScope({ root: ScopeId.Country }) },
        ),
      ]),
      occurs.any,
    ),
  ],
});
