// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, definitionLocalisation, fieldEquals, taggedBlocks } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const traditionSwap: DefinitionType = defineType({
  id: DefinitionTypeId.TraditionSwap,
  source: taggedBlocks("common/traditions", "name", [], true, {
    rootKeyFilter: { mode: "include", values: ["tradition_swap"] },
    container: { kind: "any-container" },
  }),
  variants: [{ id: "not_inheriting_name", when: fieldEquals("inherit_name", true) }],
  localisation: [
    definitionLocalisation("Name", "", false),
    definitionLocalisation("Effects", "_desc", false),
    definitionLocalisation("Flavor", "_delayed", false),
    definitionLocalisation("Name", "", true, "not_inheriting_name"),
  ],
  modifiers: [],
  entries: [],
});
