// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { bareValues, defineType } from "../ir.js";

import type { DefinitionType } from "../ir.js";

// Same shape as `job_tags`, and cwt gets it wrong the same way: the game's
// `common/trait_tags/00_tags.txt` is a list of bare words, and traits write
// `tags = { organic positive special }` against them.
export const traitTags: DefinitionType = defineType({
  id: DefinitionTypeId.TraitTags,
  source: bareValues("common/trait_tags"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [],
});
