// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId } from "../catalog.js";

import { defineType, fileDefinitions } from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const traitTags: DefinitionType = defineType({
  id: DefinitionTypeId.TraitTags,
  source: fileDefinitions("common/trait_tags"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [],
});
