// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  between,
  block,
  defineType,
  definitionLocalisation,
  effectEntries,
  enumKey,
  enumRef,
  field,
  fieldEquals,
  fieldPresent,
  item,
  keyedBlocks,
  literal,
  modifierEntries,
  modifierRuleEntries,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  scriptValue,
  triggerEntries,
  typeKey,
  typeRef,
  whenVariant,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const trait: DefinitionType = defineType({
  id: DefinitionTypeId.Trait,
  source: keyedBlocks("common/traits"),
  variants: [
    { id: "species_trait", when: fieldPresent("leader_class") },
    { id: "leader_trait", when: fieldPresent("leader_class") },
    { id: "leader_trait_subclass", when: fieldEquals("subclass_trait", true) },
    { id: "leader_trait_veteran", when: fieldEquals("veteran_class_locked_trait", true) },
    { id: "leader_trait_destiny", when: fieldEquals("destiny_trait", true) },
    { id: "leader_trait_replacement", when: fieldPresent("replace_traits") },
    { id: "leader_trait_not_replacement", when: fieldPresent("replace_traits") },
  ],
  localisation: [
    definitionLocalisation("Name", "$", false),
    definitionLocalisation("Description", "$_desc", false),
    definitionLocalisation("Name", "$", true, "leader_trait_not_replacement"),
    definitionLocalisation("Description", "$_desc", true, "leader_trait_not_replacement"),
  ],
  modifiers: [],
  entries: [
    field("host_has_dlc", enumRef(EnumId.Dlcs), occurs.optional),
    field("immortal_leaders", primitive("boolean"), occurs.optional, { documentation: "Default = no" }),
    field("icon", primitive("file"), occurs.optional, {
      documentation: "If omitted, the default icon is gfx/interface/icons/traits/<trait_name>.dds",
    }),
    field(
      "icon",
      block([
        field(
          "layer",
          block([
            field("icon", typeRef("sprite"), occurs.one, {
              documentation:
                'Texture name defined in "interface" folder. Default trait icons are in "interface/icons/traits" folder.',
            }),
            field("icon", primitive("file"), occurs.optional),
            field("color", typeRef("named_color"), occurs.optional, {
              documentation: 'Layer color tint. Color name defined in "common\\named_colors" folder.',
            }),
            field("visible", block([triggerEntries()]), occurs.optional, {
              documentation: "Scripted trigger. If false, hide layer.",
              scope: replaceScope({ root: ScopeId.Leader }),
            }),
          ]),
          occurs.oneOrMore,
          { documentation: "There are no limits to the amount of layers that can be used." },
        ),
        field("icon", typeRef("sprite"), occurs.optional),
      ]),
      occurs.optional,
      { documentation: "Layered icon format introduced in Paragon." },
    ),
    field("leader_trait_rarity", enumRef(EnumId.LeaderTraitRarity), occurs.optional),
    field("cost", primitive("integer"), occurs.optional, {
      documentation: "This trait costs/gives this amount of points when selected in species/ruler creation.",
    }),
    field("cost", block([modifierRuleEntries()]), occurs.optional, {
      documentation: "This trait costs/gives this amount of points when selected in species/ruler creation.",
    }),
    field("auto_mod", primitive("boolean"), occurs.optional),
    field("category", enumRef(EnumId.SpeciesCategoryType), occurs.optional),
    field("valid_for_all_ethics", primitive("boolean"), occurs.optional),
    field("allowed_ethics", block([item(typeRef("ethos"), occurs.oneOrMore)]), occurs.optional, {
      documentation: "This only does something if valid_for_all_ethics is set to no",
    }),
    field("valid_for_all_origins", primitive("boolean"), occurs.optional, {
      documentation: '"yes" required for species traits to apply "allowed_origins" but not leader traits',
    }),
    field("allowed_origins", block([item(typeRef("civic_or_origin", "origin"), occurs.oneOrMore)]), occurs.optional, {
      documentation: "This only does something if valid_for_origins is set to no",
    }),
    field("sorting_priority", primitive("integer"), occurs.optional),
    field("bound_to_planet_classes", block([item(typeRef("planet_class"), occurs.any)]), occurs.optional),
    field("leader_trait_type", enumRef(EnumId.LeaderTraitRarity), occurs.optional),
    whenVariant("species_trait", [
      field("assembly_score", block([modifierRuleEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Species, from: ScopeId.Planet }),
      }),
      field("short_name", primitive("localisation"), occurs.optional),
      field("allowed_archetypes", block([item(typeRef("species_archetype"), occurs.oneOrMore)]), occurs.one),
      field("allowed_planet_classes", block([item(typeRef("planet_class"), occurs.oneOrMore)]), occurs.optional),
      field("allowed_planet_classes_override", block([triggerEntries()]), occurs.optional),
      field("ideal_planet_class", typeRef("planet_class"), occurs.optional),
      field("species_class", block([item(typeRef("species_class"), occurs.oneOrMore)]), occurs.optional),
      field("modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Country }),
      }),
      field("assembling_modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Planet }),
      }),
      field("declining_modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Planet }),
      }),
      field("growing_modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Planet }),
      }),
      ruleSetEntries("triggered_pop_group_modifier", {
        documentation: "won't show in trait tooltips, use custom_tooltip/custom_tooltip_with_modifiers",
      }),
      ruleSetEntries("triggered_planet_growth_habitability_modifier", {
        scope: replaceScope({ root: ScopeId.Planet, from: ScopeId.Species, fromFrom: ScopeId.Country }),
      }),
      ruleSetEntries("triggered_leader_modifier_pop", {
        documentation: "won't show in trait tooltips, use custom_tooltip/custom_tooltip_with_modifiers",
      }),
      field("sapient", primitive("boolean"), occurs.optional, { documentation: "Default = yes" }),
      field("forced_happiness", primitive("boolean"), occurs.optional, { documentation: "Default = no" }),
      field("improves_leaders", primitive("boolean"), occurs.optional, { documentation: "Default = no" }),
      field("advanced_trait", primitive("boolean"), occurs.optional, { documentation: "Default = no" }),
      field("leader_age_min", primitive("integer"), occurs.optional),
      field("auto_mod_habitability", primitive("boolean"), occurs.optional),
      field("leader_age_max", primitive("integer"), occurs.optional),
      field("species_potential_add", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Species, from: ScopeId.Country }),
      }),
      field("species_possible_add", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Species, from: ScopeId.Country }),
      }),
      field("species_potential_remove", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Species, from: ScopeId.Country }),
      }),
      field("species_possible_remove", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Species, from: ScopeId.Country }),
      }),
      field("allowed_civics", block([item(typeRef("civic_or_origin", "civic"), occurs.any)]), occurs.optional),
      field("country_modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Country }),
      }),
      field("localized_tags", block([item(primitive("localisation"), occurs.any)]), occurs.optional),
      field("species_class_override", block([triggerEntries()]), occurs.optional),
      field(
        "portrait_override",
        block([item(typeRef("portrait_group"), occurs.any), item(typeRef("portrait"), occurs.any)]),
        occurs.optional,
      ),
      ruleSetEntries("triggered_planet_pop_group_modifier_species"),
      field("species_possible_merge_add", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Species, from: ScopeId.Country }),
      }),
      field("tags", block([item(typeRef("trait_tags"), occurs.any)]), occurs.optional),
      field("species_possible_merge_remove", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Species, from: ScopeId.Country }),
      }),
      field(
        "prerequisites",
        block([
          item(typeRef("technology"), occurs.optional),
          field("OR", block([item(typeRef("technology"), occurs.any)]), occurs.optional),
        ]),
        occurs.optional,
      ),
      field("opposites", block([item(typeRef("trait", "species_trait"), occurs.any)]), occurs.optional),
      field("forbidden_ethics", block([item(typeRef("ethos"), occurs.any)]), occurs.optional),
      field("potential_crossbreeding_chance", primitive("number"), occurs.optional),
      field("slave_cost", block([field("energy", primitive("integer"), occurs.one)]), occurs.optional),
      field("infertile", primitive("boolean"), occurs.optional),
      field(
        "random_weight",
        block([field(typeKey("species_class"), primitive("number"), occurs.oneOrMore)]),
        occurs.optional,
      ),
      field(
        "triggered_species_modifier",
        block([
          field("potential", block([triggerEntries()]), occurs.optional),
          modifierEntries(),
          field("mult", scriptValue("number"), occurs.optional),
        ]),
        occurs.any,
        { scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }) },
      ),
      field(
        "resources",
        block([field("category", typeRef("economic_category"), occurs.one), ruleSetEntries("economic_template")]),
        occurs.optional,
      ),
    ]),
    whenVariant("leader_trait", [
      field("starting_ruler_trait", literal(true), occurs.optional, {
        documentation: "This trait is available in ruler creation. (Default: no)",
      }),
      field(
        "forbidden_origins",
        block([item(typeRef("civic_or_origin", "origin"), occurs.oneOrMore)]),
        occurs.optional,
        { documentation: "OR - This trait is blocked in ruler creation if listed origins are selected." },
      ),
      field("councilor_trait", primitive("boolean"), occurs.optional, {
        documentation: "Is this trait only active if the leader is on the Council? (Default: no)",
      }),
      field("negative", primitive("boolean"), occurs.optional, {
        documentation: "Is this a negative trait? (Default: no)",
      }),
      field("is_councilor_trait_for_ruler", primitive("boolean"), occurs.optional, {
        documentation: 'Does the "modifier" block apply to empire if leader is ruler? (Default: no)',
      }),
      field("subclass_trait", literal(true), occurs.optional),
      field("subclass_background_icon", typeRef("sprite"), occurs.optional),
      field("veteran_class_locked_trait", literal(true), occurs.optional),
      field("destiny_trait", literal(true), occurs.optional),
      field("destiny_background_icon", typeRef("sprite"), occurs.optional),
      field("ethic_destiny_trait", primitive("boolean"), occurs.optional),
      field("ftl_inhibitor", literal(true), occurs.optional, {
        documentation:
          "Does the General cause FTL inhibitor effects? Note: unclear if/how this might apply to other leader types",
      }),
      field("immortal_leaders", primitive("boolean"), occurs.optional, {
        documentation: "Is this leader immortal? (Default: no)",
      }),
      field("randomized", primitive("boolean"), occurs.optional, {
        documentation:
          "Is this trait available during leader generation, level up or yearly negative trait chance. (Default: yes)",
      }),
      field("hide_age", primitive("boolean"), occurs.optional, { documentation: "(Default: no)" }),
      field("can_retreat", primitive("boolean"), occurs.optional),
      field("self_modifier", block([modifierEntries()]), occurs.optional, {
        documentation: "Modifier applied to leader itself.",
        scope: replaceScope({ root: ScopeId.Leader }),
      }),
      field("modifier", block([modifierEntries()]), occurs.optional, {
        documentation:
          "Modifier applied to scope leader is assigned to (e.g. fleet, or science ship) or country if councilor trait.",
        scope: replaceScope({ root: ScopeId.Country }),
      }),
      field("planet_modifier", block([modifierEntries()]), occurs.optional, {
        documentation: "Modifier applied to planet if General assigned to defense army.",
        scope: replaceScope({ root: ScopeId.Planet }),
      }),
      field("assist_research_planet_modifier", block([modifierEntries()]), occurs.any, {
        documentation: "Modifier applied to planet if Scientist's science vessel assigned to assist research.",
        scope: replaceScope({ root: ScopeId.Planet }),
      }),
      ruleSetEntries("triggered_leader_modifier_leader", {
        documentation: "Modifier applied to the leader itself if the given condition is fulfilled.",
      }),
      field(
        "triggered_desc",
        block([
          field("trigger", block([triggerEntries()]), occurs.optional, {
            documentation: "Trigger appends additional localization key to existing text.",
          }),
          field("exclusive_trigger", block([triggerEntries()]), occurs.optional, {
            documentation: "Exclusive trigger replaces all other text in tooltip with localization key.",
          }),
          field("text", primitive("localisation"), occurs.one),
        ]),
        occurs.any,
        {
          documentation: "Show key if trigger/exclusive_trigger is true.",
          scope: replaceScope({ root: ScopeId.Leader }),
        },
      ),
      field("custom_subtitle", primitive("localisation"), occurs.optional, {
        documentation: "Replaces auto-generated trait subtitle with localization key.",
      }),
      field(
        "prerequisites",
        block([
          item(typeRef("technology"), occurs.optional),
          field("OR", block([item(typeRef("technology"), occurs.any)]), occurs.optional),
        ]),
        occurs.optional,
        { documentation: "AND - Trait only available if the technology specified has been researched by the Empire." },
      ),
      field(
        "triggered_modifier",
        block([
          field("potential", block([triggerEntries()]), occurs.optional),
          modifierEntries(),
          field("mult", scriptValue("number"), occurs.optional),
          field("custom_tooltip", primitive("localisation"), occurs.any),
          field("show_only_custom_tooltip", primitive("boolean"), occurs.optional),
        ]),
        occurs.any,
        { scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }) },
      ),
      field("councilor_modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }),
      }),
      field(
        "triggered_councilor_modifier",
        block([
          field("potential", block([triggerEntries()]), occurs.optional),
          modifierEntries(),
          field("mult", scriptValue("number"), occurs.optional),
          field("custom_tooltip", primitive("localisation"), occurs.any),
          field("show_only_custom_tooltip", primitive("boolean"), occurs.optional),
        ]),
        occurs.any,
        { scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }) },
      ),
      field("fleet_modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }),
      }),
      field(
        "triggered_fleet_modifier",
        block([
          field("potential", block([triggerEntries()]), occurs.optional),
          modifierEntries(),
          field("mult", scriptValue("number"), occurs.optional),
          field("custom_tooltip", primitive("localisation"), occurs.any),
          field("show_only_custom_tooltip", primitive("boolean"), occurs.optional),
        ]),
        occurs.any,
        { scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }) },
      ),
      field("army_modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }),
      }),
      field(
        "triggered_army_modifier",
        block([
          field("potential", block([triggerEntries()]), occurs.optional),
          modifierEntries(),
          field("mult", scriptValue("number"), occurs.optional),
          field("custom_tooltip", primitive("localisation"), occurs.any),
          field("show_only_custom_tooltip", primitive("boolean"), occurs.optional),
        ]),
        occurs.any,
        { scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }) },
      ),
      field("sector_modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }),
      }),
      field(
        "triggered_sector_modifier",
        block([
          field("potential", block([triggerEntries()]), occurs.optional),
          modifierEntries(),
          field("mult", scriptValue("number"), occurs.optional),
          field("custom_tooltip", primitive("localisation"), occurs.any),
          field("show_only_custom_tooltip", primitive("boolean"), occurs.optional),
        ]),
        occurs.any,
        { scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }) },
      ),
      field("planet_modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Planet }),
      }),
      field(
        "triggered_planet_modifier",
        block([
          field("potential", block([triggerEntries()]), occurs.optional),
          modifierEntries(),
          field("mult", scriptValue("number"), occurs.optional),
          field("custom_tooltip", primitive("localisation"), occurs.any),
          field("show_only_custom_tooltip", primitive("boolean"), occurs.optional),
        ]),
        occurs.any,
        { scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Planet }) },
      ),
      field("background_planet_modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Planet }),
      }),
      field(
        "triggered_background_planet_modifier",
        block([
          field("potential", block([triggerEntries()]), occurs.optional),
          modifierEntries(),
          field("mult", scriptValue("number"), occurs.optional),
        ]),
        occurs.any,
        { scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Planet }) },
      ),
      field("system_modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.System }),
      }),
      field(
        "triggered_system_modifier",
        block([
          field("potential", block([triggerEntries()]), occurs.optional),
          modifierEntries(),
          field("mult", scriptValue("number"), occurs.optional),
        ]),
        occurs.any,
        { scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.System }) },
      ),
      field("federation_modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }),
      }),
      field(
        "triggered_federation_modifier",
        block([
          field("potential", block([triggerEntries()]), occurs.optional),
          modifierEntries(),
          field("mult", scriptValue("number"), occurs.optional),
        ]),
        occurs.any,
        { scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }) },
      ),
      field("galcom_modifier", block([modifierEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }),
      }),
      field(
        "triggered_galcom_modifier",
        block([
          field("potential", block([triggerEntries()]), occurs.optional),
          modifierEntries(),
          field("mult", scriptValue("number"), occurs.optional),
        ]),
        occurs.any,
        { scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }) },
      ),
      field("leader_class", literal("all"), occurs.one),
      field("leader_class", block([item(enumRef(EnumId.LeaderClasses), between(1, 5))]), occurs.one),
      field("leader_trait_rarity", enumRef(EnumId.LeaderTraitRarity), occurs.one),
      field("trade_acceptance_weight", primitive("integer"), occurs.optional),
      field("leader_potential_add", block([triggerEntries()]), occurs.optional, {
        scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }),
      }),
      field("requires_traits", block([item(typeRef("trait", "species_trait"), occurs.oneOrMore)]), occurs.optional, {
        documentation: "AND - Trait only available if the leaders species has this trait.",
      }),
      field("requires_governments", block([item(typeRef("government"), occurs.oneOrMore)]), occurs.optional, {
        documentation: "OR - Trait only available if the Empire has this type of government form.",
      }),
      field("opposites", block([item(typeRef("trait", "leader_trait"), occurs.any)]), occurs.optional, {
        documentation: "OR - Trait only available if none of the listed traits are currently on leader.",
      }),
      field("replace_traits", block([item(typeRef("trait", "leader_trait"), occurs.oneOrMore)]), occurs.optional, {
        documentation: "AND - Trait will remove listed traits currently on leader when added.",
      }),
      field("fleet_specialization_tag", enumRef(EnumId.ComponentTags), occurs.optional, {
        documentation: "AI will outfit ships with components based on this tag if trait is selected.",
      }),
      field("selectable_weight", primitive("integer"), occurs.optional, {
        documentation: "Weight for availability at level up. Default is 100.",
      }),
      field(
        "selectable_weight",
        block([field(enumKey(EnumId.WeightOrFactor), primitive("number"), occurs.one), modifierRuleEntries()]),
        occurs.optional,
        {
          documentation: "Weight for availability at level up. Default is 100.",
          scope: replaceScope({ root: ScopeId.Leader, from: ScopeId.Country }),
        },
      ),
      field("notify_on_gained", primitive("boolean"), occurs.optional, { documentation: "(Default: yes)" }),
      field("on_gained_effect", block([effectEntries()]), occurs.optional, {
        documentation: "Effects in this block fire when trait is acquired.",
        scope: replaceScope({ root: ScopeId.Leader }),
      }),
      field("background_icon", typeRef("sprite"), occurs.optional),
      field("force_councilor_trait", literal(true), occurs.optional),
      field("species_potential_add", block([triggerEntries()]), occurs.optional),
    ]),
    field("ai_categories", block([item(enumRef(EnumId.TraitAiClasses), between(1, 4))]), occurs.optional),
    field(
      "triggered_desc",
      block([
        field("trigger", block([triggerEntries()]), occurs.optional, {
          documentation: "Trigger appends additional localization key to existing text.",
        }),
        field("exclusive_trigger", block([triggerEntries()]), occurs.optional, {
          documentation: "Exclusive trigger replaces all other text in tooltip with localization key.",
        }),
        field("text", primitive("localisation"), occurs.one),
      ]),
      occurs.any,
    ),
    field("initial", primitive("boolean"), occurs.optional),
    field("randomized", primitive("boolean"), occurs.optional),
    field("hidden", primitive("boolean"), occurs.optional),
    field("custom_tooltip", primitive("localisation"), occurs.optional, {
      documentation: "Replaces auto-generated modifier effect text with localization key.",
    }),
    field("custom_tooltip_with_modifiers", primitive("localisation"), occurs.optional, {
      documentation: "Appends localization key to the end of auto-generated modifier effect text.",
    }),
    field("ai_weight", primitive("integer"), occurs.optional),
    field(
      "ai_weight",
      block([field(enumKey(EnumId.WeightOrFactor), primitive("integer"), occurs.optional), modifierRuleEntries()]),
      occurs.optional,
    ),
  ],
});
