// Generated by `npm run import:cwt` from cwtools-stellaris-config, then maintained by hand.
// Re-running the importer proposes a diff; it never overwrites hand edits automatically.

import { DefinitionTypeId, EnumId, ScopeId } from "../catalog.js";

import {
  block,
  defineType,
  enumRef,
  field,
  item,
  keyedBlocks,
  literal,
  modifierEntries,
  occurs,
  primitive,
  replaceScope,
  ruleSetEntries,
  triggerEntries,
  typeKey,
  typeRef,
} from "../ir.js";

import type { DefinitionType } from "../ir.js";

export const zones: DefinitionType = defineType({
  id: DefinitionTypeId.Zones,
  source: keyedBlocks("common/zones"),
  variants: [],
  localisation: [],
  modifiers: [],
  entries: [
    field("icon", typeRef("sprite"), occurs.optional),
    field("base_buildtime", primitive("integer"), occurs.optional),
    field("max_buildings_planet_class", primitive("boolean"), occurs.optional),
    field("planet_limit", primitive("integer"), occurs.optional),
    field("swap_type", typeRef("district"), occurs.optional),
    field("swap_type_weight", primitive("integer"), occurs.optional),
    field("potential", block([triggerEntries()]), occurs.optional, { scope: replaceScope({ root: ScopeId.Planet }) }),
    field("planet_limit", block([field("base", primitive("integer"), occurs.one)]), occurs.optional),
    field("unlock", block([triggerEntries()]), occurs.optional, { scope: replaceScope({ root: ScopeId.Planet }) }),
    field(
      "resources",
      block([
        field("category", literal("planet_zones"), occurs.one),
        field("cost", block([field(typeKey("resource"), primitive("integer"), occurs.one)]), occurs.one),
      ]),
      occurs.any,
    ),
    field(
      "ai_resource_production",
      block([
        field(typeKey("resource"), primitive("integer"), occurs.any),
        field("trigger", block([triggerEntries()]), occurs.optional),
      ]),
      occurs.optional,
    ),
    field(
      "triggered_district_planet_modifier",
      block([field("potential", block([triggerEntries()]), occurs.optional), modifierEntries()]),
      occurs.any,
      { scope: replaceScope({ root: ScopeId.Planet }) },
    ),
    field("planet_modifier", block([modifierEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Planet }),
    }),
    field(
      "triggered_desc",
      block([
        field("trigger", block([triggerEntries()]), occurs.optional),
        field("text", primitive("localisation"), occurs.one),
      ]),
      occurs.any,
    ),
    field("max_buildings", primitive("integer"), occurs.optional),
    field(
      "zone_sets",
      block([item(enumRef(EnumId.ZoneSet), occurs.any), item(enumRef(EnumId.ZoneSetAdditional), occurs.any)]),
      occurs.optional,
    ),
    field(
      "include",
      block([item(literal("all"), occurs.optional), item(typeRef("building"), occurs.any)]),
      occurs.optional,
    ),
    field("included_building_sets", block([item(enumRef(EnumId.BuildingSets), occurs.any)]), occurs.any, {
      severity: "warning",
    }),
    field("excluded_building_sets", block([item(enumRef(EnumId.BuildingSets), occurs.any)]), occurs.optional, {
      severity: "warning",
    }),
    field(
      "convert_to",
      block([item(typeRef("zones"), occurs.any), item(enumRef(EnumId.ZoneType), occurs.any)]),
      occurs.optional,
    ),
    field("show_in_tech", typeRef("technology"), occurs.optional),
    ruleSetEntries("triggered_district_modifier_planet"),
    ruleSetEntries("triggered_planet_modifier_planet"),
    field("ai_priority", primitive("integer"), occurs.optional),
    field("ai_weight_coefficient", primitive("number"), occurs.any),
    field("icon", typeRef("sprite"), occurs.optional),
    field("base_buildtime", primitive("integer"), occurs.optional),
    field("max_buildings_planet_class", primitive("boolean"), occurs.optional),
    field("planet_limit", primitive("integer"), occurs.optional),
    field("swap_type", typeRef("district"), occurs.optional),
    field("swap_type_weight", primitive("integer"), occurs.optional),
    field("potential", block([triggerEntries()]), occurs.optional, { scope: replaceScope({ root: ScopeId.Planet }) }),
    field("planet_limit", block([field("base", primitive("integer"), occurs.one)]), occurs.optional),
    field("unlock", block([triggerEntries()]), occurs.optional, { scope: replaceScope({ root: ScopeId.Planet }) }),
    field(
      "resources",
      block([
        field("category", literal("planet_zones"), occurs.one),
        field("cost", block([field(typeKey("resource"), primitive("integer"), occurs.one)]), occurs.one),
      ]),
      occurs.any,
    ),
    field(
      "ai_resource_production",
      block([
        field(typeKey("resource"), primitive("integer"), occurs.any),
        field("trigger", block([triggerEntries()]), occurs.optional),
      ]),
      occurs.optional,
    ),
    field(
      "triggered_district_planet_modifier",
      block([field("potential", block([triggerEntries()]), occurs.optional), modifierEntries()]),
      occurs.any,
      { scope: replaceScope({ root: ScopeId.Planet }) },
    ),
    field("planet_modifier", block([modifierEntries()]), occurs.optional, {
      scope: replaceScope({ root: ScopeId.Planet }),
    }),
    field(
      "triggered_desc",
      block([
        field("trigger", block([triggerEntries()]), occurs.optional),
        field("text", primitive("localisation"), occurs.one),
      ]),
      occurs.any,
    ),
    field("max_buildings", primitive("integer"), occurs.optional),
    field(
      "zone_sets",
      block([item(enumRef(EnumId.ZoneSet), occurs.any), item(enumRef(EnumId.ZoneSetAdditional), occurs.any)]),
      occurs.optional,
    ),
    field(
      "include",
      block([item(literal("all"), occurs.optional), item(typeRef("building"), occurs.any)]),
      occurs.optional,
    ),
    field("included_building_sets", block([item(enumRef(EnumId.BuildingSets), occurs.any)]), occurs.any, {
      severity: "warning",
    }),
    field("excluded_building_sets", block([item(enumRef(EnumId.BuildingSets), occurs.any)]), occurs.optional, {
      severity: "warning",
    }),
    field(
      "convert_to",
      block([item(typeRef("zones"), occurs.any), item(enumRef(EnumId.ZoneType), occurs.any)]),
      occurs.optional,
    ),
    field("show_in_tech", typeRef("technology"), occurs.optional),
    ruleSetEntries("triggered_district_modifier_planet"),
    ruleSetEntries("triggered_planet_modifier_planet"),
    field("ai_priority", primitive("integer"), occurs.optional),
    field("ai_weight_coefficient", primitive("number"), occurs.any),
  ],
});
