import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { schema } from "../../src/schema/index.js";
import { indexGame, type GameIndex } from "./extract.js";

const REPOSITORY_ROOT: string = fileURLToPath(new URL("../../", import.meta.url));
const DEFAULT_GAME_PATH: string = String.raw`D:\steam\steamapps\common\Stellaris`;
const OUTPUT_DIRECTORY: string = join(REPOSITORY_ROOT, "src", "generated", "vanilla");

function compareOrdinal(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function identifier(value: string): string {
  const parts: readonly string[] = value.split(/[^A-Za-z0-9]+/u).filter((part) => part.length > 0);
  const joined: string = parts
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1).toLowerCase()}`)
    .join("");
  const prefixed: string = /^[A-Za-z_$]/u.test(joined) ? joined : `Value${joined}`;
  return prefixed.length === 0 ? "Value" : prefixed;
}

/**
 * Emits the identifiers vanilla defines, per definition type.
 *
 * Each type gets a frozen array plus a union alias widened with `string & {}`,
 * so a mod's own identifiers stay assignable while vanilla names still complete.
 * Only names are emitted — no localisation text, no numbers, no script bodies.
 */
/**
 * Emits the identifiers vanilla defines, per definition type.
 *
 * A union alias per type plus a separately annotated array. One `as const`
 * object holding all 59,802 identifiers exceeds what the compiler will
 * serialise (TS7056) and cannot satisfy `isolatedDeclarations`, so the type
 * side and the value side are kept apart.
 *
 * A type with more identifiers than the threshold widens to `string`: past that
 * point the union costs more in check time than it returns in completion.
 * Only names are emitted — no localisation text, no numbers, no script bodies.
 */
const MAX_UNION_MEMBERS = 3000;

function renderIds(index: GameIndex): {
  readonly source: string;
  readonly mapSource: string;
  readonly widened: readonly string[];
} {
  const nonEmpty = index.types.filter((entry) => entry.ids.length > 0);
  const widened: string[] = [];
  const lines: string[] = [
    "// Generated by `npm run index:game` from an installed copy of Stellaris.",
    `// Game version: ${index.version}. Identifiers only — see PLAN.md R1.`,
    "",
  ];

  for (const entry of nonEmpty) {
    const name: string = identifier(entry.type);
    const tooWide: boolean = entry.ids.length > MAX_UNION_MEMBERS;

    if (tooWide) {
      widened.push(entry.type);
    }

    const union: string = tooWide
      ? [
          `/** ${String(entry.ids.length)} identifiers — too many to union without hurting check time. */`,
          `export type Vanilla${name}Id = string;`,
        ].join("\n")
      : [`export type Vanilla${name}Id =`, ...entry.ids.map((id) => `  | ${JSON.stringify(id)}`)].join("\n") + ";";

    lines.push(
      union,
      "",
      `export const vanilla${name}Ids: readonly string[] = [`,
      ...entry.ids.map((id) => `  ${JSON.stringify(id)},`),
      "];",
      "",
    );
  }

  const mapSource: string = [
    "// Generated by `npm run index:game` from an installed copy of Stellaris.",
    "",
    `import type { ${nonEmpty.map((entry) => `Vanilla${identifier(entry.type)}Id`).join(", ")} } from "./ids.js";`,
    "",
    "/** Which union belongs to which definition type. */",
    "export interface VanillaIdsByType {",
    ...nonEmpty.map((entry) => `  readonly ${JSON.stringify(entry.type)}: Vanilla${identifier(entry.type)}Id;`),
    "}",
    "",
  ].join("\n");

  return { source: lines.join("\n"), mapSource, widened };
}

/** Members of enums whose values live in the game files rather than the schema. */
function renderEnumMembers(index: GameIndex): string {
  const nonEmpty = index.enums.filter((entry) => entry.members.length > 0);

  return [
    "// Generated by `npm run index:game` from an installed copy of Stellaris.",
    `// Game version: ${index.version}.`,
    "//",
    "// An extracted enum's members are defined by the game's own script, so they",
    "// cannot be known from the schema alone. Without them a key drawn from one",
    "// has to be treated as accepting anything, which is what made most types",
    "// unable to report an unknown field.",
    "",
    "export const extractedEnumMembers: Readonly<Record<string, readonly string[]>> = {",
    ...nonEmpty.map(
      (entry) =>
        `  ${JSON.stringify(entry.id)}: [${entry.members.map((member) => JSON.stringify(member)).join(", ")}],`,
    ),
    "};",
    "",
  ].join("\n");
}

async function gameVersion(gamePath: string): Promise<string> {
  try {
    const raw: string = await readFile(join(gamePath, "launcher-settings.json"), "utf8");
    return /"rawVersion"\s*:\s*"([^"]+)"/u.exec(raw)?.[1] ?? "unknown";
  } catch {
    return "unknown";
  }
}

const gamePath: string = process.env["STELLARIS_GAME_PATH"] ?? DEFAULT_GAME_PATH;
const version: string = await gameVersion(gamePath);
const index: GameIndex = await indexGame(schema, gamePath, version);

await mkdir(OUTPUT_DIRECTORY, { recursive: true });
const ids = renderIds(index);
await writeFile(join(OUTPUT_DIRECTORY, "ids.ts"), ids.source, "utf8");
await writeFile(join(OUTPUT_DIRECTORY, "id-map.ts"), ids.mapSource, "utf8");
await writeFile(join(OUTPUT_DIRECTORY, "enum-members.ts"), renderEnumMembers(index), "utf8");
await writeFile(
  join(OUTPUT_DIRECTORY, "index.ts"),
  ['export * from "./enum-members.js";', 'export * from "./ids.js";', ""].join("\n"),
  "utf8",
);

const typesWithIds: number = index.types.filter((entry) => entry.ids.length > 0).length;
const enumsWithMembers: number = index.enums.filter((entry) => entry.members.length > 0).length;

console.log(
  [
    "SUMMARY mode=index-game",
    `version=${index.version}`,
    `types=${String(index.types.length)}`,
    `typesWithIds=${String(typesWithIds)}`,
    `ids=${String(index.types.reduce((total, entry) => total + entry.ids.length, 0))}`,
    `extractedEnums=${String(index.enums.length)}`,
    `enumsWithMembers=${String(enumsWithMembers)}`,
    `enumMembers=${String(index.enums.reduce((total, entry) => total + entry.members.length, 0))}`,
    `filesRead=${String(index.filesRead)}`,
    `widenedToString=${String(ids.widened.length)}`,
  ].join(" "),
);

const emptyTypes: readonly string[] = index.types
  .filter((entry) => entry.ids.length === 0)
  .map((entry) => entry.type)
  .sort(compareOrdinal);

if (emptyTypes.length > 0) {
  console.error(
    `INDEX ${String(emptyTypes.length)} types yielded no identifiers: ${emptyTypes.slice(0, 20).join(", ")}`,
  );
}
