import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { requireGamePath } from "../game-path.js";

import { schema } from "../../src/schema/index.js";
import { indexGame, type GameIndex } from "./extract.js";

const REPOSITORY_ROOT: string = fileURLToPath(new URL("../../", import.meta.url));
const OUTPUT_DIRECTORY: string = join(REPOSITORY_ROOT, "src", "generated", "vanilla");

function compareOrdinal(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function identifier(value: string): string {
  const parts: readonly string[] = value.split(/[^A-Za-z0-9]+/u).filter((part) => part.length > 0);
  const joined: string = parts
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1).toLowerCase()}`)
    .join("");
  const prefixed: string = /^[A-Za-z_$]/u.test(joined) ? joined : `Value${joined}`;
  return prefixed.length === 0 ? "Value" : prefixed;
}

/**
 * Emits the identifiers vanilla defines, per definition type.
 *
 * Each type gets a frozen array plus a union alias widened with `string & {}`,
 * so a mod's own identifiers stay assignable while vanilla names still complete.
 * Only names are emitted — no localisation text, no numbers, no script bodies.
 */
/**
 * Emits the identifiers vanilla defines, per definition type.
 *
 * A union alias per type plus a separately annotated array. One `as const`
 * object holding all 59,802 identifiers exceeds what the compiler will
 * serialise (TS7056) and cannot satisfy `isolatedDeclarations`, so the type
 * side and the value side are kept apart.
 *
 * A type with more identifiers than the threshold widens to `string`: past that
 * point the union costs more in check time than it returns in completion.
 * Only names are emitted — no localisation text, no numbers, no script bodies.
 */
const MAX_UNION_MEMBERS = 3000;

function renderIds(index: GameIndex): {
  readonly source: string;
  readonly mapSource: string;
  readonly widened: readonly string[];
} {
  const nonEmpty = index.types.filter((entry) => entry.ids.length > 0);
  const widened: string[] = [];
  const lines: string[] = [
    "// Generated by `npm run index:game` from an installed copy of Stellaris.",
    `// Game version: ${index.version}. Identifiers only, no game content.`,
    "",
  ];

  for (const entry of nonEmpty) {
    const name: string = identifier(entry.type);
    const tooWide: boolean = entry.ids.length > MAX_UNION_MEMBERS;

    if (tooWide) {
      widened.push(entry.type);
    }

    const union: string = tooWide
      ? [
          `/** ${String(entry.ids.length)} identifiers — too many to union without hurting check time. */`,
          `export type Vanilla${name}Id = string;`,
        ].join("\n")
      : [`export type Vanilla${name}Id =`, ...entry.ids.map((id) => `  | ${JSON.stringify(id)}`)].join("\n") + ";";

    lines.push(
      union,
      "",
      `export const vanilla${name}Ids: readonly string[] = [`,
      ...entry.ids.map((id) => `  ${JSON.stringify(id)},`),
      "];",
      "",
    );
  }

  // A runtime lookup as well as the type map: validation needs the actual names,
  // and the union alias is erased.
  lines.push(
    "export const vanillaIdsByType: Readonly<Record<string, readonly string[]>> = {",
    ...nonEmpty.map((entry) => `  ${JSON.stringify(entry.type)}: vanilla${identifier(entry.type)}Ids,`),
    "};",
    "",
  );

  const mapSource: string = [
    "// Generated by `npm run index:game` from an installed copy of Stellaris.",
    "",
    `import type { ${nonEmpty.map((entry) => `Vanilla${identifier(entry.type)}Id`).join(", ")} } from "./ids.js";`,
    "",
    "/** Which union belongs to which definition type. */",
    "export interface VanillaIdsByType {",
    ...nonEmpty.map((entry) => `  readonly ${JSON.stringify(entry.type)}: Vanilla${identifier(entry.type)}Id;`),
    "}",
    "",
  ].join("\n");

  return { source: lines.join("\n"), mapSource, widened };
}

/** Members of enums whose values live in the game files rather than the schema. */
function renderEnumMembers(index: GameIndex): string {
  const nonEmpty = index.enums.filter((entry) => entry.members.length > 0);

  return [
    "// Generated by `npm run index:game` from an installed copy of Stellaris.",
    `// Game version: ${index.version}.`,
    "//",
    "// An extracted enum's members are defined by the game's own script, so they",
    "// cannot be known from the schema alone. Without them a key drawn from one",
    "// has to be treated as accepting anything, which is what made most types",
    "// unable to report an unknown field.",
    "",
    "export const extractedEnumMembers: Readonly<Record<string, readonly string[]>> = {",
    ...nonEmpty.map(
      (entry) =>
        `  ${JSON.stringify(entry.id)}: [${entry.members.map((member) => JSON.stringify(member)).join(", ")}],`,
    ),
    "};",
    "",
  ].join("\n");
}

async function gameVersion(gamePath: string): Promise<string> {
  try {
    const raw: string = await readFile(join(gamePath, "launcher-settings.json"), "utf8");
    return /"rawVersion"\s*:\s*"([^"]+)"/u.exec(raw)?.[1] ?? "unknown";
  } catch {
    return "unknown";
  }
}

const gamePath: string = requireGamePath();
const version: string = await gameVersion(gamePath);
const index: GameIndex = await indexGame(schema, gamePath, version);

await mkdir(OUTPUT_DIRECTORY, { recursive: true });
const ids = renderIds(index);
await writeFile(join(OUTPUT_DIRECTORY, "ids.ts"), ids.source, "utf8");
await writeFile(join(OUTPUT_DIRECTORY, "id-map.ts"), ids.mapSource, "utf8");
await writeFile(join(OUTPUT_DIRECTORY, "enum-members.ts"), renderEnumMembers(index), "utf8");
await writeFile(
  join(OUTPUT_DIRECTORY, "files.ts"),
  [
    "// Generated by `npm run index:game` from an installed copy of Stellaris.",
    `// Game version: ${index.version}. File names only.`,
    "//",
    "// Shipping a file whose name vanilla already uses replaces it entirely, so",
    "// `emit` needs this list to warn about the collision.",
    "",
    "export const vanillaFiles: Readonly<Record<string, readonly string[]>> = {",
    ...Object.entries(index.vanillaFiles)
      .sort(([left], [right]) => compareOrdinal(left, right))
      .map(
        ([directory, names]) => `  ${JSON.stringify(directory)}: [${names.map((n) => JSON.stringify(n)).join(", ")}],`,
      ),
    "};",
    "",
  ].join("\n"),
  "utf8",
);
await writeFile(
  join(OUTPUT_DIRECTORY, "modifier-names.ts"),
  [
    "// Generated by `npm run index:game` from an installed copy of Stellaris.",
    `// Game version: ${index.version}. Modifier names only, no game content.`,
    "//",
    "// Taken from the keys of the game's own modifier strings. Every modifier the",
    "// executable carries has one, which is how a modifier newer than the newest",
    "// -debug dump becomes known. Lowercased: the game does not distinguish case",
    "// here, and vanilla writes both spellings.",
    "",
    "export const vanillaModifierNames: readonly string[] = [",
    ...index.modifierNames.map((name) => `  ${JSON.stringify(name)},`),
    "];",
    "",
  ].join("\n"),
  "utf8",
);
await writeFile(
  join(OUTPUT_DIRECTORY, "field-names.ts"),
  [
    "// Generated by `npm run index:game` from an installed copy of Stellaris.",
    `// Game version: ${index.version}. Field names only, no game content.`,
    "//",
    "// For the types that declare their own fields — `common/defines` and the",
    "// unchecked interface defines — the engine decides what keys exist, so the",
    "// valid set is whatever the game ships rather than whatever a corpus lists.",
    "",
    "export const vanillaFieldNames: Readonly<Record<string, readonly string[]>> = {",
    ...Object.entries(index.fieldNames)
      .sort(([left], [right]) => compareOrdinal(left, right))
      .map(([type, names]) => `  ${JSON.stringify(type)}: [${names.map((n) => JSON.stringify(n)).join(", ")}],`),
    "};",
    "",
  ].join("\n"),
  "utf8",
);
await writeFile(
  join(OUTPUT_DIRECTORY, "tagged-keys.ts"),
  [
    "// Generated by `npm run index:game` from an installed copy of Stellaris.",
    `// Game version: ${index.version}. Block keys only, no game content.`,
    "//",
    "// A tagged type's block key is a tag, not its identity: an event is written",
    "// `country_event = { id = utopia.1 }`. cwt declares no tags, so these are read",
    "// off the game — without them `define` would write the id as the key and the",
    "// game would load nothing.",
    "",
    "export const vanillaTaggedKeys: Readonly<Record<string, readonly string[]>> = {",
    ...index.types
      .filter((entry) => entry.tags.length > 0)
      .map((entry) => `  ${JSON.stringify(entry.type)}: [${entry.tags.map((tag) => JSON.stringify(tag)).join(", ")}],`),
    "};",
    "",
  ].join("\n"),
  "utf8",
);
await writeFile(
  join(OUTPUT_DIRECTORY, "game-version.ts"),
  [
    "// Generated by `npm run index:game` from an installed copy of Stellaris.",
    "//",
    "// `modsCompatibilityVersion` is what the launcher compares a mod's",
    "// `supported_version` against; a mod that does not cover it is listed as out",
    "// of date and the player is warned before every session.",
    "",
    `export const vanillaGameVersion = ${JSON.stringify(index.version)};`,
    `export const vanillaModsCompatibilityVersion = ${JSON.stringify(index.modsCompatibilityVersion)};`,
    "",
  ].join("\n"),
  "utf8",
);
await writeFile(
  join(OUTPUT_DIRECTORY, "scripted-parameters.ts"),
  [
    "// Generated by `npm run index:game` from an installed copy of Stellaris.",
    `// Game version: ${index.version}. Parameter names only, no game content.`,
    "//",
    "// A call to a scripted trigger or effect passes `$NAME$` substitutions by",
    "// name. A name the callee never mentions is substituted nowhere, so the call",
    "// quietly does something other than what was written; these are what makes",
    "// that detectable.",
    "",
    "export const vanillaScriptedParameters: Readonly<Record<string, readonly string[]>> = {",
    ...Object.entries(index.scriptedParameters)
      .sort(([left], [right]) => compareOrdinal(left, right))
      .map(([id, names]) => `  ${JSON.stringify(id)}: [${names.map((n) => JSON.stringify(n)).join(", ")}],`),
    "};",
    "",
  ].join("\n"),
  "utf8",
);
await writeFile(
  join(OUTPUT_DIRECTORY, "index.ts"),
  [
    'export * from "./enum-members.js";',
    'export * from "./field-names.js";',
    'export * from "./game-version.js";',
    'export * from "./files.js";',
    'export type * from "./id-map.js";',
    'export * from "./ids.js";',
    'export * from "./modifier-names.js";',
    'export * from "./scripted-parameters.js";',
    'export * from "./tagged-keys.js";',
    "",
  ].join("\n"),
  "utf8",
);

const typesWithIds: number = index.types.filter((entry) => entry.ids.length > 0).length;
const enumsWithMembers: number = index.enums.filter((entry) => entry.members.length > 0).length;

console.log(
  [
    "SUMMARY mode=index-game",
    `version=${index.version}`,
    `types=${String(index.types.length)}`,
    `typesWithIds=${String(typesWithIds)}`,
    `ids=${String(index.types.reduce((total, entry) => total + entry.ids.length, 0))}`,
    `extractedEnums=${String(index.enums.length)}`,
    `enumsWithMembers=${String(enumsWithMembers)}`,
    `enumMembers=${String(index.enums.reduce((total, entry) => total + entry.members.length, 0))}`,
    `filesRead=${String(index.filesRead)}`,
    `widenedToString=${String(ids.widened.length)}`,
    `vanillaDirectories=${String(Object.keys(index.vanillaFiles).length)}`,
    `modifierNames=${String(index.modifierNames.length)}`,
    `gameDeclaredFields=${String(Object.values(index.fieldNames).reduce((total, names) => total + names.length, 0))}`,
    `callablesIndexed=${String(Object.keys(index.scriptedParameters).length)}`,
    `callableParameters=${String(Object.values(index.scriptedParameters).reduce((total, names) => total + names.length, 0))}`,
    `taggedTypes=${String(index.types.filter((entry) => entry.tags.length > 0).length)}`,
  ].join(" "),
);

/**
 * Types intentionally left empty after checking the installed 4.4.6 game.
 *
 * This is a reasoned allowlist rather than a list of inconvenient results:
 * any newly empty type is still an indexing defect and makes this command fail.
 */
const EXPECTED_EMPTY_TYPE_REASONS: Readonly<Record<string, string>> = {
  // `common/defines` contains only 00_defines.txt and
  // 00_defines_additional_content.txt; neither declares an NEngine root block.
  NEngine: "no NEngine root block exists in either installed common/defines file",

  // The singular directory is absent. The 28 definitions in the plural
  // `common/artifact_actions` directory already belong to `artifact_actions`;
  // redirecting this legacy type there would duplicate every identifier.
  artifact_action: "obsolete singular duplicate of the indexed artifact_actions type",

  // No root-level `random_list = { name = ... initializer = ... }` definition
  // exists under this directory. The only text matches are nested control-flow
  // random_list blocks inside ordinary initializer scripts.
  solar_system_initializer_random_list:
    "no root-level initializer random-list definition exists in the installed solar_system_initializers",

  // Neither the installed game nor any of its 19 DLC archives contains this
  // directory or a `conversion_rate` definition. `set_trade_conversions` in
  // policies is effect syntax and does not define IDs of this type.
  trade_conversion: "legacy trade-conversion definitions are absent from the installed game and DLC archives",
};

const emptyTypes: readonly string[] = index.types
  .filter((entry) => entry.ids.length === 0)
  .map((entry) => entry.type)
  .sort(compareOrdinal);

if (emptyTypes.length > 0) {
  console.error(`INDEX ${String(emptyTypes.length)} types yielded no identifiers: ${emptyTypes.join(", ")}`);
}

for (const type of emptyTypes) {
  const reason: string | undefined = EXPECTED_EMPTY_TYPE_REASONS[type];
  if (reason !== undefined) {
    console.error(`INDEX expected-empty ${type}: ${reason}`);
  }
}

const unexplainedEmptyTypes: readonly string[] = emptyTypes.filter(
  (type) => EXPECTED_EMPTY_TYPE_REASONS[type] === undefined,
);

if (unexplainedEmptyTypes.length > 0) {
  console.error(`INDEX unexplained empty types: ${unexplainedEmptyTypes.join(", ")}`);
  process.exitCode = 1;
}
