import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { schema } from "../../src/schema/index.js";
import { generateScopeApi, type ScopeCodegenResult } from "./scope.js";
import { generateDefinitionTypes, type TypeCodegenResult } from "./types.js";

const REPOSITORY_ROOT: string = fileURLToPath(new URL("../../", import.meta.url));

/**
 * The open value shapes every generated definition leans on.
 *
 * Trigger and effect blocks are deliberately open: their key set is the whole
 * command table plus whatever scripted triggers a mod defines, and narrowing
 * them would reject script the game accepts. They are typed for shape, not for
 * membership — `verify` and `stellaris-ts check` do membership.
 */
const SCRIPT_MODULE: string = `// Generated by \`npm run codegen\`. Do not edit — fix the generator.

import type { ComparedValue, EntriesValue, RawValue, RepeatedValue } from "../../runtime/values.js";

/**
 * The forms the format has that a plain value does not: a comparison, a key
 * written more than once, an ordered entry list, and raw script. Every field
 * accepts them, because any field can need one.
 */
export type Authored = ComparedValue | EntriesValue | RawValue | RepeatedValue;

/** Any value PDX script can hold. */
export type PdxValue = boolean | number | string | PdxBlock | readonly PdxValue[] | Authored;

/** Any block. Keys repeat in PDX, so a repeated key may carry an array. */
export interface PdxBlock {
  readonly [key: string]: PdxValue | undefined;
}

/**
 * A trigger block. Left open on purpose: the legal keys are every trigger the
 * game ships plus every scripted trigger in scope, which no static type can
 * enumerate. Membership is checked by \`stellaris-ts check\`, not by the type.
 */
export interface TriggerBlock {
  readonly [key: string]: PdxValue | undefined;
}

/** An effect block. Open for the same reason as {@link TriggerBlock}. */
export interface EffectBlock {
  readonly [key: string]: PdxValue | undefined;
}

/** A modifier block: modifier name to magnitude. */
export interface ModifierBlock {
  readonly [key: string]: PdxValue | undefined;
}

/** A triggered-modifier block. */
export interface ModifierRuleBlock {
  readonly [key: string]: PdxValue | undefined;
}
`;

const REFS_MODULE: string = `// Generated by \`npm run codegen\`. Do not edit — fix the generator.

import type { VanillaIdsByType } from "../vanilla/id-map.js";

/**
 * The identifiers vanilla declares for one definition type.
 *
 * Resolves to \`string\` when the index has no entry for the type, so a
 * reference stays usable before \`npm run index:game\` has run.
 */
export type VanillaId<Type extends string> = Type extends keyof VanillaIdsByType ? VanillaIdsByType[Type] : string;
`;

const result: TypeCodegenResult = generateDefinitionTypes(schema);
const scopes: ScopeCodegenResult = generateScopeApi(schema);
const modules: readonly { readonly path: string; readonly source: string }[] = [
  { path: "src/generated/types/script.ts", source: SCRIPT_MODULE },
  { path: "src/generated/types/refs.ts", source: REFS_MODULE },
  ...result.modules,
  ...scopes.modules,
  {
    path: "src/generated/types/index.ts",
    source: [
      "// Generated by `npm run codegen`. Do not edit — fix the generator.",
      "",
      'export type * from "./definitions.js";',
      'export type * from "./refs.js";',
      'export type * from "./scopes.js";',
      'export type * from "./script.js";',
      "",
    ].join("\n"),
  },
];

await Promise.all(
  modules.map(async (module) => {
    const absolute: string = join(REPOSITORY_ROOT, module.path);
    await mkdir(dirname(absolute), { recursive: true });
    await writeFile(absolute, module.source, "utf8");
  }),
);

console.log(
  [
    "SUMMARY mode=codegen",
    `modules=${String(modules.length)}`,
    `definitions=${String(result.definitionCount)}`,
    `properties=${String(result.propertyCount)}`,
    `literalUnions=${String(result.literalUnionCount)}`,
    `scopes=${String(scopes.scopeCount)}`,
    `scopeMembers=${String(scopes.memberCount)}`,
    `unconstrainedCommands=${String(scopes.unconstrainedCommands)}`,
  ].join(" "),
);
