import type { SchemaModel, ScriptCommandDefinition } from "../../src/schema/ir.js";
import type { EmittedModule } from "./types.js";

/**
 * Generates the scope-aware surface.
 *
 * `has_country_flag` is legal in a country scope and meaningless in a planet
 * one, and the game says nothing about the difference — it just does not fire.
 * The schema knows which scopes each command accepts, so the mistake can be a
 * compile error instead.
 *
 * The membership is expanded here rather than computed in the type system. With
 * 2,339 commands over 41 scopes, a conditional type would make every keystroke
 * in an editor pay for the whole table; a generated interface per scope costs
 * the compiler nothing at use time.
 *
 * How much this is worth depends entirely on the source data, and right now the
 * data is thin: 2,328 of the 2,339 commands carry no scope constraint at all in
 * the ported corpus, so they are offered in every scope. The generator reports
 * that count rather than letting a nearly-empty constraint pass for safety.
 * Narrowing it means importing the scope-change tables the corpus keeps
 * separately, which is not done yet.
 */

export interface ScopeCodegenResult {
  readonly modules: readonly EmittedModule[];
  readonly scopeCount: number;
  readonly memberCount: number;
  readonly unconstrainedCommands: number;
}

function compareOrdinal(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function pascal(value: string): string {
  const parts: readonly string[] = value.split(/[^A-Za-z0-9]+/u).filter((part) => part.length > 0);
  const joined: string = parts
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1).toLowerCase()}`)
    .join("");
  return /^[A-Za-z_$]/u.test(joined) ? joined : `Scope${joined}`;
}

function propertyName(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(key) ? key : JSON.stringify(key);
}

/**
 * Which scopes a command may be written in.
 *
 * `unspecified` means the corpus never said, and an unstated constraint is not
 * the same as a constraint of none — those commands are offered everywhere
 * rather than nowhere, so the types never reject script for lack of data.
 */
function scopesFor(command: ScriptCommandDefinition, all: readonly string[]): readonly string[] {
  if (command.input.kind === "listed-scopes") {
    return command.input.scopes.length === 0 ? all : command.input.scopes;
  }

  return all;
}

export function generateScopeApi(model: SchemaModel): ScopeCodegenResult {
  const scopeIds: readonly string[] = [...model.scopes.map((scope) => scope.id)].sort(compareOrdinal);
  const byScope = new Map<string, { triggers: Set<string>; effects: Set<string> }>();

  for (const id of scopeIds) {
    byScope.set(id, { triggers: new Set<string>(), effects: new Set<string>() });
  }

  let unconstrained = 0;

  for (const command of model.commands) {
    if (command.family !== "trigger" && command.family !== "effect") {
      continue;
    }

    if (command.input.kind !== "listed-scopes" || command.input.scopes.length === 0) {
      unconstrained += 1;
    }

    for (const scope of scopesFor(command, scopeIds)) {
      const bucket = byScope.get(scope);
      if (bucket === undefined || command.id.length === 0) {
        continue;
      }
      (command.family === "trigger" ? bucket.triggers : bucket.effects).add(command.id);
    }
  }

  const declarations: string[] = [];
  let memberCount = 0;

  for (const id of scopeIds) {
    const bucket = byScope.get(id);
    if (bucket === undefined) {
      continue;
    }

    const triggers: readonly string[] = [...bucket.triggers].sort(compareOrdinal);
    const effects: readonly string[] = [...bucket.effects].sort(compareOrdinal);
    memberCount += triggers.length + effects.length;

    declarations.push(
      `/** Triggers legal in the \`${id}\` scope. */`,
      `export interface ${pascal(id)}Triggers {`,
      ...triggers.map((name) => `  readonly ${propertyName(name)}?: PdxValue;`),
      "  readonly [key: string]: PdxValue | undefined;",
      "}",
      "",
      `/** Effects legal in the \`${id}\` scope. */`,
      `export interface ${pascal(id)}Effects {`,
      ...effects.map((name) => `  readonly ${propertyName(name)}?: PdxValue;`),
      "  readonly [key: string]: PdxValue | undefined;",
      "}",
      "",
    );
  }

  const scopeUnion: string = scopeIds.map((id) => JSON.stringify(id)).join(" | ");

  return {
    modules: [
      {
        path: "src/generated/types/scopes.ts",
        source: [
          "// Generated by `npm run codegen`. Do not edit — fix the generator.",
          "//",
          "// A command's legal scopes are expanded here rather than resolved in the",
          "// type system: 2,339 commands over 41 scopes as a conditional type would",
          "// make every use pay for the whole table.",
          "",
          'import type { PdxValue } from "./script.js";',
          "",
          `export type ScopeName = ${scopeUnion};`,
          "",
          "/** Which triggers each scope accepts. */",
          "export interface TriggersByScope {",
          ...scopeIds.map((id) => `  readonly ${propertyName(id)}: ${pascal(id)}Triggers;`),
          "}",
          "",
          "/** Which effects each scope accepts. */",
          "export interface EffectsByScope {",
          ...scopeIds.map((id) => `  readonly ${propertyName(id)}: ${pascal(id)}Effects;`),
          "}",
          "",
          ...declarations,
        ].join("\n"),
      },
    ],
    scopeCount: scopeIds.length,
    memberCount,
    unconstrainedCommands: unconstrained,
  };
}
