import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { requireGamePath } from "../game-path.js";
import { schema } from "../../src/schema/index.js";
import { withCorrections } from "../../src/schema/corrections.js";
import { definitionTypes } from "../../src/schema/definitions/index.js";
import { withGameDeclaredFields } from "../../src/schema/open-fields.js";
import { vanillaDefinitionTypes } from "../../src/schema/vanilla-types.js";
import { vanillaFieldNames } from "../../src/generated/vanilla/index.js";
import { checkConformance } from "../verify-schema/conformance.js";
import type { DefinitionType, ScriptCommandDefinition, SchemaModel } from "../../src/schema/ir.js";

/**
 * Infers the scope a definition body runs in.
 *
 * The corpus states it for 16 of 235 types, and nothing else does: the game's
 * `-debug` documentation says which scopes each *command* reads, and says
 * nothing about definitions. But the two together are enough — a command
 * written straight into a body reads that body, so intersecting what every such
 * command accepts leaves what the body is.
 *
 * A single scope surviving the intersection is proposed. An empty one means the
 * commands disagree and the body is not one scope; more than one means nothing
 * separated them. Neither is guessed at.
 *
 * The proposal is then checked the only way it can be: `verify:conformance`
 * re-reads every definition the game ships with the inferred scopes applied, and
 * a wrong one shows up as a command written where it cannot read.
 */

const REPOSITORY_ROOT: string = fileURLToPath(new URL("../../", import.meta.url));
const OUTPUT: string = join(REPOSITORY_ROOT, "src", "schema", "vanilla-entry-scopes.ts");

/**
 * How many commands must agree before a scope is proposed.
 *
 * One command is one line of one dump, and a single mistake in it would name the
 * wrong scope for a whole type.
 */
const MINIMUM_WITNESSES = 4;

function compareOrdinal(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

const observations = new Map<string, { candidates: Set<string> | undefined; witnesses: number }>();

const observe = (type: string, command: ScriptCommandDefinition, atEntryScope: boolean): void => {
  if (!atEntryScope || command.input.kind !== "listed-scopes" || command.input.scopes.length === 0) {
    return;
  }

  const record = observations.get(type) ?? { candidates: undefined, witnesses: 0 };
  record.witnesses += 1;

  if (record.candidates === undefined) {
    record.candidates = new Set<string>(command.input.scopes);
  } else {
    for (const scope of [...record.candidates]) {
      if (!command.input.scopes.some((allowed) => allowed === scope)) {
        record.candidates.delete(scope);
      }
    }
  }

  observations.set(type, record);
};

const gamePath: string = requireGamePath();

// Everything except this file's own output. Reading the assembled schema instead
// would find every body already pinned down — by the last run of this command —
// and empty the file it wrote.
const base: SchemaModel = {
  ...schema,
  definitionTypes: withGameDeclaredFields(
    withCorrections([...definitionTypes, ...vanillaDefinitionTypes]),
    vanillaFieldNames,
  ),
};

// Only the types the corpus leaves open: where cwt names a scope, it names it.
const stated: ReadonlySet<string> = new Set(
  base.definitionTypes
    .filter((type: DefinitionType) => typeof type.entryScope === "string")
    .map((type: DefinitionType) => type.id),
);

await checkConformance(base, gamePath, { observeCommands: observe });

interface Proposal {
  readonly type: string;
  readonly scope: string;
  readonly witnesses: number;
}

const proposals: Proposal[] = [];
let ambiguous = 0;
let contradictory = 0;
let tooFew = 0;

for (const [type, record] of observations) {
  if (stated.has(type) || record.candidates === undefined) {
    continue;
  }

  if (record.witnesses < MINIMUM_WITNESSES) {
    tooFew += 1;
    continue;
  }

  if (record.candidates.size === 0) {
    contradictory += 1;
    continue;
  }

  if (record.candidates.size > 1) {
    ambiguous += 1;
    continue;
  }

  const scope: string | undefined = [...record.candidates][0];

  if (scope !== undefined) {
    proposals.push({ type, scope, witnesses: record.witnesses });
  }
}

proposals.sort((left, right) => compareOrdinal(left.type, right.type));

const lines: string[] = [
  "// Generated by `npm run propose:scopes` from the installed game, then reviewed.",
  "//",
  "// The scope each definition body runs in, inferred from the commands vanilla",
  "// writes straight into it: a command reads one kind of object, so what every",
  "// one of them accepts is what the body is. The corpus states this for 16 types",
  "// and nothing states it for the rest.",
  "//",
  "// Checked by re-reading the game with them applied: `verify:conformance`",
  "// reports a command written where it cannot read, so a wrong scope here would",
  "// be reported for every definition of that type.",
  "",
  "export const vanillaEntryScopes: Readonly<Record<string, string>> = {",
  ...proposals.flatMap((proposal) => [
    `  // ${String(proposal.witnesses)} commands written straight into the body accept it`,
    `  ${JSON.stringify(proposal.type)}: ${JSON.stringify(proposal.scope)},`,
  ]),
  "};",
  "",
  "/**",
  " * Applies the inferred scopes to the types that state none.",
  " *",
  " * Never replaces one the corpus states: where cwt names a scope it names it",
  " * deliberately, and an inference has no business overruling that.",
  " */",
  "export function withEntryScopes(types: readonly DefinitionType[]): readonly DefinitionType[] {",
  "  return types.map((type) => {",
  '    if (typeof type.entryScope === "string") {',
  "      return type;",
  "    }",
  "",
  "    const inferred: string | undefined = vanillaEntryScopes[type.id];",
  "    return inferred === undefined ? type : { ...type, entryScope: inferred };",
  "  });",
  "}",
  "",
];

lines.unshift('import type { DefinitionType } from "./ir.js";', "");

await writeFile(OUTPUT, lines.join("\n"), "utf8");

console.log(
  [
    "SUMMARY mode=propose-scopes",
    `stated=${String(stated.size)}`,
    `proposed=${String(proposals.length)}`,
    `ambiguous=${String(ambiguous)}`,
    `contradictory=${String(contradictory)}`,
    `tooFewWitnesses=${String(tooFew)}`,
  ].join(" "),
);
