import { captureKey, captureScalar, enumExtraction, extractedEnum, extractionField, staticEnum } from "./ir.js";
import type { EnumDefinition } from "./ir.js";

export const enums: readonly EnumDefinition[] = [
  staticEnum("DLCs", [
    "Ancient Relics Story Pack",
    "Anniversary Portraits",
    "Apocalypse",
    "Aquatics Species Pack",
    "Arachnoid Portrait Pack",
    "Astral Planes",
    "BioGenesis",
    "Cosmic Storms",
    "Creatures of the Void Portrait Pack",
    "Distant Stars Story Pack",
    "Federations",
    "First Contact Story Pack",
    "Galactic Paragons",
    "Grand Archive",
    "Humanoids Species Pack",
    "Infernals Species Pack",
    "Leviathans Story Pack",
    "Lithoids Species Pack",
    "Mammalian Species Pack",
    "Megacorp",
    "Necroids Species Pack",
    "Nemesis",
    "Overlord",
    "Plantoids Species Pack",
    "Rick The Cube Species Portrait",
    "Shadows of the Shroud",
    "Stargazer Species Portrait",
    "Synthetic Dawn Story Pack",
    "The Machine Age",
    "Toxoids Species Pack",
    "Utopia",
    "Vipra the Vapor Species Portrait",
  ]),
  staticEnum("acceptance_types", ["default", "leader"]),
  staticEnum("action_types", ["positive", "negative", "aggressive", "neutral"]),
  staticEnum("actionshortcut", [
    "accept",
    "cancel",
    "delete",
    "focus_camera",
    "start",
    "reset",
    "track_on_map",
    "toggle_cloud_save",
  ]),
  staticEnum("aggro_range_measure_from", ["self", "return_point"]),
  staticEnum("agreement_subject_expand", ["can_expand", "can_expand_with_tithe", "cannot_expand"]),
  staticEnum("agreement_term_type", ["discrete", "discrete_number", "specialist_type", "resource"]),
  staticEnum("agreement_wars", ["none", "defensive", "offensive", "all"]),
  staticEnum("ai_attitude_behaviours", ["attack", "weaken", "alliance", "vassalize", "trade", "coexist"]),
  staticEnum("ai_personality_behaviours", [
    "conqueror",
    "subjugator",
    "liberator",
    "opportunist",
    "slaver",
    "uplifter",
    "purger",
    "displacer",
    "infiltrator",
    "dominator",
    "robot_exploiter",
    "robot_liberator",
    "propagator",
    "multispecies",
    "crisis_fighter",
    "holy_planets",
    "demands_clear_borders",
    "wants_tribute",
    "sneak_attacker",
    "decadent",
    "isolationist",
    "attack_neutrals",
    "crisis_leader",
    "custodian",
    "enigmatic",
    "limited",
    "berserker",
  ]),
  staticEnum("ambient_object", ["abandoned_weapon_station", "small_debris_object"]),
  staticEnum("ambient_object_flag_enum", [
    "psionic_aura_level2_entity",
    "psionic_aura_level3_entity",
    "relic_world_debris",
  ]),
  staticEnum("animation_life", ["life", "life_abs", "system", "spawn"]),
  staticEnum("animation_mode", ["overlay", "add", "multiply"]),
  staticEnum("animation_op", ["MUL", "ADD", "ABS"]),
  staticEnum("animation_type", ["scrolling", "rotating", "pulsing", "rotating_ccw", "rotating_cw"]),
  staticEnum("astral_actions_upgrade", ["action_flash_forge_hyper_relay", "action_quantum_catapult_insight_2"]),
  staticEnum("astral_rift_on_roll_failed", ["standard_astral_rift_on_roll_failed"]),
  staticEnum("audible_behaviour", ["fail"]),
  staticEnum("aura_types", ["ships", "fleets"]),
  staticEnum("authority_postfixes", ["hive_mind", "machine_intelligence"]),
  staticEnum("auto_open_type", ["none", "player", "others", "all", "always"]),
  staticEnum("awareness_levels", ["none", "low", "medium", "high", "full"]),
  staticEnum("bio_finish_anim_state", ["rage", "superweapon"]),
  staticEnum("building_categories", [
    "army",
    "manufacturing",
    "government",
    "pop_assembly",
    "resource",
    "unity",
    "research",
    "trade",
    "amenity",
    "planet_buildings",
    "amenities",
  ]),
  staticEnum("building_owner_type", ["normal", "corporate", "subject_holding"]),
  extractedEnum("building_sets", [
    enumExtraction("common/buildings", [extractionField("building_sets"), captureScalar()], true, false),
  ]),
  staticEnum("bypass_connection_type", [
    "any_other",
    "one_to_one",
    "scripted_connection",
    "hyper_relay",
    "to_any_system",
  ]),
  staticEnum("card_categories_focus", [
    "country_focus",
    "core_focus",
    "exploration",
    "conquest",
    "development",
    "unity",
    "research",
    "trade",
    "amenity",
  ]),
  staticEnum("cede_claims", ["true", "occupied_only", "false"]),
  staticEnum("cluster_method", ["one_every_x_empire", "constant"]),
  staticEnum("colossus_status", ["charging", "firing"]),
  staticEnum("combat_anchor", ["root", "parent"]),
  staticEnum("combat_range", ["min", "max", "median"]),
  staticEnum("complex_maths_enum", [
    "set",
    "weight",
    "add",
    "subtract",
    "factor",
    "mult",
    "multiply",
    "divide",
    "modulo",
    "round_to",
    "max",
    "min",
    "pow",
  ]),
  staticEnum("component_bio_potential", [
    "ship_uses_space_fauna_titan_thrusters = yes",
    "ship_uses_space_fauna_cruiser_thrusters = yes",
    "ship_uses_space_fauna_destroyer_thrusters = yes",
    "ship_uses_space_fauna_corvette_thrusters = yes",
    "ship_uses_space_fauna_battleship_thrusters = yes",
  ]),
  staticEnum("component_bio_prereq", [
    "",
    "tech_thrusters_2 tech_thrusters_bio_integration",
    "tech_thrusters_3 tech_thrusters_bio_integration",
    "tech_thrusters_4 tech_thrusters_bio_integration",
    "tech_dark_matter_propulsion tech_thrusters_bio_integration",
  ]),
  staticEnum("component_bio_stack_info_id", [
    "anti_evasion",
    "anti_fire_rate",
    "bio_anti_evasion",
    "bio_anti_fire_rate",
    "bio_evasion",
    "bio_fire_rate",
    "bio_healing",
    "disruptor_regen",
    "evasion",
    "fire_rate",
    "healing",
  ]),
  staticEnum("component_pd_targets", ["strike_craft", "missile"]),
  extractedEnum("component_slots", [
    enumExtraction(
      "common/section_templates",
      [extractionField("component_slot"), extractionField("name"), captureScalar()],
      true,
      false,
    ),
  ]),
  extractedEnum("component_tags", [enumExtraction("common/component_tags", [captureScalar()], true, false)]),
  staticEnum("component_target_focus", ["single", "spread"]),
  staticEnum("component_target_type", ["target_allies", "target_controlled", "target_enemies", "target_own"]),
  staticEnum("component_upgrade_path", [
    "artillery",
    "buffer",
    "carrier",
    "debuffer",
    "default",
    "empty",
    "growth",
    "harbinger_chitin",
    "harbinger_incubator",
    "mauler_biter",
    "mauler_pursuit",
    "picket",
    "line",
    "stinger_fire_rate",
    "stinger_range",
    "swarm",
    "torpedo",
    "weaver_booster",
    "weaver_growth_aura",
  ]),
  staticEnum("construction_type", [
    "none",
    "starbase",
    "mining_station",
    "research_station",
    "observation_post",
    "starbase_shipyard",
    "spaceport",
    "starbase_defenses",
    "starbase_beastport",
    "starbase_hatchery",
  ]),
  staticEnum("contact_rules", ["always", "never", "on_action_only", "does_first_contact_sites", "auto"]),
  staticEnum("coordinate_transform_method", ["add", "sub", "mul", "div"]),
  staticEnum("country_flag_enum", [
    "affected_by_celestial_storm",
    "affected_by_electric_storm",
    "affected_by_gravity_storm",
    "affected_by_magnetic_storm",
    "affected_by_nexus_storm",
    "affected_by_particle_storm",
    "affected_by_shroud_storm",
    "affected_by_solar_storm",
    "affluence_center_can_build",
    "affluence_emporium_can_build",
    "apex_aquatic",
    "apex_arthropoid",
    "apex_avian",
    "apex_fungoid",
    "apex_humanoid",
    "apex_lithoid",
    "apex_machine",
    "apex_mammalian",
    "apex_molluscoid",
    "apex_necroid",
    "apex_plantoid",
    "apex_reptilian",
    "apex_toxoid",
    "army_recruited",
    "army_recruited_patron",
    "awakening_not_allowed",
    "beholder_psi_pops_cooldown_timer",
    "beholder_psi_pops_timer",
    "breached_shroud",
    "broken_shackles_homeworld@root",
    "build_dyson_sphere_swarm",
    "buildings_good_energy",
    "buildings_good_food",
    "buildings_good_minerals",
    "chinorr_combine",
    "class_3_singularity_can_build",
    "class_4_singularity_can_build",
    "commander_given",
    "commander_given_patron",
    "crisis_beacon_timer",
    "cyber_creed_undercover_leader_hammer",
    "curator_enclave_diplomacy_engaged",
    "decision_gh_life_seeding_ongoing",
    "devour_war_active",
    "dimensional_fabricator_can_build",
    "dimensional_replicator_can_build",
    "dportal_trade_crisis",
    "dportal_trade_high",
    "dportal_trade_low",
    "dportal_trade_normal",
    "end_of_cycle_lost_planets",
    "end_of_the_cycle_reckoning",
    "end_violence",
    "enigmatic_fortress_disabled",
    "eotc_destruction_mitigated",
    "exploration_focus_230_completed",
    "failed_fund_contribution",
    "fe_administration_1_can_build",
    "fe_administration_hive_1_can_build",
    "fe_administration_machine_1_can_build",
    "fe_assembly_1_can_build",
    "fe_clinic_1_can_build",
    "fe_entertainment_1_can_build",
    "fe_fortress_can_build",
    "fe_hive_control_second",
    "fe_hive_war_third",
    "fe_lab_1_can_build",
    "fe_market_1_can_build",
    "fe_mine_1_can_build",
    "fe_security_1_can_build",
    "fe_silo_1_can_build",
    "fe_sky_dome_can_build",
    "fed_origin_system_1",
    "georadiation_signal_1_planet",
    "georadiation_signal_1_star",
    "georadiation_signal_2_planet",
    "georadiation_signal_2_star",
    "grand_archive_8410_end_dialog",
    "has_already_traded_specimens",
    "has_private_clinics",
    "has_uplifted_species",
    "hostile_to_nomads",
    "human_plantoid",
    "increase_leader_upkeep",
    "intelligent_learners_development",
    "kaleidoscope_planet",
    "keep_deposit_on_terraform",
    "legendary_leader_coma",
    "loaning_fleet",
    "logistics_assistance",
    "logistics_assistance_patron",
    "lootboxed_recently",
    "matriarch_horror",
    "mercenary_enclave_planet",
    "micro_forge_can_build",
    "mindwarden_logistics_cooldown",
    "mmat_vs_spir_development",
    "nano_forge_can_build",
    "necrophage_elevation_timer",
    "necrophage_start_empire",
    "new_atomic_age",
    "new_bronze_age",
    "new_iron_age",
    "new_late_medieval_age",
    "nourishment_center_can_build",
    "nourishment_complex_can_build",
    "ongoing_preftl_chain",
    "only_unbidden_this_time",
    "oracle_completed",
    "paragon_origin_ascension_flag_flipping__tactical_interface",
    "paragon_origin_cybernetic_ascension",
    "paragon_origin_finished_story",
    "paragon_origin_genetic_ascension",
    "paragon_origin_psionic_ascension",
    "paragon_origin_synthetic_ascension",
    "planet_storm_to_signal_found",
    "police_recruited",
    "police_recruited_patron",
    "prescripted_blorg",
    "primitive_cousins_of_@root.owner",
    "raid_target_asked",
    "raid_target_asked_patron",
    "received_collection_stage_2_reward_aesthetic_wonder",
    "received_collection_stage_2_reward_historical_item",
    "received_collection_stage_2_reward_xeno_geology",
    "recently_got_affluence_emporium",
    "recently_got_class_3_singularity",
    "recently_got_dimensional_replicator",
    "recently_got_fe_administration_1",
    "recently_got_fe_administration_hive_1",
    "recently_got_fe_administration_machine_1",
    "recently_got_fe_assembly_1",
    "recently_got_fe_clinic_1",
    "recently_got_fe_entertainment_1",
    "recently_got_fe_fortress",
    "recently_got_fe_lab_1",
    "recently_got_fe_market_1",
    "recently_got_fe_mine_1",
    "recently_got_fe_security_1",
    "recently_got_fe_silo_1",
    "recently_got_fe_sky_dome",
    "recently_got_micro_forge",
    "recently_got_nourishment_complex",
    "reckoning_intel_given",
    "reckoning_intel_given_patron",
    "recycled_vir",
    "reemployment_center_timer",
    "shroud_song_10_selected",
    "shroud_song_11_selected",
    "shroud_song_12_selected",
    "shroud_song_13_selected",
    "shroud_song_1_selected",
    "shroud_song_2_selected",
    "shroud_song_3_selected",
    "shroud_song_4_selected",
    "shroud_song_5_selected",
    "shroud_song_6_selected",
    "shroud_song_7_selected",
    "shroud_song_8_selected",
    "shroud_song_9_selected",
    "shroudwalker_attune_patron_cooldown",
    "shroudwalker_contact_patron_cooldown",
    "shroudwalker_delving_ritual_cooldown",
    "situation_red_giant_add_fuel",
    "skydome_can_build",
    "slave_rebels",
    "slave_revolt",
    "started_zroni_storyline",
    "target_of_operation_arm_privateers",
    "tech_1_researched",
    "tech_2_researched",
    "tech_fe_market_1",
    "tech_fe_security_1",
    "tech_fe_security_1_can_build",
    "the_composer_of_strands_betrayal",
    "the_cradle_of_souls_betrayal",
    "the_eater_of_worlds_betrayal",
    "the_instrument_of_desire_betrayal",
    "the_voor",
    "thesis_insufficient",
    "traded_planet_x",
    "triggered_storm_in_a_box",
    "uncapped_generator_districts",
    "unplugged_pre_ftl_empire_flag",
    "use_on_action_when_establishing_comms",
    "works_with_formless",
    "zro_bought",
    "zro_bought_patron",
    "zroni_storyline_completed",
  ]),
  staticEnum("country_type_module", [
    "anti_crisis_military_minister_module",
    "berserk_military_minister_module",
    "enclave_founder_minister_module",
    "enclave_mercenary_military_minister_module",
    "enclave_mercenary_seller_minister_module",
    "foreign_minister_module",
    "formless_military_minister_module",
    "galactic_community_patrol_military_minister_module",
    "horde_interior_minister_module",
    "horde_military_minister_module",
    "interior_minister_module",
    "invaders_interior_minister_module",
    "invaders_military_minister_module",
    "machine_interior_minister_module",
    "machine_military_minister_module",
    "mercenary_buyer_minister_module",
    "military_minister_module",
    "space_monsters_module",
    "space_monsters_modules",
    "standard_grand_archive_module",
    "standard_species_rights_module",
    "swarm_interior_minister_module",
    "swarm_military_minister_module",
    "synth_queen_interior_minister_module",
    "synth_queen_military_minister_module",
    "voidworms_module",
  ]),
  staticEnum("crisis_types", ["prethoryn", "unbidden", "contingency", "synth_queen", "all"]),
  staticEnum("custom_progress_mode", ["normal", "simplified", "clamped"]),
  staticEnum("days_months_years", ["days", "months", "years"]),
  staticEnum("diplo_phrase_types", [
    "select",
    "consider",
    "propose",
    "accept",
    "refuse",
    "reject",
    "propose_vote",
    "opinion",
  ]),
  staticEnum("direction", [
    "BOTTOM",
    "CENTER",
    "CENTERED_LEFT",
    "CENTERED_UP",
    "CENTERED_UP_BY_LINE",
    "CENTERUP",
    "CENTER_CENTER",
    "CENTER_LEFT",
    "CENTER_RIGHT",
    "CENTER_UP",
    "CENTRE",
    "LEFT_UP",
    "RIGHT_DOWN",
    "TOP",
    "UPPER_CENTER",
    "CENTER_DOWN",
    "LEFT",
    "LOWER_LEFT",
    "LOWER_RIGHT",
    "RIGHT",
    "TOP_LEFT",
    "UPPER_LEFT",
    "UPPER_RIGHT",
    "vertical",
  ]),
  extractedEnum("district_sets", [
    enumExtraction("common/planet_classes", [extractionField("district_set"), captureScalar()], true, false),
  ]),
  staticEnum("economic_modifier_categories", ["produces", "cost", "upkeep", "logistics"]),
  staticEnum("economic_modifier_types", ["mult", "add"]),
  staticEnum("election_types", ["none", "oligarchic", "democratic"]),
  staticEnum("emitter_type", ["point", "sphere", "box"]),
  staticEnum("end_fleet_contract_reason", ["expired", "broken", "cancelled"]),
  staticEnum("enum_point_of_interest", [
    "ai_crisis_poi.1",
    "ai_crisis_poi.2",
    "ai_crisis_poi.3",
    "ai_crisis_poi.4",
    "behemoth_incubation_poi@root",
    "curator_poi_dragon",
    "curator_poi_dreadnought",
    "curator_poi_fortress",
    "curator_poi_hatchling",
    "curator_poi_hiver",
    "curator_poi_horror",
    "curator_poi_scavenger_bot",
    "curator_poi_stellarite",
    "curator_poi_technosphere",
    "curator_poi_tiyanki",
    "curator_poi_wraith",
    "hidden_planet_poi",
    "rubricator_coordinates_poi",
    "voidworm_system_huge_poi",
    "voidworm_system_large_poi",
    "voidworm_system_medium_poi",
    "voidworm_system_small_poi",
    "voidworm_system_tiny_poi",
    "zroni_legacy_poi_1",
    "zroni_legacy_poi_2",
    "zroni_legacy_poi_3",
  ]),
  staticEnum("enum_ship_family_name", [
    "harbinger_class",
    "mauler_class",
    "offspring_harbinger_class",
    "offspring_mauler_class",
    "offspring_stinger_class",
    "offspring_weaver_class",
    "stinger_class",
    "weaver_class",
  ]),
  staticEnum("envoy_tasks", [
    "federation",
    "first_contact",
    "galactic_community",
    "harm_relations",
    "improve_relations",
    "none",
    "patron_attunement",
    "spy_network",
    "strengthen_imperial_authority",
    "undermine_imperial_authority",
  ]),
  staticEnum("espionage_operation_targets", [
    "none",
    "megastructure",
    "country",
    "fleet",
    "army",
    "pop_faction",
    "federation",
    "starbase",
    "spynetwork",
  ]),
  staticEnum("ethic_leader_creator_ethic_enum", [
    "authoritarian",
    "egalitarian",
    "fanatic_authoritarian",
    "fanatic_egalitarian",
    "fanatic_militarist",
    "fanatic_pacifist",
    "fanatic_spiritualist",
    "fanatic_xenophile",
    "fanatic_xenophobe",
    "gestalt_consciousness",
    "materialist",
    "militarist",
    "pacifist",
    "spiritualist",
    "xenophile",
    "xenophobe",
  ]),
  staticEnum("ethic_leader_creator_species_class_enum", ["random_non_machine", "random_pre_ftl", "random"]),
  extractedEnum("event_chain_counter", [
    enumExtraction("common/missions", [extractionField("counter"), captureKey()], true, false),
    enumExtraction("common/event_chains", [extractionField("counter"), captureKey()], true, false),
  ]),
  staticEnum("event_window_type", [
    "crisis_leader_conversation",
    "leader_recruit",
    "leader_story",
    "leader_conversation",
  ]),
  staticEnum("exclusive_diplomacy_ask", [
    "action_ask_to_become_dominion",
    "action_ask_to_become_satellite",
    "action_ask_to_become_signatory",
    "action_ask_to_become_subsidiary",
    "action_ask_to_become_thrall",
    "action_ask_to_become_tributary",
    "action_stop_stratified_technological_enlightenment",
    "action_stratified_technological_enlightenment",
  ]),
  staticEnum("exclusive_diplomacy_demand", [
    "action_demand_dominion",
    "action_demand_satellite",
    "action_demand_signatory",
    "action_demand_subsidiary",
    "action_demand_thrall",
    "action_demand_tributary",
  ]),
  staticEnum("exe_set_variable", [
    "aesthetic_wonder_specimen_count",
    "aianom_energy_dep1",
    "aianom_energy_dep2",
    "aianom_energy_dep3",
    "aianom_energy_dep4",
    "aianom_engineering_dep1",
    "aianom_engineering_dep2",
    "aianom_engineering_dep3",
    "aianom_engineering_dep4",
    "aianom_mineral_dep1",
    "aianom_mineral_dep2",
    "aianom_mineral_dep3",
    "aianom_mineral_dep4",
    "aianom_physics_dep1",
    "aianom_physics_dep2",
    "aianom_physics_dep3",
    "aianom_physics_dep4",
    "aianom_society_dep1",
    "aianom_society_dep2",
    "aianom_society_dep3",
    "aianom_society_dep4",
    "astral_rift_baol_species",
    "empire_size",
    "event_target:culled_node.trigger:has_base_skill",
    "event_target:destroyed_colony.trigger:pop_amount",
    "event_target:looted_planet.trigger:pop_amount",
    "event_target:patron_revenge_spawn@this",
    "event_target:rebel_empire.trigger:fleet_power",
    "event_target:ruler_pop_faction.trigger:pop_amount",
    "from.starbase.fleet.trigger:fleet_power",
    "from.trigger:empire_size",
    "from.trigger:num_vivarium_slots",
    "genesis_new_species_selected_planet",
    "historical_item_specimen_count",
    "leader.trigger:has_total_skill",
    "local_kill_pop_amount",
    "local_num_attackers",
    "local_pop_amount",
    "local_size_option",
    "local_spent_biomass",
    "number_fleets_spawned",
    "owner.trigger:disciple_of_the_cradle_councilors_count",
    "owner.trigger:fleet_power",
    "owner.trigger:num_ascension_perks",
    "root.local_country_biomass",
    "root.local_devastation",
    "root.local_pop_amount",
    "root.trigger:fleet_power",
    "species.modifier:planet_jobs_specialist_only_produces_mult",
    "species.modifier:planet_jobs_worker_only_produces_mult",
    "subjects_minus_one",
    "trigger:capital_tier",
    "trigger:council_agenda_progress_percent",
    "trigger:empire_size",
    "trigger:empire_sprawl_over_cap",
    "trigger:has_base_skill",
    "trigger:has_experience",
    "trigger:has_total_civic_points",
    "trigger:has_total_skill",
    "trigger:has_unlocked_council_positions",
    "trigger:has_unused_civic_points",
    "trigger:is_difficulty",
    "trigger:leader_age",
    "trigger:leader_lifespan",
    "trigger:max_naval_capacity",
    "trigger:num_ascension_perks",
    "trigger:num_candidate_supported",
    "trigger:num_galaxy_systems",
    "trigger:num_moons",
    "trigger:num_non_aggression_pacts",
    "trigger:num_owned_leaders",
    "trigger:num_planetary_ascension_tiers",
    "trigger:planet_garrison_strength",
    "trigger:planet_size",
    "trigger:planet_stability",
    "trigger:pop_amount",
    "trigger:subjects",
    "trigger:support",
    "trigger:years_passed",
    "trophy_hunter_gained_energy",
    "trophy_hunter_gained_exotic_gases",
    "trophy_hunter_gained_food",
    "trophy_hunter_gained_minerals",
    "trophy_hunter_gained_rare_crystals",
    "trophy_hunter_gained_unity",
    "xeno_geology_specimen_count",
  ]),
  staticEnum("fallen_empire_usage", ["fallen_empire_init"]),
  staticEnum("falloff_type", ["linear"]),
  staticEnum("fauna_fleet_growth_stance", ["controlled", "excessive", "none"]),
  staticEnum("fe_building_upgrade_variables", [
    "affluence_emporium_build_count",
    "affluence_emporium_build_upgrade_count",
    "affluence_emporium_upgrade_count",
    "nourishment_complex_build_count",
    "nourishment_complex_build_upgrade_count",
    "nourishment_complex_upgrade_count",
    "dimensional_replicator_build_count",
    "dimensional_replicator_build_upgrade_count",
    "dimensional_replicator_upgrade_count",
    "class_3_singularity_build_count",
    "class_3_singularity_build_upgrade_count",
    "class_3_singularity_upgrade_count",
    "micro_forge_build_count",
    "micro_forge_build_upgrade_count",
    "micro_forge_upgrade_count",
    "fe_sky_dome_build_count",
    "fe_sky_dome_build_upgrade_count",
    "fe_sky_dome_upgrade_count",
    "fe_fortress_build_count",
    "fe_fortress_build_upgrade_count",
    "fe_fortress_upgrade_count",
    "fe_administration_1_build_count",
    "fe_administration_1_build_upgrade_count",
    "fe_administration_1_upgrade_count",
    "fe_administration_hive_1_build_count",
    "fe_administration_hive_1_build_upgrade_count",
    "fe_administration_hive_1_upgrade_count",
    "fe_administration_machine_1_build_count",
    "fe_administration_machine_1_build_upgrade_count",
    "fe_administration_machine_1_upgrade_count",
    "fe_assembly_1_build_count",
    "fe_assembly_1_build_upgrade_count",
    "fe_assembly_1_upgrade_count",
    "fe_clinic_1_build_count",
    "fe_clinic_1_build_upgrade_count",
    "fe_clinic_1_upgrade_count",
    "fe_security_1_build_count",
    "fe_security_1_build_upgrade_count",
    "fe_security_1_upgrade_count",
    "fe_market_1_build_count",
    "fe_market_1_build_upgrade_count",
    "fe_market_1_upgrade_count",
    "fe_silo_1_build_count",
    "fe_silo_1_build_upgrade_count",
    "fe_silo_1_upgrade_count",
    "fe_entertainment_1_build_count",
    "fe_entertainment_1_build_upgrade_count",
    "fe_entertainment_1_upgrade_count",
    "fe_lab_1_build_count",
    "fe_lab_1_build_upgrade_count",
    "fe_lab_1_upgrade_count",
    "fe_mine_1_build_count",
    "fe_mine_1_build_upgrade_count",
    "fe_mine_1_upgrade_count",
  ]),
  staticEnum("feature_flags", [
    "active_reconnaissance_unlocked",
    "add_advanced_traits",
    "advanced_gene_modding",
    "alien_cloning_unlocked",
    "allow_psionic_aura_intensity_growth",
    "allow_psionic_aura_intensity_spread",
    "assist_cloaking_detection_unlocked",
    "assist_research",
    "bliss_standard",
    "build_terraform_station",
    "campaign_edicts",
    "droids",
    "experimental_subspace_navigation",
    "gateway_activation",
    "gateway_construction",
    "habitability_gene_modding",
    "hyper_relay_construction",
    "jump_method",
    "megaengineering",
    "modify_robots",
    "modify_traits",
    "mutations",
    "planetary_ftl_inhibitor",
    "pop_self_modification",
    "robot_leaders",
    "robots",
    "sustain_cosmic_storm_unlocked",
    "synths",
    "tech_automated_exploration",
    "terraform_inhabited",
    "unity_ambitions",
    "unlock_arcane_deciphering",
    "unlock_astral_rift_exploration",
    "unlock_astral_threads_actions",
    "unlock_gravity_snares",
    "unlock_psionic_aura",
    "unlocks_auto_research",
    "uplifting",
    "wormhole_stabilization",
  ]),
  staticEnum("federation_ownership_limit_type", ["default"]),
  staticEnum("federation_settings", ["research_sharing", "failed_vote_half_price"]),
  staticEnum("federation_succession_terms", ["status_change", "years_10", "years_20", "years_30", "years_40"]),
  staticEnum("federation_succession_types", [
    "strongest",
    "diplomatic_weight",
    "rotation",
    "challenge",
    "random",
    "tech",
    "fleet",
  ]),
  staticEnum("fleet_flag_enum", ["dragon_mission_2", "formless_defense_fleet"]),
  staticEnum("fleet_orders", [
    "aggressive_stance_fleet_order",
    "assist_research_order",
    "auto_explore_order",
    "build_megastructure_fleet_order",
    "build_orbital_station_order",
    "build_space_station_order",
    "collect_data_fleet_order",
    "colonize_planet_order",
    "destroy_planet_order",
    "evade_hostiles_order",
    "excavate_archaeological_site_fleet_order",
    "experimental_subspace_navigation_fleet_order",
    "explore_astral_rift_fleet_order",
    "explore_bypass_order",
    "follow_order",
    "initiate_cosmic_storm_order",
    "jumpdrive_order",
    "jumpdrive_windup",
    "land_armies_order",
    "merge_fleet_order",
    "move_to_system_point_order",
    "orbit_planet_order",
    "planet_killer_weapon_fire_order",
    "planet_killer_weapon_windup_order",
    "repair_fleet_order",
    "research_anomaly_order",
    "research_discovery_order",
    "return_fleet_order",
    "survey_planet_order",
    "terraform_fleet_order",
    "upgrade_design_at_orbitable_fleet_order",
    "upgrade_design_at_starbase_fleet_order",
    "use_bypass_order",
  ]),
  staticEnum("fleet_stance", ["aggressive", "passive", "evasive"]),
  staticEnum("focus_rewards_mode", ["end", "left", "right"]),
  staticEnum("font_languages", [
    "l_braz_por",
    "l_english",
    "l_french",
    "l_german",
    "l_polish",
    "l_russian",
    "l_spanish",
    "l_simp_chinese",
    "l_korean",
    "l_japanese",
  ]),
  staticEnum("font_style", ["regular"]),
  staticEnum("force_type", ["planar", "friction", "point", "spin", "turbulence", "vortex"]),
  staticEnum("galaxy_setup_values", [
    "num_empires",
    "num_advanced_empires",
    "num_fallen_empires",
    "num_marauder_empires",
    "mid_game_year",
    "end_game_year",
    "victory_year",
    "num_guaranteed_colonies",
    "num_gateways",
    "num_wormhole_pairs",
    "num_hyperlanes",
    "habitable_worlds_scale",
    "primitive_worlds_scale",
    "crisis_strength_scale",
    "tech_costs_scale",
    "num_stars",
  ]),
  staticEnum("galcom_resolution_position", ["support", "oppose", "abstain"]),
  staticEnum("genders", ["female", "male", "indeterminable"]),
  staticEnum("genders_not_set", ["male", "female", "indeterminable", "not_set"]),
  staticEnum("global_flags", [
    "authoritarian_leader_1",
    "authoritarian_leader_2",
    "egalitarian_leader_1",
    "egalitarian_leader_2",
    "FLDrone_doing_global",
    "first_league_system_discovered",
    "ghost_signal_1_flag",
    "irassian_system_discovered",
    "materialist_leader_1",
    "materialist_leader_2",
    "militarist_leader_1",
    "militarist_leader_2",
    "pacifist_leader_1",
    "pacifist_leader_2",
    "rampaging_kaijus_created",
    "spiritualist_leader_1",
    "spiritualist_leader_2",
    "synth_queen_crisis_5",
    "synth_queen_crisis_6",
    "xenophile_leader_1",
    "xenophile_leader_2",
    "xenophobe_leader_1",
    "xenophobe_leader_2",
  ]),
  staticEnum("gridbox", [
    "district_arcology_mixed_industry",
    "district_arcology_research",
    "district_resort",
    "district_industrial",
    "district_generator",
  ]),
  staticEnum("growth_category", [
    "GROWTH_CAT_PROMOTION",
    "GROWTH_CAT_GROWTH",
    "GROWTH_CAT_ASSEMBLY",
    "GROWTH_CAT_OTHER",
  ]),
  staticEnum("gui_fade_types", ["smoothstep", "accelerated", "decelerated", "linear"]),
  staticEnum("hardcoded_map_mode_filters", [
    "exploration",
    "expansion",
    "exploitation",
    "details",
    "unions",
    "players",
    "sectors",
    "trade_routes",
  ]),
  staticEnum("hardcoded_map_mode_tooltip", ["opinion", "country", "intel"]),
  staticEnum("has_astral_rift_flag_enum", ["split_opened_rift"]),
  staticEnum("home_system_method", ["breadth_first"]),
  staticEnum("hyperlane_euclidean", ["hyperlane", "euclidean"]),
  staticEnum("inline_script_flags", [
    "received_collection_stage_1_reward_aesthetic_wonder",
    "received_collection_stage_1_reward_historical_item",
    "received_collection_stage_1_reward_xeno_geology",
    "selected_relic_r_celestial_resonator",
    "selected_relic_r_crystallinus_diffuser",
    "selected_relic_r_entangled_relay",
    "selected_relic_r_everchanging_stone",
    "selected_relic_r_executus_compendium",
    "selected_relic_r_flowmetal_alloy",
    "selected_relic_r_gavel_of_the_tribunal",
    "selected_relic_r_propagandosphere",
    "selected_relic_r_prototype_vir_core",
    "selected_relic_r_pulsestone",
    "selected_relic_r_the_modularium",
    "selected_relic_r_the_pattern_maker",
    "selected_relic_r_tiyanki_matriarch_nerve_core",
    "selected_relic_r_vaporous_mega_orchid",
    "shroud_bestowed_boon",
    "shroud_bestowed_curse",
    "can_create_paperclip_universe",
    "consumed_aquatic_dna",
    "consumed_arthropoid_dna",
    "consumed_avian_dna",
    "consumed_fungoid_dna",
    "consumed_habitability_dna",
    "consumed_humanoid_dna",
    "consumed_infernal_dna",
    "consumed_leader_dna",
    "consumed_lithoid_dna",
    "consumed_mammalian_dna",
    "consumed_molluscoid_dna",
    "consumed_necroid_dna",
    "consumed_plantoid_dna",
    "consumed_pop_growth_dna",
    "consumed_pop_output_dna",
    "consumed_psionic_dna",
    "consumed_reptilian_dna",
    "consumed_toxoid_dna",
    "consumed_upkeep_dna",
    "crystal_armor_1_weight",
    "cycle_of_fortune",
    "cycle_of_growth",
    "cycle_of_harmony",
    "cycle_of_knowledge",
    "cycle_of_omens",
    "cycle_of_prosperity",
    "is_player_crisis",
    "orbital_ring_trading_hub_sabotaged",
    "paragon_origin_ascension_flag_flipping_all_seeing",
    "paragon_origin_ascension_flag_flipping_astropath",
    "paragon_origin_ascension_flag_flipping_battle_calculation_systems",
    "paragon_origin_ascension_flag_flipping_brain_growth",
    "paragon_origin_ascension_flag_flipping_cognitive_analyzers",
    "paragon_origin_ascension_flag_flipping_divided_attention",
    "paragon_origin_ascension_flag_flipping_focus",
    "paragon_origin_ascension_flag_flipping_gene_splicing",
    "paragon_origin_ascension_flag_flipping_irresistible_charisma",
    "paragon_origin_ascension_flag_flipping_permanent_transmitters",
    "paragon_origin_ascension_flag_flipping_psychic_beacon",
    "paragon_origin_ascension_flag_flipping_recycling_algorithms",
    "paragon_origin_ascension_flag_flipping_shared_learning_network",
    "paragon_origin_ascension_flag_flipping_sleep_inhibitors",
    "paragon_origin_ascension_flag_flipping_tactical_interface",
    "paragon_origin_ascension_flag_flipping_the_voice",
    "paragon_origin_ascension_flag_flipping_vast_engineering_database",
    "recent_preftl_espionage_academic",
    "released_empire",
    "selected_relic_r_preservation_chamber",
    "smorgasblorg_aquatic",
    "smorgasblorg_arthropoid",
    "smorgasblorg_avian",
    "smorgasblorg_fungoid",
    "smorgasblorg_habitability",
    "smorgasblorg_humanoid",
    "smorgasblorg_infernal",
    "smorgasblorg_leader",
    "smorgasblorg_lithoid",
    "smorgasblorg_mammalian",
    "smorgasblorg_molluscoid",
    "smorgasblorg_necroid",
    "smorgasblorg_plantoid",
    "smorgasblorg_pop_growth",
    "smorgasblorg_pop_output",
    "smorgasblorg_psionic",
    "smorgasblorg_reptilian",
    "smorgasblorg_toxoid",
    "smorgasblorg_upkeep",
    "subterranean_nation",
    "subterranean_nation_fc",
    "unlock_accord_annihilation",
    "unlock_accord_destruction",
    "unlock_accord_distortion",
    "unlock_accord_eradication",
    "unlock_accord_extermination",
    "unlock_accord_fractalization",
    "unlock_accord_intensification",
    "unplugged_prevent_pre_ftl_devastation",
    "use_default_ships",
  ]),
  staticEnum("intel_level", ["none", "low", "medium", "high", "full"]),
  extractedEnum("intel_tokens", [
    enumExtraction("common/intel_categories", [extractionField("intel_level"), captureScalar()], true, false),
  ]),
  staticEnum("job_categories", [
    "specialist",
    "worker",
    "simple_drone",
    "complex_drone",
    "pre_sapients",
    "ruler",
    "precursor",
  ]),
  staticEnum("job_triggers", [
    "can_fill_drone_job",
    "can_fill_worker_job",
    "can_fill_specialist_job",
    "can_fill_ruler_job",
  ]),
  staticEnum("leader_classes", ["official", "commander", "scientist", "envoy"]),
  staticEnum("leader_flag_enum", [
    "block_homeworld_traits",
    "renowned_materialist1",
    "legendary_leader_coma",
    "defeated_humanoid_evopred",
    "defeated_mammalian_evopred",
    "defeated_reptilian_evopred",
    "defeated_avian_evopred",
    "defeated_arthropoid_evopred",
    "defeated_molluscoid_evopred",
    "defeated_fungoid_evopred",
    "defeated_plantoid_evopred",
    "defeated_lithoid_evopred",
    "defeated_necroid_evopred",
    "defeated_aquatic_evopred",
    "defeated_toxoid_evopred",
    "defeated_infernal_evopred",
    "defeated_machine_evopred",
    "paragon_origin_genetic_ascension",
    "paragon_origin_psionic_ascension",
    "renowned_leader",
    "temp_election_leader",
  ]),
  staticEnum("leader_recruit_tag_type", ["hire_leader", "dismiss_leader"]),
  staticEnum("leader_trait_rarity", [
    "common",
    "veteran",
    "paragon",
    "free_or_veteran",
    "negative",
    "destiny",
    "subclass",
  ]),
  extractedEnum("light_animations", [
    enumExtraction("gfx/lights", [extractionField("animation"), extractionField("name"), captureScalar()], true, false),
  ]),
  extractedEnum("locators", [
    enumExtraction("gfx/models", [extractionField("locator"), extractionField("name"), captureScalar()], true, false),
    enumExtraction(
      "gfx/models",
      [extractionField("state"), extractionField("locator"), extractionField("name"), captureScalar()],
      true,
      false,
    ),
  ]),
  staticEnum("maths", ["add", "subtract", "multiply", "divide", "modulo"]),
  staticEnum("meg_build_type", ["inside_gravity_well", "outside_gravity_well", "around_planet"]),
  staticEnum("megastructure_block_type", ["none", "self_type", "multi_stage_type"]),
  staticEnum("message_setting_category", [
    "diplomacy",
    "military",
    "economy",
    "government",
    "science",
    "fleets",
    "planets",
    "leaders",
    "other",
    "cosmic_storm",
    "focuses",
  ]),
  staticEnum("mia_types", [
    "mia_emergency_ftl",
    "mia_return_home",
    "mia_reinforce",
    "mia_forced_to_decloak",
    "mia_fleet_eaten",
  ]),
  staticEnum("model_animation_types", [
    "idle",
    "idle2",
    "sad",
    "sad2",
    "death",
    "death2",
    "death3",
    "attack",
    "moving",
    "survey",
    "scan",
    "miss",
    "miss2",
    "miss_reversed",
    "miss2_reversed",
    "start",
    "fly",
    "working",
  ]),
  extractedEnum("model_states", [
    enumExtraction("gfx", [extractionField("state"), extractionField("name"), captureScalar()], true, false),
  ]),
  staticEnum("move_pattern", [
    "none",
    "stationary",
    "charge",
    "orbit",
    "follow",
    "stay_at_range",
    "flee",
    "maintain_distance",
  ]),
  staticEnum("mutation_components_size", ["small", "medium", "large", "extra_large"]),
  extractedEnum("name_list_categories", [
    enumExtraction("common/name_lists", [extractionField("category"), captureScalar()], true, false),
  ]),
  staticEnum("old_leader_classes", ["governor", "admiral", "general"]),
  staticEnum("open_space_method", ["depth_first"]),
  staticEnum("opinion_levels", ["terrible", "poor", "neutral", "good", "excellent"]),
  staticEnum("optimisation_batch", ["begin", "end"]),
  staticEnum("order_by", [
    "capital_scope.trigger:pop_amount",
    "local_pop_amount",
    "local_spent_biomass",
    "owner.trigger:disciple_of_the_cradle_councilors_count",
    "trigger:fleet_power",
    "trigger:pop_amount",
    "trigger:psionic_pop_amount",
    "trigger:sapient_pop_amount",
    "trigger:pop_group_size",
  ]),
  extractedEnum("particle_force", [
    enumExtraction("gfx/particles", [extractionField("force"), extractionField("name"), captureScalar()], true, false),
  ]),
  extractedEnum("patrons_callings_po", [
    enumExtraction(
      "common/patrons/callings",
      [extractionField("tier"), extractionField("counter"), captureKey()],
      true,
      false,
    ),
  ]),
  staticEnum("patrons_category", ["minor_patron", "major_patron", "great_patron"]),
  extractedEnum("patrons_deeds_po", [
    enumExtraction("common/patrons/deeds", [extractionField("counter"), captureKey()], true, false),
  ]),
  staticEnum("planet_resource_compare_types", ["produces", "upkeep", "balance"]),
  extractedEnum("policy_flag", [
    enumExtraction(
      "common/policies",
      [extractionField("option"), extractionField("policy_flags"), captureScalar()],
      true,
      false,
    ),
  ]),
  extractedEnum("policy_option", [
    enumExtraction(
      "common/policies",
      [extractionField("option"), extractionField("name"), captureScalar()],
      true,
      false,
    ),
  ]),
  extractedEnum("pop_faction_actions", [
    enumExtraction("common/pop_faction_types", [extractionField("actions"), captureKey()], true, false),
  ]),
  staticEnum("pop_faction_inline_flag_enum", [
    "galcom_resolution_passed_anti_imperialist",
    "galcom_resolution_passed_pro_imperialist",
    "galcom_resolution_passed_anti_isolationist",
    "galcom_resolution_passed_pro_isolationist",
    "galcom_resolution_passed_anti_traditionalist",
    "galcom_resolution_passed_pro_traditionalist",
    "galcom_resolution_passed_anti_progressive",
    "galcom_resolution_passed_pro_progressive",
    "galcom_resolution_passed_anti_prosperity",
    "galcom_resolution_passed_pro_prosperity",
    "galcom_resolution_passed_anti_supremacist",
    "galcom_resolution_passed_pro_supremacist",
    "galcom_resolution_passed_anti_technologist",
    "galcom_resolution_passed_pro_technologist",
    "galcom_resolution_passed_anti_totalitarian",
    "galcom_resolution_passed_pro_totalitarian",
    "galcom_resolution_passed_anti_xenoist",
    "galcom_resolution_passed_pro_xenoist",
  ]),
  extractedEnum("pop_faction_parameters", [
    enumExtraction("common/pop_faction_types", [extractionField("parameters"), captureKey()], true, false),
  ]),
  staticEnum("pop_group_flag_enum", [
    "cant_work",
    "non_purge_pop_group",
    "upl_ethic_colind",
    "upl_ethic_pacmil",
    "upl_ethic_spimat",
    "upl_ethic_xenoph",
  ]),
  staticEnum("portrait_refresh", ["planet", "room", "character", "all"]),
  staticEnum("pre_ftl_relationship_types", [
    "commercial_pact",
    "defensive_pact",
    "migration_access",
    "is_under_societal_enlightenment",
    "is_under_open_technological_enlightenment",
    "is_under_stratified_technological_enlightenment",
    "has_pre_ftl_trade",
  ]),
  staticEnum("prereq_for_categories", ["ship", "custom", "component", "diplo_action", "feature", "resource"]),
  staticEnum("progress_direction", ["monodirectional", "bidirectional"]),
  staticEnum("projectile_impact_size", ["small", "medium", "large"]),
  staticEnum("range_components_enum", ["weapon", "strike_craft"]),
  staticEnum("rarity", ["common", "epic", "exceptional", "rare", "highest"]),
  staticEnum("relation_flag_enum", ["AbandonedRefugees", "pirate_relation", "rebelling_slaves_former_owner"]),
  staticEnum("relative_power_categories", ["all", "fleet", "technology", "economy", "proxy_war"]),
  staticEnum("relative_power_values", ["pathetic", "inferior", "equivalent", "superior", "overwhelming"]),
  staticEnum("research_areas", ["engineering", "physics", "psionics", "society"]),
  staticEnum("resource_type", ["basic", "advanced", "strategic", "rare", "other"]),
  staticEnum("satellite_naming_policy", ["upper_case_roman_numerals", "lower_case_latin_letters"]),
  staticEnum("scaled_modifier_calc", [
    "pop_amount",
    "pop_count",
    "pop_happiness",
    "planet_distance_empire",
    "planets_in_country",
  ]),
  staticEnum("scope_type_tokens", [
    "agreement",
    "alliance",
    "ambient_object",
    "archaeological_site",
    "army",
    "astral_rift",
    "background_planet",
    "bypass",
    "cosmic_storm",
    "country",
    "debris",
    "deposit",
    "design",
    "dlc_recommendation",
    "espionage_asset",
    "espionage_operation",
    "exhibit",
    "explorer",
    "federation",
    "first_contact",
    "fleet",
    "galcom",
    "galactic_community",
    "galactic_object",
    "leader",
    "lock_country",
    "megastructure",
    "no_scope",
    "none",
    "planet",
    "pop",
    "pop_job",
    "pop_faction",
    "pop_group",
    "self",
    "sector",
    "ship",
    "ship_growth_stage",
    "situation",
    "species",
    "spy_network",
    "star",
    "starbase",
    "storms",
    "trait",
    "war",
  ]),
  staticEnum("scripted_action_activity_key", [
    "behemoth_burst_activity_key",
    "behemoth_drain_activity_key",
    "behemoth_reflexes_activity_key",
    "behemoth_spike_activity_key",
    "behemoth_turbo_activity_key",
  ]),
  staticEnum("scripted_modifier_categories", [
    "all",
    "army",
    "component",
    "country",
    "deposit",
    "economic_unit",
    "espionage",
    "federation",
    "fleet",
    "habitability",
    "leader",
    "megastructure",
    "none",
    "planet",
    "pop",
    "pop_faction",
    "pop_group",
    "pop_job",
    "ship",
    "species",
    "starbase",
    "station",
    "system",
    "trade",
  ]),
  staticEnum("scripted_scale_type", ["effect_size_var", "beam_size_var"]),
  extractedEnum("scrollbar_types", [
    enumExtraction(
      "interface",
      [extractionField("scrollbarType"), extractionField("name"), captureScalar()],
      true,
      false,
    ),
  ]),
  extractedEnum("section_slots", [
    enumExtraction("common/ship_sizes", [extractionField("section_slots"), captureKey()], true, false),
  ]),
  staticEnum("ship_flag_enum", ["behemoth_hatchling"]),
  staticEnum("ship_owner_types", ["country", "federation", "galactic_community", "global_ship_design"]),
  staticEnum("ship_size_ship_roles", [
    "artillery",
    "artillery_stealth",
    "brawler",
    "brawler_stealth",
    "buffer_role",
    "buffer_role_stealth",
    "carrier",
    "carrier_stealth",
    "citadel",
    "debuffer_role",
    "debuffer_role_stealth",
    "energy_torpedoes",
    "energy_torpedoes_stealth",
    "explosive",
    "explosive_stealth",
    "gunship",
    "gunship_stealth",
    "screen",
    "screen_stealth",
  ]),
  extractedEnum("shipsize_classes", [
    enumExtraction("common/ship_sizes", [extractionField("class"), captureScalar()], true, false),
  ]),
  staticEnum("simple_maths_enum", ["round", "ceiling", "floor", "abs", "square_root", "square"]),
  extractedEnum("situation_approaches", [
    enumExtraction(
      "common/situations",
      [extractionField("approach"), extractionField("name"), captureScalar()],
      true,
      false,
    ),
  ]),
  staticEnum("situation_category", ["positive", "negative", "neutral"]),
  staticEnum("situation_flag_enum", [
    "breach_shroud_approach_selected",
    "celebration_void_spawn",
    "cyber_5_stage_1_fire",
    "cybernetic_creed_cyberization_no_funding",
    "shroud_forged_500_negative",
    "shroud_forged_500_positive",
    "shroud_forged_510_negative_1",
    "shroud_forged_510_negative_2",
    "shroud_forged_510_positive_1",
    "shroud_forged_510_positive_2",
    "shroud_forged_520_negative_1",
    "shroud_forged_520_negative_2",
    "shroud_forged_520_positive_1",
    "shroud_forged_530_negative_2",
    "shroud_forged_540_positive_2",
    "shroud_forged_550_negative_1",
    "shroud_forged_550_positive_1",
    "shroud_forged_560_negative_2",
    "shroud_forged_560_positive_2",
    "shroud_forged_570_negative_1",
    "shroud_forged_570_positive_1",
    "shroud_forged_580_positive_1",
    "shroud_forged_590_negative_1",
    "shroud_forged_590_positive_1",
    "shroud_forged_600_negative_2",
    "shroud_forged_600_positive_2",
    "shroud_forged_610_negative_1",
    "shroud_forged_610_positive_1",
    "shroud_forged_620_negative_1",
    "shroud_forged_620_negative_2",
    "shroud_forged_620_positive_1",
    "shroud_forged_630_negative_1",
    "shroud_forged_630_positive_2",
    "shroud_forged_640_positive_1",
    "shroud_forged_650_negative_1",
    "shroud_forged_650_positive_1",
    "shroud_forged_660_negative_1",
    "shroud_forged_660_positive_2",
    "shroud_forged_670_negative_1",
    "shroud_forged_670_positive_1",
    "shroud_forged_680_positive_1",
    "shroud_forged_690_negative_1",
    "shroud_forged_690_positive_1",
    "took_pops",
    "voidspawn_celebration",
  ]),
  extractedEnum("situation_stages", [
    enumExtraction("common/situations", [extractionField("stages"), captureKey()], true, false),
  ]),
  staticEnum("slot_type", ["strike_craft", "weapon"]),
  staticEnum("solar_sys_init_planet_class", [
    "random",
    "random_colonizable",
    "random_non_ideal",
    "random_non_colonizable",
    "ideal_planet_class",
    "random_asteroid",
    "none",
  ]),
  staticEnum("sort_type", ["depth", "age", "distance"]),
  staticEnum("sp_event_scopes", ["ship_event", "planet_event", "country_event"]),
  staticEnum("species_category_type", [
    "normal",
    "cyborg",
    "robotic",
    "psionic",
    "advanced_genetic",
    "overtuned",
    "malleable",
    "mutation",
  ]),
  staticEnum("species_rights_type", [
    "citizenship",
    "military_service",
    "slavery",
    "purge",
    "living_standard",
    "migration_control",
    "population_control",
    "colonization_control",
    "none",
  ]),
  staticEnum("specimen_type", ["aesthetic_wonder", "historical_item", "xeno_geology"]),
  staticEnum("sprite_type", ["character", "character_large", "character_without_room", "empty_room", "room", "planet"]),
  staticEnum("spynetwork_flag_enum", ["operation_diplomatic_incident_timer", "recently_stole_technology"]),
  staticEnum("standard_format", ["center", "centre", "left", "right"]),
  extractedEnum("star_class_random_list", [
    enumExtraction("common/star_classes", [extractionField("name"), captureScalar()], true, false),
  ]),
  staticEnum("target_type_enum", ["enemy", "ally", "controlled", "owned"]),
  staticEnum("tech_ai_type", ["all", "military"]),
  staticEnum("tech_departments", ["society_technology", "engineering_technology", "physics_technology"]),
  staticEnum("technology_areas", ["engineering", "society", "physics"]),
  extractedEnum("textcolors", [
    enumExtraction("interface", [extractionField("textcolors"), captureKey()], true, false),
  ]),
  staticEnum("texture_size", ["small"]),
  staticEnum("trade_types", ["market_buy", "market_sell", "not_set"]),
  extractedEnum("tradition_swap", [
    enumExtraction(
      "common/traditions",
      [extractionField("tradition_swap"), extractionField("name"), captureScalar()],
      true,
      false,
    ),
  ]),
  staticEnum("trait_ai_classes", ["engineering", "physics", "society", "survey", "subclass_commander_admiral"]),
  staticEnum("truce_types", ["war", "liberation", "alliance", "guarantee", "none"]),
  staticEnum("tutorial_levels", ["0", "1", "2", "full", "medium", "none"]),
  staticEnum("type_of_mutation", ["offensive", "defensive", "aux"]),
  staticEnum("usage_type", ["empire_init", "misc_system_init", "custom_empire", "fallen_empire_init", "origin"]),
  staticEnum("utility_component_slots", [
    "SMALL_UTILITY_1",
    "SMALL_UTILITY_2",
    "SMALL_UTILITY_3",
    "SMALL_UTILITY_4",
    "SMALL_UTILITY_5",
    "SMALL_UTILITY_6",
    "SMALL_UTILITY_7",
    "SMALL_UTILITY_8",
    "SMALL_UTILITY_9",
    "SMALL_UTILITY_10",
    "SMALL_UTILITY_11",
    "SMALL_UTILITY_12",
    "SMALL_UTILITY_13",
    "SMALL_UTILITY_14",
    "SMALL_UTILITY_15",
    "SMALL_UTILITY_16",
    "SMALL_UTILITY_17",
    "SMALL_UTILITY_18",
    "SMALL_UTILITY_19",
    "SMALL_UTILITY_20",
    "SMALL_UTILITY_21",
    "SMALL_UTILITY_22",
    "SMALL_UTILITY_23",
    "SMALL_UTILITY_24",
    "SMALL_UTILITY_25",
    "SMALL_UTILITY_26",
    "SMALL_UTILITY_27",
    "SMALL_UTILITY_28",
    "SMALL_UTILITY_29",
    "SMALL_UTILITY_30",
    "MEDIUM_UTILITY_1",
    "MEDIUM_UTILITY_2",
    "MEDIUM_UTILITY_3",
    "MEDIUM_UTILITY_4",
    "MEDIUM_UTILITY_5",
    "MEDIUM_UTILITY_6",
    "MEDIUM_UTILITY_7",
    "MEDIUM_UTILITY_8",
    "MEDIUM_UTILITY_9",
    "MEDIUM_UTILITY_10",
    "MEDIUM_UTILITY_11",
    "MEDIUM_UTILITY_12",
    "MEDIUM_UTILITY_13",
    "MEDIUM_UTILITY_14",
    "MEDIUM_UTILITY_15",
    "MEDIUM_UTILITY_16",
    "MEDIUM_UTILITY_17",
    "MEDIUM_UTILITY_18",
    "MEDIUM_UTILITY_19",
    "MEDIUM_UTILITY_20",
    "MEDIUM_UTILITY_21",
    "MEDIUM_UTILITY_22",
    "MEDIUM_UTILITY_23",
    "MEDIUM_UTILITY_24",
    "MEDIUM_UTILITY_25",
    "MEDIUM_UTILITY_26",
    "MEDIUM_UTILITY_27",
    "MEDIUM_UTILITY_28",
    "MEDIUM_UTILITY_29",
    "MEDIUM_UTILITY_30",
    "LARGE_UTILITY_1",
    "LARGE_UTILITY_2",
    "LARGE_UTILITY_3",
    "LARGE_UTILITY_4",
    "LARGE_UTILITY_5",
    "LARGE_UTILITY_6",
    "LARGE_UTILITY_7",
    "LARGE_UTILITY_8",
    "LARGE_UTILITY_9",
    "LARGE_UTILITY_10",
    "LARGE_UTILITY_11",
    "LARGE_UTILITY_12",
    "LARGE_UTILITY_13",
    "LARGE_UTILITY_14",
    "LARGE_UTILITY_15",
    "LARGE_UTILITY_16",
    "LARGE_UTILITY_17",
    "LARGE_UTILITY_18",
    "LARGE_UTILITY_19",
    "LARGE_UTILITY_20",
    "LARGE_UTILITY_21",
    "LARGE_UTILITY_22",
    "LARGE_UTILITY_23",
    "LARGE_UTILITY_24",
    "LARGE_UTILITY_25",
    "LARGE_UTILITY_26",
    "LARGE_UTILITY_27",
    "LARGE_UTILITY_28",
    "LARGE_UTILITY_29",
    "LARGE_UTILITY_30",
    "LARGE_UTILITY_31",
    "LARGE_UTILITY_32",
    "LARGE_UTILITY_33",
    "LARGE_UTILITY_34",
    "LARGE_UTILITY_35",
    "LARGE_UTILITY_36",
    "LARGE_UTILITY_37",
    "LARGE_UTILITY_38",
    "LARGE_UTILITY_39",
    "LARGE_UTILITY_40",
    "LARGE_UTILITY_41",
    "LARGE_UTILITY_42",
    "LARGE_UTILITY_43",
    "LARGE_UTILITY_44",
    "LARGE_UTILITY_45",
    "LARGE_UTILITY_46",
    "LARGE_UTILITY_47",
    "LARGE_UTILITY_48",
    "LARGE_UTILITY_49",
    "LARGE_UTILITY_50",
    "LARGE_UTILITY_51",
    "LARGE_UTILITY_52",
    "LARGE_UTILITY_53",
    "LARGE_UTILITY_54",
    "LARGE_UTILITY_55",
    "LARGE_UTILITY_56",
    "LARGE_UTILITY_57",
    "LARGE_UTILITY_58",
    "LARGE_UTILITY_59",
    "LARGE_UTILITY_60",
    "AUX_UTILITY_1",
    "AUX_UTILITY_2",
    "AUX_UTILITY_3",
    "AUX_UTILITY_4",
    "AUX_UTILITY_5",
    "AUX_UTILITY_6",
    "AUX_UTILITY_7",
    "AUX_UTILITY_8",
    "AUX_UTILITY_9",
    "AUX_UTILITY_10",
    "AUX_UTILITY_11",
    "AUX_UTILITY_12",
    "AUX_UTILITY_13",
    "AUX_UTILITY_14",
    "AUX_UTILITY_15",
    "AUX_UTILITY_16",
    "AUX_UTILITY_17",
    "AUX_UTILITY_18",
    "AUX_UTILITY_19",
    "AUX_UTILITY_20",
    "AUX_UTILITY_21",
    "AUX_UTILITY_22",
    "AUX_UTILITY_23",
    "AUX_UTILITY_24",
    "AUX_UTILITY_25",
    "AUX_UTILITY_26",
    "AUX_UTILITY_27",
    "AUX_UTILITY_28",
    "AUX_UTILITY_29",
    "AUX_UTILITY_30",
  ]),
  staticEnum("utility_slot_size", ["extra_large", "large", "medium", "small", "aux"]),
  staticEnum("varname_enum", [
    "this.ascensions_added",
    "this.destroyed_colony_pop",
    "this.experimental_progress",
    "this.research_after",
    "this.spawned_shroudstone",
  ]),
  staticEnum("vertical_alignment", ["centre", "center", "top", "bottom"]),
  extractedEnum("vertical_scrollbar_types", [
    enumExtraction(
      "interface",
      [extractionField("extendedScrollbarType"), extractionField("name"), captureScalar()],
      true,
      false,
    ),
  ]),
  staticEnum("voidworms_spawn_system_size", ["tiny", "small", "medium", "large", "huge"]),
  staticEnum("vote_types", ["unanimous_vote", "majority_vote", "leader"]),
  staticEnum("war_sides", ["attackers", "defenders"]),
  staticEnum("weapon_slot_size", [
    "extra_large",
    "large",
    "medium",
    "small",
    "torpedo",
    "point_defence",
    "planet_killer",
    "titanic",
    "engulf",
    "any",
  ]),
  staticEnum("weapon_type", [
    "weapon_type_energy",
    "weapon_type_kinetic",
    "weapon_type_explosive",
    "weapon_type_strike_craft",
    "weapon_type_point_defense",
  ]),
  staticEnum("weapon_type2", ["instant", "point_defence", "missile", "planet_killer", "engulf"]),
  staticEnum("weight_or_base", ["weight", "base"]),
  staticEnum("weight_or_factor", ["weight", "factor"]),
  extractedEnum("zone_set", [
    enumExtraction("common/zones", [extractionField("zone_sets"), captureScalar()], true, false),
  ]),
  staticEnum("zone_set_additional", ["zone_default"]),
  staticEnum("zone_type", ["all", "any"]),
];
