import { anyScope, dynamicScope, fixedScopes, listedScopes, typeRef, valueSet } from "./ir.js";
import type { LinkDefinition, ScopeDefinition } from "./ir.js";

export const scopes: readonly ScopeDefinition[] = [
  { id: "agreement", displayName: "Agreement", aliases: ["agreement"] },
  { id: "alliance", displayName: "Alliance", aliases: ["alliance"] },
  { id: "ambient_object", displayName: "Ambient Object", aliases: ["ambientobject", "ambient_object"] },
  {
    id: "archaeological_site",
    displayName: "Archaeological Site",
    aliases: ["archaeologicalsite", "archaeological_site"],
  },
  { id: "army", displayName: "Army", aliases: ["army"] },
  { id: "astral_rift", displayName: "Astral Rift", aliases: ["astral_rift"] },
  { id: "background_planet", displayName: "Background Planet", aliases: ["backgroundplanet", "background_planet"] },
  { id: "bypass", displayName: "Bypass", aliases: ["bypass"] },
  { id: "cosmic_storm", displayName: "Cosmic Storm", aliases: ["cosmic_storm", "storms"] },
  {
    id: "cosmic_storm_influence_field",
    displayName: "Cosmic Storm Influence Field",
    aliases: ["cosmic_storm_influence_field"],
  },
  { id: "country", displayName: "Country", aliases: ["country"] },
  { id: "debris", displayName: "Debris", aliases: ["debris"] },
  { id: "deposit", displayName: "Deposit", aliases: ["deposit"] },
  { id: "design", displayName: "Design", aliases: ["design"] },
  { id: "dlc_recommendation", displayName: "DLC Recommendation", aliases: ["dlc_recommendation"] },
  { id: "espionage_asset", displayName: "Espionage Asset", aliases: ["espionage_asset"] },
  { id: "espionage_operation", displayName: "Espionage Operation", aliases: ["espionage_operation"] },
  { id: "exhibit", displayName: "Exhibit", aliases: ["exhibit"] },
  { id: "explorer", displayName: "Explorer", aliases: ["explorer"] },
  { id: "federation", displayName: "Federation", aliases: ["federation"] },
  { id: "first_contact", displayName: "First Contact", aliases: ["first_contact"] },
  { id: "fleet", displayName: "Fleet", aliases: ["fleet"] },
  { id: "leader", displayName: "Leader", aliases: ["leader"] },
  { id: "lock_country", displayName: "Lock Country", aliases: ["lockcountry", "lock_country"] },
  { id: "megastructure", displayName: "Megastructure", aliases: ["megastructure"] },
  { id: "planet", displayName: "Planet", aliases: ["planet"] },
  { id: "pop", displayName: "Pop", aliases: ["pop"] },
  { id: "pop_faction", displayName: "Pop Faction", aliases: ["popfaction", "pop_faction"] },
  { id: "pop_group", displayName: "Pop Group", aliases: ["pop_group"] },
  { id: "pop_job", displayName: "Pop Job", aliases: ["job", "pop_job"] },
  { id: "sector", displayName: "Sector", aliases: ["sector"] },
  { id: "ship", displayName: "Ship", aliases: ["ship"] },
  { id: "ship_growth_stage", displayName: "Ship Growth Stage", aliases: ["ship_growth_stage"] },
  { id: "situation", displayName: "Situation", aliases: ["situation"] },
  { id: "species", displayName: "Species", aliases: ["species"] },
  { id: "spy_network", displayName: "Spy Network", aliases: ["spy_network", "spynetwork"] },
  { id: "star", displayName: "Star", aliases: ["star"] },
  { id: "starbase", displayName: "Starbase", aliases: ["starbase"] },
  { id: "system", displayName: "System", aliases: ["galacticobject", "system", "galactic_object"] },
  { id: "trait", displayName: "Trait", aliases: ["trait"] },
  { id: "war", displayName: "War", aliases: ["war"] },
];

export const links: readonly LinkDefinition[] = [
  {
    kind: "scope-link",
    id: "space_owner",
    input: listedScopes(
      "megastructure",
      "planet",
      "country",
      "ship",
      "fleet",
      "system",
      "army",
      "ambient_object",
      "starbase",
      "archaeological_site",
      "spy_network",
      "debris",
    ),
    output: fixedScopes("country"),
  },
  {
    kind: "scope-link",
    id: "owner_or_space_owner",
    input: listedScopes(
      "megastructure",
      "planet",
      "country",
      "ship",
      "fleet",
      "system",
      "army",
      "starbase",
      "archaeological_site",
      "spy_network",
      "debris",
    ),
    output: fixedScopes("country"),
  },
  { kind: "scope-link", id: "overlord", input: listedScopes("country"), output: fixedScopes("country") },
  { kind: "scope-link", id: "defender", input: listedScopes("war"), output: fixedScopes("country") },
  { kind: "scope-link", id: "attacker", input: listedScopes("war"), output: fixedScopes("country") },
  { kind: "scope-link", id: "instigator", input: listedScopes("war"), output: fixedScopes("country") },
  { kind: "scope-link", id: "aura_owner", input: listedScopes("system"), output: fixedScopes("country") },
  {
    kind: "scope-link",
    id: "owner",
    input: listedScopes(
      "species",
      "ship",
      "pop",
      "pop_group",
      "fleet",
      "planet",
      "pop_faction",
      "sector",
      "leader",
      "country",
      "starbase",
      "system",
      "first_contact",
      "megastructure",
      "army",
      "deposit",
      "archaeological_site",
      "spy_network",
      "espionage_operation",
      "situation",
      "agreement",
      "debris",
      "bypass",
      "astral_rift",
    ),
    output: fixedScopes("country"),
  },
  {
    kind: "scope-link",
    id: "controller",
    input: listedScopes("planet", "starbase", "fleet", "ship", "debris"),
    output: fixedScopes("country"),
  },
  {
    kind: "scope-link",
    id: "planet_owner",
    input: listedScopes(
      "megastructure",
      "planet",
      "pop",
      "pop_group",
      "leader",
      "army",
      "starbase",
      "deposit",
      "archaeological_site",
    ),
    output: fixedScopes("country"),
  },
  { kind: "scope-link", id: "last_created_country", input: anyScope(), output: fixedScopes("country") },
  {
    kind: "scope-link",
    id: "leader",
    input: listedScopes(
      "planet",
      "country",
      "ship",
      "fleet",
      "leader",
      "army",
      "pop_faction",
      "federation",
      "archaeological_site",
      "first_contact",
      "spy_network",
      "espionage_operation",
      "astral_rift",
    ),
    output: fixedScopes("leader"),
  },
  { kind: "scope-link", id: "last_created_leader", input: anyScope(), output: fixedScopes("leader") },
  {
    kind: "scope-link",
    id: "solar_system",
    input: listedScopes(
      "planet",
      "ship",
      "fleet",
      "system",
      "ambient_object",
      "megastructure",
      "starbase",
      "archaeological_site",
      "first_contact",
      "deposit",
      "pop",
      "pop_group",
      "army",
      "country",
      "leader",
      "debris",
      "bypass",
      "astral_rift",
    ),
    output: fixedScopes("system"),
  },
  { kind: "scope-link", id: "last_created_system", input: anyScope(), output: fixedScopes("system") },
  {
    kind: "scope-link",
    id: "planet",
    input: listedScopes(
      "megastructure",
      "planet",
      "pop",
      "pop_group",
      "leader",
      "army",
      "starbase",
      "deposit",
      "archaeological_site",
    ),
    output: fixedScopes("planet"),
  },
  { kind: "scope-link", id: "capital_scope", input: listedScopes("country", "sector"), output: fixedScopes("planet") },
  {
    kind: "scope-link",
    id: "orbit",
    input: listedScopes("fleet", "ship", "megastructure", "army", "planet", "starbase"),
    output: fixedScopes("planet"),
  },
  {
    kind: "scope-link",
    id: "home_planet",
    input: listedScopes("country", "species", "pop", "pop_group", "leader"),
    output: fixedScopes("planet"),
  },
  { kind: "scope-link", id: "target_system", input: listedScopes("cosmic_storm"), output: fixedScopes("system") },
  { kind: "scope-link", id: "last_created_ship", input: anyScope(), output: fixedScopes("ship") },
  { kind: "scope-link", id: "mining_station", input: listedScopes("planet"), output: fixedScopes("fleet") },
  { kind: "scope-link", id: "research_station", input: listedScopes("planet"), output: fixedScopes("fleet") },
  { kind: "scope-link", id: "last_created_fleet", input: anyScope(), output: fixedScopes("fleet") },
  {
    kind: "scope-link",
    id: "fleet",
    input: listedScopes("ship", "starbase", "leader", "army", "fleet", "astral_rift"),
    output: fixedScopes("fleet"),
  },
  {
    kind: "scope-link",
    id: "excavator_fleet",
    input: listedScopes("archaeological_site"),
    output: fixedScopes("fleet"),
  },
  {
    kind: "scope-link",
    id: "unhappiest_pop",
    input: listedScopes("planet", "country"),
    output: fixedScopes("pop_group"),
  },
  { kind: "scope-link", id: "last_created_pop_faction", input: anyScope(), output: fixedScopes("pop_faction") },
  { kind: "scope-link", id: "last_created_ambient_object", input: anyScope(), output: fixedScopes("ambient_object") },
  { kind: "scope-link", id: "last_created_army", input: anyScope(), output: fixedScopes("army") },
  {
    kind: "scope-link",
    id: "owner_species",
    input: listedScopes(
      "species",
      "ship",
      "pop",
      "pop_group",
      "fleet",
      "planet",
      "pop_faction",
      "sector",
      "leader",
      "country",
      "starbase",
      "system",
      "first_contact",
      "megastructure",
      "army",
      "deposit",
      "archaeological_site",
      "spy_network",
      "espionage_operation",
      "situation",
      "agreement",
      "debris",
      "bypass",
      "astral_rift",
    ),
    output: fixedScopes("species"),
  },
  {
    kind: "scope-link",
    id: "owner_main_species",
    input: listedScopes(
      "species",
      "ship",
      "pop",
      "pop_group",
      "fleet",
      "planet",
      "pop_faction",
      "sector",
      "leader",
      "country",
      "starbase",
      "system",
      "first_contact",
      "megastructure",
      "army",
      "deposit",
      "archaeological_site",
      "spy_network",
      "espionage_operation",
      "situation",
      "agreement",
      "debris",
      "bypass",
      "astral_rift",
    ),
    output: fixedScopes("species"),
  },
  { kind: "scope-link", id: "last_created_species", input: anyScope(), output: fixedScopes("species") },
  { kind: "scope-link", id: "built_species", input: listedScopes("country"), output: fixedScopes("species") },
  {
    kind: "scope-link",
    id: "species",
    input: listedScopes("country", "ship", "leader", "pop", "pop_group", "army", "species"),
    output: fixedScopes("species"),
  },
  {
    kind: "scope-link",
    id: "pop_faction",
    input: listedScopes("pop", "pop_group", "leader", "pop_faction"),
    output: fixedScopes("pop_faction"),
  },
  { kind: "scope-link", id: "last_created_pop_faction", input: anyScope(), output: fixedScopes("pop_faction") },
  { kind: "scope-link", id: "default_pop_faction", input: listedScopes("pop"), output: fixedScopes("pop_faction") },
  {
    kind: "scope-link",
    id: "sector",
    input: listedScopes(
      "planet",
      "system",
      "leader",
      "ship",
      "fleet",
      "ambient_object",
      "megastructure",
      "starbase",
      "archaeological_site",
      "first_contact",
      "system",
      "sector",
      "pop",
      "pop_group",
      "army",
      "deposit",
      "debris",
      "bypass",
    ),
    output: fixedScopes("sector"),
  },
  { kind: "scope-link", id: "core_sector", input: listedScopes("country"), output: fixedScopes("sector") },
  {
    kind: "scope-link",
    id: "ruler",
    input: listedScopes(
      "species",
      "ship",
      "pop",
      "pop_group",
      "fleet",
      "planet",
      "pop_faction",
      "sector",
      "leader",
      "country",
      "starbase",
      "system",
      "first_contact",
      "megastructure",
      "army",
      "deposit",
      "archaeological_site",
      "spy_network",
      "espionage_operation",
      "situation",
      "agreement",
      "debris",
      "bypass",
      "astral_rift",
    ),
    output: fixedScopes("leader"),
  },
  {
    kind: "scope-link",
    id: "heir",
    input: listedScopes(
      "species",
      "ship",
      "pop",
      "pop_group",
      "fleet",
      "planet",
      "pop_faction",
      "sector",
      "leader",
      "country",
      "starbase",
      "system",
      "first_contact",
      "megastructure",
      "army",
      "deposit",
      "archaeological_site",
      "spy_network",
      "espionage_operation",
      "situation",
      "agreement",
      "debris",
      "bypass",
      "astral_rift",
    ),
    output: fixedScopes("leader"),
  },
  {
    kind: "scope-link",
    id: "star",
    input: listedScopes(
      "planet",
      "ship",
      "fleet",
      "system",
      "ambient_object",
      "bypass",
      "megastructure",
      "starbase",
      "archaeological_site",
      "first_contact",
      "debris",
      "astral_rift",
    ),
    output: fixedScopes("planet"),
  },
  { kind: "scope-link", id: "last_created_design", input: anyScope(), output: fixedScopes("design") },
  { kind: "scope-link", id: "design", input: listedScopes("ship"), output: fixedScopes("design") },
  {
    kind: "scope-link",
    id: "starbase",
    input: listedScopes("system", "planet", "ship", "fleet", "starbase"),
    output: fixedScopes("starbase"),
  },
  { kind: "scope-link", id: "capital_star", input: listedScopes("country"), output: fixedScopes("planet") },
  { kind: "scope-link", id: "no_scope", input: anyScope(), output: dynamicScope() },
  { kind: "scope-link", id: "megastructure", input: anyScope(), output: fixedScopes("megastructure") },
  {
    kind: "scope-link",
    id: "system_star",
    input: listedScopes(
      "planet",
      "ship",
      "fleet",
      "system",
      "ambient_object",
      "megastructure",
      "starbase",
      "archaeological_site",
      "first_contact",
      "deposit",
      "pop",
      "pop_group",
      "army",
      "country",
      "leader",
      "debris",
      "bypass",
      "astral_rift",
    ),
    output: fixedScopes("planet"),
  },
  {
    kind: "scope-link",
    id: "observation_outpost_owner",
    input: listedScopes("planet"),
    output: fixedScopes("country"),
  },
  { kind: "scope-link", id: "observation_outpost", input: listedScopes("planet"), output: fixedScopes("fleet") },
  { kind: "scope-link", id: "branch_office_owner", input: listedScopes("planet"), output: fixedScopes("country") },
  {
    kind: "scope-link",
    id: "archaeological_site",
    input: listedScopes(
      "planet",
      "ship",
      "fleet",
      "ambient_object",
      "megastructure",
      "starbase",
      "system",
      "archaeological_site",
      "debris",
    ),
    output: fixedScopes("archaeological_site"),
  },
  { kind: "scope-link", id: "alliance", input: listedScopes("country"), output: fixedScopes("federation") },
  { kind: "scope-link", id: "federation", input: listedScopes("country"), output: fixedScopes("federation") },
  { kind: "scope-link", id: "federation_leader", input: listedScopes("federation"), output: fixedScopes("country") },
  {
    kind: "scope-link",
    id: "associated_federation",
    input: listedScopes("country"),
    output: fixedScopes("federation"),
  },
  { kind: "scope-link", id: "last_added_deposit", input: listedScopes("planet"), output: fixedScopes("deposit") },
  { kind: "scope-link", id: "envoy_location_country", input: listedScopes("leader"), output: fixedScopes("country") },
  { kind: "scope-link", id: "sector_capital", input: listedScopes("sector"), output: fixedScopes("planet") },
  { kind: "scope-link", id: "orbital_station", input: listedScopes("planet"), output: fixedScopes("fleet") },
  { kind: "scope-link", id: "contact_country", input: listedScopes("first_contact"), output: fixedScopes("country") },
  {
    kind: "scope-link",
    id: "reverse_first_contact",
    input: listedScopes("first_contact"),
    output: fixedScopes("first_contact"),
  },
  {
    kind: "scope-link",
    id: "spynetwork",
    input: listedScopes("espionage_operation"),
    output: fixedScopes("spy_network"),
  },
  {
    kind: "scope-link",
    id: "target",
    input: listedScopes("espionage_operation", "situation", "agreement", "spy_network"),
    output: dynamicScope(),
  },
  { kind: "scope-link", id: "growing_species", input: listedScopes("planet"), output: fixedScopes("species") },
  { kind: "scope-link", id: "assembling_species", input: listedScopes("planet"), output: fixedScopes("species") },
  { kind: "scope-link", id: "declining_species", input: listedScopes("planet"), output: fixedScopes("species") },
  { kind: "scope-link", id: "galactic_emperor", input: anyScope(), output: fixedScopes("country") },
  { kind: "scope-link", id: "galactic_custodian", input: anyScope(), output: fixedScopes("country") },
  { kind: "scope-link", id: "orbital_defence", input: listedScopes("planet"), output: fixedScopes("fleet") },
  { kind: "scope-link", id: "army_leader", input: listedScopes("planet"), output: fixedScopes("leader") },
  { kind: "scope-link", id: "creator", input: listedScopes("leader"), output: fixedScopes("country") },
  { kind: "data-link", id: "script_value", prefix: "value:", source: typeRef("script_value") },
  { kind: "data-link", id: "modifier", prefix: "modifier:", source: valueSet("modifier") },
  { kind: "scope-link", id: "explorer", input: listedScopes("astral_rift"), output: fixedScopes("country") },
  { kind: "scope-link", id: "background_planet", input: listedScopes("leader"), output: fixedScopes("planet") },
  {
    kind: "scope-link",
    id: "astral_rift",
    input: listedScopes("system", "leader"),
    output: fixedScopes("astral_rift"),
  },
  { kind: "scope-link", id: "lock_country", input: listedScopes("bypass"), output: fixedScopes("country") },
  { kind: "scope-link", id: "founder_species", input: listedScopes("country"), output: fixedScopes("species") },
  {
    kind: "scope-link",
    id: "storm_influence_field",
    input: listedScopes("system"),
    output: fixedScopes("cosmic_storm_influence_field"),
  },
  { kind: "scope-link", id: "last_created_cosmic_storm", input: anyScope(), output: fixedScopes("cosmic_storm") },
  {
    kind: "scope-link",
    id: "last_created_cosmic_storm_influence_field",
    input: anyScope(),
    output: fixedScopes("cosmic_storm_influence_field"),
  },
  { kind: "scope-link", id: "spawner_planet", input: listedScopes("army"), output: fixedScopes("planet") },
  {
    kind: "scope-link",
    id: "ship_growth_stage",
    input: listedScopes("ship"),
    output: fixedScopes("ship_growth_stage"),
  },
];
